### ISSUE TITLE
loginWithPassword . ( Not stable ) 

### ISSUE THREAD

**Issue by fa-deve** [WHAnonymous/Chat-API#1000]
sometimes i can login  :
![login1](https://cloud.githubusercontent.com/assets/14147885/9818519/5d1c4648-58a9-11e5-8324-7a4e3af59a28.png)

and in other time i cannot login 

![error](https://cloud.githubusercontent.com/assets/14147885/9818517/5bd5c070-58a9-11e5-9ba8-48711b541024.png)

note : number exists not blocked
any help ? please .

**Comment by 0xTryCatch** [comment]
Really? Stop opening issues for the same question over and over again.

**Comment by mgp25** [comment]
@fa-deve it should be your connectivity, not API issue

**Comment by fa-deve** [comment]
@mgp25 what can i do to solve this problem ?
