### ISSUE TITLE
cannot receive message from individual 

### ISSUE THREAD

**Issue by shvburade** [WHAnonymous/Chat-API#1002]
i am trying to receive message from individual but what i get message like this.

```xml
<message from="91********@s.whatsapp.net" type="text" offline="0" id="Oe/3oCXeEe/M1" t="1442038732" notify="Shiva Burade">
rx    <enc v="1" type="pkmsg">3���!�-QZ qb���s@'�Q�we^n�?�+��:Q!���b&;�t��õv+�D�44���I����/"B3 !�j��x\Z��h� T }���;q�q�' ��h�]"hϸ��Ӵ�S{@�C�m�Go����(ʷ�00<enc>
rx  </message>
```

i can receive messages from group but cannot receive any message from individual

**Comment by shvburade** [comment]
what have you done? there is no duplicate i found

**Comment by CODeRUS** [comment]
https://github.com/WHAnonymous/Chat-API/issues?utf8=%E2%9C%93&q=encrypted
