### ISSUE TITLE
WA Web & QR Code String

### ISSUE THREAD

**Issue by sckebby** [WHAnonymous/Chat-API#1003]
Hi WHAnonymous,
I have receive this "Disconnect Notification / Action" from Web.Whatsapp.com.

Do you know the way, or are you working on the way to Connect / Send Action to connect Chat-API on web.whatsapp.com with the QR Code readed string ?

I am trying to develop the request to Open web.whatsapp.com connection, but I think i need help.
With your better experience around the Chat-API, do you have an idea about how to do it ?

Thank you.
```
rx  <notification from="44XXXXXXXXX@s.whatsapp.net" type="web" id="797411440" t="1442167514">
rx    <action type="delete" t="1442167488" name="dNsgUk0vY6erNfMVrTMeXA==">@bPH+fT9bOjLMPr63caPD7EyCgypNTHiNOY5YOLcc+Nm8nQN+7SQfOnGb</action>
rx  </notification>

tx  <ack to="44XXXXXXXXX@s.whatsapp.net" class="notification" id="797411440" type="web"></ack>

rx  <notification from="44XXXXXXXXX@s.whatsapp.net" type="web" id="3331385459" t="1442167516">
rx    <action type="delete" modify="clear" name="dNsgUk0vY6erNfMVrTMeXA==" code="ICm/5fmGCFMcOMOBdaZhU9kTAIGiwRvtFSqsCeMXiSY="></action>
rx  </notification>

tx  <ack to="44XXXXXXXXX@s.whatsapp.net" class="notification" id="3331385459" type="web"></ack>
```

**Comment by mgp25** [comment]
@sckebby We know how to do it, but we won't is not necessary to implement WhatsApp Web with this API, there is no point.

Regards

**Comment by sckebby** [comment]
Thanks you mgp25 for response, can you please explain me, or send me how can I do that request please ? considering I can do a script to retreive the QR Code string easily to pass it to the request, I need only the right call.

Thank you for support.
Regards.

**Comment by 0xTryCatch** [comment]
WhatsApp Web is very complicated, you will not get it to work easily.

**Comment by sckebby** [comment]
I am interessed only into the Connection, not all the streaming of data or Text.

**Comment by sckebby** [comment]
Hi 0xTryCatch, thank you for response.
 
I was thinking about a Call like this:
```
<iq id="3" xmlns="urn:xmpp:whatsapp:web" type="set">
    <action type="add" modify="update" name="gfThfd43g35erNfMVrTMeXA==" code="ICm/5fmGCFMctrEfd5FdfDGDfDt5GdFD674dwe&esSY="></action>
  </iq>
```
xmlns="xmlpp:whatsapp:web" ==> ???
type="add" ===> ??
modify="update" ===> ???

Name & Code should be the present into the QR Code String.
Do you have the right value for xmlns, type and modify ?

Thank for help,
Regards.
