### ISSUE TITLE
retry, expire, code for onLoginFailed event

### ISSUE THREAD

**Issue by kwiiby** [WHAnonymous/Chat-API#1004]
Hey, could you guys put "retry", "expire" and "code" attributes on onLoginFailed callback when receives a failure (not-authorized for example)? I already changed in my code, but would be nice API to have this.

Thank you!!

**Comment by vladimir0909** [comment]
https://github.com/WHAnonymous/Chat-API/pulls

**Comment by mgp25** [comment]
@kwiiby send a pull request :smile:

**Comment by ariel12345** [comment]
I have this problem that my account is blocked and this presents a serious error to me , so what I have to do ????????????????? Please help me , I could not send a message once
