### ISSUE TITLE
any danger using this after cease&desist ?

### ISSUE THREAD

**Issue by sebcl** [WHAnonymous/Chat-API#1006]
I just read that letter you received from FB/WA lawyers and i'm wondering about this. Didn't they close everything for you, or did you get a consensus?

**Comment by gi097** [comment]
No, they can't close anything for him/her; WHAnonymous doesn't excist. 

Yeah, when using this client, there always be a small risk for bans, when WhatsApp inc. finds out we are using an unofficial client.

However, we are only USING their servers not ABUSING them, so they can't do anything.

**Comment by david-perez** [comment]
So basically the person/people in charge of WHAnonymous account ignored the letter and never heard back from them? Why can't they close the repository? Is it because there's no way of contacting the owner of the repo, so there is no one to contact/sue?
