### ISSUE TITLE
GetMessages() return an empty array

### ISSUE THREAD

**Issue by casion** [WHAnonymous/Chat-API#1007]
Hello people,

I'm testing your api with a simple code. I just send "hi" to a number and it respond "hello" automatically.

My code was working last night, but now the method "GetMessages()" is returning a empty array.

I already tried using a custom bind and still the same. Also, the examples provided dont show any received message.

But if I enable debug, it show me a XML with encrypted message.

Is some change on WH server? Its really strange, this problem occurs on official examples too.

best regards,
PH

**Comment by mgp25** [comment]
@casion if you receive encrypted messages its because you had that number in an android device. Check the wiki and older issues to do a workaround and receive plaintext messages

Regards
