### ISSUE TITLE
Encrypted Text Msg

### ISSUE THREAD

**Issue by ushaskml** [WHAnonymous/Chat-API#1010]
I am using your Chat API for past two months,and its working well.From last week onwards we found a problem as  when client send  any  messages to groups its working fine,but while receiving  individual messages,  getting encrypted  text messages like below

rx  <message from="7924xxxxxxx@s.whatsapp.net" id="1437088740.--353" type="text" t="1437088740" notify="aa">
rx    <enc v="1" type="pkmsg">�Ψ!�+X��#-wb?�o��Q�0����V#���Z0�=!�å�b�劉=Y�uP���Z<��tR�V�&q"B3!�v�τ=$B�$j�}����;F7��Y*"27���t��>�g��d�H㬎b?(����0</enc>
rx  </message>

I cannot receive any text message because of onGetMessage() does not fire.

I use ajaxdemo->socket.php & this is my code

while (running($time)) {
    while($w->pollMessage());
    running($time); //check again if timestamp has been updated
    $outbound = $_SESSION["outbound"];
    $_SESSION["outbound"] = array();
    session_write_close();
    if (count($outbound) > 0) {
        foreach ($outbound as $message) {
            $w->sendMessage($message["target"], $message["body"]);
            $w->pollMessage();
        }
    }
    //check for received messages:
    $messages = $w->getMessages();
    if (count($messages) > 0) {
        $inbound = $_SESSION["inbound"];
        $_SESSION["inbound"] = array(); //lock
        foreach ($messages as $message) {
            $data = @$message->getChild("body")->getData();
            if ($data != null && $data != '') {
                $inbound[] = $data;
            }
        }
        $_SESSION["inbound"] = $inbound;
        session_write_close();
    }
}

I already used   resetaccount.php and registertool.php & generate new password.But no improvement.
Sir, Pls help me to solve this big issue..

Regards,
Ushadevi.S

**Comment by gi097** [comment]
This was already told MANY times before, you should look at the closed issues. We can't do anything until the axolotl decryption will be added into the library, so you have to wait. (It's still in progress)

**Comment by mgp25** [comment]
Read the damn wiki, there is a workaround published

**Comment by TimVosch** [comment]
@mgp25 Just tried it twice didn't work, still receiving encrypted messages :(
Can we see the progress on axolotl port? Btw, you probably know already but just in case. Yowsup already has the encryption solved. Too bad yowsup crashes every few minutes.

**Comment by mgp25** [comment]
@TimVosch Yes, i know. Maybe next weekend or so could be finished, but i dont have an ETA, im very busy with univeristy, but yeah maybe within 1 week or 2 will be finished.

**Comment by TimVosch** [comment]
Thanks for the update. University is a priority.  I'll try to look into the encryption stuff as well maybe I can help with something.





On Sun, Sep 20, 2015 at 3:47 PM -0700, "mgp25" <notifications@github.com> wrote:
@TimVosch Yes, i know. Maybe next weekend or so could be finished, but i dont have an ETA, im very busy with univeristy, but yeah maybe within 1 week or 2 will be finished.

---
