### ISSUE TITLE
s.whatsapp.net not available.

### ISSUE THREAD

**Issue by rkazanova** [WHAnonymous/Chat-API#1011]
Do you know new alternative server?

**Comment by mgp25** [comment]
@rkazanova Do you have latest code? Post your debug log.

Hace you read #556 before opening this issue?

**Comment by rkazanova** [comment]
just do ping s.whatsapp.net

**Comment by mgp25** [comment]
@rkazanova No. Have you used latest code? Have you checked latest source?

**Comment by rkazanova** [comment]
I will update it and try it

**Comment by rkazanova** [comment]
Stack trace:
#0 /src/whatsprot.class.php(548): WhatsProt->doLogin()
#1 contactsync.php(44): WhatsProt->loginWithPassword('ZxW9VOUTnattCvj...')
#2 {main}
  thrown in /src/whatsprot.class.php on line 2235
WhatsappAPI answer: Status: 500 Internal Server Error
X-Powered-By: PHP/5.5.9-1ubuntu4.11
Content-type: text/html

**Comment by rkazanova** [comment]
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /home/romkazanova/git/mobile_whatsapp_api/src/whatsprot.class.php:2235

**Comment by 0xTryCatch** [comment]
Use ```blockChecker.php```

**Comment by rkazanova** [comment]
Yes , my numbers were blocked,  It works for new numbers
