### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by kuzevanoff** [WHAnonymous/Chat-API#1013]
I've geted my password. Than i've done some simple code like:
$username = "my numb"; 
$nickname = "my nickname";
$debug = true; 

$w = new WhatsProt($username, $nickname, $debug);
$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword("KI15UezSRIaSJQ13iRYQDji1yIE="); 

Responce is:
<response>�|'�ϊS�R$�C�k`M�"��%�g��U���~�</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

Fixe it please. It happen very often.
Thanks.

**Comment by 0xTryCatch** [comment]
Update the API

**Comment by kuzevanoff** [comment]
What do u mean?
i've downloaded Chat-API-master.zip today!!!
So, please, reopen my issue

**Comment by mgp25** [comment]
@kuzevanoff your number is blocked. If you have any doubt:

- Read the F.A.Q.: https://github.com/WHAnonymous/Chat-API/wiki/Frequently-asked-questions
- Read the wiki: https://github.com/WHAnonymous/Chat-API/wiki
- Read #556

**Comment by kuzevanoff** [comment]
Wait please. This is response. In the status i see OK

Array
(
    [in] => 991301010
    [cc] => 79
    [id] => ?h㽥????_utp??
    [lg] => ru
    [lc] => RU
    [sim_mcc] => 250
    [sim_mnc] => 000
    [method] => sms
    [token] => 976e4f7e94b6a22c64dc705d3be11445
)
stdClass Object
(
    [status] => ok
    [login] => my numb
    [pw] => a2A+AwYG4haSHlfo8H75eZjTjhw=
    [type] => existing
    [expiration] => 1467636547
    [kind] => free
    [price] => 33,00 руб.
    [cost] => 33.00
    [currency] => RUB
    [price_expiration] => 1445718868
)

**Comment by mgp25** [comment]
@kuzevanoff can you show whats the [login] value?

**Comment by kuzevanoff** [comment]
@mgp25 please check your email address.

**Comment by VicthorFx** [comment]
Your username if you are from México for example 5215570617951
with "1" between code country and phone number

**Comment by ariel12345** [comment]
I have this problem that my account is blocked and this presents a serious error to me , so what I have to do ????????????????? Please help me , I could not send a message once
