### ISSUE TITLE
How to receive messages of devices iOS with Axolotl encryption

### ISSUE THREAD

**Issue by ddfrreire** [WHAnonymous/Chat-API#1015]
messages received of devices iOS is encrypted, how fix? 
https://github.com/WHAnonymous/Chat-API/wiki/WhatsApp-incoming-updates#31-august-2015

Debug Chat-API:
```
rx  <message from="xxx@s.whatsapp.net" type="text" id="xxx-600" offline="0" t="xxx" notify="xxxx">
rx    <enc v="1" type="msg">3 !%÷¿R18¾åÙ¢'G©Óe#ÅÊ/@ÙÂØ'IÑ)÷Ç—s"5 cãPI#OêÒOÖ\Ã[ï5¿lïµ*</enc>
rx  </message> 
```

**Comment by 0xTryCatch** [comment]
https://github.com/WHAnonymous/Chat-API/issues?utf8=%E2%9C%93&q=encrypted
