### ISSUE TITLE
upload image

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#1017]
@WHAnonymous @mgp25  i get the fhash of the image and use it in another function to don't upload it again but this is take the same time

this is method i used

$w->sendMessageImage($GroupID, $Path,false,$Size,$FHash,$Caption); // Send image
$w->pollMessage();

i pass the fhash and size and path but this method take long time as like upload it

**Comment by mgp25** [comment]
Continue in #1016 

Read this #556
