### ISSUE TITLE
#1018 Invalid Close.

### ISSUE THREAD

**Issue by Skorm92** [WHAnonymous/Chat-API#1019]
Hi,

https://github.com/WHAnonymous/Chat-API/issues/1018

You blatantly close that Issue while forwarding me to a issue I believe is not related to my issue,
That issue is about the message that are encrypted.

I'm not on that stage yet, I merely wish to echo it out without debugging.
even if it's still encrypted.

I don't need to decrypt my message at this moment, I wish to echo the message (even with encrypted messages).

If you still believe this is related to the issue you forwared me to, please close this one again and elaborate the link between the issue's :)

Thank you in advance.

**Comment by mgp25** [comment]
onGetMessage wont work with encrypted messages only plaintext messages, altough this is already answered in many issues. Before opening issues is always good to search if it was already asked.

Regards

**Comment by Skorm92** [comment]
I couldn't find that in the articles I've read (I wasn't looking for issue's related to decrypting)

My first stage will be encryption then. 

Thank you for the explanation! :)
