### ISSUE TITLE
sendGetRequestLastSeen function not found

### ISSUE THREAD

**Issue by tim-hanssen** [WHAnonymous/Chat-API#1020]
Hey all,

In the Wiki I found a function  sendGetRequestLastSeen($to) that looks not to be in the code anymore.
Can anyone explain what I should use instead?

Thxs.

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#requesting-last-seen-and-profile-picture

#938
