### ISSUE TITLE
Can't create 2nd group after 30 minutes the 1st group has been created.

### ISSUE THREAD

**Issue by catch2patch** [WHAnonymous/Chat-API#1025]
Hi all!
Thanks to all of the contributors for the great tool.
I've already mentioned that my hobby is online gaming. I like playing multiplayer games and I really love programming useful tools that can help my clan to win battles and obtain resources. 
I already have positive experience in programming the boss respawn notification system using yowsup and whatsapi. Now I'd like to code the resources managing notification system. The game we are playing has the complicated farming system (lots of farms and fields with various resources) and different groups of people (parties) are in charge of their own types of resources. Sometimes they rotate.
I need to code a bot that creates a group, gatheres all the people of certain party in it and then posts a reminder when their certain resource type is ready to be collected, forged, sold or something.

It doesn't seem difficult to code. We have the functions like sendGroupsChatCreate, sendGroupsParticipantsAdd etc.
But after a couple of days testing I've found a bug. When I create a group and adding the persons I need, it's OK. But after approx. 30 minutes, any group-related actions become impossible and the whatsapp account gets blocked. I've been using the latest chat-api version. It looks weird but non-group related actions (like sending messages etc) are OK.

Here's the debug of the typical test reproduction: http://pastebin.com/B4fREtAB

The account gets blocked permanently. Seems that something's wrong with the protocol. Can anybody reproduce the problem? Just make a group and try to create one more group in 30-40 minutes.

**Comment by 0xTryCatch** [comment]
Post a debug log

**Comment by catch2patch** [comment]
Edited the post. Couldn't post the log with the right markdown so made a paste on the pastebin: http://pastebin.com/B4fREtAB

**Comment by mgp25** [comment]
@catch2patch i'll check, but i dont see any error at all, the only thing i see is a bad iq request behaviour: In the second case you are requesting an image:

```xml
tx  <iq id="1" type="get" xmlns="w:profile:picture" to="yyyyyyyyyy17@s.whatsapp.net">
tx    <picture type="image"></picture>
tx  </iq>
```

before this:

```xml
rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>
```

I recommend you to add a couple of `$w->pollMessage();` right after the `loginWithPassword($password);`

**Comment by catch2patch** [comment]
@mgp25 thanks for your attention. I've tried to add $w->pollMessage(); after the loginWithPassword($password);
The nodes went in the right order, but it hasn't affect the problem.

Can you reproduce my test?

**Comment by mgp25** [comment]
@does the problem persists?

**Comment by catch2patch** [comment]
Yes. I want to be sure if someone else can reproduce it.
Could you please create a group and create one more group in 35-40 minutes?
But beware of having the number blocked :(

**Comment by mgp25** [comment]
@catch2patch i don't have numbers to try sorry. I think the problem is a bad behaviour, instead of creating a duplicate group, try removing the last one and create this new one, or add a participant to the existing one or even create a seconds group but with more participants.

I also recommend you to follow this: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#whatsapp-workflow

If you have any number i can test with, i'll do.

Regards

**Comment by catch2patch** [comment]
Hi. I have a few test numbers left. I've emailed them to you. If it won't be enough, I can buy more sim cards. I am also a bit confused about this issue. It's very easy to reproduce, it affects all the users that use api to work with groups and it seems to be quite serious. But if it really was, we'd have lots of open issues related to it. 

If you won't reproduce it and sucessfully create 2nd group after 30 minutes, could you please post the debug log, for I could compare it with mine?

**Comment by mgp25** [comment]
No issue. It was a bad coded behaviour.

**Comment by phpjoker** [comment]
@mgp25 Please put here a correct and well coded behavior!
Thanks.

**Comment by mgp25** [comment]
Wiki
