### ISSUE TITLE
Getting encrypted message

### ISSUE THREAD

**Issue by jaysonroni** [WHAnonymous/Chat-API#1029]
Yesterday for some reason i Re-registered my number with WART and after that we received encrypted (junk) message from some contacts. I don't know why and how this happening with us.. because before register this was work fine... please help us.. we receive message as below

3������!�a�{�4�$}T{��X�����R�pS@���I7�
^�!��\�P��W��DR%7F���=���B�+�����"B3
!������L��,�0s���U0%��t�J�0�BY7��

We already tried with new password but yet getting solutions. so kindly help me in this matter

**Comment by CODeRUS** [comment]
https://github.com/WHAnonymous/Chat-API/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+encrypted
