### ISSUE TITLE
Delete/leave group automatically

### ISSUE THREAD

**Issue by albertgil1989** [WHAnonymous/Chat-API#1031]
Hello, you greetings from Venezuela .
I have a question I've been trying to solve a while and I really would help his advice. I want when my account is added to a group , you automatically leave the group . How do I catch the group ID of a message to apply the following?

```php
$groupId;
$w->sendGroupsLeave($groupId);
```

I appreciate your help , thanks.

**Comment by mgp25** [comment]
@albertgil1989 remember to quote your code (i did for you this time). This is explained in the wiki, use event system, there is documentation in the wiki and you can find examples in the `/examples` folder

Regards

**Comment by albertgil1989** [comment]
=(

**Comment by mgp25** [comment]
@albertgil1989 


- Event system: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#using-events
- List of the events: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#list-of-all-events

With this you can do what you want.

Regards
