### ISSUE TITLE
Fetch all synced contacts

### ISSUE THREAD

**Issue by kwiiby** [WHAnonymous/Chat-API#1032]
Hello, I wonder how my address book works, where they are stored, in my cellphone or in WhatsApp servers?

When I already have WhatsApp and the cell is changed then registered in WhatsApp, automatically all conversations will be there, right?

How do I pull the list of contacts synchronized? Is there any function available? I didn't find.

Thank you guys.

**Comment by mgp25** [comment]
Read wiki: https://github.com/WHAnonymous/Chat-API/wiki/Sync

Also this question has been answered many times, you can search it in the closed issues.

Regards

**Comment by kwiiby** [comment]
I did not find the answer in this link and not the old questions, do not know if I have a lack of attention or if it is not really clear. Could you please explain to me why I can not see my address book? thank you.

**Comment by CODeRUS** [comment]
phonebook is uploaded to server and used by server to understand who is known by you and who is not. you cant download uploaded phonebook back from server, you can't also delete something from it, it will be eaten by facebook forever.

**Comment by kwiiby** [comment]
when I cellular change, WhatsApp application does not make a FunXMPP request to download the agenda? how they get that? How they fetch?

**Comment by CODeRUS** [comment]
If you tick an option it will upload encrypted backup to google cloud and download it. If not, it will use only your new phonebook.

**Comment by kwiiby** [comment]
If I migrate from Android to iPhone, without backup, all my conversation are gone? so it makes sense.

**Comment by CODeRUS** [comment]
Yeah. Iphones syncing it to icloud. rom whatsapp servers application only download groups and broadcasts lists.

**Comment by kwiiby** [comment]
So.. there is a possibility to sync twice the same contact, right? WhatApp can't blame me for that.

**Comment by CODeRUS** [comment]
sure, no problems here. only timings between syncs and using proper methods are important.

**Comment by kwiiby** [comment]
thanks
