### ISSUE TITLE
Message Encyprt 

### ISSUE THREAD

**Issue by H4Code** [WHAnonymous/Chat-API#1033]
i receive Encrypt Message :(

**Comment by CODeRUS** [comment]
sad story :(

**Comment by H4Code** [comment]
so what can i do ?

**Comment by CODeRUS** [comment]
try to find answers in previous issues: https://github.com/WHAnonymous/Chat-API/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+encrypted

**Comment by fharias** [comment]
Hi @CODeRUS did you resolve something about Encrypt message, or you have some problem with Whatsapp that is the problem why you dont publish the solution.

**Comment by mgp25** [comment]
@fharias read the wiki
