### ISSUE TITLE
Call to undefined function socket_create()

### ISSUE THREAD

**Issue by zakaria-saade** [WHAnonymous/Chat-API#1034]
Hello everyone
i have i have whatsapp API. it wors fine on my localhost but when i use online(webhosting), i face this problem "Call to undefined function socket_create() in whatsprot.class.php"
i want your help please
thanks advance

**Comment by p031985s** [comment]
Hi there...

It means your web hosting does not have enabled sockets.

**Comment by zakaria-saade** [comment]
I have checked and found that php socket function is already enabled on the server where your website is hosted with us you can check the same using url http://3alam3agib.com/phpinfo.php

**Comment by mgp25** [comment]
@zakaria-saade No, you dont have it installed/enabled

**Comment by zakaria-saade** [comment]
what is the solution

**Comment by mgp25** [comment]
Install or enable php sockets

Dependencies: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#dependencies

**Comment by zakaria-saade** [comment]
@mgp25 
Dear, php socket is installed on my hosting and u can check via
http://3alam3agib.com/phpinfo.php

**Comment by mgp25** [comment]
@zakaria-saade You don't have it installed/enabled i told you before! You need `php sockets`
