### ISSUE TITLE
Send Location in Single Chat doesn't work

### ISSUE THREAD

**Issue by TobiasReittinger** [WHAnonymous/Chat-API#1035]
Following code (from `exampleFuntional.php`) doesn't work in a Single Chat (not a group):

```php
$w->sendLocation($target, '4.948568', '52.352957');
```

Can somebody help me please?

**Comment by mgp25** [comment]
@TobiasReittinger if you dont post debug log we can't help you. Always if you open an issue, post full debug log

**Comment by TobiasReittinger** [comment]
Here the debug log:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="...">4���...%r�s�ơt!�6���:�fp...</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>�Sl>Q��|m�e�dM;q�</challenge>

tx  <response>;�і�j�3 mԼ�Q�k��.�8G_U�m3c晃�ͨ</response>

rx  <success t="..." props="4" kind="free" status="active" creation="1442940482" expiration="1474476482">����:� Жq�g���O1�</success>

tx  <presence name="Test"></presence>

**Comment by mgp25** [comment]
@TobiasReittinger you are not requesting anything

**Comment by TobiasReittinger** [comment]
That's how I send a message:

$w->sendMessage($target , $message);

but the command for sending a location doesn't work:

$w->sendLocation($target, '4.948568', '52.352957');

**Comment by mgp25** [comment]
@TobiasReittinger read the wiki, there is no function called `sendLocation`

Regards

**Comment by TobiasReittinger** [comment]
@mgp25 yes I know, but that both lines were in the exampleFunctional.php:

```
//send Location
//$w->sendLocation($target, '4.948568', '52.352957');
```

**Comment by mgp25** [comment]
@TobiasReittinger yes, `name` and `url` are optional params.
