### ISSUE TITLE
Stream replaced by new connection

### ISSUE THREAD

**Issue by TobiasReittinger** [WHAnonymous/Chat-API#1036]
I have a program that is always waiting for an "incoming" message, but during that process I want to send a message. Following error occurs:

```
rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>
```

How can I run both programs?

**Comment by 0xTryCatch** [comment]
You can't. Only one simultaneous connection is allowed.

**Comment by TobiasReittinger** [comment]
I use following loop: 
```
while (true) {
    $w->PollMessage();
    $msgs = $w->GetMessages();

    foreach ($msgs as $m) {
       // print_r($m);
    }
}
```
How can I detect that there is a stream error (when I send a message) and start the waiting process again?

**Comment by mgp25** [comment]
@TobiasReittinger you are replacing your session by a new one. You should check messages and send in the same script.

See `exampleFunctional.php`, there is an implementation of what im saying.

Regards

**Comment by TobiasReittinger** [comment]
@mgp25  Thank you very much, you are awesome!
