### ISSUE TITLE
Stream replaced by new connection

### ISSUE THREAD

**Issue by TobiasReittinger** [WHAnonymous/Chat-API#1037]
I have a program that is always waiting for an "incoming" message, but during that process I want to send a message. Following error occurs:
```
rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>
```
I'm using following loop: 
```
while (true) {
    $w->PollMessage();
    $msgs = $w->GetMessages();

    foreach ($msgs as $m) {
       // print_r($m);
    }
}
```
How can I detect that there is a stream error (when I send a message) and start the waiting process again?

**Comment by mgp25** [comment]
Duplicate #1036

**Comment by TobiasReittinger** [comment]
I'm searching for an answer of my second question...

**Comment by 0xTryCatch** [comment]
It doesn't help if you open multiple tickets. On the contrary.

**Comment by TobiasReittinger** [comment]
You are right, but it doesn't help when you close this issue and I'm still searching for an open answer. So I have to open an new one and open one.
