### ISSUE TITLE
Function to get whatsapp name (or whatsapp nickname)

### ISSUE THREAD

**Issue by javiersalvay** [WHAnonymous/Chat-API#1039]
Guys,
Does someone know the function to get the whatsapp name (or whatsapp nickname)?
I have checked on wiki and there is not nothing like getname(). The near one is the getprofileimage.
THanks!
Javier

**Comment by mgp25** [comment]
@javiersalvay is not possible to retrieve contact's name, this is stored locally in our device (address book, etc). What you can do is to obtain the push name the user has. When the user sends a message there is a `notify`  attribute in the node that contains that data, you can obtain this by using the event system. More info.  in the wiki.

Regards
