### ISSUE TITLE
exampleFunctional time limit

### ISSUE THREAD

**Issue by TobiasReittinger** [WHAnonymous/Chat-API#1040]
In the exampleFunctional.php there is a great example: the interactive conversation. I want to run this "watching" file to get all incoming messages, but after some time (circa 120 sec.) the program stops running without any note. I set all time limits of the php.ini to 0 = endless, so I guess the time limit is in the code. Can somebody help me please?

**Comment by mgp25** [comment]
Run it in command line, not webserver
