### ISSUE TITLE
sendSync function documentation is lacking information about parameters

### ISSUE THREAD

**Issue by 3esmit** [WHAnonymous/Chat-API#1042]
Hi, 
I'm digging into whatsprot.class.php and I see that the function sendSync have a lot of parameters that are not explained into wiki.
I found this using google https://github.com/WHAnonymous/Chat-API/wiki/Sync and this says that in the first login should be sendSync($contacts, null, 0), 0 would be full registration. 

Also, I read that you cannot unsync a contact, but the function sendSync have a second parameter called $deletedContacts. 

What happens with the array of numbers synced as deletedContacts? 
What is the pratical diference from the contexts background, interactive and registration?
When should I use full, delta, query or chunked mode?

**Comment by mgp25** [comment]
@3esmit i know there is lack of information, i'll write about that.

Right now, use only `sendSync` by default, this is:

```php
$w->sendSync($numbers);
```

Regards
