### ISSUE TITLE
How to get receipt ack

### ISSUE THREAD

**Issue by CodingAnonymous** [WHAnonymous/Chat-API#1043]
Hi,

how can I get the following ack/receipt in a varibale/string?

```xml
<ack to="@s.whatsapp.net" class="receipt" id="kqr/L2IZaGoV0"></ack>

rx  <presence from="@s.whatsapp.net"></presence>

<is online> rx  <receipt from="@s.whatsapp.net" type="read" id="kqr/L2IZaGoV0" t="1443389687"></receipt>

tx  <ack to="@s.whatsapp.net" class="receipt" id="kqr/L2IZaGoV0" type="read"></ack>

rx  <presence from="@s.whatsapp.net" type="unavailable" last="1443389707"></presence>
```

Can somebody explain the variables of ```onGetReceipt( $from, $id, $offline, $retry )``` (nothing in the wiki...)? 
Thanks in advance!

**Comment by mgp25** [comment]
`$from`: JID
`$id`: id
`$offline`: I do not remember, but try it and you will see the value
`$retry`: A counter

There is no info in the wiki because i think is very intuitive, the name itself explains the value.

Regards

**Comment by CodingAnonymous** [comment]
Thanks!
What does the ```$retry``` count?
How can I get the above postet ack/recieve in a String?
