### ISSUE TITLE
how seperate the send/receive interface to be specific to each user

### ISSUE THREAD

**Issue by raniongolu** [WHAnonymous/Chat-API#1044]
how to use fun xmpp protocol for chat-api
how seperate the send/receive interface to be specific to each user
is there any options

**Comment by mgp25** [comment]
What do you mean? You want to use it with different numbers at the same time, is that right?

**Comment by raniongolu** [comment]
no i want chat rooms like facebook,gmail

**Comment by mgp25** [comment]
Check examples: https://github.com/WHAnonymous/Chat-API/tree/master/examples

Check CLI client, and read wiki for more documentation

Regards

**Comment by Hawkz69** [comment]
How do I use different numbers for the same time?
Is there a way to capture the number of user , when he sent me a message ?

thank you
