### ISSUE TITLE
Encrypted messages

### ISSUE THREAD

**Issue by yniv** [WHAnonymous/Chat-API#1046]
Since a couple of days when I register new numbers using the register tool and then login and polling messages for them I get only encrypted messages like these: 

3��!'�Nicx�H�MI���rt�,^P�!D����cOVv!U��*&ƶ����]���շ_h���/��A�9"B3
!U���!��1)־I[Wm�1!VH�P�r��'��c"bO����G�]tY\x�Yذ�`[�(����0

I'm using the S40 2.13.4 version...
Any ideas???

**Comment by yniv** [comment]
Hi, why did you close it? If it's duplicate please point me to the duplicated issue pls

**Comment by 0xTryCatch** [comment]
If you can type on your keyboard you can also use the search function in the issues

**Comment by yniv** [comment]
Ok sorry, I checked the FAQ and previous issues but, using resetAccount and registerAcount did not solve the problem... I'm still getting the encrypted messages... Did i miss something?
