### ISSUE TITLE
Encoding accented messages

### ISSUE THREAD

**Issue by mauriciodcuy** [WHAnonymous/Chat-API#1047]
Hi I am trying to send messages and captions with accents but I am having some problems.
I found this issue that is the same but no solution was found.
https://github.com/WHAnonymous/Chat-API/issues/336

Thanks for your help!
Regards

Mauricio

**Comment by mgp25** [comment]
Yes, the solution is posted, UTF-8 encode

**Comment by mauriciodcuy** [comment]
Could you please give me a clue where to include that code. In the php.ini?
When I do an echo, the accent mark shows right.
Thanks for you help
Regards

**Comment by mgp25** [comment]
https://secure.php.net/manual/en/function.utf8-encode.php

**Comment by mauriciodcuy** [comment]
Thanks a lot that really help me.
Now it works.
Regards
