### ISSUE TITLE
Keep Connected

### ISSUE THREAD

**Issue by Plins** [WHAnonymous/Chat-API#1048]
Hi There, im doing some tests. I'm fascinated with this API but i have a problem..
After 2 minutes of inactivity my 'app test' turn off 'Disconnected'...
In WhatsApp Web, we have the possibility to choose to keep connected. Exists some property  to set or method to do it? how can i do it? 

Very Thanks!

**Comment by mauriciodcuy** [comment]
I have the same question, there is a function sendPing(); 
But it is not working for me..
Thanks.
Regards

**Comment by Plins** [comment]
Mauriciodcuy, i tried change to change timeout to 9999999, but not work too

**Comment by mauriciodcuy** [comment]
Yes I directly remove that line. But it didn't work.

**Comment by vladimir0909** [comment]
```php
<?php

$w = new WhatsProt('phone number', 'name');
$w->connect();
$w->loginWithPassword('password');

while (true) {
    $w->sendPing();
    sleep(30); # 30 seconds (timeout is probably 300)
}
```

**Comment by Plins** [comment]
You tried trigger sendping every 1 minute?

**Comment by Plins** [comment]
@vladimir0909 thx, when i arrive home, i'll ttry

**Comment by Plins** [comment]
@vladimir0909  not works ;/

**Comment by Plins** [comment]
@WHAnonymous can you help me?

**Comment by Plins** [comment]
@mauriciodcuy I did an analysis in whatsapp's life cycle and i made some tests... as @vladimir0909 said, you need send pings to whatsapp server but you need send every 29-30 seconds.
i did this way:
```` 
while(true){
if (Count == 29)
            {
                if (wa.ConnectionStatus == ApiBase.CONNECTION_STATUS.CONNECTED)
                {
                    SendMsg("55xxxxxxxxxx", "Connected yet");
                }

                wa.SendPing();

                Total++;
                Count = 1;
            }


            lblTime.Text = $"{Total}({Count})";

            Count++;
}
````
