### ISSUE TITLE
sendGetClientConfig no longer working

### ISSUE THREAD

**Issue by viniciusjarina** [WHAnonymous/Chat-API#1051]
Hello

It seems [sendClientConfig](https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L825) is no longer working 😢

https://gist.github.com/viniciusjarina/4644c95898626e712c89

**Comment by mgp25** [comment]
It's working perfectly:

```xml
tx  <iq id="1" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="S40" version="2.13.4"></config>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="1"></iq>
```
