### ISSUE TITLE
How to Not Getting status notification about Friend Status, Picture, etc

### ISSUE THREAD

**Issue by assegaf** [WHAnonymous/Chat-API#1052]
Once we have more friend on whatsapp, its keep notifying us about new status of friend, new profile picture changes, etc ,,

how to Not receive them ? I mean we dont need processing each status update/profile image changes, just eat our 3G bandwidth. any idea ?

**Comment by mgp25** [comment]
@assegaf notifications are only received once, we automatically ack notifications
