### ISSUE TITLE
How to properly subscribe contact presence?

### ISSUE THREAD

**Issue by 3esmit** [WHAnonymous/Chat-API#1055]
I'm getting some issues about some numbers not notifying after subscribing when script restarts. 

I want to know the right moments to use sendPresenceSubscription($number) and sendPresenceUnsubscription($number);

Now what i'm doing is 
1. Subscribe the presence of every contact on connect. It never unsubscribe any presence, just If the contact is not listed anymore as to be monitored. 
2. Or should I subscribe after connect and unsubscribe before disconnect? 
3. Or maybe something else?

The my script is used for monitor wa contacts (<150 total)
I'm using password obtained with Android WA PasswordExtractor on a vm android running in my pc.
Contacts are sync in the first connect and etc. (the sequence specified in wiki is followed).

Thank you.

**Comment by mgp25** [comment]
@3esmit only use `sendPresenceSubscription($number)` when you sync that user, that means, that you only subscribe to the user once.

`sendPresenceUnsubscription($number)` only when you block or delete that contact.

**Comment by 3esmit** [comment]
Seems like it stop monitoring the contact after a while.
Sometimes the last presence event I got is an online, and it just get back working if I resubscribe the contact. 
I am thinking in a workaround to resubscribe all contacts after ping.  
What do you think?

**Comment by david-perez** [comment]
@3esmit I've also observed this behaviour. If I do not resubscribe periodically to my contacts, eventually I'll stop receiving presence updates from them. Sometimes the last presence event I receive is an online node, and WhatsApp will fail to notify me of the offline node if I do not resubscribe.

@mgp25 I doubt the official client only subscribes once after sync. Can someone double check this?

Also in [this issue](https://github.com/WHAnonymous/Chat-API/issues/938) it was said that we should subscribe every time we need to request the last seen of a contact. If we're supposed to subscribe only once after syncing a new contact, how are we supposed to know the last seen of someone? Should we store  to disk the last last seen of every single one of our contacts after every time we receive an offline node for each of them?

**Comment by mgp25** [comment]
You can also send presence as many times you want before sending a message to the contact (once in the same session)

**Comment by 3esmit** [comment]
@mgp25 My script never send messages to contacts, just monitoring their presence, status and profile picture. I configured to resubscribe all contacts every 10 minutes to see if the problem persists. 
My script is like a personal enhanced WhatsDog (app avaliable in playstore), and it's important for me to receive all presence events the more accurate as possible.  

Also, I've experienced problems where WAServer stopped sending presence event of certain numbers (even when asked for with sendPresenceSubscription), maybe because my script was syncing too many times the same contact and acting unusual (now I fixed this, but old script still seems to work better).

**Comment by mgp25** [comment]
@3esmit i'll keep that in mind. This November there is going to be a very big update of the API, and all features will work perfectly, promise :smile: 

Regards

**Comment by 3esmit** [comment]
@mpg25 I'm willing to contribute with this project. I'm kind of lost how all this ChatAPI works, I still have little idea.. I think I will try to sniff the data from an android client using this https://launchpad.net/~wireshark-whatsapp/+archive/ubuntu/ppa , do you think it will work?

**Comment by david-perez** [comment]
@3esmit Have a look at [this](https://gitlab.maikel.pro/maikeldus/WhatsSpy-Public) open source project, which internally uses Chat-Api.

**Comment by unicast** [comment]
I have similar problem with getting Last Seen status.
On official client on IOS I'm receiving Last Seen without any problem, but with Chat-API I'm always receiving type="unavailable" last="none"
