### ISSUE TITLE
Getting encrypted message

### ISSUE THREAD

**Issue by bikashmondal** [WHAnonymous/Chat-API#1056]
I am trying to receive whatsapp messages but i am getting encrypted messag. I have also seen the issue in https://github.com/WHAnonymous/Chat-API/issues/109
Please take a look at my code:-

$debug = true;
$username = '91xxxxxxxxxxx';
$password = "L9Djoxxxx+/HxxxxxWK3X24="; 
$nickname = 'SG'; 
$w = new WhatsProt($username, $nickname, $debug);
$w->connect();
$w->loginWithPassword($password);
$w->sendSetProfilePicture("demo/venom.jpg");
$s= $w->pollMessage();
for($i=0;$i<20;$i++){
      print($m->NodeString(""));
}

I have also looked at https://github.com/WHAnonymous/Chat-API/wiki/Frequently-asked-questions#avoid-encrypted-messages but it is also not working.
Is anything wrong in my code? Please help me on this.

**Comment by cincarnato** [comment]
there is nothing wrong with your code. Look at this: https://github.com/WHAnonymous/Chat-API/search?utf8=%E2%9C%93&q=encrypted&type=Issues

The team is working on encrypted message. Soon, encrypted messages will be supported. Be patient

My suggestion, register a new number, without using on android or IOS

**Comment by mgp25** [comment]
Exactly what @cincarnato said. There will be a very big update this november.

Regards

**Comment by bikashmondal** [comment]
Thanks for your reply.
What do you mean by register a new number without using ion android or IOS? Should i use a number which is not registered in whatsapp before?

**Comment by bikashmondal** [comment]
I have tried a new number and i got the verification code. When i was trying to get the password it is showing "Blocked". Could you please help me on this.
