### ISSUE TITLE
sendLockGroup() not working anymore?

### ISSUE THREAD

**Issue by modsfabio** [WHAnonymous/Chat-API#1058]
Does anyone else have this problem? 
It's just not working. The group is not being locked.

**Comment by mgp25** [comment]
@modsfabio debug log? where is the debug log? i dont see the debug log

**Comment by modsfabio** [comment]
tx  <iq id="5" xmlns="w:g2" type="set" to="**********-*************@g.us">
tx    <locked></locked>
tx  </iq>

rx  <iq from="**********-*************@g.us" type="result" id="5">
rx    <locked></locked>
rx  </iq>


This is all I can see from the sendLockGroup() -Command

**Comment by mgp25** [comment]
@modsfabio WhatsApp is not using this feature anymore. I'll remove this function from our code.

Regards

**Comment by mgp25** [comment]
@modsfabio also read this guide: https://github.com/WHAnonymous/Chat-API/wiki/How-to-write-correctly-in-Github

Remember to quote your code

**Comment by modsfabio** [comment]
@mgp25 Thanks that helped :)
