### ISSUE TITLE
how i can delete nodes?

### ISSUE THREAD

**Issue by daylox** [WHAnonymous/Chat-API#1059]
hello first sorry for bad english!

how i can delete nodes after the message was sent?

i need to make another message ex: Your Message has been sent

and thanks

**Comment by modsfabio** [comment]
What exaclty are you trying to do?

**Comment by daylox** [comment]
![sans titre](https://cloud.githubusercontent.com/assets/14987552/10305303/0516fcee-6c0f-11e5-8f9c-b609ee450aef.PNG)

i wanna delete those messages please! how i can do it?

**Comment by 0xTryCatch** [comment]
You can't, no such option in WhatsApp
