### ISSUE TITLE
received text messages

### ISSUE THREAD

**Issue by gratbrav** [WHAnonymous/Chat-API#1060]
Hi,

since today i cant received text messages. Video or Image messages be delivered correct.

I use the myevents.php file with: (reduced)
<pre>
    ...
 public $activeEvents = array(
 'onGetMessage',
 'onGetVideo',
 'onGetImage',
...
);
    public function onGetMessage($mynumber, $from, $id, $type, $time, $name, $body) 
    {
        echo 'ongetmessage';
    }
    public function onGetImage($mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption) 
    {
       echo 'ongetimages';
    }

    public function onGetVideo($mynumber, $from, $id, $type, $time, $name, $url, $file, $size, $mimeType, $fileHash, $duration, $vcodec, $acodec, $preview, $caption)
    {
          echo 'ongetvideo';
    }
</pre>

This works perfect for the last two month.

My script is still runing, and if i send a text message via mobile phone i can see the blue ticks but the function onGetMessage is never called.

This works:
- received video/image/voice message from mobile
- send text/video/image from API to mobile

Not working:
- received text messages from mobile.

If I used the same WA Account from API in my mobile phone I can received text messages.

Any idea?

**Comment by 0xTryCatch** [comment]
https://github.com/WHAnonymous/Chat-API/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+encrypted

**Comment by mgp25** [comment]
@gratbrav read this guide: https://github.com/WHAnonymous/Chat-API/wiki/How-to-write-correctly-in-Github

Remember to quote your code
