### ISSUE TITLE
Manually send read tick

### ISSUE THREAD

**Issue by estcap** [WHAnonymous/Chat-API#1061]
I've been working on a system which runs 24/7 based on this API to be able to interact to customers who desire to communicate via Whatsapp or SMS rather than by phone.
The problem is that when a customer sends a message, this API automatically sends a read receipt to them when I pull the message. The customers, who don't know this is a centralized system, think they are being ignored.

How could I just send received receipts (two gray ticks) by default instead? How to manually send the read ticks later?

Thanks and great work with this API !

UPDATE to add some source code:

```php
$w = new WhatsProt($username, $nickname, $debug);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->eventManager()->bind("onGetImage", "onImage");
$w->eventManager()->bind("onMessageReceivedClient", "onMessageReceivedClient");
$w->eventManager()->bind("onGetProfilePicture", "onGetProfilePicture");
$w->eventManager()->bind("onGetSyncResult", "onGetSyncResult");


$w->Connect();
$w->LoginWithPassword($password);



$w->sendGetPrivacyBlockedList();



while (!file_exists('stopLock')) {  // if this file exists it exits
      if (!$w->isConnected()) {
		 
 
        $w->Connect();
        $w->LoginWithPassword($password);
      }

      try {
		 	
		
        sendMessages();
		$w->pollMessage();
		usleep(1000000); //Wait 1 sec
      }
      catch(Exception $e) {
	error_log(date('l jS \of F Y h:i:s A') . " >> " . "Exception, disconnecting to connect again: " . $e->getMessage() . "\n", 3, "/usr/local/whatsapp/whatsap.log");
  
        $w->disconnect();
      }
    }

$w->disconnect();
```

**Comment by mgp25** [comment]
@estcap first of all, read this guide and quote your code: https://github.com/mgp25/Chat-API/wiki/How-to-write-correctly-in-Github

Read receipt is being set by default. Now you can't do it manually, but it will have that feature in the next release of the API.

Regards

**Comment by estcap** [comment]
Thank you for your quick reply!
Sorry for commenting after you closed this ticket, but I was wondering if this workaround could work (I will use it only for sending receipts to TEXT and IMAGE incoming messages) or am I missing something?:

I would edit ```processInboundData($data, $autoReceipt, $type)``` in whatsprot.class.php and set "receipt" as default for $type, leaving the function as:

```php

    protected function processInboundData($data, $autoReceipt = true, $type = "receipt")
    {
        $node = $this->reader->nextTree($data);
        if ($node != null) {
            $this->processInboundDataNode($node, $autoReceipt, $type);
        }
    }
	
```
I would then add this function in whatsprot.class.php:

```php

    function sendReceiptRead($from, $id)
    {
        $messageHash = array();
        if ($type == "read") {
            $messageHash["type"] = "receipt";
        }
        
        $messageHash["to"] = $from;
        $messageHash["id"] = $id;

        
         $messageNode = new ProtocolNode("receipt", $messageHash, null, null);
        
        $this->sendNode($messageNode);
        
    }
```


I would then keep track of the Receipts (that with these modifications would be sent as $type = "reciept", so no blue ticks for my customers) with onSendMessageReceived event.

Once I open the conversation I could send this for each message  I did not send a read reciept:
```php
$w->sendReceiptRead($from, $id);
```

I know this is just a temporal workaround, but would it work or am I missing something that could make my numbers blocked in the long run?

Thanks again.
