### ISSUE TITLE
How you wrote this API?

### ISSUE THREAD

**Issue by zerodwided** [WHAnonymous/Chat-API#1063]
Hi

it may seems a bit odd, but i risk and asking:

how you gathered all this fine information about whatsapp?
i really interested in!

i didn't anything like this before, but i like to do!
if i get a clear clue, i want to write same api for TANGO (or may other social mobile networking, viber, line...)

these are what came to my mind for achieving that:
-rooted virtual installed android 
-listening to i/o, network activity of app (HOW?)
-listening to memory (HOW?)
-recreating roles and function for demonstrating real activity of app

again i know this may be over wanting 
but i will be appreciated if i got any help!

thanks

**Comment by mgp25** [comment]
@zerodwided This is not a good place to ask this questions. Is not that easy, you require some basic knowledge like programming and other stuff, if you want send me a mail better

Regards
