### ISSUE TITLE
Running Multiple Instances of API in same machine

### ISSUE THREAD

**Issue by zerodwide** [WHAnonymous/Chat-API#1064]
Hi

is it possible to run multiple instances (with multiple number registered)?

i am using api in php-cli and i want to have two number working in time

the api working with socket at port 443 and i think there should no problem if two client in a machine connect to that

suggestions:
1. modifying api for configuring two number and run two times with different start parameter from terminal
2. copy entire api and set each one for one number and run separately

I'm looking for method 1 but didn't tried yet.
how many static variables defined? may those fail if run in same time?

thanks

**Comment by mgp25** [comment]
Yes, it's possible, but not an API issue, that should be coded by the developer

Regards

**Comment by zerodwide** [comment]
thanks
