### ISSUE TITLE
WhatsApp Number Registration (Some time showing not-authorized node and sometime success node)  But no message sending

### ISSUE THREAD

**Issue by vlnsnewton** [WHAnonymous/Chat-API#1068]
Dear All
@mgp25 
While i am using 9180102017** number.
I am able to get otp code on my mobile and able to get password successfully but while i am trying to send message these credentials it is showing:
```xml
rx <failure>
rx <not-authorized></not-authorized>
rx </failure>
```

so according to wiki my number is blocked. So i use blockchecker.php for confirming the same. But it says your number is not blocked and give me some other password.

And now when i am using this password for sending message it is again not able to send message but not showing any not-authorized node.
My browser is showing.
stream
auth
start
stream
challenges
response
success
presence

```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>


tx  <auth mechanism="WAUTH-2" user="9180102017**">g�z9180102017**�@\o߀p`�;�W-�-1444370997</auth>


rx  <start from="s.whatsapp.net"></start>


rx  <stream:features></stream:features>


rx  <challenge>�H�!(qM�r>�����}�?�</challenge>


tx  <response>￲s��m�B��k�i�%S*�=WG������@>5</response>


rx  <success t="1444371389" props="4" kind="free" status="active" creation="1444329814" expiration="1475865814">Ë�̷�灵�bp��z��y;</success>


tx  <presence name="fhruy"></presence>
```

I am not getting where is error and if my number is blocked then why `blockchecker.php` is showing it as not blocked.
2. and if i am checking last seen of this number from another android device then it is showing the updated one.
3. and some time i found that api shows number blocked but still i run the same number.
4. is this something related to credentials mismatch not to number block.

Here is my simple code

```php
$sender = 	"9180102017**"; // Mobile number with country code (but without + or 00)
$password =   "*******************"; // Password you received from WhatsApp
$nickname="fhruy";
$dst = "919717474431";
require '../src/whatsprot.class.php';
$w = new WhatsProt($sender, $nickname, true);
//$w->codeRequest('sms');
//$w->codeRegister('*******');
$w->connect(); 
$w->loginWithPassword($password);
//$w->sendGetGroups();
//$w->checkCredentials();
$newContact = array($dst);
$w->sendSyn($newContact);
$w->sendPresenceSubscription($dst);
$w->sendMessageComposing($dst); // Send composing
$w->sendMessagePaused($dst); // Send paused
$message = 'Hi! :) this is a test message';
$w->sendMessage($dst , $message); // Send message
$w->pollMessage();
```

and i havn't did any change in  `blockchecker.php` except placing my number.

Thanx

waiting for ur kind revert.

**Comment by mgp25** [comment]
@vlnsnewton 

In your code:

```php
$w->sendSyn($newContact);
```

That's not right, it should be:

```php
$w->sendSync($newContact);
```

Also, the script finishes too soon, i recommend you to add more `pollMessage()` in order to send the message. I also recommend you to run scripts in terminal (command line).

So your code should be like this (Notice that i hid your numbers, change it):

```php
<?php
require '../src/whatsprot.class.php';

//// CONFIG ///
$sender =   "9180102017**"; // Mobile number with country code (but without + or 00)
$password =   "*******************"; // Password you received from WhatsApp
$nickname="fhruy";
$dst = "9197174744**";
$message = 'Hi! :) this is a test message';
////////

$w = new WhatsProt($sender, $nickname, true);
$w->connect(); 
$w->loginWithPassword($password);

$w->sendSyn(array($dst));
$w->sendPresenceSubscription($dst);
$w->sendMessageComposing($dst); // Send composing
sleep(1);
$w->sendMessagePaused($dst); // Send paused
$w->sendMessage($dst , $message); // Send message
for($i = 0; $i < 5; $i++) {
    $w->pollMessage();
}
```

Regards

**Comment by vlnsnewton** [comment]
@mgp25  
still not working same output
 now i am using same code u written above with required changes like 
sendSync(array($dst));

**Comment by mgp25** [comment]
@vlnsnewton 

- Do you have all dependencies installed?

If you have dependencies installed, i suggest you to test your script in command line before trying to run it directly in a webserver. 

The code seems fine, so its something related to the server.

**Comment by vlnsnewton** [comment]
@mgp25 
yes by using command line it is showing fatal error.

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="918010201766">T▒▒▒918010201766▒▒,▒▒▒▒▒▒/ְ
▒1444372163</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>▒s▒▒EÇ▒}▒%{y'p▒~h</challenge>

tx  <response>I▒▒^a▒▒+1K▒]xf@▒p▒▒!▒I    N▒5~7V</response>

rx  <success t="1444372555" props="4" kind="free" status="active" creation="1444329814" expiration="1475865814">▒       ▒▒"▒*▒[▒▒է▒21▒q▒</success>

PHP Warning:  file_put_contents(/var/www/html/hybrid29/wa/src/wadata/nextChallenge.918010201766.dat): failed to open stream: Permission denied in /var/www/html/hybrid29/wa/src/whatsprot.class.php on line 2528
tx  <presence name="fhruy"></presence>

PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/hybrid29/wa/src/whatsprot.class.php on line 2243

**Comment by mgp25** [comment]
@vlnsnewton there is your problem:

First of all you need to change permissions in this folder `/var/www/html/hybrid29/wa/src/wadata/` `chmod 777`, or if you are using an FTP, grant write permissions to that folder.

Also you have this error: 
```
PHP Fatal error:  Call to undefined function mcrypt_create_iv() in /var/www/html/hybrid29/wa/src/whatsprot.class.php on line 2243
```

Which means you dont have installed `mcrypt` extension for php. If you install it you will sove this problem

Regards

**Comment by vlnsnewton** [comment]
@mgp25 
my wadata directory has 777 permission and nexchallange has 644 permission

**Comment by vlnsnewton** [comment]
@mgp25  
is this ```mcrypt``` extension is newly added in chat-api because in ur previous api i have successfully able to send message with same directory/dependencies and permissions.

and thanx for quoting suggestion :)

**Comment by mgp25** [comment]
@vlnsnewton then change file permissions to 777

`mcrypt` was added long time ago. That gives the user better security

Regards

**Comment by ariel12345** [comment]
I have this problem that my account is blocked and this presents a serious error to me , so what I have to do ????????????????? Please help me , I could not send a message once
