### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by arth1992** [WHAnonymous/Chat-API#1069]
Whenever i change number it shows this error each and every piece of code is correct. Any particular reason for this ? or any special requirement needed to make the number work

**Comment by mgp25** [comment]
@arth1992 as you have said, is an `Internal Server Error 500` not API issue. It's a server issue.

Regards

**Comment by arth1992** [comment]
But if i  change to old number it works fine .

**Comment by arth1992** [comment]
n i also tried your examples folder to test it and it shows the same error
