### ISSUE TITLE
how to send message to multiple numbers and send from multiple accounts?

### ISSUE THREAD

**Issue by daylox** [WHAnonymous/Chat-API#1073]
Hello

how i can send message to multiple numbers and send from multiple whatsapp accounts 

i try to use array to send message to multiple numbers but it's doesn't work
and i try to use random() to send from multiple whatsapp accounts and it's doesn't work too

thanks :)

**Comment by CODeRUS** [comment]
this is not possible with  chat-api, sorry

**Comment by daylox** [comment]
okey thanks :)
