### ISSUE TITLE
Missing description in "Extracting password from device"

### ISSUE THREAD

**Issue by francwalter** [WHAnonymous/Chat-API#1076]
In the description [Extracting password from device](https://github.com/WHAnonymous/Chat-API/wiki/Extracting-password-from-device) I don't find a description what is ment with this part (a bash-script):
```
#!/bin/bash

TELNUM='99123456789'
if ! [ -r pw ]; then exit 1; fi

dd if=pw of=pw_salt bs=1 skip=29 count=4
hexdump -e '2/1 "%02x"' pw_salt
dd if=pw of=pw_iv bs=1 skip=33 count=16
dd if=pw of=pw_ekey bs=1 skip=49 count=20

echo -n 'c2991ec29b1d0cc2b8c3b7556458c298c29203c28b45c2973e78c386c395' | xxd -r -p > pbkdf2_pass.bin
echo -n $TELNUM | hexdump -e '2/1 "%02x"' | xxd -r -p >> pbkdf2_pass.bin
```
It is not explained in the code, what this does or how it is used. I read that there is a variable TELNUM to be changed but I don't find an explanation for the hex "c2991ec29b1d0cc2b8c3b7556458c298c29203c28b45c2973e78c386c395" in the second last command.
What is that? Do I need to change it? What do I put there?
I think maybe this is some message from the phone where the password is used?
Please explain.

Thanks
frank

**Comment by mgp25** [comment]
@francwalter read full description: https://github.com/WHAnonymous/Chat-API/wiki/Extracting-password-from-device#bash

Only thing to change is `TELNUM`

**Comment by francwalter** [comment]
OK, it works. I did change only TELNUM and the new generated password works!
Thank you.
But it would be nice to add one line to explain this bash script, e.g.:
> save and run this bash script:
I would do it if it were a real wiki.

**Comment by mgp25** [comment]
@francwalter some things are obvious enough, no one pays me for this, i wrote the wiki to guide people, but i cant spent all my time writing a full documentation wiki, some of the things should be researched by the user

**Comment by francwalter** [comment]
Your right.
I guess as this bash thing addresses a bit advanced users anyway, there is no beginners question at this point :)
Anyway, I found it and it works, great and thanks for your work and time!!!
