### ISSUE TITLE
Number blocked.

### ISSUE THREAD

**Issue by abhishekdeshkar** [WHAnonymous/Chat-API#1079]
Hello,

My number got blocked. I sync my friend list and sent them my exam time table and my phone number got blocked. Why ?

**Comment by 0xTryCatch** [comment]
We don't know

**Comment by mgp25** [comment]
@abhishekdeshkar where is your debug log? without debug log i can't help you. Have you tried `blockChecker.php`

Read the wiki and always post debug log

**Comment by abhishekdeshkar** [comment]
Yes I checked. It says your number is blocked. Is that possible that I sent same image to 40-50 college friends and they banned ?

**Comment by mgp25** [comment]
@abhishekdeshkar Have you read the wiki?

If you send a message to a contact and that contact don't have your number added, you will be blocked, as simple as that.

**Comment by abhishekdeshkar** [comment]
When I send message to single contact and that contact dont have my number at that time it doesn't get blocked. Then why this time ?

**Comment by mgp25** [comment]
Read the wiki
