### ISSUE TITLE
sendMessageAudio : extensions : audio/x-hx-aac-adts ?

### ISSUE THREAD

**Issue by yagerstano** [WHAnonymous/Chat-API#1081]
Undefined index: 
```
audio/x-hx-aac-adts in func.php on line 241
```
Was trying to send .wav audio file

Bad file maybe ?

**Comment by viniciusjarina** [comment]
Try sending a mp3 or aac file.

**Comment by mgp25** [comment]
```php
'audio/wav'       => 'wav',
```

Depends on the mime type it has, the one i posted is the one we are using for .wav files

Regards

**Comment by yagerstano** [comment]
the mime type of my file : audio/x-hx-aac-adts.
func.php might need a default in the switch as it does not handle all cases.
meaning some legit mime types will get this error.

**Comment by mgp25** [comment]
@yagerstano send a pull request
