### ISSUE TITLE
Emoji Parser

### ISSUE THREAD

**Issue by arth1992** [WHAnonymous/Chat-API#1085]
There is no function to ##1F604## kind of code to unicode so that it can see as smiley in whatsapp message. I tried all your provided soultions in wiki but no one worked. Is there any bug in api , beacuse i also tried your example which also behaves as same.

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/wiki/Frequently-asked-questions#how-can-i-send-emojis

+ 

There is emoji helper class

**Comment by arth1992** [comment]
i already have utf8 header set in php file. n when i use smiley.class.php it doesnt work. I use  __get($code)  to parse the whole message i.e "This is a test message ##1F601##"  but is shows blank.

**Comment by mgp25** [comment]
@arth1992 have you read the damn link i posted? + please quote the stuff for easy reading

**Comment by arth1992** [comment]
check it now @mgp25

**Comment by mgp25** [comment]
@arth1992 have you read the wiki?

#How can i send emojis?

You will need to have UTF8 enabled. Once then, you can send an emoji like this:

```php
$msg = "Hello \xF0\x9F\x98\x84 !";
```

All emojis here (Bytes - utf8): http://apps.timwhitlock.info/emoji/tables/unicode


This is explained in the wiki, use that format

**Comment by arth1992** [comment]
@mgp25 i already visited that link . I want a function which perform this action. ie a function that convert ```php F601 ``` to ```php  \xF0\x9F\x98\x84 ```

**Comment by mgp25** [comment]
@arth1992 you have to code it yourself, is not an API related issue

**Comment by q4z1** [comment]
Here is way to decode hex messages and converting most emojis to html entities.

The function wp_encode_emoji is taken from:
http://wp-a2z.com/oik_api/wp_encode_emoji/

`function wp_encode_emoji( $content ) {
  if ( function_exists( 'mb_convert_encoding' ) ) {
    $regex = '/(
		     \x23\xE2\x83\xA3               # Digits
		     [\x30-\x39]\xE2\x83\xA3
		   | \xF0\x9F[\x85-\x88][\xA6-\xBF] # Enclosed characters
		   | \xF0\x9F[\x8C-\x97][\x80-\xBF] # Misc
		   | \xF0\x9F\x98[\x80-\xBF]        # Smilies
		   | \xF0\x9F\x99[\x80-\x8F]
		   | \xF0\x9F\x9A[\x80-\xBF]        # Transport and map symbols
		)/x';

    $matches = array();
    if ( preg_match_all( $regex, $content, $matches ) ) {
      if ( ! empty( $matches[1] ) ) {
        foreach ( $matches[1] as $emoji ) {
          /*
					 * UTF-32's hex encoding is the same as HTML's hex encoding.
					 * So, by converting the emoji from UTF-8 to UTF-32, we magically
					 * get the correct hex encoding.
					 */
          $unpacked = unpack( 'H*', mb_convert_encoding( $emoji, 'UTF-32', 'UTF-8' ) );
          if ( isset( $unpacked[1] ) ) {
            $entity = '&#x' . ltrim( $unpacked[1], '0' ) . ';';
            $content = str_replace( $emoji, $entity, $content );
          }
        }
      }
    }
  }

  return $content;
}

$hex = "f09f988ef09f9898f09f98842068616861"; // example hex message
$pattern ="/^([a-f0-9])+$/";
if(preg_match($pattern, $hex) > 0){
  $ha = array();
  $i=0;
  while($i<strlen($hex)){
    if(substr($hex, $i, 2) == "f0"){
      // 4 byte emoji
      $ha[] = substr($hex, $i, 8);
      $i += 8;
    }else if(substr($hex, $i, 2) == "e2"){
      // 3 byte emoji
      $ha[] = substr($hex, $i, 6);
      $i += 6;
    }else if(substr($hex, $i, 1) == "c"){
      // 2 byte utf
      $ha[] = substr($hex, $i, 4);
      $i += 4;
    }else{
      // 1 byte utf
      $ha[] = substr($hex, $i, 2);
      $i += 2;
    }
  }
  
  for($i=0; $i<count($ha); $i++){
    $utf = "";
    $split = str_split($ha[$i], 2);
    foreach($split as $byte){
      $utf .= pack("H*", $byte);
    }
    $ha[$i] = $utf;
  }
  
  $msg = "";
  foreach($ha as $utf){
    $msg .= wp_encode_emoji($utf);
  }
}else{
  $msg = $hex;
}
echo $msg."\n";`
