### ISSUE TITLE
Response after sending message 

### ISSUE THREAD

**Issue by arth1992** [WHAnonymous/Chat-API#1086]
When i send a message i get response like this 
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="91992*******">Z��91992*******���)!���p�Uh�g� �1444915763</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>:e,9���&�o�=�N�{�</challenge>

tx  <response>$��[v�9�=U>r�k_��D]�,�+�~$�g ��</response>

rx  <success t="1444916064" props="4" kind="free" status="active" creation="1439018495" expiration="1470554495">��jm�w}�1�ꫲʻ��</success>

tx  <presence name="DB Corp"></presence>

tx  <chatstate to="91992*******@s.whatsapp.net">
tx    <composing></composing>
tx  </chatstate>

tx  <chatstate to="91992*******@s.whatsapp.net">
tx    <paused></paused>
tx  </chatstate>

tx  <message to="91992*******@s.whatsapp.net" type="text" id="1444915764-1" t="1444915766">
tx    <body>1F600</body>
tx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="91992*******@s.whatsapp.net"></presence>

rx  <presence from="91992*******@s.whatsapp.net" type="unavailable" last="1444915568"></presence>

rx  <ack from="91992*******@s.whatsapp.net" class="message" id="1444915764-1" t="1444916067"></ack>

rx  <receipt from="91992*******@s.whatsapp.net" id="1444915764-1" t="1444916069"></receipt>

tx  <ack to="91992*******@s.whatsapp.net" class="receipt" id="1444915764-1"></ack>

Message sent successfully!
```

There is no function in api to retrieve status like if message is read or not , and parse this response in proper json format

Can you provide some solution for this ?

**Comment by mgp25** [comment]
@arth1992 please can you quote properly the debug log. Here is a guide to quote debug and code: https://github.com/WHAnonymous/Chat-API/wiki/How-to-write-correctly-in-Github

When you have quote it, let me know

**Comment by arth1992** [comment]
@mgp25  updated. n sorry for the inconvenience u had

**Comment by mgp25** [comment]
@arth1992 yes, there is, read the wiki, and check event system

There are examples using events in `/examples` folder

Regards

**Comment by arth1992** [comment]
@mgp25  i have read whole wiki , only after reading and trying examples i came here . and the problem still persist.

**Comment by mgp25** [comment]
@arth1992 use event system and check the available events, also listed in the wiki too

**Comment by arth1992** [comment]
@mgp25  i used event on send message ```php
public function onSendMessage($mynumber, $target, $messageId, $node)
    {
        echo "<p>Whoa! Your message sent.</p>";
    } ```   but still all the ```tx``` and ```rx``` gets print alongwith tha above function messsage. How to escape all this response nodes
