### ISSUE TITLE
Last seen always returns the same value

### ISSUE THREAD

**Issue by MarcoG3** [WHAnonymous/Chat-API#1087]
```xml
tx  <presence type="subscribe" to="TheNumberQueried@s.whatsapp.net"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="12267741740@s.whatsapp.net"></presence>

rx  <presence from="TheNumberQueried@s.whatsapp.net" type="unavailable" last="1444917543"></presence>
```

This is what I get. If I want to search for another number, in the logs I still see TheNumberQueried last seen value. Hows that?

**Comment by mgp25** [comment]
@MarcoG3 i don't understand you, give a real example

**Comment by MarcoG3** [comment]
```php
$i = 0;
$this->_protocol->sendPresenceSubscription($prefix . $phone);

while($i < 5 && empty($this->_lastSeen))
{
    sleep(1);
    $this->_protocol->pollMessage();

    $i++;
}
```

This is a part of the code I use to get last seen value. I didn't find any other way to get it aside from asynchronous way. It is hard to explain using debug message, just know that whatever number I try to get the last seen on whatsapp, I get the same value.

**Comment by mgp25** [comment]
@MarcoG3 you shouldnt do that in a loop, whatsapp takes its time to give a new result, remeber that what you are doing there is sending a subscription multiple times, so it doesnt make sense at all

Regards

**Comment by MarcoG3** [comment]
I don't send a subscription multiple times, I send it once and every second I try to poll message to see if I received the last seen response. It makes sense because I get the result after couple of second and I've set a timeout of 5 seconds. If I try to increase it to 15 seconds it still gives the same result.

I send this

```
tx  <presence type="subscribe" to="FirstNumber@s.whatsapp.net"></presence>
```

and receive this

```
rx  <presence from="12267741740@s.whatsapp.net"></presence>

rx  <presence from="NumberIQueriedBefore@s.whatsapp.net" type="unavailable" last="1444917543"></presence>
```

```FirstNumber``` is the number I am actually querying.
```NumberIQueriedBefore``` is the number I queried couple minutes ago and its different than ```FirstNumber```

**Comment by mgp25** [comment]
@MarcoG3 sorry, i misunderstood your code, yes you are right.

Does that number exists? If its online you will receive a node like this one:

```xml
rx  <presence from="12267741740@s.whatsapp.net"></presence>
```

which means the user is online at the moment. If you are subscribing to `12267741740` you are getting:

```xml
rx  <presence from="12267741740@s.whatsapp.net"></presence>  
```

So its online

**Comment by MarcoG3** [comment]
Yes the number exists. The problem is that I receive a node with a "from" different than the number I am "asking" the last seen. How is that possible?

**Comment by mgp25** [comment]
@MarcoG3 send me a mail with the number, and let me try it, and ill tell you

**Comment by MarcoG3** [comment]
The problem is not the number. If I query a number, for example, every 5 minutes I get correct value, if I query it with some seconds of delay I get the previous number results everytime. I guess WhatsApp limited the number somehow, it worked until yesterday.

**Comment by mgp25** [comment]
You shouldnt request the time that fast is the only thing i can say to you

**Comment by MarcoG3** [comment]
Even if I request it every minute the problem occurs. Could you check it with 2-3 numbers and let me know if it works for you?

**Comment by mgp25** [comment]
@MarcoG3 sure

**Comment by MarcoG3** [comment]
Any update?

**Comment by mgp25** [comment]
@MarcoG3 im waiting you to send me the numbers

**Comment by MarcoG3** [comment]
Oh, sorry. I thought you had numbers to test it with. By the way I just tested again and it now works, looks like yesterday WhatsApp had some problem. Thank you for your time and have a great day

**Comment by 3esmit** [comment]
MarcoG3, are you using a new WA account or a password extracted with android tool? I found out that if I use a WA account previously used in official app, sometimes there are already numbers subscribed for presence. When you open a chat with a contact it subscribes the precense.

**Comment by MarcoG3** [comment]
@3esmit This actually is a phone number that was never used on official app. I noticed the subscription persists in WA server until you subscribe for more and more numbers, it's like a queue.
