### ISSUE TITLE
Help with onGetError event

### ISSUE THREAD

**Issue by foxpcteam** [WHAnonymous/Chat-API#1088]
Hi,
i have read the wiki. and did not found any info about "onGetError" event.

i want to get feedback if there was any error and the message did not send true Chat-API.

so i have create function

```php
		function onGetError( $mynumber, $from, $id, $data ) {
		 // if i got error i can send the same message true sms for example
		}
```

now i have add
```php
$w->eventManager()->bind("onGetError", "onGetError");
```
after 
```php
$w->sendMessage($target,$message );
```

what i am missing?

Thanks

**Comment by mgp25** [comment]
@foxpcteam is that hard to quote code properly? Please, next time quote it.

_sigh..._ if you are not receiving anything from your event it means you didn't receive any error node

**Comment by foxpcteam** [comment]
Hi,
i will use this events to send sms if the WH field for some reson
```php
onConnectError( $mynumber, $socket )
onLoginFailed( $mynumber, $data )
onCredentialsBad( $mynumber, $status, $reason )
onGetPrivacyBlockedList( $mynumber, $data )
onGetError( $mynumber, $from, $id, $data )
```
The question is how can i pass $message and $target parameter to each event?
or if there is any other way to get this parameters from the event so i can send sms.

Thanks

**Comment by 0xTryCatch** [comment]
This is not an API questions but a programming question.

**Comment by 3esmit** [comment]
Try using onSyncResult, if user don't have WA send via SMS. Also I think there is some functions to check if user recievied/read the message that can be used to what you need.
