### ISSUE TITLE
Encrypted messages after registering new numbers - I READ THE FAQ

### ISSUE THREAD

**Issue by yniv** [WHAnonymous/Chat-API#1091]
Since a couple of weeks all newly registered numbers are getting encrypted messages...!
I registered them with registerAccount.php and also used resetAccount.php (as the FAQ says) but it doesn't help!
Anybody else has this problem? Is there a solution out there?
Any Help will be greatly appreciated!

**Comment by mgp25** [comment]
@yniv oks, you have read the wiki, ok, but have you read previous issues? I think not, because i already explained this:

Chat API (php) will have support of encrypted messages in the next API release on the 1st of November. Chat API (.NET) won't support encrypted messages.

**Comment by vovanb** [comment]
What should be done to support encryption in .Net?

**Comment by mgp25** [comment]
@vovanb lots of things and i dont have time enought to do it in .NET

**Comment by vovanb** [comment]
Ok - so technically it is possible - let's wait to you php version and them
we(community) could update .net version may be.

On Sun, Oct 18, 2015 at 12:33 PM, mgp25 <notifications@github.com> wrote:

> @vovanb <https://github.com/vovanb> lots of things and i dont have time
> enought to do it in .NET
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1091#issuecomment-148995153>
> .
>



-- 
Sincerely,
Vladimir

**Comment by yniv** [comment]
@vovanb It is possible. Yowsup has already implemented it in python. I'm willing to port it to .NET. any help will be is appreciated
@mgp25 looks like first we need to port the libaxolotl-java right?

**Comment by mgp25** [comment]
Check my repos, thats it
