### ISSUE TITLE
Group Media messages not acked

### ISSUE THREAD

**Issue by ankushsachdeva** [WHAnonymous/Chat-API#1092]
When WhatsAPI client receives any media as a group message it does not send the ack even when autoReceipt is true

**Comment by mgp25** [comment]
@ankushsachdeva post debug log

**Comment by ankushsachdeva** [comment]
Ack for a group media message looks like this
<receipt to="91xxxxxxxxxx-xxxxxxxxxx@g.us" id="/xxxxxxxxxxxx"></receipt>

It is missing participant attribute

**Comment by ankushsachdeva** [comment]
Ack for a group media message looks like this
```xml
<receipt to="91xxxxxxxxxx-xxxxxxxxxx@g.us" id="/xxxxxxxxxxx"></receipt>
```
It is missing participant attribute

**Comment by mgp25** [comment]
Receipt != Ack

I'll check this, and if there is any error, i will push a fix in the next API release on the 1st of November

Regards
