### ISSUE TITLE
name of the location

### ISSUE THREAD

**Issue by raniongolu** [WHAnonymous/Chat-API#1098]
onGetLocation not showing name of the location $url came empty

**Comment by mgp25** [comment]
Show debug log and your code

Regards

**Comment by raniongolu** [comment]
function onGetLocation($mynumber, $from, $id, $type, $time, $name, $nameLocation, $longitude, $latitude, $url, $preview )
	{
echo $url;
echo $nameLocation;
}
$w->eventManager()->bind("onGetLocation", "onGetLocation");

**Comment by mgp25** [comment]
@raniongolu and debug log?
