### ISSUE TITLE
What is the type attribute of  sendReceipt() to just send a "message recieved" ack?

### ISSUE THREAD

**Issue by estcap** [WHAnonymous/Chat-API#1099]
I am tweaking the library a bit, particularly to manually send the read receipts.
When one calls ```pollMessages()``` , it actually assumes that ```$type='read'``` .
What is the value of ```type``` to just send double gray ticks (aka message reached my device but I have not read it yet)?

**Comment by mgp25** [comment]
@estcap i know, this is already included in the next API release that will be published on the 1st November

`receipt`

Regards
