### ISSUE TITLE
I receive whatsapp message is in encrypted format - (PHP)

### ISSUE THREAD

**Issue by Cubel89** [WHAnonymous/Chat-API#1100]
I am receiving encrypted messages even after you have removed the account and have created it from http://www.watools.es/ 

Debug:
[```]
rx  <receipt from="3462xxxxxxx@s.whatsapp.net" type="read" id="zfTNj/0tzvFQ0" offline="0" t="1445409317"></receipt>
tx  <ack to="3462xxxxxxx@s.whatsapp.net" class="receipt" id="zfTNj/0tzvFQ0" type="read"></ack>
rx  <message from="3462xxxxxxx@s.whatsapp.net" type="text" id="b4EG9TtrS3er5" offline="0" t="1445409322" notify="Cubel">
rx    <enc v="1" type="msg">3 !¦D%C*RG"·®[²‘–B®H 3sWDï‰ý›y"b/&@ÑEPŠdR€Ëè|Ã•Q@‘?\*</enc>
rx  </message>
tx  <receipt type="read" to="3462xxxxxxx@s.whatsapp.net" id="b4EG9TtrS3er5"></receipt>
[```]

sendGetServerProperties
[```]
tx  <iq id="3" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="S40" version="2.13.4"></config>
tx  </iq>
[```]

**Comment by mgp25** [comment]
@Cubel89 you haven't read previous issues, you haven't quoted correctly the debug and thats not `sendGetServerProperties`

This Friday im releasing new API which support encryption.
