### ISSUE TITLE
'Class 'ProtobufMessage' not found' 

### ISSUE THREAD

**Issue by 3x14159265** [WHAnonymous/Chat-API#1101]
I'm getting following error message when calling ```pollMessages()```:

```
'Class 'ProtobufMessage' not found' in vendor/whatsapp/chat-api/src/libaxolotl-php/protocol/pb_proto_WhisperTextProtocol.php:12
```
"whatsapp/chat-api": "2.5.5" && "whatsapp/chat-api": "2.5.5.1"

**Comment by jcav2** [comment]
Go to https://github.com/WHAnonymous/Chat-API/wiki/Dependencies

You need PHP Protobuf installed.

Regards,
Juan

<http://www.surbit.uy/>

[image: Facebook] <https://www.facebook.com/surbituy?fref=ts>

Ing. Juan Carlos Alvarez / CEO
juan@surbit <juan@surbit.uy>.uy / 099495475

Surbit
26826065
Park Way M18 S14 LagomarCanelones - Uruguay
http://www.surbit.uy

2015-10-21 11:48 GMT-03:00 david pichsenmeister <notifications@github.com>:

**Comment by mgp25** [comment]
@3x14159265 i just added compatibility fix, for people who dont wan't or doesnt have modules installed, it should work now for you

**Comment by 3x14159265** [comment]
cool, thanks :)
