### ISSUE TITLE
Class 'ProtobufMessage' not found

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#1103]
Fatal error: Class 'ProtobufMessage' not found in C:\xampp\htdocs\whatsapp\src\libaxolotl-php\protocol\pb_proto_WhisperTextProtocol.php on line 12 @mgp25 @WHAnonymous

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/wiki/Dependencies

**Comment by beljk** [comment]
look dear , i am newer in php so i don't know what i do exactly but i think you mean i must install this Dependencies so can you give me steps to do that for windows @mgp25

**Comment by mgp25** [comment]
@beljk can you try now with the latest commit?

Regards

**Comment by beljk** [comment]
Dear @mgp25  i know you are tired :) but i still found the same issue

**Comment by welcomehelp** [comment]
Is this helpful?
http://php.net/manual/en/install.windows.extensions.php

**Comment by mgp25** [comment]
@beljk check now latest commit

**Comment by beljk** [comment]
Dear @mgp25  now is working fine , Thanks a lot for you
Best regards
