### ISSUE TITLE
Why php 5.6?

### ISSUE THREAD

**Issue by pcabreus** [WHAnonymous/Chat-API#1104]
I'm using an old version of this library, today I update my code and see that requirement. My server is PHP 5.4 not 5.6 please, and the other dependencies...for what??.
Can I keep the old version 2.5.4 and will work ok???

**Comment by mgp25** [comment]
_sigh..._

1. Have you tried before opening this issue?
2. Is explained in the wiki why you need Curve25519 and Protobuf
3. It bothers me when people make questions with a lot of quiestion marks

Its better this:
>  Can I keep the old version 2.5.4 and will work ok?

than this:

>  Can I keep the old version 2.5.4 and will work ok???

And answering to your question:

If you don't plan to use e2e encryption, go ahead, it will work in your actual php version.

_Turning off notifications_
Gn

Regards

**Comment by pcabreus** [comment]
Sorry for my ??? It was because I was not good in that moment.

**Comment by pcabreus** [comment]
So why do so much in the wiki and no create a blog, with an article for every big change and why of this change. I need review all the wiki every day locking for changes?
