### ISSUE TITLE
Block Number Problem! Block number if check whatsapp users

### ISSUE THREAD

**Issue by rkazanova** [WHAnonymous/Chat-API#1107]
Do somebody know why whatsapp blocks accounts if we do only synchronizing contacts?

**Comment by 0xTryCatch** [comment]
Debug log please

**Comment by rkazanova** [comment]
Debug isn't help here. Cannot connect to whatsapp by reason : blocked
 
PHP Fatal error:  Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in git/mobile_whatsapp_api/src/whatsprot.class.php:179
Stack trace:
#0git/mobile_whatsapp_api/examples/blockChecker.php(34): WhatsProt->checkCredentials()
#1 {main}
  thrown in git/mobile_whatsapp_api/src/whatsprot.class.php on line 179

**Comment by 0xTryCatch** [comment]
Nobody knows

**Comment by 3esmit** [comment]
Probably a problem with your script. Who sync 500 contacts per day? This might sound strange to WA Server. Also, your server ip might be flagged as abusive too. Try changing server IP and generating a script that looks like an human. 

Maybe you should sync a contact just one time, and a batch of them everytime.

**Comment by 0xTryCatch** [comment]
You are abusing WhatsApp so they block you.

**Comment by candidature** [comment]
And what is the process to unblock?

**Comment by 0xTryCatch** [comment]
Email them and ask for forgiveness. Slight chance they will help you.

**Comment by mgp25** [comment]
![damn](http://s22.postimg.org/p423cs9mp/sydn6.jpg)

**Comment by hansrouge** [comment]
@mgp25 I dont want to bother you, but I still have the same problem.

I tried it with a number that didnt connect to WA for a month and I use a new webspace with a new ip.
I didn't sync this account for 30 days and today I tried to sync just 3 contacts and the number got blocked.
```
tx  <iq id="3" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="background" sid="130900578740000000" index="0" last="true">
tx      <user>+**</user>
tx      <user>+**</user>
tx      <user>+*</user>
tx    </sync>
tx  </iq>

rx  <iq from="**@s.whatsapp.net" type="result" id="3">
rx    <sync index="0" sid="130900578740000000" last="true" version="1445580674305897">
rx      <in>
rx        <user jid="**@s.whatsapp.net">+**</user>
rx        <user jid="**@s.whatsapp.net">+**</user>
rx        <user jid="**@s.whatsapp.net">+**</user>
rx      </in>
rx    </sync>
rx  </iq>

rx <stream:error>
rx  <system-shutdown></system-shutdown>
rx </stream:error>
```

I seems a little strange, that I cant even sync 3 numbers. That is not abusive or anything. :-/

**Comment by catch2patch** [comment]
Have you updated you code to the latest release?

**Comment by hansrouge** [comment]
Not yet, it doesnt seem to be stable enough and I need to do too much changes.
It doesnt seem to be a problem with the WA version, does it?

**Comment by rkazanova** [comment]
I have updated version one time before last release. I check that in last release didn't add something magic.

**Comment by mgp25** [comment]
@hansrouge Its something from your connection/server/script. It works perfectly and its super stable + i recommend you to update the code because it has many improvements. And again, i tell you its something related to your connection, not API issue, thats why you are getting:

```xml
rx <stream:error>
rx  <system-shutdown></system-shutdown>
rx </stream:error>
```

I just tried and like always, API works perfect

```xml
tx  <iq id="1" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="130900633040000000" index="0" last="true">
tx      <user>+A</user>
tx      <user>+B</user>
tx    </sync>
tx  </iq>

rx  <presence from="MyNumber@s.whatsapp.net"></presence>

rx  <iq from="MyNumber@s.whatsapp.net" type="result" id="1">
rx    <sync index="0" sid="130900633040000000" last="true" version="1445242290533772">
rx      <in>
rx        <user jid="A@s.whatsapp.net">+A</user>
rx        <user jid="B@s.whatsapp.net">+B</user>
rx      </in>
rx    </sync>
rx  </iq>
```

**Comment by hansrouge** [comment]
@mgp25  I will email you.

**Comment by 0xTryCatch** [comment]
@hansrouge put me on CC please

**Comment by hansrouge** [comment]
@0xTryCatch Sure! Where can I find your mail? It is not in your profile.
