### ISSUE TITLE
Cannot access protected property WhatsProt::$axolotlStore

### ISSUE THREAD

**Issue by burpy** [WHAnonymous/Chat-API#1109]
If I get a message I get this error:

`PHP Fatal error:  Cannot access protected property WhatsProt::$axolotlStore in /usr/share/php/vendor/whatsapp/chat-api/src/handlers/NotificationHandler.php on line 84`

with the current version v2.5.5.2.

**Comment by mgp25** [comment]
@burpy it should work now

Regards
