### ISSUE TITLE
Right use of API

### ISSUE THREAD

**Issue by candidature** [WHAnonymous/Chat-API#1110]
Hi,
I plan to use these APIs in my business. I may be creating 100's of groups spread over months and add 30-50 phone numbers to each group.

My usage would be for my business expansion purpose, will that qualify as "abuse" for whatsapp to block my number?

How can i legally stay in the right path and take benefit of this technology.

--

**Comment by 0xTryCatch** [comment]
It is not allowed: https://www.whatsapp.com/legal/

**Comment by candidature** [comment]
very bad.. i have no choice that to switch to telegram.

**Comment by mgp25** [comment]
@candidature you can also use this other API i did: https://github.com/mgp25/Telegram-Bot-API

**Comment by candidature** [comment]
@mgp25 Thank you so much for the pointer. I think equivalent of whatsapp group telegram has channel. In telegram's groups feature we can't add more people after creation.
I think your API still don't have channel creation and user addition support. Do you plan to add that?
