### ISSUE TITLE
Alternative Extension Curve25519

### ISSUE THREAD

**Issue by tuadmin** [WHAnonymous/Chat-API#1111]
for alternative in pure php for LIB Curve25519

https://github.com/lt/PHP-Curve25519/tree/master/lib

and other projects interesants for LIB PROTOBUF(
Still I do not understand how the library works)

https://code.google.com/p/pb4php/

**Comment by 0xTryCatch** [comment]
Thanks

**Comment by mgp25** [comment]
@tuadmin we have built our own curve extension because that doesnt have some functions we need.

**Comment by tuadmin** [comment]
y no lo pueden portar a PHP , por que uso windows 10 y no se como
compilarlo aca

**Comment by mgp25** [comment]
@tuadmin Protobuf and curve extensions are optional, you can run the API without any problem

These extensions only enables encryption/decryption of messages.

No, i don't have time to port it, im a student and i have a lot of study and more stuff to do. There are guides in internet on how to compile them for windows

Regards
