### ISSUE TITLE
Problem Send Message in Login.php

### ISSUE THREAD

**Issue by emarketingw** [WHAnonymous/Chat-API#1113]
While sending it is giving error in line 63 in login.php file always.

Please advise.

**Comment by 0xTryCatch** [comment]
Ok

**Comment by emarketingw** [comment]
we got this error
please advice
Fatal error: Can't use method return value in write context in C:\xampp\htdocs\brand\src\Login.php on line 63

**Comment by everyusernameistaken123** [comment]
It's because of your php-version, you need php >= 5.5 for the latest version of ChatAPI

**Comment by farhansyihab** [comment]
Fatal error: Can't use method return value in write context in \src\Login.php on line 63 
need help
