### ISSUE TITLE
Block Checker Not working

### ISSUE THREAD

**Issue by faisalcse** [WHAnonymous/Chat-API#1114]
Blockchecker.php file is not working. It is giving error:

Fatal error: Can't use method return value in write context in Login.php on line 63

Thanks

**Comment by mgp25** [comment]
@faisalcse is not an API issue, its something you haven't updated. Check google or dependencies or even composer.json

**Comment by faisalcse** [comment]
mgp25 I have updated and taken the latest file from the chat-api. but it is not working. Is there any place need to update or need to add?

**Comment by mgp25** [comment]
@faisalcse update to latest commit, thats it, see requirements: 

https://github.com/WHAnonymous/Chat-API/wiki/Dependencies
