### ISSUE TITLE
Cannot access protected property MyWhatsProt::$axolotlStore

### ISSUE THREAD

**Issue by everyusernameistaken123** [WHAnonymous/Chat-API#1115]
I got this error today:
Cannot access protected property MyWhatsProt::$axolotlStore in [...]/handlers/NotificationHandler.php on line 84

It sounds like an coding-issue - but I have to admit, I am not using the encryption. I read, its still possible without? But it seems like, if I am receiving encrypted messages, this error is triggered?

EDIT: Ouch, sorry... I see this is a duplicate :-S

**Comment by Cubel89** [comment]
If I get a message I get this error:
Fatal error: Class 'KeyHelper' not found in /home/usuario/public_html/src/whatsprot.class.php on line 309

**Comment by everyusernameistaken123** [comment]
After updateing to the latest commit, I get this message from Cubel89 too

**Comment by mgp25** [comment]
It should work everything fine now, send me feedback.

Regards

**Comment by everyusernameistaken123** [comment]
Yes, this helped, thanks!

**Comment by Cubel89** [comment]
You may now not receive messages from people who formerly received well?
I mention this because doing tests on my mobile I have always received messages encrypted did not come out, but now my phone does not show double chek

<enc v="1" type="msg">3 !¦D%C*RG"·®[²‘–B®H 3sWDï‰ý›y"ëØúŽö»K¢»\rÁì@(‹¹Šº”</enc>

**Comment by mgp25** [comment]
@Cubel89 if you want to decrypt messages install (protobuf and curve extensions like explained in the wiki).

Messages not decrypted wont be double checked (the same as whatsapp does), so please don't continue this issue if you don't have installes these extensions

Regards

**Comment by Cubel89** [comment]
Okey Okey,
I did not mean to bad, it was just a question if the update had done something wrong, because before only received messages unencrypted now it's the opposite. A closer look at what you mention me.

Thank you

**Comment by MattPorto** [comment]
I have the same issue now. after I install the protobuf and curve extensions to decrypt the messages, I receive this exception:  Fatal error: PHP Fatal error:  Class 'KeyHelper' not found in /home/user/.../Chat-API/src/whatsprot.class.php on line 334.
