### ISSUE TITLE
Not Receive Messages

### ISSUE THREAD

**Issue by usinadeideia** [WHAnonymous/Chat-API#1116]
Good morning peoples

I would like to take a doubt, I have a number that signed up in WhatsApp.php that makes sending messages, but does not read the incoming message. Reseted and I registered again using reseaccount and registeraccount, not solved. What could it be?

Thanks

**Comment by mgp25** [comment]
If you dont have protobuf and curve extensions, encrypted messages are not marked as read, plaintext messages yes.

Regards
