### ISSUE TITLE
LOG: [2015-10-25 17:13:22] [ERROR]: Iq error with 1 id

### ISSUE THREAD

**Issue by hansrouge** [WHAnonymous/Chat-API#1118]
Hi,

what does this error mean?
It appears in the Log-File with the newest version of the API.
id 1 = privacy

It happens with every WA-Account.

Thanks.

**Comment by 0xTryCatch** [comment]
Show the nodes please

**Comment by 0xTryCatch** [comment]
It probably means you have no blocked list

**Comment by hansrouge** [comment]
Thats where it appears in the debug:

```
rx  <presence from="**@s.whatsapp.net"></presence>

rx  <iq from="**@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

--> privacy

tx  <iq id="2" xmlns="w:b" type="get" to="s.whatsapp.net">
tx    <lists></lists>
tx  </iq>
```

So this creates it:
```
rx  <iq from="**@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>
```

**Comment by mgp25** [comment]
sigh... @hansrouge is just a way to see thing quicker, is not an error at all. Read what @0xTryCatch posted

I recommend you to researcg for yourself before opening a new issue, most of times the answer is just in front of us

**Comment by hansrouge** [comment]
@mgp25 @0xTryCatch  Thank you both. It just confused me, because it said "Error".
