### ISSUE TITLE
2 Way communication number blocked!

### ISSUE THREAD

**Issue by rayidi** [WHAnonymous/Chat-API#1119]
Hello,

I'm working on a 2 way communication.
Since 3 weeks my number working perfectly, suddenly today it went down...
I'm sharing the log, kindly help me to get it back.

Thanks in advance.

`tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="9199XXXXXXXX">ÚøýÌ9199XXXXXXXX6r$UÅÀ‡Šmâ$8a-Ð[~¤1445758501</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>f’ûÏˆÞ•à*Ëàzø6(ŠÍ&</challenge>

tx  <response>µ’BùÝ¹ç8<?ÈXñÀ†o¤—æ¾Ýx·[÷‚ð x6‚œÙZƒ'</response>

rx  <success t="1445758501" props="4" kind="free" status="active" creation="1443510219" expiration="1475046219">ŒZ¤Ì›³‹U$Ô¤I7wy</success>

tx  <presence name="Joe"></presence>

rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>

rx  <presence from="9199XXXXXXXX@s.whatsapp.net"></presence>

PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/ChatAPI/src/whatsprot.class.php:565
Stack trace:
#0 /var/www/html/speedy.php(98): WhatsProt->pollMessage()
#1 {main}
  thrown in /var/www/html/ChatAPI/src/whatsprot.class.php on line 565
rx  <presence from="919999131034@s.whatsapp.net"></presence>

rx  <presence from="917202885938@s.whatsapp.net" type="unavailable" last="1445758351"></presence>

rx  <presence from="919833164070@s.whatsapp.net" type="unavailable" last="1445758473"></presence>

rx  <presence from="919810969090@s.whatsapp.net" type="unavailable" last="1445758470"></presence>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="919967307197@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="918410344719@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="919034150771@s.whatsapp.net" type="unavailable" last="1445758021"></presence>

tx  <message to="919967307197@s.whatsapp.net" type="text" id="173jgVkDoPvB0" t="1445758510">
tx    <body>Yes we do. Let me know where do you want to travel?</body>
tx  </message>

rx  <ack from="919967307197@s.whatsapp.net" class="message" id="173jgVkDoPvB0" t="1445758510"></ack>

rx  <receipt from="919967307197@s.whatsapp.net" id="173jgVkDoPvB0" t="1445758513"></receipt>

tx  <ack to="919967307197@s.whatsapp.net" class="receipt" id="173jgVkDoPvB0"></ack>

rx  <presence from="919967307197@s.whatsapp.net"></presence>

rx  <receipt from="919967307197@s.whatsapp.net" type="read" id="173jgVkDoPvB0" t="1445758517"></receipt>

tx  <ack to="919967307197@s.whatsapp.net" class="receipt" id="173jgVkDoPvB0" type="read"></ack>

rx  <presence from="919810969090@s.whatsapp.net"></presence>

rx  <presence from="919967307197@s.whatsapp.net" type="unavailable" last="deny"></presence>

tx  <iq id="1" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <message to="917202885938@s.whatsapp.net" type="text" id="173jgVkDoPvB1" t="1445758561">
tx    <body>Thank you. Feel free to reach out whenever you want to.</body>
tx  </message>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

PHP Warning:  socket_write(): unable to write to socket [32]: Broken pipe in /var/www/html/ChatAPI/src/whatsprot.class.php on line 3804
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/ChatAPI/src/whatsprot.class.php:3806
Stack trace:
#0 /var/www/html/ChatAPI/src/whatsprot.class.php(3944): WhatsProt->sendData('???Qi0GY?_g???...')
#1 /var/www/html/ChatAPI/src/whatsprot.class.php(1236): WhatsProt->sendNode(Object(ProtocolNode))
#2 /var/www/html/speedy.php(118): WhatsProt->sendPing()
#3 {main}
  thrown in /var/www/html/ChatAPI/src/whatsprot.class.php on line 3806

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="9199XXXXXXXX">2‹9199XXXXXXXXŒZ¤Ì›³‹U$Ô¤I7wy1445758801</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>C‚åË)±™"§nl5×ß</challenge>

tx  <response>Ê‰z]må=V¦íÆú
_6ïôÞïÖ¸Ó˜UžÌUñ4qw</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /var/www/html/ChatAPI/src/whatsprot.class.php:2270
Stack trace:
#0 /var/www/html/ChatAPI/src/whatsprot.class.php(551): WhatsProt->doLogin()
#1 /var/www/html/speedy.php(82): WhatsProt->loginWithPassword('5AAQwYDfZYlADNe...')
#2 {main}
  thrown in /var/www/html/ChatAPI/src/whatsprot.class.php on line 2270`

**Comment by 0xTryCatch** [comment]
Your number is blocked permanently
