### ISSUE TITLE
Decrypt problem - BAD Mac! / Incomplete message

### ISSUE THREAD

**Issue by mgulino** [WHAnonymous/Chat-API#1121]
Good evening. First, I want to thank you for sharing your excellent work.

I'm having problems when the API decrypts incoming messages and I can not identify the reason . This problem only occurs with some users.

There are two errors that appear in the debug .

-. Decrypted Message: Bad Mac! No valid sessions
```xml
rx  <chatstate from="YYYYYYYY@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="YYYYYYYY@s.whatsapp.net" type="text" id="Uerz+947c53Y9" t="1445819417" notify="Sergio Ballestero">
rx    <enc v="1" type="pkmsg">ä¾!Xk/dlA:·±§9sa!Ê+cØ+×:´°e­¥!ù3AÇÀf      ü!í±SÎ
%=¼cA
     ìpÐG^vBi"B3
!4âH}S¨]4YH0÷-ÕÈå<»ìþ
O"*¼W
´Úeb:?Ò
       rx  </message>

tx  <ack to="YYYYYYYY@s.whatsapp.net" class="message" id="Uerz+947c53Y9" t="1445819417"></ack>


-> Decrypted Message: Bad Mac!
Bad Mac!
No valid sessions - /whatsappi/libaxolotl-php/SessionCipher.php - 182Message Uerz+947c53Y9 could not be decrypted, sending retry.

tx  <receipt id="Uerz+947c53Y9" to="YYYYYYYY@s.whatsapp.net" type="retry" t="1445819417">
tx    <retry v="1" count="6" id="Uerz+947c53Y9" t="1445819417"></retry>
tx    <registration>¥Ö4{</registration>
tx  </receipt>

rx  <ack from="YYYYYYYY@s.whatsapp.net" class="receipt" type="retry" id="Uerz+947c53Y9">
rx    <retry v="1" count="6" id="Uerz+947c53Y9" t="1445819417"></retry>
rx    <registration>G
                     rx  </ack>

```

-. Decrypted Message: Incomplete message
```xml
rx  <presence from="XXXXXXXXX@s.whatsapp.net"></presence>
rx  <chatstate from="XXXXXXXXX@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="XXXXXXXXX@s.whatsapp.net" type="text" id="9205D968ED07FAC4F21F" t="1445819049" notify="JosÃ© Scuderi">
rx    <enc v="1" type="pkmsg">Ûò!cçaýxÇðñaKùæ
lÐ°·ý
ÝdÅjH!6:ª·{A¬ÝË^ß)
                  çÑ7ä:õ<æ¥¤Öq"B3
!§ðØèõ
ÌÅð±©·)®'ê½E/Tz(±20</enc>
rx  </message>

tx  <ack to="XXXXXXXXX@s.whatsapp.net" class="message" id="9205D968ED07FAC4F21F" t="1445819049"></ack>

-> Decrypted Message: Incomplete message - /whatsappi/libaxolotl-php/protocol/PreKeyWhisperMessage.php - 43Message 9205D968ED07FAC4F21F could not be decrypted, sending retry.

tx  <receipt id="9205D968ED07FAC4F21F" to="XXXXXXXXX@s.whatsapp.net" type="retry" t="1445819049">
tx    <retry v="1" count="5" id="9205D968ED07FAC4F21F" t="1445819049"></retry>
tx    <registration>¥Ö4{</registration>
tx  </receipt>

rx  <ack from="XXXXXXXXX@s.whatsapp.net" class="receipt" type="retry" id="9205D968ED07FAC4F21F">
rx    <retry v="1" count="5" id="9205D968ED07FAC4F21F" t="1445819049"></retry>
rx    <registration>G
                     rx  </ack>
```

I believe I have followed all the steps that are in the documentation. Could you please tell me if this error is caused by a modification of WhastApp or I have to make some change to fix the problem ?

Thanks a lot!!!

**Comment by mgp25** [comment]
@mgulino that issue its normal, but it fixes it self, i mean:

Whe the API cant decrypt a message, it sends a receipt asking for the correct data to decrypt the message, as you can see here: 

```xml
tx  <receipt id="9205D968ED07FAC4F21F" to="XXXXXXXXX@s.whatsapp.net" type="retry" t="1445819049">
tx    <retry v="1" count="5" id="9205D968ED07FAC4F21F" t="1445819049"></retry>
tx    <registration>¥Ö4{</registration>
tx  </receipt>
```

Then the server answers us with the correct data, so we replace the data we have with the new one, if its not able to decrypt it again it will send a receipt again asking for new data, til the server tell us that the message is invalid. As you can see, yours stopped at 5 o 6 count.

At this point, i recommend you to:

- Remove the axolotl database and if possible remove the chat from the phisical device. That should fix completely this error, usuallt caused because we tried many times sending different data.

I'll wait for your feedback

Regards

**Comment by mgulino** [comment]
Thanks @mgp25. Y did what you say and works. Now, the messages are decrypted when they arrive.

**Comment by bdbais** [comment]
"At this point, i recommend you to:

    Remove the axolotl database and if possible remove the chat from the phisical device. That should fix completely this error, usually this is caused because we tried many times sending different data."
I can't find this database on installation, could you say me which file or command I must to use to clean this error ?

**Comment by anativ** [comment]
@bdbais there is no "installation of a DB"
The db is created when needed by the SqliteAxolotlStore
https://github.com/mgp25/Chat-API/blob/f8a1f492a21eefd26d1479ca75b57841fa5b229c/src/SqliteAxolotlStore.php#L92

**Comment by anativ** [comment]
@mgp25 is it safe to delete the DB automatically on every Bad Mac exception?
Or do you have any other idea on how to solve this issue on "long running programs"?

**Comment by 0xTryCatch** [comment]
It is safe

**Comment by sakaturo** [comment]
@0xTryCatch  how can i  generated the keys again? Or is this done automatically by the api?
