### ISSUE TITLE
E2E crashes

### ISSUE THREAD

**Issue by pizzacrew** [WHAnonymous/Chat-API#1126]
Hello,

I have many numbers and the encryption works well. However my new mobile number cannot send encrypted chat messages, but can receive messages.

Debug Log: http://pastebin.com/ziPwUERN

`Error: PHP Warning:  Invalid argument supplied for foreach() in ***/src/handlers/IqHandler.php on line 256
PHP Fatal error:  Call to a member function getChainKey() on null in ***/src/libaxolotl-php/state/SessionState.php on line 137`

Thanks in advance.
Btw. number is not blocked, I can use the number on Windows where I don't have encryption.

**Comment by mgp25** [comment]
@pizzacrew post your code

**Comment by pizzacrew** [comment]
Sure: http://pastebin.com/fa2h4LMz

**Comment by mgp25** [comment]
@pizzacrew can you post the number which you were using?

**Comment by pizzacrew** [comment]
Due to privacy I send the number to your email. Hope it is okay.

**Comment by mgp25** [comment]
@pizzacrew can you try deleting the axolotl .db which is places in `wadata` folder and retry again?

Tell me if that worked

**Comment by pizzacrew** [comment]
I can test this tomorrow. However I have new information for you. The bug seems to happen for a specific receiver phone number, and not because of a sender phone.
Maybe the receiver device does not support encryption because his whatsapp client is too old?

**Comment by mgp25** [comment]
@pizzacrew in theory all clients should have end to end encryption enabled. Anyway, for that concrete number you can still force plaintext messages:

```
    public function sendMessage($to, $plaintext, $force_plain = false)
```

Set `$force_plain` to `true`, that should work.

Regards

**Comment by pizzacrew** [comment]
Maybe a better error handling would be better. So I can check if returned msgId is NULL and then try again with force_plan = true :)

**Comment by mgp25** [comment]
@pizzacrew if you want, send a pull request with the patch

Regards

**Comment by jpgomez1975** [comment]
Hi @pizzacrew 
How can you manage or fix this error? Im driving crazy...
Regards

**Comment by RajibHossen** [comment]
I am also getting this error. At first, it was working then all of a sudden I am getting this exception. How did you solve this?

**Comment by jpgomez1975** [comment]
Hi my friend,
Im still working to fin a solution to this issue. I let you know if I get
it.
Regards,
Juan



Juan Pablo Gómez
Director Ad hoc
www.adhocsite.com.ar <http://www.adhocsite.com.ar/> 
Moldes 4670 (C1429AGJ)
te. (+5411) 4704-5253
skype. j_p_gomez


 

  _____  

De: Md. Rajib Hossen [mailto:notifications@github.com] 
Enviado el: miércoles, 23 de diciembre de 2015 05:11
Para: WHAnonymous/Chat-API
CC: jpgomez1975
Asunto: Re: [Chat-API] E2E crashes (#1126)



I am also getting this error. At first, it was working then all of a sudden
I am getting this exception. How did you solve this?


Reply to this email directly or view
<https://github.com/WHAnonymous/Chat-API/issues/1126#issuecomment-166831208>
it on GitHub.
<https://github.com/notifications/beacon/AKv8F7A4NpykUx-3_KfWqUGTMhKpI5f3ks5
pSk6PgaJpZM4GVwN1.gif> 

Se certificó que el correo no contiene virus.
Comprobada por AVG - www.avg.es
Versión: 2016.0.7303 / Base de datos de virus: 4492/11237 - Fecha de la
versión: 22/12/2015

**Comment by victorblq** [comment]
Hi guys!
Do you have some update about this problem?
Same issue here! Thx.

**Comment by Nakani** [comment]
Hello , I have this same problem , but this message only appears when I send to a particular number , did what mgp25 mentioned , which was force_plain exchange to true, but the error was gone but he does not send to this blessed number.
