### ISSUE TITLE
Script crash just after connecting for a fraction of a second

### ISSUE THREAD

**Issue by estcap** [WHAnonymous/Chat-API#1130]
This is my PHP code, which I don't change since yesterday (I just added the updated encryption version of this library) and it worked through all night. I ommit the events

```php

$w = new WhatsProt($username, $nickname, $debug);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage");
$w->eventManager()->bind("onGetImage", "onImage");
$w->eventManager()->bind("onMessageReceivedClient", "onMessageReceivedClient");
$w->eventManager()->bind("onGetProfilePicture", "onGetProfilePicture");
$w->eventManager()->bind("onGetSyncResult", "onGetSyncResult");
$w->eventManager()->bind("onSendMessageReceived", "onSendMessageReceived");
$w->eventManager()->bind("onGetAudio", "onAudio");
$w->enableReadReceipt(false);  // no envia los vistos 

$w->Connect();
$w->LoginWithPassword($password);

$w->pollMessage();

$w->sendSetPrivacySettings('last','none');
$w->pollMessage();

//Status 
$w->sendSetPrivacySettings('status','all');
$w->pollMessage();

//Profile picture
$w->sendSetPrivacySettings('profile','all');
$w->pollMessage();


$contador_ping = 1;

while (!file_exists('stopLock')) {  // Si existe ese archivo se CIERRA!
      if (!$w->isConnected()) {
		 
	
        $w->Connect();
        $w->LoginWithPassword($password);
      }

      try {
		 	
		
        sendMessages();
		$w->pollMessage();
		usleep(1000000); //Wait 1 sec
		
		if($contador_ping == 29){
			$w->SendPing();
			error_log(date('l jS \of F Y h:i:s A') . " >> " . "Requesting SendPing... \n", 3, "/usr/local/whatsapp/whatsap.log");
  			$contador_ping = 1;
			
		} else {
			
			$contador_ping ++;
			
		}
		
      }
      catch(Exception $e) {
	error_log(date('l jS \of F Y h:i:s A') . " >> " . "Exception, disconnecting to connect again: " . $e->getMessage() . "\n", 3, "/usr/local/whatsapp/whatsap.log");
  
        $w->disconnect();
      }
    }

$w->disconnect();
?>
```

I suspect it has something to do with something a customer sent/did with my number.
When I start the script, I see in my phone that the number I use with this library goes online for a fraction of a second, and then dissconects. The log is the following (I scribbled sensitive information just in case, *MYNUMBER* is my number and so on) :

```
    tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="*MYNUMBER*">·
{*MYNUMBER*ÛÄïN„=n”&a
‘QÍþ01445949937</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>ª;+N, |Á—n¬£¼>[É</challenge>

tx  <response>õE|‡VY˜AH„rz f«{…
Ï®ò§¥Ec”×nw</response>

rx  <success t="1445949938" props="4" kind="free" status="active" creation="1436360096" expiration="1467896096">›GßÙgšÏÚ„-³*BÍ</success>

tx  <presence name="*MYSTATUS*"></presence>

rx  <receipt from="*CUSTOMER1*@s.whatsapp.net" type="retry" id="ofGqiS8vg8pw6" offline="2" t="1445948227">
rx    <retry v="1" count="1" id="ofGqiS8vg8pw6" t="1445948225"></retry>
rx    <registration>^e</registration>
rx  </receipt>

tx  <iq id="1" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="*CUSTOMER1*@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="*MYNUMBER*@s.whatsapp.net"></presence>

rx  <presence from="*CUSTOMER2*@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="1">
rx    <list>
rx      <user jid="*CUSTOMER1*@s.whatsapp.net">
rx        <registration>^e</registration>
rx        <type></type>
rx        <identity>ÞXÌÆ«Ü•ßKýõB#´Ú‚Xf_XlO
^o‰M</identity>
rx        <skey>
rx          <id>   </id>
rx          <value>m”k(n‘‹ŠË+h@¨Wá)Å"'ó<‡:%</value>
rx          <signature>¿óº&W¤úÁÂËdŽØL”
Ô3w¯ƒ0ÄšŸdÅ-Zu‹8h·n£<=¡± ä2È|ˆz$1W‹</signature>
rx        </skey>
rx        <key>
rx          <id>Hâ</id>
rx          <value>,ñÓœ<:è¶Ï¦Üó×r³0UÐl</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>
```

All the times I tried to start my script, it just stops right after recieving that <list> element from Whatsapp servers.

**Comment by mgp25** [comment]
@estcap first of all:

According to WhatsApp EULA, you only can use WhatsApp for personal usage, not your case so i can't give you support.

Anyway, is not an API issue, this: 

```xml
rx  <iq from="s.whatsapp.net" type="result" id="1">
rx    <list>
rx      <user jid="*CUSTOMER1*@s.whatsapp.net">
rx        <registration>^��e</registration>
rx        <type>�</type>
rx        <identity>ÞXÌÆ«Ü•�ß�K�ýõB#´Ú‚Xf_XlO
^o‰M</identity>
rx        <skey>
rx          <id>   </id>
rx          <value>m”k(n‘‹Š�Ë+h@¨W�á)Å�"'ó�<‡:%</value>
rx          <signature>�¿ó�º&W¤úÁÂËdŽØL”
Ô��3w�¯ƒ0ÄšŸdÅ-Zu‹8h·n£<=¡± ä2È|ˆz$1W‹��</signature>
rx        </skey>
rx        <key>
rx          <id>�Hâ</id>
rx          <value>,ñÓœ�<��:è¶Ï¦�Üó×r³��0UÐl</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>
```

Is when requesting contact prekey,  if there would be any error would be while encrypting/decrypting the message, not this case, so the error is yours.

**Comment by estcap** [comment]
It is personal use. With "customer" I mean to my contacts like in modeling in a use case (English is not my native language)
Thanks, I will look at it in more detail.

**Comment by estcap** [comment]
I hope you read these answers even after you closed them, I don't want to open other issue.
I found another error in other log I have:

```PHP Fatal error:  Class 'UntrustedIdentityException' not found in /usr/local/whatsapp/src/libaxolotl-php/SessionBuilder.php on line 153```

**Comment by mgp25** [comment]
@estcap i recommend you removing the axolotl database from `wadata` folder, if there is any error with that, that will solve them.

And if you still disconnecting after that, then you have something wrong in your code, try debugging step by step, and if you see something, we can help you.

@estcap ill check that issue, thanks

Regards

**Comment by mgp25** [comment]
@estcap i recommend you removing the axolotl database from `wadata` folder, if there is any error with that, that will solve them.

And if you still disconnecting after that, then you have something wrong in your code, try debugging step by step, and if you see something, we can help you.

@estcap ill check that issue, thanks

Regards

**Comment by mgp25** [comment]
@estcap i recommend you removing the axolotl database from `wadata` folder, if there is any error with that, that will solve them.

And if you still disconnecting after that, then you have something wrong in your code, try debugging step by step, and if you see something, we can help you.

@estcap ill check that issue, thanks

Regards

**Comment by estcap** [comment]
That solved it!
I guess this is a temporary workaround and it will likely happen again, right? I don't see other people with same issue, but if you wanted, would it be useful to you if I sent you any log? I could send you the .db if you wanted to see it. 

Thanks again

**Comment by mgp25** [comment]
@estcap in theory that should happen. Anyway ill research it and fix it if its possible

Regards

**Comment by estcap** [comment]
@mgp25 Hi again.
I saw the bugfix https://github.com/WHAnonymous/Chat-API/commit/0aecd3ee666fb68c24abb2b58334af43a222c76e
Does it directly addres this issue?
