### ISSUE TITLE
Change const DATA_FOLDER

### ISSUE THREAD

**Issue by grinay** [WHAnonymous/Chat-API#1131]
Hello. I create whatsapp service and use your whatsapp api installed by composer. Every times after update I need change folder permission for write in vendor\whatsapp\chat-api\src\wadata. This is not good because vendor folder contain components and modules and shouldn't change.
Can you add opportunity for change const DATA FOLDER in further release ?

**Comment by mgp25** [comment]
@grinay if you want, send a pull request. I'll check it, and if it's fine ill add it.

Regards
