### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#1132]
Dear @mgp25  , i have number registered by this api and when the number not authorized when login then i try to register the same number again by regiterTool , its change password and not send me code then login again and get the same issue . so i change the password more than 10 to login . whats wrong 

debug message
```xml
[] Logging in as 'Adv' (201210634470) tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="201210634470"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>vºjEWi´­„ˆ*´(e¹\</challenge>

tx  <response>ø?öÙÖ¹óÕ5-Ñâ@Ô½—e¨LArÿÍ$À•r{%B</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

`Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\whatsapp\src\Login.php:53 Stack trace: #0 C:\xampp\htdocs\whatsapp\src\whatsprot.class.php(265): Login->doLogin() #1 C:\xampp\htdocs\whatsapp\examples\LoginWebpage.php(19): WhatsProt->loginWithPassword('PX9Uqsq/dM2eF4S...') #2 {main} thrown in C:\xampp\htdocs\whatsapp\src\Login.php on line 53`

**Comment by mgp25** [comment]
@beljk next time you dont quote code properly, ill close issue directly

It's explained in the wiki, if you have already an identity, you dont receive a sms code, as simple as that, i recommend you to full read wiki.

Sometimes the number is not the same as the login number, when using `registerTool` look at the debug log, and check for the `[login] => ` value, thats the one you have to use.

And use `blockChecker.php` to make sure it's not blocked. Try first, what i told you above

**Comment by beljk** [comment]
the same issue , i change password 6 times but still not login

**Comment by mgp25** [comment]
@beljk send me number to mail mail and the identity

**Comment by beljk** [comment]
@mgp25 Check your inbox

**Comment by beljk** [comment]
@mgp25 Did you checked the last Email ?

**Comment by mgp25** [comment]
@beljk your number/service or whatever seems to be blocked due to bad behaviour or just the service is banned

Regards

**Comment by beljk** [comment]
@mgp25 so whats wrong , i follow the steps as  described and still doesn't work :S i register another number and the same issue .

**Comment by ariel12345** [comment]
I have this problem that my account is blocked and this presents a serious error to me , so what I have to do ????????????????? Please help me , I could not send a message once
