### ISSUE TITLE
It worked well in the last three months, now: rx  <failure> rx    <not-authorized></not-authorized> rx  </failure>

### ISSUE THREAD

**Issue by Raisel** [WHAnonymous/Chat-API#1134]
I built an agenda that communicates with only 3 numbers of WhatsApp. The numbers that receive messages are known and have the sender in the address book. In addition to sending these simple messages with schedules, in the last 45 days I had been synchronizing contacts, one every twenty minutes, an average of 51 per day, and not all had whatsapp.

Yesterday I noticed that the script had no more success to log in WhatsApp account, was when I did some tests but found nothing. I tried to update the API chat but the new version presented several errors in PHP ... I went back to the previous one. I tried to enable whatsapp on an iphone and it worked OK, so if there is a problem in the API or in my server IP.

There follows the debug

>[] Logging in as 'Foco InterimobiliÃ¡rias' (55219810111xx) tx  <stream:features>
>tx    <readreceipts></readreceipts>
>tx    <groups_v2></groups_v2>
>tx    <privacy></privacy>
>tx    <presence></presence>
>tx  </stream:features>
>
>tx  <auth mechanism="WAUTH-2" user="55219810111XX">/ó˜R55219810111XXÚ>,£ˆ=™Þìý±þV&äã‚³1446004038</auth>
>
>rx  <start from="s.whatsapp.net"></start>
>
>rx  <stream:features></stream:features>
>
>rx  <challenge>Ìã“³énX•"sHC#lDK</challenge>
>
>tx  <response>ÐEt­.ð*M6“Iä^$¸Õ)tg{$ìN]O“SÓH'EFwº‹</response>
>
>rx  <failure>
>rx    <not-authorized></not-authorized>
>rx  </failure>

>Fatal error: Uncaught exception 'LoginFailureException' in >/home/interimo/public_html/foco/whatsapp/src/whatsprot.class.php:2244 Stack trace: #0 >/home/interimo/public_html/foco/whatsapp/src/whatsprot.class.php(541): WhatsProt->doLogin() #1 >/home/interimo/public_html/foco/_whatsapp.php(128): WhatsProt->loginWithPassword('bC8pG.............') #2 {main} thrown in >/home/interimo/public_html/foco/whatsapp/src/whatsprot.class.php on line 2244
>

I shall be grateful for any help,

thank you!

**Comment by mgp25** [comment]
According to WhatsApp EULA, you can only use WhatsApp for personal usage.

So we can't give you support.

Regards

**Comment by Raisel** [comment]
but it seems that my ip has blocked?

**Comment by mgp25** [comment]
@Raisel there is a script `blockChecker.php`. Have you tried it? It's explained in the wiki, _sigh..._

**Comment by Raisel** [comment]
I did not understand how to use the script blockChecker.php, even reading the wiki.
is it in the shel?

**Comment by Raisel** [comment]
Please see this

>interimo@interimobiliarias.com.br [~/public_html/foco/whatsapp/whatsapp]# php blockChecker.php
####################
#                  #
# WA Block Checker #
#                  #
####################


>Username (country code + number without + or 00): 5521981011192
Array
(
    [cc] => 55
    [in] => 21981011192
    [id] => Ò-*¸¿ø$ Ç
                         [lg] => pt
    [lc] => BR
)
stdClass Object
(
    [status] => fail
    [reason] => missing_param
    [param] => in
)

>Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /home/interimo/public_html/foco/whatsapp/src/whatsprot.class.php:181
Stack trace:
#0 /home/interimo/public_html/foco/whatsapp/whatsapp/blockChecker.php(34): WhatsProt->checkCredentials()
#1 {main}
  thrown in /home/interimo/public_html/foco/whatsapp/src/whatsprot.class.php on line 181
interimo@interimobiliarias.com.br [~/public_html/foco/whatsapp/whatsapp]#
