### ISSUE TITLE
Code generate error (Api old_version)

### ISSUE THREAD

**Issue by kartikkapatel** [WHAnonymous/Chat-API#1138]
In past api work perfectly but now throw the error during generating code for new number:
Output:
Array ( [in] =>  ********** [cc] => 972 [id] => ‚yÑ}ßˆßÀ?:Í>h¼—à; [lg] => he [lc] => IL [sim_mcc] => 425 [sim_mnc] => 000 [method] => sms [token] => 71be4aae78c80cd3fb02fd78a33b3f77 ) stdClass Object ( [status] => fail [reason] => old_version )

Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in /src/whatsapp/whatsprot.class.php:386 Stack trace: #0 exampleRegister.php(46): WhatsProt->codeRequest('sms') #1 {main} thrown in /src/whatsapp/whatsprot.class.php on line 386

**Comment by 0xTryCatch** [comment]
Update the API
