### ISSUE TITLE
registerTool: number blocked after sms arrives

### ISSUE THREAD

**Issue by ledazinha** [WHAnonymous/Chat-API#1139]
I'm trying to register a number with the registerTool provided by the library. The sms with the code arrives, but when I input the code, I get this message:

```
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
```

When I execute the tool and try to register the number again, the result is:

```
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
There was a problem trying to request the code.
```

This number was never used with whatsapp before. This is happening with the most up-to-date version of the api.

**Comment by mgp25** [comment]
Not API issue

**Comment by disearth** [comment]
then What is the issue ?

**Comment by estcap** [comment]
Your number was blocked because of reasons unknown. That would be the issue.
How to solve it? I don't think you can.. just get another number
