### ISSUE TITLE
Questions about syncing

### ISSUE THREAD

**Issue by pizzacrew** [WHAnonymous/Chat-API#1140]
Hello there,

I have some questions about the right process of using the API. I have already read the wiki section, however it is not clear (sorry).

1. When should I subscribe the presences of my users?
After a reconnect, I still receive presences of my added phone numbers. So I think it is enough to subscribe it when adding a number to my own phone book and to unsubscribe when removing the number.
However, a few users recommend to subscribe each time before sending a message? Or should I subscribe each login for each user?

2. When should I sync a user? I also think it is enough to sync 1 time for each number when adding the number to my own phone book... I have tested broadcast without syncing after login, and it works?

3. What do you mean with "mode" and "context" for syncing? https://github.com/WHAnonymous/Chat-API/wiki/Sync
For example, when do I need to set mode to "chunked"?
Do I need to sync _all_ my contacts with "mode = 'full', context = 'interactive'" each login or when adding a new number to my phone book?

Thanks in advance.

**Comment by mgp25** [comment]
@pizzacrew 

1. Once is okay
2. Only once, not more. Now your account is flaged even more, great! don't do bad behaviours, not syncing is like shouting "Hey there WhatsApp, im using the API", and eventually you will get blocked.
3. Only use delta interactive and full registration (only once when registered)

**Comment by pizzacrew** [comment]
Thanks for your answer. So the following workflow is okay?

1. Connect in WhatsApp
2. Sync phonenumber 0123456
3. subscribe phonenumber 0123456
4. send message to 0123456
5. disconnect

1. Connect in Whatsapp
2. send message to 0123456
3. Disconnect

In the second session I don't need to sync and subscribe because I did it in the first session?

**Comment by mgp25** [comment]
@pizzacrew yes
