### ISSUE TITLE
Image relative path does not work?

### ISSUE THREAD

**Issue by PedroGabriel** [WHAnonymous/Chat-API#1141]
Hello!
I was using a relative path to send images using sendMessageImage but it never worked with images...

It just does not send anything so I was following into whatsprot.class.php and noticed in the func.php it has a function called "getExtensionFromMime" and it's return was getting empty.

I don't know if my image mime was wrong or anything else but to workaround as all my images was jpeg I set the return to:
```
if(isset($extensions[$mime]))
    return $extensions[$mime];
else
    return $extensions['image/jpeg'];
```
So, does relative paths work? or just direct uri?

Thanks btw.

**Comment by mgp25** [comment]
direct
