### ISSUE TITLE
New Api issue

### ISSUE THREAD

**Issue by kartikkapatel** [WHAnonymous/Chat-API#1142]
( ! ) Fatal error: Can't use method return value in write context in D:\xampp\htdocs\Chat-API-master\src\Login.php on line 63
Call Stack
#	Time	Memory	Function	Location
1	1.0050	134920	{main}( )	..\login_ex.php:0
2	1.0136	587528	require_once( 'D:\xampp\htdocs\Chat-API-master\src\whatsprot.class.php' )	..\login_ex.php:3

**Comment by 0xTryCatch** [comment]
PHP 5.6 is required
