### ISSUE TITLE
Broadcasts

### ISSUE THREAD

**Issue by pizzacrew** [WHAnonymous/Chat-API#1144]
Hello,
how do I add a number to my existing broadcast list?
I have found no function for this.
The function `$wObj->sendGroupsParticipantsAdd('*****@broadcast', '*****');` does not work.

Thanks in advance.

**Comment by mgp25** [comment]
`sendGroupsParticipantsAdd` as the name says, its for groups, not broadcasts.

Just send a new broadcast with the new number added to the array
