### ISSUE TITLE
Semantic Versioning Problem

### ISSUE THREAD

**Issue by GoktugOzturk** [WHAnonymous/Chat-API#1145]
Given a version number MAJOR.MINOR.PATCH, increment the:
    MAJOR version when you make incompatible API changes,
    MINOR version when you add functionality in a backwards-compatible manner, and
    PATCH version when you make backwards-compatible bug fixes.

This repos requirements changed from PHP5.3 to PHP5.6 on 2.5.5 version.
Since my datacenter supports php 5.5, I can't use it anymore. (whatsup "old version" error)

I think version 2.5.5.X releases should be 3.0

**Comment by mgp25** [comment]
Datacenter? Do you know the API is supossed to be used only for personal usage, mm?

I follow that versions according to the WA protocol, which is better for me to keep track of the changes
