### ISSUE TITLE
missing_param: what does it mean?

### ISSUE THREAD

**Issue by Raisel** [WHAnonymous/Chat-API#1147]
I can not connect to the server, since even changed the ip to see if that would be the problem (		curl_setopt($ch, CURLOPT_INTERFACE,'eth0:cp3')):

>####################
#                  #
# WA Block Checker #
#                  #
####################

>Username (country code + number without + or 00): 55219641947xx
Array
(
    [cc] => 55
    [in] => 219641947xx
    [id] => hg°&1s6°yn|üõÜc7Ñ
    [lg] => pt
    [lc] => BR
)
stdClass Object
(
    [status] => fail
    [reason] => missing_param
    [param] => in
)

>Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the co   de.' in /home/xxxxxxx/public_html/xxxxxxxxx/whatsapp/src/whatsprot.class.php:181
Stack trace:
#0 /home/xxxxxx/public_html/xxxxxxx/whatsapp/whatsapp/blockChecker.php(34): WhatsProt->checkCredentials   ()
#1 {main}
  thrown in /home/xxxxx/public_html/xxxxxxx/whatsapp/src/whatsprot.class.php on line 181
xxxx@xxxxxx.com.br [~/public_html/xxxxxxxx/whatsapp/whatsapp]#

**Comment by 0xTryCatch** [comment]
Not quoted
