### ISSUE TITLE
Login.php fails right after sending auth, socket get closed

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#1150]
I've found in this new version (downloaded 2 days ago) that login fails (socket get closed) right after sending auth node. The new login code is in Login.php file when it was before in whatsprot.class.php

I've checked the code with an old version (a january version) and it looks the same code, organized differently but basically the same, and it is still working now for login.

The resource string to open the socket in both is S40-2.13.9-443 that is the latest device version published. The user and password is also the same for both.

I've tried even without challenge data and sending auth like this works in one and fails in the other:

 `
tx <auth mechanism="WAUTH-2" user="(((hidden)))"></auth>
`

Any idea?

**Comment by hgc2002** [comment]
Found the issue, actually two:

1.-The routine isConnected() I had it checking also the loginStatus, and currently that is wrong while login.

2.- The doLogin routine in Login.php never runs parent->connect() so the issue was not after sending anything, but sending in a nonexisting socket from first place.

Regards,

**Comment by mgp25** [comment]
@hgc2002 use `isConnected()` after log in, if you want to see if you logged in correctly, there are two events:

```
    onLoginFailed( $mynumber, $data )
    onLoginSuccess( $mynumber, $kind, $status, $creation, $expiration )
```

Regards
