### ISSUE TITLE
Sync question

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#1151]
Let me explain: in the phone, if I receive a message from X that is not in my contact list, phone ask me if I want to block X or add it to my contacts.

Now, I want to respond, but the phone don't give me that chance until I set X as a contact.

Do I really need to do this with Chat-API, I mean, what happen if I simply send the response to X before making a sendSync('X')? Could be that response making X my contact automatically without doing a sendSync on purpose?

Regards,

**Comment by mgp25** [comment]
@hgc2002 you need to do the same as the client, if not, your number will be flaged and blocked
