### ISSUE TITLE
onGetMessage Event

### ISSUE THREAD

**Issue by Woorales** [WHAnonymous/Chat-API#1152]
I have followed the instructions on how to set events, my code looks like this:

test.php

```php
require_once ('../src/whatsprot.class.php');
require_once ('../src/events/MyEvents.php');
$username = "MyPhoneNumber";  
$nickname = "MYNickName";    
$debug    = false;   
$password= "MyPassword";
$w = new WhatsProt($username, $nickname, $debug);

$w->connect();
$w->loginWithPassword($password);

$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents);

$w->sendMessage("MyPhoneNumer", "Test Message");

while(true)
{
     $w->pollMessage();
}

```

In MyEvents.php i have the following (i did uncomment the onGetMessage and the onSendMessage events on the top of the file):

```php
public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
    {
        echo "Message from ".$name." ".$body;
    }
    
    public function onSendMessage($mynumber, $target, $messageId, $node) {
        echo "Message Sent";
    }

```

When i run test.php in my browser i do see the text "Message Sent" and i do recive the message on my cellphone, but when i send a reply message i dont see it in the browser, in the cellphone i can see that the message is marked as read; If i send a new message before i run test.php i can see the message as pending until i run the script, when i run it i cant see the message on the browser, but in my cellphone is marked as read.

**Comment by mgp25** [comment]
@Woorales without debug log this is useless. Always post debug log.

You are receiving encrypted messages, that event is only fired when receiving plaintext messages or if we decrypted the message.

For further help, post debug log.

Regards

**Comment by Woorales** [comment]
This is the log:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="5214425028127"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>6Ûåd´à*4©b•£M}Ÿ>ÈG</challenge>

tx  <response>þcÝáÆ·Î}:‡äòÅ"	ÇâUÅ¥tÏa"¶;•Ô! úÒ</response>

rx  <success t="1446477516" props="4" kind="free" status="active" creation="1445740403" expiration="1477276403">fQ7„ßJ±Ûàj-ÀF«ma</success>

tx  <presence name="Tito"></presence>

rx  <receipt from="5214423232026@s.whatsapp.net" type="read" id="gVlDo0tR07n80" offline="0" t="1446477487">
rx    <list>
rx      <item id="ePWY0TkKmXeb0"></item>
rx    </list>
rx  </receipt>

tx  <ack to="5214423232026@s.whatsapp.net" class="receipt" id="gVlDo0tR07n80" type="read"></ack>

**Comment by mgp25** [comment]
@Woorales how do you expect the events to be fired when you didn't receive/send any message?

**Comment by Woorales** [comment]
I do send new messages as you can see here:
![2015-11-02-10-38-16](https://cloud.githubusercontent.com/assets/629179/10887633/ca830b00-814d-11e5-8899-eb0712e9aba6.png)

A few minutes ago i update the code to the last version of Chat-API, and now i dont get the messages  mark as recived, this is the log:


```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="**************">�o`�**************��OH:s���~NO�	��2(;M1446482113</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>��C����u^������	</challenge>

tx  <response>�{�D~Npg�^Л-��U���]�̈́���P�?lc:</response>

rx  <success t="1446482113" props="4" kind="free" status="active" creation="1445740403" expiration="1477276403">�'�ڇeVz��?�'Q�</success>

tx  <presence name="Tito"></presence>

rx  <message from="**************@s.whatsapp.net" type="text" id="1446481696.--138" offline="3" t="1446481698" notify="Rodrigo">
rx    <enc v="1" type="msg">3 !uGK~p �v�;�^0��q�D]�_���h���)`,")\Ǒ����_���]��D��;��</enc>
rx  </message>

rx  <message from="**************@s.whatsapp.net" type="text" id="1446481846.--141" offline="3" t="1446481847" notify="Rodrigo">
rx    <enc v="1" type="msg">3 !uGK~p �v�;�^0��q�D]�_���h���)`-"~�"��Ws�hqY��_�^1�"j@</enc>
rx  </message>

rx  <message from="**************@s.whatsapp.net" type="text" id="dqDpbAWSpcGQ5" offline="1" t="1446482045" notify="Rodrigo">
rx    <enc v="1" type="msg">3 !uGK~p �v�;�^0��q�D]�_���h���)`."��b`Qz-������e���,</enc>
rx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="3"></offline>
rx  </ib>

rx  <presence from="**************@s.whatsapp.net"></presence>

rx  <presence from="**************@s.whatsapp.net" type="unavailable" last="deny"></presence>

```

As far as i can see, i have 3 messages, since my phone number is correct in the 3 elements that look like "<message from="**************@s.whatsapp.net" also the sender names is correct notify="Rodrigo"

**Comment by mgp25** [comment]
@Woorales if you dont enable encryption, messages cant be decrypted and cant be marked as read.
Read dependencies in wiki

Regards
