### ISSUE TITLE
PHP error on function register

### ISSUE THREAD

**Issue by mapring0019** [WHAnonymous/Chat-API#1156]
When i run: `[root@localhost examples]# php exampleRegister.php` it wasn't worked and show error as below:
```
PHP Parse error:  syntax error, unexpected '[' in /root/Node/Chat-API/src/func.php on line 306
```

**Comment by John-Henrique** [comment]
exists a character '[' no necessary, see this file in line 306

**Comment by mgp25** [comment]
Are you using php 5.6? Read wiki please: https://github.com/WHAnonymous/Chat-API/wiki/Dependencies
