### ISSUE TITLE
Composer find 2 dependency with a same name

### ISSUE THREAD

**Issue by dshuplyakov** [WHAnonymous/Chat-API#1159]
Recently, I have updated **Chat-API to v2.5.5.3** and get conflict. Log4php and Chat-API have files with same name "Logger.php".

Composer log:

```Warning: Ambiguous class resolution, "Logger" was found in both "/project/vendor/whatsapp/chat-api/src/Logger.php" and "\project\vendor\apache\log4php\src\main\php\Logger.php", \the first will be used.```

If I use your logger and set in autoload_classmap.php:
>'Logger' => $vendorDir . '/whatsapp/chat-api/src/Logger.php', 

my project crashes because it can't work with Logger.php of Chat-api. 

Otherwise, if I write
>'Logger' => $vendorDir . 'apache/log4php/src/main/php/Logger.php',  

it crashes too because it tries to load Logger.php at 6 line of whatsprot.class.php

My composer.json:

```{
"require": {
    "php":">=5.3.0",
    "apache/log4php": "2.3.0",
     "whatsapp/chat-api": "dev-master"
    } 
}```

Could you help me to resolve this problem?

**Comment by sckebby** [comment]
Hi,
as mensioned in the Wiki --> Dependencies, you need to use PHP >= 5.6+.
Do you have try to upgrade to PHP 5.6 ?

**Comment by dshuplyakov** [comment]
Yes, of course

> root@arch990:/var/www/site# php -v
> PHP 5.6.14-1~dotdeb+7.1 (cli) (built: Oct  2 2015 03:37:04)
> Copyright (c) 1997-2015 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
>    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Comment by mgp25** [comment]
Disable the other logger and it will fix it

Regards
