### ISSUE TITLE
Enc messages 

### ISSUE THREAD

**Issue by ddfrreire** [WHAnonymous/Chat-API#1160]
I did update of lib. but, continues getting messages encrypted. 

```
rx  <message from="xxx@s.whatsapp.net" type="text" id="xxx-93" offline="3" t="14466xxx" notify="xxx">
rx    <enc v="1" type="msg">3 !՝U�����D�r�_8N��#ؓ��~ୌm7"*p�ޜ�Δ��]��ߓy!�&���</enc>
rx  </message>
```

What to do?

**Comment by ddfrreire** [comment]
Already update api and remove account with resetAccount.php. But, continues getting messages encrypted.

**Comment by mgp25** [comment]
Read the all the wiki, its explained in the readme and dependencies page. Is not that hard! just read the wiki, everything is in there.

**Comment by gravmatt** [comment]
I read the wiki and installed the dependencies but it is still not working. Messages look like they are encrypted. Even after reseting.

**Comment by mgp25** [comment]
@gravmatt you dont have installed php protobuf and curve25519 extensions

**Comment by ddfrreire** [comment]
Thank you @mgp25. I forgot of answer on day, but was only install extensions and it's worked.

**Comment by gravmatt** [comment]
@mgp25 thanks for the hint.
