### ISSUE TITLE
Questions about presence (un)subscription

### ISSUE THREAD

**Issue by rogobob** [WHAnonymous/Chat-API#1164]
1. Wiki says I should subscribe presence to EVERY contact on first login (and also sometimes on subsequent logins, as described here: https://github.com/WHAnonymous/Chat-API/issues/620#issuecomment-95100206). Does that include contacts who turn out to be non existing in WhatsApp after syncing them?
2. Do I have to subscribe to presence after getting onNumberWasAdded event? As I understand I should mark the contact as EXISTING in my app, so that seems logical.
3. Do I have to unsubscribe after getting onNumberWasRemoved event?

**Comment by mgp25** [comment]
1. Why would you subscribe something that not exists?
2. Only when you have synced the number / going to start a conversation
3. When you remove the number from your contact list

Regards

**Comment by rogobob** [comment]
Does your answer to point 2 also apply for sendGetStatuses and sendGetProfilePicture? In other words, after sync, if number exists in WA, I get its status and picture

**Comment by mgp25** [comment]
Yes, also is triggered if received a notification, like profile picture updated, etc

**Comment by rogobob** [comment]
@mgp25 Alright, thank you!

Let me give you a suggestion to edit the documentation / flow so people don't ask this anymore. But you know best.

**Can I sync a number more than once?**
- You can only resync previously synced numbers on login, but NOT on every login (source: https://github.com/WHAnonymous/Chat-API/issues/620#issuecomment-95100206)

**When to subscribe for presence (call sendPresenceSubscription)?**
One of these:
- You can subscribe after a number is synced for the first time and exists in WhatsApp (this covers the situation when you log in for the first time and subscribe to numbers in your existing contact list) 
- You can subscribe before starting a conversation with a number (number must be synced and existing in WA), but only once

Also always when:
- receiving a 'number updated' notification (https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes), after unsubscribing from presence first
- receiving a 'number added' notification

Rule 1: The number should be already synced and existing in WhatsApp before subscribing
Rule 2: You must subscribe before starting a conversation with a number
Rule 3: Do not subscribe for presence before unsubscribing first

**When to unsubscribe from presence (call sendPresenceUnsubscription)?**
- when removing number from your contact list
- when receiving a 'number removed' notification (https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes)
- when receiving a 'number updated' notification (https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes)

Rule 1: The number should have been synced already
Rule 2: Do not unsubscribe for presence before subscribing first

**When to get contact status (call sendGetStatuses)?**
- after a number is synced for the first time and exists in WhatsApp
- receiving a 'number updated' notification (https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes)
- receiving a 'number added' notification

**When to get contact profile picture (call sendGetProfilePicture)?**
- after a number is synced for the first time and exists in WhatsApp
- receiving a 'number updated' notification (https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes)
- receiving a 'number added' notification

**Comment by mgp25** [comment]
@rogobob thanks, ill add this to the wiki tonigh or this weekend

Regards

**Comment by Raisel** [comment]
very good (y)
