### ISSUE TITLE
Messages sent from a Cell Phone don't reach application

### ISSUE THREAD

**Issue by boxgames1** [WHAnonymous/Chat-API#1166]
Hi. 

I have a problem with messages sent from "some" Cell Phones. The API receives the messages correctly from phone numbers wich they had a conversation previously, however, if I have a Cell Phone that never mantained a conversation with the API number, the messages don't reach API, but images.

I have the API updated with the last changes.

Is this a whatsapp new measure?

Have you detected a similar behavior?

Thanks.

**Comment by mgp25** [comment]
@boxgames1 without debug log, we cant help you

**Comment by boxgames1** [comment]
The messages don't reach the API.

I guess is a config problem or a whatsapp new measure.

**Comment by mgp25** [comment]
@boxgames1 post debug log! without debug log we cant even know

And it works perfectly by the way

**Comment by boxgames1** [comment]
This is the API Debug Log:

tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="XXXXXXXXXXX">ÈÅu¶XXXXXXXXXXXñGfù”vÿ†lS3}ßÕ1446719418</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>›é¦;›á  ”íœOòV÷Ð/Î¶</challenge>

tx  <response>"BeG0v\m<.!(ð~`–Œö(Ã½²éI•ˆ¥J</response>

rx  <success t="1446719405" props="4" kind="free" status="active" creation="1412671345" expiration="1475743345">-§ÿÀTA(8á2ùÄt¦</success>

tx  <presence name="JJJJJJJJJJ"></presence>

tx  <presence type="active"></presence>

tx  <iq id="1" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="interactive" sid="1.3091196619E+17" index="0" last="true">
tx      <user>+ZZZZZZZZZZZ</user>
tx    </sync>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="XXXXXXXXXXX@s.whatsapp.net"></presence>

rx  <presence from="VVVVVVVVVVV@s.whatsapp.net" type="unavailable" last="1446719063"></presence>

rx  <presence from="YYYYYYYYYYY@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="ZZZZZZZZZZZ@s.whatsapp.net" type="unavailable" last="1446718923"></presence>

rx  <iq from="XXXXXXXXXXX@s.whatsapp.net" type="result" id="1">
rx    <sync index="0" sid="1.3091196619E+17" last="true" version="1446718396072117">
rx      <in>
rx        <user jid="ZZZZZZZZZZZ@s.whatsapp.net">+ZZZZZZZZZZZ</user>
rx      </in>
rx    </sync>
rx  </iq>

rx  <presence from="YYYYYYYYYYY@s.whatsapp.net"></presence>

tx  <iq id="2" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="2" t="1446719501"></iq>

rx  <presence from="WWWWWWWWWWW@s.whatsapp.net"></presence>

rx  <chatstate from="WWWWWWWWWWW@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <chatstate from="WWWWWWWWWWW@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <message from="WWWWWWWWWWW@s.whatsapp.net" type="text" id="mg6hhYwFmNW36" t="1446719531" notify="______ ðŸˆ">
rx    <enc v="1" type="pkmsg">3¼ØŸ!É¬MýärW>²á¿Y¤4A&ÔšŒ(‡÷"Ô!2¶lJOù’HÝuÑ>ÒZ=õ#Ï0öË²Ï)#G@$"B3
!h<˜„À`tµ!å
Œ$t„¥½@¾¼Sš‚Åê±§©  "‰8ÂÜ&¥Ñj.5ø¸ûºåÀå6ãÈP(•¯ž«0Úu</enc>
rx  </message>

tx  <ack to="WWWWWWWWWWW@s.whatsapp.net" class="message" id="mg6hhYwFmNW36" t="1446719531"></ack>

tx  <iq id="3" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="WWWWWWWWWWW@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="3">
rx    <list>
rx      <user jid="WWWWWWWWWWW@s.whatsapp.net">
rx        <registration>%g—•</registration>
rx        <type></type>
rx        <identity>2¶lJOù’HÝuÑ>ÒZ=õ#Ï0öË²Ï)#G@$</identity>
rx        <skey>
rx          <id>   </id>
rx          <value>¼ºWå5…2Üè3o×ÏcYaÿ0IÇàb¹´</value>
rx          <signature>€=80V„®×ÊÍ~ŒHEÚp3žëR00Æ7è4nnù\,Ä¤M#òóìI#iŠÄ~œêBB2Áá</signature>
rx        </skey>
rx        <key>
rx          <id>ô³4</id>
rx          <value>³4ÌŒ À™,§mÞb!J0â‚q¸¤8|Z3@</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

tx  <ack to="WWWWWWWWWWW@s.whatsapp.net" class="message" id="mg6hhYwFmNW36" t="1446719531"></ack>


-> Decrypted Message: No such signedprekey with id: 15066 - /directory/whatsapi/SqliteAxolotlStore.php - 203Message mg6hhYwFmNW36 could not be decrypted, sending retry.

tx  <receipt id="mg6hhYwFmNW36" to="WWWWWWWWWWW@s.whatsapp.net" type="retry" t="1446719531">
tx    <retry v="1" count="1" id="mg6hhYwFmNW36" t="1446719531"></retry>
tx    <registration>#F€'</registration>
tx  </receipt>

rx  <ack from="WWWWWWWWWWW@s.whatsapp.net" class="receipt" type="retry" id="mg6hhYwFmNW36"></ack>

rx  <message from="WWWWWWWWWWW@s.whatsapp.net" type="text" id="mg6hhYwFmNW36" t="1446719532" notify="______ ðŸˆ">
rx    <enc v="1" type="pkmsg" count="1">3ûØŸ!†ŸNñ8UÒó„)‹>‹xNDVë[ï¥ÞÜ“LŠu!2¶lJOù’HÝuÑ>ÒZ=õ#Ï0öË²Ï)#G@$"B3
!ùze»r©$ªÅªmÔÉ]Tª˜>„I³{æ¼ìo  "Ø;6Ê­¡Xñ†.0?&%Ò3äTºðú(•¯ž«0Úu</enc>
rx  </message>

tx  <ack to="WWWWWWWWWWW@s.whatsapp.net" class="message" id="mg6hhYwFmNW36" t="1446719532"></ack>


-> Decrypted Message: No such signedprekey with id: 15066 - /directory/whatsapi/SqliteAxolotlStore.php - 203Message mg6hhYwFmNW36 could not be decrypted, sending retry.

tx  <receipt id="mg6hhYwFmNW36" to="WWWWWWWWWWW@s.whatsapp.net" type="retry" t="1446719532">
tx    <retry v="1" count="2" id="mg6hhYwFmNW36" t="1446719532"></retry>
tx    <registration>#F€'</registration>
tx  </receipt>

rx  <ack from="WWWWWWWWWWW@s.whatsapp.net" class="receipt" type="retry" id="mg6hhYwFmNW36">
rx    <retry v="1" count="2" id="mg6hhYwFmNW36" t="1446719532"></retry>
rx    <registration>*Ê“¤</registration>
rx  </ack>

**Comment by mgp25** [comment]
```
-> Decrypted Message: No such signedprekey with id: 15066 - /directory/whatsapi/SqliteAxolotlStore.php - 203Message mg6hhYwFmNW36 could not be decrypted, sending retry.
```

Now you know

**Comment by boxgames1** [comment]
What means that? I followed the steps of the last updates to crypt/decrypt the message.

Am I missing something?

**Comment by mgp25** [comment]
@boxgames1 just remove `axolotl.db` from `wadata` folder, restart it and it should work

**Comment by boxgames1** [comment]
Thanks. However I detected a bug. The API can't receive a text message equals to "0". I guess the problem is in the Line 345 of the MessageHandler because PHP takes the 0 as false.

Kind regards.
