### ISSUE TITLE
Sync question: different types of Sync, what for?

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#1168]
I've used to register every user using "delta" sync, and I have never used "registration". Also, I have never done a "full" sync.

I wonder if just doing "delta" syncs can be a reason of failure. What are these other options for?

Should I run a "registration" and/or "full" somewhere in the life of a connection? and in every new connection? or just once in life for every phone?

**Comment by mgp25** [comment]
@hgc2002 its explained in other issues + in the wiki.

Regards
