### ISSUE TITLE
LogInFailureException while sending from server

### ISSUE THREAD

**Issue by sphirelabs** [WHAnonymous/Chat-API#1169]
Am continuously getting the loginfailure error and < not-authorised > message while logging in to server. I tried multiple numbers, both real and virtual ones. Am getting the login password from the server using the exampleregister.php. 

But when am login in using the exact code in exampleregister after changing my credentials, its giving me loginfailure due to < not-authoriesd >. I came to know this is because whatsapp blocked my number, But I havent send a single message for this BAN. I tied registering the number in my mobile device. But now its not giving any ban messages. Am able to send messages on phone using the same number which I got login failure from server.

I tried changing the IPs, currently using VM from AZURE, tied many locations of server, changed the numbers. Still getting the same error. Can someone tell me what's going on?

**Comment by mgp25** [comment]
Without debug log we can't do anything, post debug log
