### ISSUE TITLE
Cyrillic characters in sendGetStatuses

### ISSUE THREAD

**Issue by Stepkaa** [WHAnonymous/Chat-API#1171]
After receiving status message with сyrillic letters, all I get is weird symbols like ÐŸÑ€Ð¸Ð²ÐµÑ‚ instead of Привет. How can I convert this string from CP1252 to utf-8?

**Comment by mgp25** [comment]
https://www.google.es/search?q=How+can+I+convert+this+string+from+CP1252+to+utf-8&ie=utf-8&oe=utf-8&gws_rd=cr&ei=mnc8VvOoGIGsU-zSrsAC
