### ISSUE TITLE
An error occurred registering the registration code from WhatsApp.

### ISSUE THREAD

**Issue by Digga2014** [WHAnonymous/Chat-API#1172]
Sorry, i have tried with 10 different numbers. The result is:

Array
(
    [in] => 606843857
    [cc] => 79
    [id] => s[▒▒h٨x▒2▒▒▒$3▒x
    [lg] => ru
    [lc] => RU
    [sim_mcc] => 250
    [sim_mnc] => 000
    [method] => sms
    [token] => a17e901cbe654e4309709ba6b2b2e9dc
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)

Enter the received code: 532-528
Array
(
    [cc] => 79
    [in] => 606843857
    [id] => s[▒▒h٨x▒2▒▒▒$3▒x
    [code] => 532528
)
stdClass Object
(
    [status] => fail
    [reason] => temporarily_unavailable
    [retry_after] => 3600
)
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable

Whats going on?

**Comment by 0xTryCatch** [comment]
As the error says try again later

**Comment by Digga2014** [comment]
It means that there is no error in ChatAPI?
Look at ChatAPI wiki. There is no account status: temp_unavail. Add this status into wiki =)

**Comment by disearth** [comment]
But when we try again it blocked the number.

**Comment by Digga2014** [comment]
It's true! I think that we must wait for ([retry_after] => 3600) / 60 seconds and try again. But I am trying with different phone numbers some days.
