### ISSUE TITLE
Issue on client.php

### ISSUE THREAD

**Issue by abhishekdeshkar** [WHAnonymous/Chat-API#1175]
Hello,
API works fine. But when I try to run WA CLI Client it comes with this errors.

#################################### # # # WA CLI CLIENT # # # #################################### ==================================== 
Notice: Undefined variable: argv in C:\xampp\htdocs\wa\examples\chat\client.php on line 33
Welcome to CLI WA Client ======================== Your number > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 58

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 58

Notice: Undefined variable: nickname in C:\xampp\htdocs\wa\examples\chat\client.php on line 59
there is an errorexception 'Exception' with message 'The provided phone number is not valid.' in C:\xampp\htdocs\wa\src\whatsprot.class.php:299 Stack trace: #0 C:\xampp\htdocs\wa\examples\chat\client.php(63): WhatsProt->codeRequest('sms') #1 {main} Enter sms code you have received > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 69

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 69
there is an error Your nickname > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 79

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 79
Is '' right? yes/no > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 84

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 84
Your nickname > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 88

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 88
Is '' right? yes/no > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 84

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 84
Your nickname > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 88

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 88
Is '' right? yes/no > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 84

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 84
Your nickname > 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\wa\examples\chat\client.php on line 88

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\wa\examples\chat\client.php on line 88

Why so ?

**Comment by 0xTryCatch** [comment]
You can't run it in a webserver environment. Run it in CLI

**Comment by edmund88** [comment]
#################################### # # # WA CLI CLIENT # # # #################################### ==================================== Welcome to CLI WA Client ======================== Your number > 
Fatal error: Call to undefined method WhatsProt::codeRequest() in /home/public_html/examples/WA CLI Client/client.php on line 63

Is this issue similar?
