### ISSUE TITLE
Ajax Demo, can't receive messages.

### ISSUE THREAD

**Issue by pituseligmann** [WHAnonymous/Chat-API#1176]
Hello, I've been reading on the latest issues to see if I could find something along the lines of what's happening to me but didn't quite find.

After registering to whatsapp with a new number, I am able to send messages, attachments and so to a few test numbers of my own. It works flawlessly. 

I tried configuring the Ajax Demo and I can see my number's profile picture, send a message from the <input> but I can't receive a response.

Using chrome dev tools I found out that the script is checking ajax.php and socket.php regularly. After I send a message from the PHONE to the APPLICATION, this is the log I was able to catch from the socket.php file.

```
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="5491134257911">?V_+5491134257911?????o?/?9??_?r??1446830431</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>?s[?0^??f??1%???</challenge>

tx  <response>?A????7fV?'???g??	?u?Q@WBT???{?</response>

rx  <success t="1446830485" props="4" kind="free" status="active" creation="1443665263" expiration="1475201263">??R??l??J??3???f??</success>

tx  <presence name="0"></presence>

tx  <presence type="subscribe" to="5491158844124@s.whatsapp.net"></presence>

rx  <message from="5491158844124@s.whatsapp.net" type="text" id="1446830427.--303" offline="1" t="1446830482" notify="Pitus">
rx    <enc v="1" type="pkmsg">3?!????Tdr?894?08??5H?c-??_7?j;i)!FV?,ar??;?*w???a?t???F?v"B3 !??k{????pJ??1H P?[?3c?E?nx?6o"??ag??5??*??m??94??(????0</enc>
rx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="5491134257911@s.whatsapp.net"></presence>

rx  <presence from="5491158844124@s.whatsapp.net"></presence>

rx  <presence from="5491158844124@s.whatsapp.net"></presence>
```

I read a few posts about encryption, and it's not something I enabled on my phone or anything. Does the <enc> tag mean that I need to install whatever package is required to enable de/encryption t parse the mesages? Because on the ajax demo I'm not getting any output whatsoever on the html, not even encrypted.

Thanks so much for the api, great work.

Best regards

**Comment by mgp25** [comment]
@pituseligmann only decrypted messages will be shown, yes you need to install the requirements

**Comment by pituseligmann** [comment]
I'm having some trouble installing the required libraries to be able to decrypt the messages. This post is not about that. I read that if you use the resetAccount.php script followed by the registerTool.php decryption would not be necessary. Is this right? Because after following this steps, the messages are still encrypted.

Thank you.
