### ISSUE TITLE
Change Curve25519

### ISSUE THREAD

**Issue by eliasjnior** [WHAnonymous/Chat-API#1179]
What about change the Curve25519 extension to a pure coding, like that one: https://github.com/lt/PHP-Curve25519

I think it's not just me that is getting troubles trying to install this extension and to compile this extension in Windows is not easily as Linux.

I didn't test this library (and don't know how, hahaha), it's just a sugestion.

**Comment by 0xTryCatch** [comment]
That library is not sufficient, the extension is the only way.
