### ISSUE TITLE
[Tutorial] How to install required extensions for encrypted messages

### ISSUE THREAD

**Issue by eliasjnior** [WHAnonymous/Chat-API#1180]
This is a simple tutorial. I don't know how to add in the page, so, I'm writing here.

### Installing php5-dev extension
Run the following line to install and use the "phpize" command:
```
sudo apt-get install php5-dev
```

### Install Git
Follow the Git instructions here: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
```
sudo apt-get install git
```

### Clone repositories
Go to any folder that you want, or create a new one:
```
cd /home
mkdir chat-api-extensions
cd chat-api-extensions
```
And now clone the repositories
```
git clone https://github.com/allegro/php-protobuf.git
git clone https://github.com/mgp25/curve25519-php
```

### Install extensions
Go to each cloned folder (`cd php-protobuf` and `cd curve25519`) and run:

```
phpize
./configure
make
sudo make install
```
Your extensions are installed, but need to activate.
Find where the php.ini is:
```
php -i | grep .ini
```
You will see something like: `Loaded Configuration File => /etc/php5/cli/php.ini`
This is the configuration path. Edit this file:

```
nano YOUR_CONFIGURATION_PATH
```
Go to the end of the file and add this two lines:
```
extension=curve25519.so
extension=protobuf.so
```
Now you are ready to receive encrypted messages :)

**Comment by mouhammad-zd** [comment]
You are wonderful person thanks for saving our day :D

**Comment by iffifan** [comment]
this should be in wiki

**Comment by archergod** [comment]
+1 vote to make it part of WIki

**Comment by mgp25** [comment]
I'll also add in the wiki how to turn on a computer and how to open internet explorer and move files to a folder...

**Comment by breakerh** [comment]
I agree with @mgp25  .These are basic things you need to know..
Not needed in the wiki imo

**Comment by awpsniper** [comment]
@mgp25 LOL HAHAHAHAHAHA

**Comment by manet80** [comment]
Dear friends , it addresses the issue of incoming messages ? I'm trying now to install a Linux server for this issue . Someone was able to work with this solution ?

**Comment by yashrs** [comment]
Can somebody help me out with installing these on windows pc ?
