### ISSUE TITLE
My number is not blocked but: rx <failure> rx <not-authorized></not-authorized> rx </failure>

### ISSUE THREAD

**Issue by NelsonGaldeman** [WHAnonymous/Chat-API#1181]
I can use WhatsApp thought an Android virtual machine (I've registered the WhatsApp account from there) so my number is not blocked. I'd got my WP password using your android app.

I don't know what's wrong but I constantly get:

```xml
	[] Logging in as 'N' (541136583548) tx  <stream:features>
	tx    <readreceipts></readreceipts>
	tx    <groups_v2></groups_v2>
	tx    <privacy></privacy>
	tx    <presence></presence>
	tx  </stream:features>

	tx  <auth mechanism="WAUTH-2" user="541136583548"></auth>

	rx  <start from="s.whatsapp.net"></start>

	rx  <stream:features></stream:features>

	rx  <challenge>'ÜvLöÍg´÷ì5ÝÅ ^ Ö</challenge>

	tx  <response>gð²ß‰ÃˆüßÆÄFÆÇÙ9ïKˆ‹”ç~£-93Çë</response>

	rx  <failure>
	rx    <not-authorized></not-authorized>
	rx  </failure>


	Fatal error: Uncaught exception 'LoginFailureException' in C:\AppServ\www\php\src\Login.php:53 Stack trace: #0 C:\AppServ\www\php\src\whatsprot.class.php(279): Login->doLogin() #1 C:\AppServ\www\php\tests\whatsapp.php(46): WhatsProt->loginWithPassword('i6zhz2cPYKqOanW...') #2 {main} thrown in C:\AppServ\www\php\src\Login.php on line 53
```

I've read other issues like this, but they always end in "your number is blocked" but it's not my case, that's why i'm openning a new issue.

I'm using "/tests/whatsapp.php" test script with lastest unmodified Chat-API code.

Thanks in advance.

**Comment by mgp25** [comment]
Use `blockChecker.php` (CLI script) + if you want to use that number with the API, just register it with `registerTool.php`

Regards

**Comment by NelsonGaldeman** [comment]
I ran blockChecker.php but:

Fatal error: Class 'Registration' not found in C:\AppServ\www\php\examples\blockChecker.php on line 30

I didn't find "Registration" class in the included files.

I've only changed:
	//$username = trim(fgets(STDIN));
	$username = "541136583648";

To use it from the webserver...

**Comment by mgp25** [comment]
sigh...

change this:

```php
require_once('../src/whatsprot.class.php');
```

to

```php
require_once('../src/Registration.php');
```

**Comment by NelsonGaldeman** [comment]
Now it worked.

Output:

	####################
	#                  #
	# WA Block Checker #
	#                  #
	####################


	Username (country code + number without + or 00): 

	Wrong identity. 
	Array
	(
		[cc] => 54
		[in] => 1136583548
		[id] => aõ…ˆyäû‡ú`£²:¨j’Úl½
		[lg] => es
		[lc] => AR
	)
	stdClass Object
	(
		[status] => fail
		[reason] => incorrect
		[sms_length] => 6
		[voice_length] => 6
	)

What does this means?

**Comment by jcav2** [comment]
I recommend you use wart.exe from https://github.com/mgp25/WART

Regards, Juan

<http://www.surbit.uy/>

[image: Facebook] <https://www.facebook.com/surbituy?fref=ts>

Ing. Juan Carlos Alvarez / CEO
juan@surbit <juan@surbit.uy>.uy / 099495475

Surbit
26826065
Park Way M18 S14 LagomarCanelones - Uruguay
http://www.surbit.uy

2015-11-07 14:14 GMT-03:00 Nelson Galdeman <notifications@github.com>:

**Comment by mgp25** [comment]
Means, you need to registerthe number first. Use `registerTool.php`

**Comment by NelsonGaldeman** [comment]
@mpg25 I've just registered it with wart.exe, I got the new password but I'm still getting the same messages... wrong identity with blockChecker.php and non-authorized with whatsapp.php test script. I may be doing something wrong...

**Comment by mgp25** [comment]
@NelsonGaldeman use `registerTool.php`....

**Comment by NelsonGaldeman** [comment]
I must wait 3 hours because I've just requested a code with wart.exe... I'll replay after I register the phone with registerTool.php

Thanks guys.

**Comment by mgp25** [comment]
@NelsonGaldeman you can use `voice` option

**Comment by NelsonGaldeman** [comment]
I tried, but I think I still have to wait

	####################
	#                  #
	# WA Register Tool #
	#                  #
	####################


	Username (country code + number, do not use + or 00): 

	Type sms or voice: Array
	(
		[in] => 1136583548
		[cc] => 54
		[id] => Æ]¤hÐ»ulëÞ„rp´í
		[lg] => es
		[lc] => AR
		[sim_mcc] => 722
		[sim_mnc] => 000
		[method] => voice
		[token] => 37376613200effec35253c81d0adf0e4
	)
	stdClass Object
	(
		[status] => fail
		[reason] => no_routes
		[retry_after] => 3600
	)
	There was a problem trying to request the code.

**Comment by zerodwide** [comment]
not-authorized is quite obvious!
 you are not authorized by two reasons:
1. not registered
2. blocked

**Comment by Raisel** [comment]
I had a similar problem. Which is the version of php are you using?

see issues #1148 to compare with your problem

I hope that together we can help in

Regards

**Comment by mgp25** [comment]
@zerodwide not really, also if data is wrong, which in this case seems to be this.
@Raisel not this case

@NelsonGaldeman when you have used `registerTool.php` it will output a login and a password, use that data to login and it should work

Regards

**Comment by Raisel** [comment]
Hi @mgp25 

Have you any idea what might be happening in my case?

Regards

**Comment by NelsonGaldeman** [comment]
After 2 days I tried again to register my phone with registerTool.php but I couldn't.

Resopnse:

	####################
	#                  #
	# WA Register Tool #
	#                  #
	####################


	Username (country code + number, do not use + or 00): 

	Type sms or voice: Array
	(
		[in] => 1136583548
		[cc] => 54
		[id] =>  'mke…å–îh©5yÐ™
		[lg] => es
		[lc] => AR
		[sim_mcc] => 722
		[sim_mnc] => 000
		[method] => sms
		[token] => 37376613200effec35253c81d0adf0e4
	)
	stdClass Object
	(
		[status] => fail
		[reason] => no_routes
		[retry_after] => 3600
	)
	There was a problem trying to request the code.

**Comment by mgp25** [comment]
I just tried your number, and worked perfectly:

Username (country code + number, do not use + or 00): 541136583548


Type sms or voice: sms
Array
(
    [in] => 1136583548
    [cc] => 54
    [id] => ??@?y?xnv?	n??x?v?
    [lg] => es
    [lc] => AR
    [sim_mcc] => 722
    [sim_mnc] => 000
    [method] => sms
    [token] => 37376613200effec35253c81d0adf0e4
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 25205
)


You should receive an SMS...

Check your IP

**Comment by NelsonGaldeman** [comment]
I've just received the SMS...

What about my IP? I'm using a server from USA, I'm from Argentina. Should that be a problem?

When I tried to get the enter the code it failed again.

	####################
	#                  #
	# WA Register Tool #
	#                  #
	####################


	Username (country code + number, do not use + or 00): 

	Enter the received code: Array
	(
		[cc] => 54
		[in] => 1136583548
		[id] => Ë³®¶¬•"°4xêÐmsâ"
	„
		[code] => XXXXXX
	)
	stdClass Object
	(
		[status] => fail
		[reason] => mismatch
		[retry_after] => 2
	)
	An error occurred registering the registration code from WhatsApp. Reason: mismatch

**Comment by mgp25** [comment]
@NelsonGaldeman of course it fails, becuase the identity `id` is not the same, you have generated a different one than me.

I recommend you to run the script locally, that way, you wont get any issue. Now you have to request the code again, and then register the sms code.

Regards

**Comment by NelsonGaldeman** [comment]
I will try again locally.

PD: Does this file contain the identity id? id.541136583548.dat (Just to know).

**Comment by mgp25** [comment]
@NelsonGaldeman yup

**Comment by NelsonGaldeman** [comment]
After I tried locally I could register my phone perfectly.

Now I don't get the "non-authorized" and it seems the messages are sent, but the receiver didn't get the message yet... should I open a new issue?

Thanks for the support guys... is there any donation page? If not, you should open it...

**Comment by mgp25** [comment]
@NelsonGaldeman yes, you should open a new issue, post the code and its debug log.

Donation info is in the readme: https://github.com/WHAnonymous/Chat-API

**Comment by ariel12345** [comment]
I have this problem that my account is blocked and this presents a serious error to me , so what I have to do ????????????????? Please help me , I could not send a message once

**Comment by igorer88** [comment]
Hi! I'm trying to register a number from Voxox app it generates USA numbers, but I always keep getting 

stdClass Object
(
    [status] => fail
    [reason] => blocked
)
There was a problem trying to request the code.
:/
