### ISSUE TITLE
Error in php_curve25519

### ISSUE THREAD

**Issue by EtchFoda** [WHAnonymous/Chat-API#1182]
I got this Error While Try to build php_curve25519.dll,php_protobuf.dll

C:\php-sdk\Null\win-php-sdk-builder-master\phpdev\vc11\x86\php-5.6.9>nmake php_curve25519.dll

Microsoft (R) Program Maintenance Utility Version 11.00.61030.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        "cl.exe" /D COMPILE_DL_CURVE25519 /D CURVE25519_EXPORTS=1 /nologo /FD /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3   /wd4996 /D_USE_32BIT_TIME_T=1   /MP  /Zi /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /D ZTS=1 /I "C:\php-sdk\Null\win-php-sdk-builder-master\phpdev\vc11\x86\deps\include"  /D FD_SETSIZE=256 /FoRelease_TS\ext\curve25519\ /FdRelease_TS\ext\curve25519\ /FpRelease_TS\ext\curve25519\ /FRRelease_TS\ext\curve25519\ /c ext\curve25519\curve.c
curve.c
ext\curve25519\curve.c(35) : warning C4013: 'curve25519_sign' undefined; assuming extern returning int
ext\curve25519\curve.c(57) : error C2143: syntax error : missing ';' before 'type'
ext\curve25519\curve.c(59) : error C2065: 'result' : undeclared identifier
ext\curve25519\curve.c(93) : error C2143: syntax error : missing ';' before 'type'
ext\curve25519\curve.c(94) : warning C4013: 'curve25519_donna' undefined; assuming extern returning int
ext\curve25519\curve.c(94) : error C2065: 'public' : undeclared identifier
ext\curve25519\curve.c(97) : error C2065: 'public' : undeclared identifier
ext\curve25519\curve.c(122) : error C2143: syntax error : missing ';' before 'type'
ext\curve25519\curve.c(123) : error C2065: 'shared_key' : undeclared identifier
ext\curve25519\curve.c(124) : error C2065: 'shared_key' : undeclared identifier
ext\curve25519\curve.c(124) : warning C4047: 'initializing' : 'const char *' differs in levels of indirection from 'int'
ext\curve25519\curve.c(163) : warning C4013: 'php_info_print_table_start' undefined; assuming extern returning int
ext\curve25519\curve.c(164) : warning C4013: 'php_info_print_table_row' undefined; assuming extern returning int
ext\curve25519\curve.c(165) : warning C4013: 'php_info_print_table_end' undefined; assuming extern returning int
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\cl.exe"' : return code '0x2'
Stop.
------------------------------------------------------------------------------------------------------------------------------

C:\php-sdk\Null\win-php-sdk-builder-master\phpdev\vc11\x86\php-5.6.9>nmake php_protobuf.dll

Microsoft (R) Program Maintenance Utility Version 11.00.61030.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Recreating build dirs
Recreating build dirs
Recreating build dirs
Recreating build dirs
Recreating build dirs
Recreating build dirs
        "cl.exe" /D _USRDLL /D PHP5DLLTS_EXPORTS /D PHP_EXPORTS /D LIBZEND_EXPORTS /D TSRM_EXPORTS /D SAPI_EXPORTS /D WINVER=0x500 /D COMPILE_DL_CURVE25519 /D COMPILE_DL_FILEINFO /D COMPILE_DL_MBSTRING /D COMPILE_DL_OPCACHE /D COMPILE_DL_PROTOBUF /D COMPILE_DL_SHMOP /D COMPILE_DL_SOCKETS /D COMPILE_DL_SQLITE3 /D COMPILE_DL_EXIF /D COMPILE_DL_MYSQL /D COMPILE_DL_MYSQLI /D COMPILE_DL_PDO_MYSQL /D COMPILE_DL_PDO_ODBC /D COMPILE_DL_PDO_SQLITE -Iext/bcmath/libbcmath/src  /DHAVE_MSCOREE_H=1  /Iext/date/lib /DHAVE_TIMELIB_CONFIG_H=1 /wd4244 -Dregexec=php_regexec -Dregerror=php_regerror -Dregfree=php_regfree -Dregcomp=php_regcomp -Iext/ereg/regex      /DHAVE_SQL_H=1 /DHAVE_SQLEXT_H=1 -Iext/pcre/pcrelib  /D HAVE_CONFIG_H    /I "ext/date/lib"  /DHAVE_TIMELIB_CONFIG_H=1 /I "ext\mbstring\oniguruma"  /DHAVE_ONIGURUMA_H=1    /nologo /FD /I . /I main /I Zend /I TSRM /I ext /D _WINDOWS /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3   /wd4996 /D_USE_32BIT_TIME_T=1   /MP  /Zi /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_INLINE /GF /D ZEND_DEBUG=0 /D ZTS=1 /I "C:\php-sdk\Null\win-php-sdk-builder-master\phpdev\vc11\x86\deps\include"  /D FD_SETSIZE=256 /FoRelease_TS\ext\protobuf\ /FdRelease_TS\ext\protobuf\ /FpRelease_TS\ext\protobuf\ /FRRelease_TS\ext\protobuf\ /c ext\protobuf\reader.c
reader.c
ext\protobuf\reader.c(8) : error C2054: expected '(' to follow 'inline'
ext\protobuf\reader.c(8) : error C2085: 'reader_read_fixed_uint32' : not in formal parameter list
ext\protobuf\reader.c(9) : error C2082: redefinition of formal parameter 'inline'
ext\protobuf\reader.c(9) : error C2146: syntax error : missing ',' before identifier 'fixed64_t'
ext\protobuf\reader.c(9) : error C2146: syntax error : missing ',' before identifier 'reader_read_fixed_uint64'
ext\protobuf\reader.c(9) : error C2143: syntax error : missing ';' before '('
ext\protobuf\reader.c(9) : error C2059: syntax error : ')'
ext\protobuf\reader.c(11) : error C2054: expected '(' to follow 'inline'
ext\protobuf\reader.c(11) : error C2085: 'reader_read_varint' : not in formal parameter list
ext\protobuf\reader.c(14) : error C2082: redefinition of formal parameter 'reader_init'
ext\protobuf\reader.c(14) : error C2143: syntax error : missing ';' before '{'
ext\protobuf\reader.c(31) : warning C4013: 'reader_read_fixed_uint64' undefined; assuming extern returning int
ext\protobuf\reader.c(31) : error C2440: '=' : cannot convert from 'int' to 'fixed64_t'
ext\protobuf\reader.c(46) : warning C4013: 'reader_read_fixed_uint32' undefined; assuming extern returning int
ext\protobuf\reader.c(46) : error C2440: '=' : cannot convert from 'int' to 'fixed32_t'
ext\protobuf\reader.c(61) : error C2440: '=' : cannot convert from 'int' to 'fixed64_t'
ext\protobuf\reader.c(76) : error C2440: '=' : cannot convert from 'int' to 'fixed32_t'
ext\protobuf\reader.c(89) : warning C4013: 'reader_read_varint' undefined; assuming extern returning int
ext\protobuf\reader.c(105) : warning C4146: unary minus operator applied to unsigned type, result still unsigned
ext\protobuf\reader.c(180) : error C2054: expected '(' to follow 'inline'
ext\protobuf\reader.c(181) : error C2082: redefinition of formal parameter 'reader_read_varint'
ext\protobuf\reader.c(181) : error C2143: syntax error : missing ';' before '{'
ext\protobuf\reader.c(205) : error C2054: expected '(' to follow 'inline'
ext\protobuf\reader.c(206) : error C2082: redefinition of formal parameter 'reader_read_fixed_uint32'
ext\protobuf\reader.c(206) : error C2143: syntax error : missing ';' before '{'
ext\protobuf\reader.c(217) : error C2054: expected '(' to follow 'inline'
ext\protobuf\reader.c(218) : error C2082: redefinition of formal parameter 'reader_read_fixed_uint64'
ext\protobuf\reader.c(218) : error C2143: syntax error : missing ';' before '{'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\cl.exe"' : return code '0x2'
Stop.

**Comment by mgp25** [comment]
Not API issue. I don't know how to compile it for windows

**Comment by EtchFoda** [comment]
ok i'll try to compile another extension

**Comment by EtchFoda** [comment]
all extension get errors 
no one can help and compile extension and upload them in .dll

**Comment by p031985s** [comment]
Hi there...

Di you solve it?
if yes, how?

Thank you

**Comment by EtchFoda** [comment]
not yet

**Comment by mgp25** [comment]
Extensions are already compiled and ready to use, read wiki
