### ISSUE TITLE
Missing info in how to install PHP Protobuf

### ISSUE THREAD

**Issue by pituseligmann** [WHAnonymous/Chat-API#1183]
I'm following the steps taken from the wiki ( https://github.com/WHAnonymous/Chat-API/wiki/Dependencies ).

I succesfully installed Curve25519 PHP on a Linux server with Ubuntu by doing 

```
phpize
./configure
make
sudo make install
```

But there is no documentation as to how install Protobuf. The Protobuf github explains how to use it for a given file, but I have no idea on which file I need to apply it. I also installed all other dependencies but I am still getting encrypted messages like

```
<enc v="1" type="pkmsg">3�!����Tdr�894�08��5Ĥ�c-��_7�j;i)!FV�,arȣ�;�*w���a�tޏ�תF�v"B3 !��k{����pJ��1H P�[�3c�E�nx�6o"���Ч� E�3��X|ەӷ����(����0</enc>
```

Any help would be appreciated.
Thank you very much.

**Comment by mgp25** [comment]
@pituseligmann its the same as curve25519.... its explained in the wiki...
