### ISSUE TITLE
Registration bad_token

### ISSUE THREAD

**Issue by pizzacrew** [WHAnonymous/Chat-API#1184]
Hello,

I want to register my whatsapp account as an Android device.

So I edited the registerTool.php File line 29: ```$w->codeRequest(trim($option), "T-Mobile5", 'Android');```

Also I edited the constants.php with

```
const WHATSAPP_DEVICE = 'Android';                                                           // The device name.
   
const WHATSAPP_VER = '2.12.317';                                                          // The WhatsApp version.
    
const WHATSAPP_USER_AGENT = 'WhatsApp/2.12.317 Android/5.0 Device/GalaxyS5';         // User agent used in request/registration code.
```

However I get the following error:
```
Type sms or voice: voice
Array
(
    [in] => 151*****
    [cc] => 49
    [id] => ­ú╗ý☺*Ü¶ß¥♠♦£→&u∟¸Þ‗
    [lg] => de
    [lc] => DE
    [sim_mcc] => 262
    [sim_mnc] => 000
    [method] => voice
    [token] => L2Z+CHDzhIMX+E76VW4kB5ryPc0=
)
stdClass Object
(
    [status] => fail
    [reason] => bad_token
)
There was a problem trying to request the code.```

**Comment by 0xTryCatch** [comment]
Don't edit the code unless you know what you are doing. Revert your changes and try again what the Githih code, it will work.

**Comment by pizzacrew** [comment]
But I don't think it is good to show an old Nokia device and support E2EE, if the original whatsapp software for Nokia does not support E2EE...
I assume your ```generateRequestToken``` function is deprecated.

**Comment by 0xTryCatch** [comment]
S40 has been chosen for very specific reasons so it is advised to use the API user agent.

**Comment by pizzacrew** [comment]
Thanks for answer. Can you tell me the reasons for choosing S40?

**Comment by 0xTryCatch** [comment]
Sorry no, we keep this private for the safety of this API
