### ISSUE TITLE
Datacenter IP

### ISSUE THREAD

**Issue by kwiiby** [WHAnonymous/Chat-API#1186]
You guys think that WhatsApp can monitor the IP of the client?

I'm afraid that WhatsApp may have a mechanism to determine if the IP is from a datacenter and not associate with a mobile phone and then ban the number?

**Comment by mgp25** [comment]
Why are you afraid? This API is supposed to be used only for personal usage. I use it only for personal usage.

**Comment by kwiiby** [comment]
What if I use for personal usage in a VPS?

**Comment by mgp25** [comment]
@kwiiby Facebook will follow you til death

Just kidding. if its for personal usage it doesnt matter, otherwise WA will block you, and they can flag IP, yes.

**Comment by kwiiby** [comment]
Thanks.
