### ISSUE TITLE
Can't sync any new contact, the second time. Receive connection cut.

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#1191]
Syncing a new contact works only first time. Second one blocks the user.

Even waiting more than one hour, syncing a second contact seems to work but I receive an inmediate communication cut, then my user get not authorized. Why?

The user was brand new registered. Only messages were sent to the first user synced succesfully. It couldn't send anything to the second one.

Any idea?

Thanks for your help.

**Comment by mgp25** [comment]
@hgc2002 next time you dont post code and debug log, i wont even read the issue, so plese provide always detailed information. Is a must: code + debug log

**Comment by hgc2002** [comment]
I'll get it. Sorry about this. Give me one day.

**Comment by hgc2002** [comment]
Not necessary. Strange but true, now it doesn't disable the user but send an error node with backoff time. Then, if you respect the backoff, sync works again. 

I didn't change anything before this.
