### ISSUE TITLE
Problem trying to request the code.

### ISSUE THREAD

**Issue by msmosso** [WHAnonymous/Chat-API#1197]
Hi guys, I got this error while tring to register my number.

Here in Brazil some cities have recently added a 9 in the beggining of some numbers, so I tried with and without it. But the same issue happens.

[hamcore@niflhein examples]$ php registerTool.php
####################
#                  #
# WA Register Tool #
#                  #
####################

Username (country code + number, do not use + or 00): 55229*******
Array
(
    [cc] => 55
    [in] => 2298320882
    [id] => uè¥t¢;(ÉÀ
õ%§è¥
    [lg] => pt
    [lc] => BR
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)
There was a problem trying to request the code.

**Comment by mgp25** [comment]
@msmosso quote the stuff you write

and are not requesting sms code properly, use `registerTool` without changing it

**Comment by msmosso** [comment]
@mgp25 Sorry about not quoting the code. I downloaded the code again and now i'm receiving this:
```
[hamcore@niflhein examples]$ php registerTool.php
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 55229*******


Type sms or voice: sms
Array
(
    [in] => 2298320882
    [cc] => 55
    [id] => ïe¢0½ymÐy6òzä7
    [lg] => pt
    [lc] => BR
    [sim_mcc] => 724
    [sim_mnc] => 000
    [method] => sms
    [token] => ddd587a9ce21458e1ecc3ddbe44f9da0
)
stdClass Object
(
    [status] => fail
    [reason] => no_routes
    [retry_after] => 3600
)
There was a problem trying to request the code.
```

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#number-registration

**Comment by NelsonGaldeman** [comment]
@msmosso Are you using the registerTool.php as a Client (thought an OS console) or as a web script?

**Comment by msmosso** [comment]
@mgp25 now the problem is other

![image](https://cloud.githubusercontent.com/assets/530015/11266845/c32509e6-8e8e-11e5-976e-d0407783475c.jpeg)

Am I blocked?
