### ISSUE TITLE
Warning: socket_write(): unable to write to socket [32]: Broken pipe in /whatsprot.class.php on line 2634

### ISSUE THREAD

**Issue by FrancYescO** [WHAnonymous/Chat-API#1199]
I'm just trying to do an automatic responder...
all i have done is putting all the code in a loop catching exceptions and on errors i'll restart connection, all is working good for ~48h after i get the error in the object and the script will not reconnect (not even after 1day), but stay in a dead loop spamming (only) the broken pipe warning.. here the code

killing and restart the script and restart will get my responder working again

(i'll process mssages with $w->setNewMessageBind($pn);)
```php
function connectWA(){
	global $w, $password;
	try {
        if (!$w->isConnected()) $w->connect();
        $w->loginWithPassword($password); 
	} catch(Exception $e) {
		echo date('d/m H:i:s')." Exception in connection, Retring...\n";
		sleep(10);
    }
}

while (1) {
	try {
		if (!$w->isConnected()) {
			connectWA();
			if ($w->isConnected()) echo date('d/m H:i:s')." Re-Connected to WhatsApp\n";
		} else {
			$w->pollMessage();
			sleep(0.5);
		}
	} catch(Exception $e) {
		echo date('d/m H:i:s')." Exception polling messages\n";
        $w->disconnect();
		echo date('d/m H:i:s')." Finalized disconnection\n";
    }
}
```

someone can help me?

**Comment by mgp25** [comment]
@FrancYescO make sure to post full code and debug log when the error happens

Anyway, it seems its disconnecting and therefore showing that warning/error, there are examples in the repository you can check

Regards

**Comment by FrancYescO** [comment]
infact it's all based on the code of examples/exampleFunctional.php

i just added the try/catch to reconnect on exceptions (that i have not seen in any example) but seems not catching at all if internet connection goes down (probably all stopped working after one of the last update of ChatApi)

i don't think other code can cause issue it's all copied from the example, i posted the core with my edit to catch disconnections

03/11 17:48:02 Connecting to WhatsApp
03/11 17:48:03 Connected to WhatsApp
...some message responded log

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /root/Chat-API-master/src/whatsprot.class.php on line 2634

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /root/Chat-API-master/src/whatsprot.class.php on line 2634

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /root/Chat-API-master/src/whatsprot.class.php on line 2634

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /root/Chat-API-master/src/whatsprot.class.php on line 2634

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /root/Chat-API-master/src/whatsprot.class.php on line 2634

**Comment by FrancYescO** [comment]
i did not know if is the correct way to do it.. but seems adding the exception in sendData function solved my issue
```php
            if (socket_write($this->socket, $data, strlen($data)) === false) {
				throw new ConnectionException('Socked Write failed!');
```

**Comment by lambasoft** [comment]
Im having the same error as well.
Did anyone found a solution ?

**Comment by prabube** [comment]
Hi now  am also facing this type of error. please give some suggestion.

**Warning: socket_write(): unable to write to socket [32]: Broken pipe in ../whatsprot.class.php on line 2748**

**Comment by shabnambanu1234** [comment]
Hi,
     I am trying to connect to whatsapp from my Centos godaddy vps server using WHATSAPI. I am getting same error and stuck here since last 3 days. I am providing the stack trace below. Please help . I am able to connect to whatsapp server but not login with password. 

Warning: socket_write(): unable to write to socket [32]: Broken pipe in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php on line 2748

Fatal error: Uncaught exception 'ConnectionException' with message 'Socked Write failed!' in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php:2749
Stack trace:
#0 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(2935): WhatsProt->sendData('\x80\x00\x16\x00s\x1Ew\xCBi\x7F\xB6\xA5\xBD\xFA\xE6...')
#1 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(1088): WhatsProt->sendNode(Object(ProtocolNode))
#2 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(328): WhatsProt->sendPing()
#3 /home/femiza2/public_html/WHATSAPP/src/Login.php(49): WhatsProt->pollMessage()
#4 /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php(287): Login->doLogin()
#5 /home/femiza2/public_html/WHATSAPP/MYEXAMPLES/whatsappListener.php(20): WhatsProt->loginWithPassword('G+/dhv513YS8tmi...')
#6 {main}
  thrown in /home/femiza2/public_html/WHATSAPP/src/whatsprot.class.php on line 2749

Thanks,
Shabnam
