### ISSUE TITLE
Problem with codeRequest

### ISSUE THREAD

**Issue by andrepaes** [WHAnonymous/Chat-API#1201]
Hello, i'm trying to register another number, and when i'm trying to get a new code with registerTool, this message appear :
PHP Fatal error:  Call to undefined method WhatsProt::codeRequest() in /home/andre/Chat-API-master/examples/registerTool.php on line 30
 anyone had the same error?

**Comment by mgp25** [comment]
@andrepaes update the api with the examples too

**Comment by alexjose** [comment]
This is not yet fixed. The example file `WA CLI Client\client.php` is showing the same error.
