### ISSUE TITLE
Problem sending image

### ISSUE THREAD

**Issue by bernabegh** [WHAnonymous/Chat-API#1202]
Hi, i have some problems when trying to send an image.

```php
$dst="506xxxxxxxx";
$wa = new WhatsProt($sender, $nickname, TRUE);
$wa->connect();
$wa->loginWithPassword($password);

$caption="test";
$filepath = "/var/www/html/img/some_image.jpg"; 
$fhash=hash_file('sha256',$filepath);
$fsize=0;

$wa->sendMessageImage($dst, $filepath, false, $fsize, $fhash, $caption);
$fsize=0; // with or without the real size it returns the same result. does not work !
$wa->sendMessageImage($dst, $filepath, true, $fsize, $fhash, $caption);
```

This is a screen capture of the debug and php errors
![screen shot 2015-11-12 at 11 43 52 am](https://cloud.githubusercontent.com/assets/4949875/11128637/92340cc2-8940-11e5-813e-280c20a7a6e9.png)

**Comment by mgp25** [comment]
@bernabegh 

dont set `fhash` and `fsize` if you dont know how to use it. Just leave it like this:

```php
$dst="506xxxxxxxx";
$wa = new WhatsProt($sender, $nickname, TRUE);
$wa->connect();
$wa->loginWithPassword($password);

$filepath = "/var/www/html/img/some_image.jpg"; 
$wa->sendMessageImage($dst, $filepath)
```

**Comment by bernabegh** [comment]
Thanks for your time, I tried the way u told me, but does not work yet

$caption = "xxxxxx";
$filepath = "http://static.ceroriesgo.co.cr/ceroriesgo/images/logo-criesgo.png";
$wa->sendMessageImage($dst, $filepath);
while(true){
$wa->pollMessage();
    sleep(2);
}

![screen shot 2015-11-12 at 2 35 51 pm](https://cloud.githubusercontent.com/assets/4949875/11130463/c87a2e6a-894a-11e5-94b5-487484bc3a33.png)

**Comment by bernabegh** [comment]
Fixed.
I was using a virtual machine whit an access limited IP.

layer 8 problem jajaj
