### ISSUE TITLE
Untrusted identity

### ISSUE THREAD

**Issue by pizzacrew** [WHAnonymous/Chat-API#1204]
Hello,

what does it mean when I get an exception 'untrusted identity'?
```
rx  <message from="xxxxx@s.whatsapp.net" type="text" id="oRR66aq+D/y+2" t="1447458048" notify="xxxx">
rx    <enc v="1" type="pkmsg" count="1">xxxx</enc>
rx  </message>

tx  <ack to="xxxx@s.whatsapp.net" class="message" id="oRR66aq+D/y+2" t="1447458048"></ack>


-> Decrypted Message: Untrusted identity!! - /var/www/robot_beta/src/libaxolotl-php/SessionBuilder.php - 53Message oRR66aq+D/y+2 could not be decrypted, sending retry.```

**Comment by mgp25** [comment]
@pizzacrew it means the sender identity is not being trusted for x reason. This could be for many reason, phone switching, reinstalling whatsapp, etc...

**Comment by pizzacrew** [comment]
Yes, I have reinstalled WhatsApp on my mobile device...
How do I "reload" the identity of an user in order to read the message again?

**Comment by 0xTryCatch** [comment]
Remove axolotl.db
