### ISSUE TITLE
Can not connect , it gives me a fatal error , what to do

### ISSUE THREAD

**Issue by ariel12345** [WHAnonymous/Chat-API#1206]
What do I need to do this to work , please help me , I could not send a message once , so if anyone knows how to solve it , it will help me a lot , Here I received error code

tx  < stream:features >
tx    < readreceipts >< /readreceipts >
tx    <groups_v2></groups_v2>
tx    < privacy >< /privacy >
tx    < presence >< /presence >
tx  < /stream:features >

tx  < auth mechanism="WAUTH-2" user="972890182414" >< /auth >

rx  < start from="s.whatsapp.net" >< /start >

rx  < stream:features >< /stream:features >

rx  < challenge >[�`3X����c.-������< /challenge >

tx  < response >��m�:��	�k;�7D�|�C�#mV����c6_< /response >

rx  < failure >
rx    < not-authorized >< /not-authorized >
rx  < /failure >

Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\11\src\Login.php:53 Stack trace: #0 C:\xampp\htdocs\11\src\whatsprot.class.php(279): Login->doLogin() #1 C:\xampp\htdocs\11\src\1.php(17): WhatsProt->loginWithPassword('165990') #2 {main} thrown in C:\xampp\htdocs\11\src\Login.php on line 53

**Comment by 0xTryCatch** [comment]
Stop spamming in all issues. You are blocked.
