### ISSUE TITLE
How to check if a User has a profile picture

### ISSUE THREAD

**Issue by lambasoft** [WHAnonymous/Chat-API#1207]
Hello

Supposing a user has privacy disabled for his profile picture, so anyone can see it.
And as well he deleted his profile picture, so he have no picture.

How can we check that ? 
Using the event "onGetProfilePicture" we can only get a value if user has a picture.

Is there a way to check if this user has his picture deleted.

Thanks

**Comment by mgp25** [comment]
@lambasoft i dont remember if you receive an error node or not, but if you check it with the debug log, you will see what event to use

If you still need help, post debug log requesting a profile picture from an user that has privacy enabled or doesnt have set it.

Regards
