### ISSUE TITLE
Parse error: syntax error, unexpected '[' in C:\wamp\www\Chat-API-master\src\whatsprot.class.php on line 2016

### ISSUE THREAD

**Issue by viennarzc** [WHAnonymous/Chat-API#1208]
require 'src/whatsprot.class.php';

	$username = "xxxxxxxxxxxxxxxx";    // Your number with country code, ie: 34123456789
	$password = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
	$nickname = "anonymous test";    // Your nickname, it will appear in push notifications
	$debug    = true;  // Shows debug log, this is set to false if not specified
	// $log      = true;  // Enables log file, this is set to false if not specified
	// $number = "639198294313";
// Create a instance of WhastPort.

	$w = new WhatsProt($username, $nickname, $debug);

	$w->connect(); // Connect to WhatsApp network
	$w->loginWithPassword($password); // logging in with the password we got!
	$w->sendGetPrivacyBlockedList();

	$target = '63xxxxxxxxxxx'; // The number of the person you are sending the message
	$message = 'Hi! :) this is a test message';

	$w->sendMessage($target , $message);

**Comment by mgp25** [comment]
@viennarzc what php version are you running?

**Comment by viennarzc** [comment]
@mgp25 I later found out that the PC I am using is still in PHP 5.3, I will upgrade this to 5.6, and maybe I'll be back with feedback. thanks!

**Comment by RavindraGharge** [comment]
I am getting the same Error. Need to upgrade the PHP from 5.3.

**Comment by pjucys** [comment]
Me too feel the same, I have the PHP version 5.3.13 installed on WAMP, how can I fix it?

**Comment by gojigeje** [comment]
@pjucys you need to upgrade to PHP 5.6 or later, please read the wiki:
https://github.com/WHAnonymous/Chat-API/wiki/Dependencies

**Comment by mgp25** [comment]
@gojigeje  :+1:
