### ISSUE TITLE
Newbie learning the ropes of Github with Chat api

### ISSUE THREAD

**Issue by edmund88** [WHAnonymous/Chat-API#1209]
Excited to see this API, Im getting my hands ready for this. 

I installed Github desktop version, forked it and proceed to install atom.

I did a clone in desktop and read through Wiki once more. Then the readme file.
Then to yowsup and back to wiki and readme. Im lost.

Google search : Run chat api whatsapp

Ok I need some help here guys, I cant figure out how to run this api.
From the file extension, its php. I downloaded python launcher but its more confusing.

I thought it would work if I threw it into my domain root folder, the codes showed up.
Can anybody guide me to bridging this link please?

Thank you.
Edmund

**Comment by mgp25** [comment]
@edmund88 are you going to run the script on webserver or desktop?

**Comment by edmund88** [comment]
I would like it on the webserver!

**Comment by mgp25** [comment]
@edmund88 there are examples in `/examples`  and `/tests` folders, anyway ill give you an example, then you have to research and test with them, sometimes you will fail and sometimes you will success, the important thing is that you learn.

```php
<?php
require_once('whatsprot.class.php');

$debug = false;

$nickname = 'Test';
$username = 'NUMBER';
$password = 'Password';
$target      = 'TargetNumber';

$w      = new WhatsProt($username, $nickname, $debug);

$w->sendMessage($target, 'This is a test');
$w->pollMessage();
$w->pollMessage();
$w->disconnect();
```

First of all you need an account: number and password.

As you are newbie, i recommend you using WART: https://github.com/mgp25/WART or WATools: http://www.watools.es/pwd.html

Oks, you you will have a number an a password, edit the code i posted above with the data you have. Also change `$target` to a number you want to send this test message.

The number account and target number must contain country code, for example:

In my case (Spain), my country code is 34, so my account will be country code + number: `34123456789`

Once you have set all i have told you, you can upload the script to your server and run it.

Another important thing, there is a var called `$debug`, this is set to `FALSE` so it wont show any debug information, but if you need to open a new issue remember to enable `$debug` to `TRUE` and post that information, also in debug log it show information like your number, you can replace that data with `***`.

I think with that, you can start playing with the API

Regards
