### ISSUE TITLE
Number Blocked after try register

### ISSUE THREAD

**Issue by renatovanquish** [WHAnonymous/Chat-API#1212]
Dear,
When I try to register a new number I get the message:
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
And the number is immediately blocked!
Repeat the process with different numbers in different IPs (3 different IPs).
There were 8 attempts, succeeded in just 1 number, others 7 were blocked!
I am using the latest version of the API, and example registerTool.php.
I use the API to several months, and I've done it several times successfully!
But now it is not working anymore.

**Comment by mgp25** [comment]
@renatovanquish dammit... is that hard to post the debug log? It is told to post debug log when opening a new issue.

If you want help, post full debug log and show which numbers are you using

**Comment by renatovanquish** [comment]
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number, do not use + or 00): 5511995371147


Type sms or voice: sms
Array
(
    [in] => 11995371147
    [cc] => 55
    [id] => |????w]?y??p60ͪ%gv?
    [lg] => pt
    [lc] => BR
    [sim_mcc] => 724
    [sim_mnc] => 000
    [method] => sms
    [token] => 046d3d423b53a009387e361e2111df91
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)


Enter the received code: 461938
Array
(
    [cc] => 55
    [in] => 11995371147
    [id] => |????w]?y??p60ͪ%gv?
    [code] => 461938
)
stdClass Object
(
    [status] => fail
    [reason] => temporarily_unavailable
    [retry_after] => 3600
)
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable

**Comment by yoanntel** [comment]
Hi 
i have 3 real SIM that i registered on 2 server and i have the same issue on both. It's possible to change some settings to connect the API by proxy or something else ? just to activate them...

**Comment by yoanntel** [comment]
I tried also with squid and export http_proxy="http://PROXY_IP:PORT/" and same result  ;-(

**Comment by yoanntel** [comment]
I registered 3 Real SIMs on my server and i got same status 
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable

and on my second server : 
status: fail
retry_after: 3600
reason: no_routes

**Comment by kwiiby** [comment]
Same problem here.. the problem may be the user agent? or IP? or what?

**Comment by yoanntel** [comment]
any fix ?
