### ISSUE TITLE
Number Blocked after try register

### ISSUE THREAD

**Issue by renatovanquish** [WHAnonymous/Chat-API#1213]
Dear,
When I try to register a new number I get the message:
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
And the number is immediately blocked!
Repeat the process with different numbers in different IPs (3 different IPs).
There were 8 attempts, succeeded in just 1 number, others 7 were blocked!
I am using the latest version of the API, and example registerTool.php.
I use the API to several months, and I've done it several times successfully!
But now it is not working anymore.

####################
#                                   #
# WA Register Tool      #
#                                   #
####################

Username (country code + number, do not use + or 00): 5511995371147

Type sms or voice: sms
Array
(
    [in] => 11995371147
    [cc] => 55
    [id] => |????w]?y??p60ͪ%gv?
    [lg] => pt
    [lc] => BR
    [sim_mcc] => 724
    [sim_mnc] => 000
    [method] => sms
    [token] => 046d3d423b53a009387e361e2111df91
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)

Enter the received code: 461938
Array
(
    [cc] => 55
    [in] => 11995371147
    [id] => |????w]?y??p60ͪ%gv?
    [code] => 461938
)
stdClass Object
(
    [status] => fail
    [reason] => temporarily_unavailable
    [retry_after] => 3600
)
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable

**Comment by mgp25** [comment]
@renatovanquish i think WA flagged your IPS and blocking the numbers or the number provider has been blocked. 

Remember that if you are not using this API for personal usage, the number will be blocked

Regards

**Comment by yoanntel** [comment]
Hi 
i have 3 real SIM that i registered on 2 server and i have the same issue on both. It's possible to change some settings to connect the API by proxy or something else ?  just to activate them...

**Comment by gravmatt** [comment]
@renatovanquish @mgp25  it seem WA has an IPS filter. you can't activate more then one number in a short amount of time. you have to wait until you try to activate the next number or us different proxy for every number. 

If you get the message temporarily_unavailable, your number is block for a couple hours. Just wait and try later again and everything is fine!

**Comment by oasis1234** [comment]
@mgp25. Instead of blaming the IPS or the phone operator, why don't you recognize that it's your fault.
Whatsapp isn't idiot; they detect your fake/outdated user-agent, sim params and other fake cryptographic algos.
I tried your WART without success. Then I retried using a real mobile (same IP and phone number), and voilá! registration succeedeed.
