### ISSUE TITLE
Warning: socket_write(): unable to write to socket [32]: Broken pipe in whatsprot.class.php on line 2635

### ISSUE THREAD

**Issue by lambasoft** [WHAnonymous/Chat-API#1214]
Greetings

I've searched everywhere trying to find the solution for that issue before posting , but couldn't find any.
I've been having this error lately ( I have the latest release ). Suddenly out of no where my tracker starts spamming me with thousands of lines of:

      Warning: socket_write(): unable to write to socket [32]: Broken pipe in whatsprot.class.php on line 2635

Could anyone help me find the fix for this ? Or tell me at least why is this happening ?

**Comment by marcozs84** [comment]
I experienced the same, consider that it is just a "warning", 
the connection is temporarily broken but it reconnects automatically after few seconds (at least for me),  
after that I´ve been able to continue using the API without problems even whit the "socket_write() warning" appearing from time to time

cheers

**Comment by FrancYescO** [comment]
look at my solution here

https://github.com/WHAnonymous/Chat-API/issues/1199
