### ISSUE TITLE
Managing receipts

### ISSUE THREAD

**Issue by germanalvarez** [WHAnonymous/Chat-API#1215]
To start with, I've readed several times the entire Wiki and the examples. I'm dealing with receipts now, and I'm on the point that I receive a custom message when message is sent and/or readed:

```php
public function onMessageReceivedClient($mynumber, $from, $id, $type, $time) 
    {
        if($type == "read"){
            echo "<p>El mensaje con ID ($id) ha sido LEIDO.</p>";}
        else{
            echo "<p>El mensaje con ID ($id) ha sido RECIBIDO</p>";}
    }

```
The thing is that I only receive this confirmation when sending the next one, I mean, when I send a message I receive last messages updates, not on the same sending. Its normal that this receipt delays a bit so it comes when re connecting after. 

How could I receive all updates without making any additional action? For example, not needing to send a new message to receive this receipt updates. Normally this receipt updates do not take more than 1-2 seconds to be available, isn't it?

**Comment by estcap** [comment]
Try putting extra ```$w->pollMessages()```  inside a main loop. That function processes incoming responses from the server.
For what you say, I think your code to sending messages calls it and that is why you just get that response when you send other message.
