### ISSUE TITLE
Getting Status: Fail, Reason: Blocked

### ISSUE THREAD

**Issue by igorer88** [WHAnonymous/Chat-API#1219]
Hi! I'm trying to register a number from Voxox app it generates USA numbers, but I always keep getting

```
stdClass Object
(
[status] => fail
[reason] => blocked
)
```
There was a problem trying to request the code.
:/

**Comment by mgp25** [comment]
@igorer88 provide full debug log (requesting code and registering code), and please, quote the debug properly

**Comment by igorer88** [comment]
Uhh.. I didn't know that, but there are plenty youtube "tutorials" with phones. So I thought that I could use it. 

Ps. I was trying to get the requesting code, so there isn't any, much less a registering code.

**Comment by mgp25** [comment]
I mean request and register debug log (full). Read the wiki and when you have it, post it

Regards
