### ISSUE TITLE
Number Blocked after try register

### ISSUE THREAD

**Issue by yoanntel** [WHAnonymous/Chat-API#1220]
Dear,
When I try to register a new number I get the message:
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
And the number is immediately blocked!
Repeat the process with different numbers in different IPs (3 different IPs).
There were 8 attempts, succeeded in just 1 number, others 7 were blocked!
I am using the latest version of the API, and example registerTool.php.
I use the API to several months, and I've done it several times successfully!
But now it is not working anymore.

i got the following message : 
An error occurred registering the registration code from WhatsApp. Reason: temporarily_unavailable
 and after with a second try : SIM blocked ;-(

I tried also with squid and export http_proxy="http://PROXY_IP:PORT/" and same result

**Comment by mgp25** [comment]
@yoanntel full debug log including numbers

**Comment by yoanntel** [comment]
1) It's real SIM i have them on my hand !
2) It's for personal usage too

Please help me

**Comment by mgp25** [comment]
@yoanntel post full debug log

**Comment by yoanntel** [comment]
i'm sorry but i still blocked the SIM and i not have traces from the first registration.
Do you want the traces of blocked

**Comment by yoanntel** [comment]
I make registration on the blocked SIM ?

**Comment by mgp25** [comment]
@yoanntel when you try with a new number, then remember to post full debug log

**Comment by yoanntel** [comment]
you're right i have it but only with yowsup currently 
because i try also by yowsup to register another one SIM this morning

**Comment by yoanntel** [comment]
it's can be help you to debug ?

**Comment by mgp25** [comment]
@yoanntel dont double post...

Debug log is the only way developers (us) can see what have happened. If you had read the wiki or even the readme you would realize that when opening a new issue, we always ask for a debug log. Whats the point of opening a new issue asking for help if the user don't post debug log?

**Comment by yoanntel** [comment]
Ok sorry for double post.... it's my first time on Github  ;-)

python /var/www/yowsup-master/yowsup-cli registration -C 33 -p 33632583578 -R 374067
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}

status: fail
retry_after: 3600
reason: temporarily_unavailable



And after a second registration after 3600

python /var/www/yowsup-master/yowsup-cli registration -C 33 -p 33632583578 -R 374067
INFO:yowsup.common.http.warequest:{"status":"fail","reason":"blocked"}

status: fail
reason: blocked

**Comment by yoanntel** [comment]
i got same with your API...... :-(

**Comment by mgp25** [comment]
@yoanntel if you want, send me a new number and let me try to register it, and ill tell you whats the issue

**Comment by yoanntel** [comment]
ok..  33632493693 i already placed SIM on the phone

**Comment by mgp25** [comment]
@yoanntel send me back the code when you receive it

**Comment by yoanntel** [comment]
ok i got the sms but Here ?? i'm a little bit affraid. It's my personal SIM. Can I send you in private ?

**Comment by mgp25** [comment]
@yoanntel yes, send it via email

**Comment by yoanntel** [comment]
please give me your mail ;-)

**Comment by mgp25** [comment]
here: https://github.com/mgp25 left side, you can find it

**Comment by yoanntel** [comment]
fine !

**Comment by mgp25** [comment]
@yoanntel send you back the number and the password.

It seems is your server or IP or whatever you are using. API its working flawlessly as always

Regards

**Comment by yoanntel** [comment]
humm...if my ip is blocked due to my many registration how can i register from my server ?

**Comment by yoanntel** [comment]
i just try himself 4 times on my server. Do you have a solution to change my ip address to register ? Or register by proxy or something else ? i need to register 6 more SIM

**Comment by mgp25** [comment]
@yoanntel is not API issue

**Comment by yoanntel** [comment]
it's improvement ?

**Comment by Rustem** [comment]
I have the same issue. I have three numbers for support service like call center (FAQ or Telegram BOT). I tried after different IPs hosting project in different countries and even hosting it by double proxies. Registration was not successfull. Only one number registered. After that my guess is that Whatsapp can ban by prefix. If you have 5 numbers and all of them share the same prefix except last two numbers, than you would be definitely blocked. What do you think ?
