### ISSUE TITLE
Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length

### ISSUE THREAD

**Issue by murderer99** [WHAnonymous/Chat-API#1223]
Good day!
I'v encountered this problem. Password was getted with registerTool.php, but:
`Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length (buff = 21 & treeLength = 25)'`

Stack trace: 
`#0 ../whatsprot.class.php(301): WhatsProt->readStanza()`
`#1 ../Login.php(42): WhatsProt->pollMessage()`
`#2 ../whatsprot.class.php(279): Login->doLogin()`
`#3 ../index.php(77): WhatsProt->loginWithPassword('Zjzhvc3qiy2KNts...')`
`#4 {main} thrown in ../whatsprot.class.php on line 2538`

i guess this is due to incorrect php extensions version or php settings (sockets?), becouse i was tested previous version of your lib on may-june 2015, this was works on some servers, and works not on others servers. The error was the same - `Fatal error: Uncaught exception 'ConnectionException' with message 'Tree length did not match received length...`

Now this error permanently occurs on all testing servers.

Could you send me your phpinfo()? my config attached.
[phpinfo.pdf](https://github.com/WHAnonymous/Chat-API/files/42451/phpinfo.pdf)

**Comment by mgp25** [comment]
@murderer99 

1º- API requirements can be found in the wiki.
2º- Check your code is updated
3º- Maybe you are trying to handle more data than the API can handle.

Regards

**Comment by murderer99** [comment]
1) Thx for API, 
2) code is updated, 
3) - just 

    $username = "7923603xxxx";
    $password = "Zjzhvc3qiy2KNts+lq+xxxxxxxx=";
    $nickname = "Pavel";
    $debug = true; 
    $msg = "This test";
    
    $w = new WhatsProt($username, $nickname, $debug);
    $w->connect();
    $w->loginWithPassword($password);
    $w->sendMessage($target, $msg);

**Comment by mgp25** [comment]
@murderer99 send me via mail your script and let me try it. And ill get back to you if everything is okay
