### ISSUE TITLE
Blocked after registering twice

### ISSUE THREAD

**Issue by BasvdW22** [WHAnonymous/Chat-API#1225]
I'll just leave this here.

Suddenly, I didn't receive any more messages from my own number in groups, it still worked in private chat and it would still receive messages from other people in groups, but my messages in groups were encrypted.
Then, after some time, private message were also encrypted and it would throw
```
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /root/Zermelo-WhatsApp-Bot/Chat-API/src/whatsprot.class.php:291
Stack trace:
#0 /root/Zermelo-WhatsApp-Bot/bot.php(34): WhatsProt->pollMessage()
#1 {main}
  thrown in /root/Zermelo-WhatsApp-Bot/Chat-API/src/whatsprot.class.php on line 291
```
So I tried searching for a solution in the already closed issues, tried everything, but nothing worked. I decided to reset and register my number again and got blocked.

Debug: http://pastebin.com/SX4hhnXp

Sorry for any mistakes in my grammar, I'm Dutch.

**Comment by mgp25** [comment]
@BasvdW22 do you have `curve25519` and `protobuf` extensions installed?

**Comment by BasvdW22** [comment]
Yes, I have.

**Comment by BasvdW22** [comment]
Or well, I did install them, any way I could check that?

**Comment by mgp25** [comment]
`php -m`

**Comment by BasvdW22** [comment]
Yup, listed there.

**Comment by mgp25** [comment]
@BasvdW22 the API decrypts correctly private chats messages? It should also decrypt group conversation messages.

**Comment by BasvdW22** [comment]
It decrypts private messages correctly and group messages, except for group messages sent by me.

**Comment by mgp25** [comment]
@BasvdW22 who sends the message, the script or you?

**Comment by BasvdW22** [comment]
Oh, sorry, I'm talking about me talking to the script, so the script doesn't decrypt group messages sent by me.

**Comment by mgp25** [comment]
@BasvdW22 send me an email

**Comment by BasvdW22** [comment]
Alright, done.

**Comment by mgp25** [comment]
@BasvdW22 did not receive it yet.

**Comment by BasvdW22** [comment]
Sent from basvdwollenberg@gmail.com to me@mgp25.com.

**Comment by BasvdW22** [comment]
Sorry, get to go, will be back in a few hours

**Comment by mgp25** [comment]
Error tracked, not sending ack to message `E4D1A1DC588B218C3664`. It's working at my side and many others, feel free to contact with me via mail if the issue persists.

Regards

**Comment by daniel1312** [comment]
hi ..

i have same problem last night. my WA suddenly cant receive and send messages.
pls give me solution for this case, i desperate to find solution.

tks a lot

this is my bug :+1: 

tx  <stream:features></stream:features>

tx  <auth user="6281291991802" mechanism="WAUTH-2">Xn¾Ñ6281291991802)†“@E_£ò3Šc ^o¾Ô1451447657</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>õ#‹7òñ—ºí²";[’Â6v+</challenge>

tx  <response>V*,²ÞÅMCRU6Øå®¼ÞN*Ò‡*„vºb°¾J˜Æ%Hk.<zñ!ÒÇ" u¨ò‹× Ü´å`¥ômÆÆ–0=cÒi<Ö</response>

rx  <success t="1451447657" props="4" kind="free" status="active" creation="1409498711" expiration="1466500617">ä}©ñY3ÅFbµ¶g	Â</success>

tx  <presence name="0" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <message from="628123302078@s.whatsapp.net" type="text" id="F+pJpS0mfXZoF" offline="3" t="1451447104" notify="F 415 AL">
rx    <enc v="2" type="pkmsg">3!–Pèá± Ú/ahšUâ›úœ@ç¸tþŠo2+ Ä(!¨ˆeåÅèß8~¦-iV7É@F ÒR*3 µ;X«®âG"³3 !GO:õ¹ªH·­Ûô'VçˆÑLSX¸žë?BÉ{žÖ8"€t9‚üI|Q‡Á‘]­žJ£öÚö%w×²ª\üÖÎƒ”äÒÙ¸î.Þ @ˆpÒ`½:F©xuQH^Zç-¯Ðzü¨é„ìZÃo²‘&‘ÕNÅs,üM©Ô`D- €|\š?ÈÂ'Ô–(îÒD%ÒÂ„ôÖdÎ¢×eŠ~b²l˜‘Ð(•’Ê²0†€‰</enc>
rx  </message>

rx  <message from="6289503232205@s.whatsapp.net" type="text" id="1UlvzSg5dPdG3" offline="3" t="1451447574" notify="*">
rx    <enc v="2" type="pkmsg">3!1>äz&&³¬‹ÏÔ"ˆ©ú<¿ZSX†%R)‘ûøÙ !‹´<*ýõóVû-áî~L½t†‡½«#û2&8L"B3 ![Þw^‰­JùE©`·¾´Ë_¸ƒ4«Šì9žŠt•²}"+âÕbà"9},l±mÝrRy÷rô(ã¥‹§0Ìç¦</enc>
rx  </message>

rx  <message from="6289503232205@s.whatsapp.net" type="text" id="1UlvzSg5dPdG3" offline="3" t="1451447574" notify="*">
rx    <enc v="2" type="pkmsg">3!1>äz&&³¬‹ÏÔ"ˆ©ú<¿ZSX†%R)‘ûøÙ !‹´<*ýõóVû-áî~L½t†‡½«#û2&8L"B3 ![Þw^‰­JùE©`·¾´Ë_¸ƒ4«Šì9žŠt•²}"…b¸?ÓˆÌógÍ™Qƒï£?è-j«€n(ã¥‹§0Ìç¦</enc>
rx  </message>

rx  <ib from="s.whatsapp.net">
rx    <offline count="3"></offline>
rx  </ib>

rx  <presence from="6281291991802@s.whatsapp.net"></presence>

rx  <presence from="628123302078@s.whatsapp.net" type="unavailable" last="1451447279"></presence>

rx  <presence from="6285265498553@s.whatsapp.net" type="unavailable" last="1451447272"></presence>

rx  <presence from="6281293816617@s.whatsapp.net"></presence>

rx  <presence from="6289503232205@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="62816506248@s.whatsapp.net" type="unavailable" last="1451447229"></presence>

rx  <presence from="6281336446224@s.whatsapp.net" type="unavailable" last="1451447292"></presence>

rx  <presence from="628111813334@s.whatsapp.net"></presence>

rx  <iq from="6281291991802@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="error" id="02">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>
