### ISSUE TITLE
Block numbers

### ISSUE THREAD

**Issue by eftimie-andrei** [WHAnonymous/Chat-API#1226]
Hi there!
I use Chat-api in a cli-mode to send message to my co-workers and in the last two week aprox. i have i get blocked a lot of numbers. I dont send mass messges, and for that i think it's something wrong in my code. The server loop looks like that:

```php
while (1 == 1)
{   
    $Whatsapp->pollMessage();
    $messages = $myDB->getMessageToSend();
    foreach ($messages as $message)
    {
        $sync = array($message['number']);
        $Whatsapp->sendSync($sync); 
        $Whatsapp->pollMessage(); 
        $Whatsapp->sendPresenceSubscription($message['number']); 
        $Whatsapp->sendMessage($message['number'] , $message['message']);
    }
}
```

Normaly i send 150-200 message per day, i think thats not mass messages, i really don't know why whatsapp get blocked my accouts. 

It's a problem to be connected all the time to the server? 
The same question i have with `pollMessage()` function, whatsapp can blocked me if i call many times to this function?

I don't use encryptation, it's a problem?

Can someone tell me a better way to use this great api? Thanks a lot !!!

**Comment by mgp25** [comment]
@eftimie-andrei please always quote the code for easy reading.

Remember that if you use Chat API you agree to only use it for personal usage, nothing related with work / company etc..

1. Loop:

Whats the point of this loop? Infinite loop? Bad, change it.

```php
while (1 == 1)
```
2. Syncs ans subscription

What the point of adding everytime time abs dubscribing to it? This is totally wrong. Have you read the wiki?

```php
        $Whatsapp->sendSync($sync); 
        $Whatsapp->sendPresenceSubscription($message['number']); 
```

3. Sending flow

This is not human behaviour flow. Again, have you read the wiki?

There is a lot of examples and documentation in the wiki, you can also find the "real" flow.

4. Contacts

It doesn't matter if you send 10 or 10000 messages, the point is that, if the contact you are sending the message to, doesnt have you added as contact, that will rise a spam flag. Again, this can be found in the wiki and other closed issues.

Regards
