### ISSUE TITLE
API not sending messages in a case

### ISSUE THREAD

**Issue by boxgames1** [WHAnonymous/Chat-API#1230]
Hi.

I have the following case with a cell phone which never received or sent a message to the API.

1) I send a message from the API to the phone. OK
2) From that phone I send a message to the API. OK
3) After send a message from that phone to the API, any text message I sent in the other direction 
(API---->phone) doesn't reach. However, if I send an image, it reachs the phone.

I tried to find the problem and I guess it should be a crypt problem (sqlite maybe?), but I don't see any error in my log.

I need your help.

THANKS.

**Comment by mgp25** [comment]
@boxgames1 if you dont provide debug log we can't help you. ALWAYS post debug log when opening an issue

**Comment by boxgames1** [comment]
My app's log doesn't matter for this.

I can provide you the data traced of the sent messages from the API.

OK Message:
ERROR - 2015-11-25 13:56:03 --> 
phone: 346xxxxxx17
to: 346xxxxxx39@s.whatsapp.net
msgid: 26o00uEERCu10
type: text
notify: Develop


KO Message
ERROR - 2015-11-25 13:56:22 --> 
phone: 346xxxxxx17
to: 346xxxxxx39@s.whatsapp.net
msgid: 26o00uEERCu11
type: text
notify: Develop


As you can see the log trace are the same (but msgid obviously).

**Comment by mgp25** [comment]
As i said, without debug log we can't help you. If you wanto support/help you need to post debug log

**Comment by boxgames1** [comment]
I posted the Debug log trace that I generate before send message.

What debug log do you need exactly?

Thanks.

**Comment by mgp25** [comment]
@boxgames1 the one that is explained in the wiki.

Regards

**Comment by boxgames1** [comment]
MESSAGE THAT REACHS DEVICE

===============================================================================

tx  <message to="XXXXXXXXXXX@s.whatsapp.net" type="text" id="ZMANN5O6qIVx0" t="1448526534" notify="YYYYYYYYYYYYY">
tx    <enc v="1" type="msg">3
!î¶½Jo2±£kIÙ§_oÛð»¦ÎáÚ
                      ÷ËjÍ    Yìaxz9`×Z±Í X¡þAyY</enc>
tx  </message>            O"|Y

rx  <ack from="34615044004@s.whatsapp.net" class="message" id="ZMANN5O6qIVx0" t="1448526525"></ack>

rx  <receipt from="34615044004@s.whatsapp.net" type="read" id="ZMANN5O6qIVx0" t="1448526525"></receipt>

tx  <ack to="34615044004@s.whatsapp.net" class="receipt" id="ZMANN5O6qIVx0" t="1448526525" type="read"></ack>


MESSAGE THAT DOESN'T REACH DEVICE
===============================================================================

tx  <message to="XXXXXXXXXXX@s.whatsapp.net" type="text" id="wit4er3Lnjua1" t="1448526377" notify="YYYYYYYYYYYYY">
tx    <enc v="2" type="msg">3
!î¶½Jo2±£kIÙ§_oÛð»¦ÎáÚ
                      ÷ËjÍ
                          O"¼uê
                               ÞxÀ(={HàÛ|5ÎÉàE</enc>
tx  </message>

rx  <ack from="XXXXXXXXXXX@s.whatsapp.net" class="message" id="wit4er3Lnjua1" t="1448526368"></ack>

rx  <receipt from="XXXXXXXXXXX@s.whatsapp.net" id="wit4er3Lnjua1" t="1448526368"></receipt>

tx  <ack to="XXXXXXXXXXX@s.whatsapp.net" class="receipt" id="wit4er3Lnjua1" t="1448526368"></ack>

**Comment by mgp25** [comment]
Remove your `axolotl.db` and chat in your phone and try again. Try to make a better flow.

Regards

**Comment by boxgames1** [comment]
I made the same proccess twice.

1) Remove the DB 
2) Send message from API - OK
3) Send message from phone - OK
4) Send message from API - KO

The result is the same. The only difference I detected is the version (1 in OK messages and 2 in KO messages).

Thanks.

**Comment by mgp25** [comment]
@boxgames1 remove the chat from your mobile phone, and try sending a message again

**Comment by boxgames1** [comment]
I removed the chat from the phone and tried the proccess, but appears the same problem.

**Comment by boxgames1** [comment]
For more info, the Whatsapp Server receives the message because event onMessageReceivedServer is fired. This is the log trace of my application:


Message OK
```xml
reachs event
onMessageReceivedServer
ERROR - 2015-11-26 12:22:09 --> mynumber: XXXXXXXXXXX
ERROR - 2015-11-26 12:22:09 --> from: YYYYYYYYYYY@s.whatsapp.net
ERROR - 2015-11-26 12:22:09 --> id: YeqK0yxkskkU1
ERROR - 2015-11-26 12:22:09 --> type: message
ERROR - 2015-11-26 12:22:09 --> time: 1448536914
onMessageReceivedClient
ERROR - 2015-11-26 12:22:10 --> mynumber XXXXXXXXXXX
ERROR - 2015-11-26 12:22:10 --> from YYYYYYYYYYY@s.whatsapp.net
ERROR - 2015-11-26 12:22:10 --> id YeqK0yxkskkU1
ERROR - 2015-11-26 12:22:10 --> type read
ERROR - 2015-11-26 12:22:10 --> time 1448536914
```
Message KO
```xml
reachs event
onMessageReceivedServer
ERROR - 2015-11-26 12:22:38 --> mynumber: XXXXXXXXXXX
ERROR - 2015-11-26 12:22:38 --> from: YYYYYYYYYYY@s.whatsapp.net
ERROR - 2015-11-26 12:22:38 --> id: YeqK0yxkskkU2
ERROR - 2015-11-26 12:22:38 --> type: message
ERROR - 2015-11-26 12:22:38 --> time: 1448536943
onMessageReceivedClient
ERROR - 2015-11-26 12:22:40 --> mynumber XXXXXXXXXXX
ERROR - 2015-11-26 12:22:40 --> from YYYYYYYYYYY@s.whatsapp.net
ERROR - 2015-11-26 12:22:40 --> id YeqK0yxkskkU2
ERROR - 2015-11-26 12:22:40 --> type
ERROR - 2015-11-26 12:22:40 --> time 1448536944
ERROR - 2015-11-26 12:22:40 --> participant
```

**Comment by mgp25** [comment]
@boxgames1 whats the message?

**Comment by boxgames1** [comment]
The message is a text, I simply put some log_message in MyEvents to trace the flow.

The first trace is when I send a message from the API to the Phone and reachs it.

The 2nd trace is about the message from the API to the phone that doesn't reach

**Comment by mgp25** [comment]
@boxgames1 i know its a text message, but what it's content? When i was developing axolotl there was a padding and depends in the message length and what characters.

**Comment by boxgames1** [comment]
I tried with several messages but usually 4 to 8 characters

**Comment by mgp25** [comment]
@boxgames1 send an email to me
