### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by ricardoperovano** [WHAnonymous/Chat-API#1231]
Well, I have read some issues in the wiki but them doesn't answer my question.
I read on wiki that i can only sync once per hour, but how does the whatsapp client deal if I add 3 new contacts and send messages for them ? Will it send sync 3 times or i can sync once per hour and per contact ?

Thanks in adance!

**Comment by mgp25** [comment]
@ricardoperovano if you add to contact list a phone number is the same as sync, as simple as that.

Anyway, WhatsApp will track your flow and requests, and they can determine wether you use it for personal usage or not.

**Comment by ricardoperovano** [comment]
Thankyou!

On Wed, Nov 25, 2015 at 7:12 PM, mgp25 <notifications@github.com> wrote:

> @ricardoperovano <https://github.com/ricardoperovano> if you add to
> contact list a phone number is the same as sync, as simple as that.
>
> Anyway, WhatsApp will track your flow and requests, and they can determine
> wether you use it for personal usage or not.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1231#issuecomment-159732397>
> .
>



-- 
Att
Ricardo Perovano
