### ISSUE TITLE
Blocked number

### ISSUE THREAD

**Issue by ddfrreire** [WHAnonymous/Chat-API#1232]
Hi, my number was blocked. The sim card is new, when I requested registration code in debug show blocked number. Already all os files axolotl and nextCalled but, continue of problem. Is it any possibilites for fix this problem? 

Debug:
```
Array ( [in] => xxxx [cc] => 55 [id] => xxxx [lg] => pt [lc] => BR [sim_mcc] => 724 [sim_mnc] => 000 [method] => sms [token] => xxx ) 
stdClass Object ( [status] => fail [reason] => blocked )
```

**Comment by 0xTryCatch** [comment]
No, there is no way to undo this.

**Comment by mgp25** [comment]
That normally happens when you dont use it for personal usage
