### ISSUE TITLE
How to implement end to end encription

### ISSUE THREAD

**Issue by casion** [WHAnonymous/Chat-API#1233]
Hi,

I read the wiki and some issues, and I tried to install *PHP Protobuf* and *Curve25519 PHP*.

I cant understand how it works.

Do I need to download github projects and compile? add files to the same path?

Im using:

OSX Yosemite 10.10.5
PHP 5.6

I did

```
phpize
./configure
make
sudo make install
```
for both depedencies.

This is my console:

```
rx  <message from="xxxxxxxxxxxx@s.whatsapp.net" type="text" id="B7F761A1B770E8B51711" t="1448490687" notify="PH">
rx    <enc v="1" type="pkmsg">3!L4���
2Џå�F����QT��─L�·!�K�─�0:��D�]�Q��⎼�����±���\"B3
!Յ=E6�
'_�TR!��d�&b�O��#�I
                   "�>��������6gVU���#�ak(����0</enc>
rx  </message>
```

The bot doesnt even send double check when it receive a message.

Is there any thing that Im missing?

**Comment by mgp25** [comment]
It seems you havent checked if the extensiones are loaded correctly.

Run `php -m` and check if `protobuf` and `curve25519` are listed, if not, you need to add them in `php.ini`

Regards
