### ISSUE TITLE
Connection Closed after ~70sec.

### ISSUE THREAD

**Issue by tscheckenbach** [WHAnonymous/Chat-API#1235]
I get an exception "connection closed" after ~70sec. 
whatsprot.class.php : 307 ($this->sendPing()) never gets executed

Reproduceable with the "Simple CLI client.php" example.

**Comment by mgp25** [comment]
@tscheckenbach are you using latest API code? because it sends a ping every 2 or 3 minutes of inactivity.

In the other hand, `Simple CLI client.php` is a little outdated, but you can modify it, adapt it and update it.

Regards

**Comment by tscheckenbach** [comment]
Yes I'm  using 2.5.5.4
But as said the ping never gets send -> FILE: whatsprot.class.php LINE: 307

**Comment by mgp25** [comment]
@tscheckenbach provide full debug log and line in the code where its supposed to fire `sendPing()`

Regards

**Comment by tscheckenbach** [comment]
Oh wait, it's fixed in dev-master, I can use this version until 2.5.5.5 will be released.

Thanks
Cheers, Thorsten
