### ISSUE TITLE
Chat-API GUI

### ISSUE THREAD

**Issue by abhishekdeshkar** [WHAnonymous/Chat-API#1236]
Hello,

Is there any GUI which like Whatsapp App ? I mean like web whatsapp we can send messages using GUI.

Thanks! :-)

**Comment by alfredbaudisch** [comment]
The point of this PHP API is just so you can build your own GUI.

On Thu, Nov 26, 2015 at 2:02 PM, abhishekdeshkar <notifications@github.com>
wrote:

> Hello,
>
> Is there any GUI which like Whatsapp App ? I mean like web whatsapp we can
> send messages using GUI.
>
> Thanks! :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1236>.
>



-- 
Atenciosamente,
Alfred Reinold Baudisch

- Analista Desenvolvedor Sênior
- Gerente de Projetos de Software
- Arquiteto de Dados
- Web, Desktop, Mobile, Games

Email: fale@alfredbaudisch.com
Celular: (41) 8504-5173
Skype: AlfredBaudisch

**Comment by abhishekdeshkar** [comment]
Yes I understand just curious if it's already exists. Nothing else.

**Comment by alfredbaudisch** [comment]
I think this sophisticated WA Client has been made with this API:
http://www.whatscom.com.br/


On Thu, Nov 26, 2015 at 2:13 PM, abhishekdeshkar <notifications@github.com>
wrote:

> Yes I understand just curious if it's already exists. Nothing else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1236#issuecomment-159951285>
> .
>



-- 
Atenciosamente,
Alfred Reinold Baudisch

- Analista Desenvolvedor Sênior
- Gerente de Projetos de Software
- Arquiteto de Dados
- Web, Desktop, Mobile, Games

Email: fale@alfredbaudisch.com
Celular: (41) 8504-5173
Skype: AlfredBaudisch

**Comment by abhishekdeshkar** [comment]
Okay thanks ! Please let me know if you came across the source code otherwise I will need to create from the scratch.
