### ISSUE TITLE
I don't want to receive messages.

### ISSUE THREAD

**Issue by John127** [WHAnonymous/Chat-API#1238]
Hello.
When I try to send message to particular contact it receives the other contacts messages. I don't want to receive messages I just want to send messages.
Here is my code : 
```
<?php

require_once('../src/whatsprot.class.php');


$username = "hidden";
$nickname = "hidden";
$password = "hidden";// The one we got registering the number
$debug = true;

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

$w->sendMessage('1234567890' , 'test message');
$w->disconnect();
```

Thanks!

**Comment by mgp25** [comment]
@John127 you are disconnecting too soon, according to the readme, you should search in the previous issues before opening a new one, because this has been answered multiple times, so please, next time, search before ask. And read the wiki!!

```php
<?php

require_once('../src/whatsprot.class.php');


$username = "hidden";
$nickname = "hidden";
$password = "hidden";// The one we got registering the number
$debug = true;

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

$w->sendMessage('1234567890' , 'test message');
$i = 0;
for($i; $i < 5; $i++)
{
     $w->pollMessage();
}
$w->disconnect();
```

**Comment by John127** [comment]
You didn't get my point. I meant to say that I DONT WANT TO RECEIVE message from anyone. I just want to send message. I tried your code but I do receive message from others.

**Comment by mgp25** [comment]
@John127 maybe YOU DONT GET MY POINT. When you are sending a message in WhatsApp you can receive a message at the sametime in the background, just read the damn wiki, man. And if you dont want to check as read or received just disable the auto receipt.

USE YOUR LOGIC OR COMMON SENSE. This API works the same as WhatsApp does.
