### ISSUE TITLE
onGetReceipt get items list ID's

### ISSUE THREAD

**Issue by dasvis** [WHAnonymous/Chat-API#1239]
Hello,

I send various messages (each one with own id) to a contact in a time space and the contact reads all message at the same moment. I get the receipt with the last id which contains a item list with the others messages ID that have been read at the same time.

```
rx  <receipt from="34123123123@s.whatsapp.net" type="read" id="6z2B0CrNPLbr0" offline="0" t="1448615616">
rx    <list>
rx      <item id="+tMorJs47pyE0"></item>
rx      <item id="49bILj4lzUtk1"></item>
rx      <item id="49bILj4lzUtk0"></item>
rx    </list>
rx  </receipt>

tx  <ack to="34123123123@s.whatsapp.net" class="receipt" id="6z2B0CrNPLbr0" t="1448615616" type="read"></ack>

echo onGetReceipt 34123123123, 6z2B0CrNPLbr0, 0, , read, 1448615616
```

I would like get the items list ID to store read time on Db.

I really appreciate any help you can provide

**Comment by mgp25** [comment]
@dasvis read the wiki, use events.

**Comment by dasvis** [comment]
I have read the wiki and i don't see any event that capture list :)

**Comment by mgp25** [comment]
Line 2083 of whatsprot.class. Please, check code, read wiki before opening issue.
