### ISSUE TITLE
Make sure that my messages won't be sent/delivered to the contacts which removed me from their contact list?

### ISSUE THREAD

**Issue by herokiller** [WHAnonymous/Chat-API#1240]
It seems it's impossible to find out whether my number was deleted from contact list. Is it possible somehow to make sure my messages won't be sent or delivered to those contacts?

**Comment by gi097** [comment]
No, when you send a message it will always be delivered (unless you are blocked by that user). You don't necessarily need to have synced a contact in order to receive a message.

**Comment by herokiller** [comment]
I mean I need to make sure my messages won't reach people who haven't added me (or added and deleted me afterwards). I think it's the problem of my numbers being blocked (no spam or massive messages). I noticed that broadcast messages are not delivered to those who didn't add me, is that right?

**Comment by gi097** [comment]
You are right. But that will only work for broadcast messages. But normal messages will arrive.
