### ISSUE TITLE
SOCKS5 Support

### ISSUE THREAD

**Issue by src332** [WHAnonymous/Chat-API#1241]
Please add SOCKS5 support for using TOR, because Facebook Inc. will fight against the users of this API!

**Comment by mgp25** [comment]
Nope

**Comment by vishalkacha** [comment]
Hi Guys

I face some issue in installing chat-api.Please check the below error message.


vishal@vishal-H81M-S:/var/www/html/Chat-API$ php composer.phar require whatsapp/chat-api
Using version v2.5.5.4 for whatsapp/chat-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for whatsapp/chat-api dev-master -> satisfiable by whatsapp/chat-api[dev-master].
    - Can only install one of: whatsapp/chat-api[v2.5.5.4, dev-master].
    - Installation request for whatsapp/chat-api v2.5.5.4 -> satisfiable by whatsapp/chat-api[v2.5.5.4].


Installation failed, reverting ./composer.json to its original content.
