### ISSUE TITLE
Channel Block

### ISSUE THREAD

**Issue by toddybaconavida** [WHAnonymous/Chat-API#1242]
Hi, thank you for your effort on making this great library.

I just started playing with the examples and wiki some days ago and  things went fine. I registered w/ personal phone number and everything just worked, but I got scared after reading about getting numbers being blocked then I bought 6 SIM numbers to keep mine safe, they just worked as expected, until today:

I've played with them for a week or so, exchanging messages between themselves and my own number, mostly of them using the examples scripts without changing too much than the content of the messages/image paths. Suddenly, since today at morning, when trying to run 'Simple CLI Client', right after trying to send the first message I've got the ```[LoginFailureException]```, that seems to be a permanent block according to other issues/wiki.

Well, I tried the same with each of my numbers, took sometime between trying each of them, rebooted my router(dynamic ip here), tried a machine on DigitalOcean, followed the 'login/sync flow' from wiki.. Well, all my tries were in vain, same for each of them:

```
~/Chat-API/examples# php Simple\ CLI\ client.php ******6130064
####################################
#                                  #
#           WA CLI CLIENT          #
#                                  #
####################################

====================================
[] logging in as 'wtf help' (******326876)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="******326876"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>vˆqâ
                   kéπ¨◊º_b%¡</challenge>

tx  <response>Õ¶T(ûY]£["ES#!$_)òÖDï€≠k/response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

PHP Fatal error:  Uncaught exception 'LoginFailureException' in /root/Chat-API/src/Login.php:53
Stack trace:
#0 /root/Chat-API/src/whatsprot.class.php(279): Login->doLogin()
#1 /root/Chat-API/examples/Simple CLI client.php(62): WhatsProt->loginWithPassword('utqr490GWnHdao+...')
#2 {main}
  thrown in /root/Chat-API/src/Login.php on line 53
~/Chat-API/examples# packet_write_wait: Connection to 159.203.111.119: Broken pipe
```

Does Chat-API just stopped working? Is it working for you? WhatsApp update?

Sorry for the long message.. Thank you for any support guys

Sad, I will not enjoy the weekend anymore :(

**Comment by mgp25** [comment]
@toddybaconavida Chat API works perfectly, it's working for everyone. No, there is no WhatsApp update, it works perfectly.

If you are using the API with a bad flow, you will be blocked for sure, if you use a flagged server too, the same happens with IP.

I have the same test number for more than 1/2 years, i only just it for personal usage and never got blocked.

I recommend you to check your code again, and try to improve it.

Regards
