### ISSUE TITLE
Get Whatsapp password.

### ISSUE THREAD

**Issue by John127** [WHAnonymous/Chat-API#1243]
Hello Lord,

I'm looking for WhatsApp device password extractor. I checked your post here : https://github.com/WHAnonymous/Chat-API/wiki/Extracting-password-from-device

I have nexus phone and running marshmallow. It works till KitKat but doesn't work in Lollipop and Marshmallow. Can you please update code or can you please share the code so I can do some changes ?

Q - Why I need password from the Device ?
A - It's because I can use WhatsApp on both web side and in phone. It doesn't work when both are active but It works when 1 side is turned off. For example if phone is turned off I can send message from my number and when web is turned off I can send through the my phone(same number). I have already checked the Official API but If I get password through that API, I won't be able to use in my phone. Currently I have phone with Jelly Bean OS and It works like a charm but problem with newer versions. I appreciate if you share your code. I hope you understand.

Thank You!

**Comment by mgp25** [comment]
@John127 its in the wiki, use bash

**Comment by John127** [comment]
Yes I know it's in bash. But would you mind to share that code ?
