### ISSUE TITLE
Decrypt Message

### ISSUE THREAD

**Issue by ilhamiarie** [WHAnonymous/Chat-API#1244]
Hello @mgp25, thanks for yout lib.

I'm having problems when receiving encrypted messages ter , like the example below.

\<message from="6281321871184@s.whatsapp.net" type="text" id="ZigIGWK7EFV/1B" t="1448723095" notify="suxxhxdi">
\<enc v="1" type="pkmsg">3308fdcbea03122105ada894f653c780ffa33679a9638d0d3807c5a541272e70bb5a7e7db6bffbca011a21052643d7dbcddc5400b007c5bd91bff4d3105d9cb4b156887bdd6e5d244a12ef412242330a210576514fd98e15af8ca685ceb6a6157c0e6950208f260864f7097da5345d45ac7d101b180022103f8cd4fcccff1711dac5183033123b9ad0e740129f39fbc928f0cfcacc043000</enc>
\</message>

I am using win 7 64 bit and PHP 5.6

**Comment by mgp25** [comment]
@ilhamiarie 

1. Read the wiki.
2. Quote de code
