### ISSUE TITLE
Number not blocked but still not-authorized?

### ISSUE THREAD

**Issue by transonly** [WHAnonymous/Chat-API#1245]
```
####################
#                  #
# WA Block Checker #


Username (country code + number without + or 00): 31639307538


Your number 31639307538 with the following password h98TomRVtzjpM8Uky0pHt4hOb7I= is not blocked
```

#  Then i run this script CLI:
```php
    <?php
    require_once '../src/whatsprot.class.php';
    $username = "31639307538"; //Mobile Phone prefixed with country code so for india it will be 91xxxxxxxx
    $password = "isasecret";
    $w = new WhatsProt($username, 0, "WhatsApp Messaging", true); //Name your application by replacing     "WhatsApp Messaging"
    $w->connect();

    $w->LoginWithPassword($password);
    $target = '31627333603'; //Target Phone,reciever phone
    $message = 'Your message comes here';
    $w->SendPresenceSubscription($target); //Let us first send presence to user
    $w->sendMessage($target,$message ); // Send Message
    ?>
```

# What gives me the following result:
```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="31639307538">�@G31639307538�y���`�
t�E���Z�}1448786265</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>�[S!oվO���d�}�<a:</challenge>

tx  <response>��Fr�-�S|{�L{�!�玿,�p�d���!�����</response>

Bitvise SSH Clientrx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```
```
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /var/www/NEWchat/lib/whatsapp/src/Login.php:53
Stack trace:
#0 /var/www/NEWchat/lib/whatsapp/src/whatsprot.class.php(279): Login->doLogin()
#1 /var/www/NEWchat/lib/whatsapp/whatsappphp/totester.php(8): WhatsProt->loginWithPassword('jEjvmpzy+MO7zsz...')
#2 {main}
  thrown in /var/www/NEWchat/lib/whatsapp/src/Login.php on line 53
# Note:
# This line:

Your number 31639307538 with the following password h98TomRVtzjpM8Uky0pHt4hOb7I= is not blocked
```

returns another password each time? It's not like the password i've in the config.

## General question about markdown:

How to indent code block with 4 spaces? Rule by rule?

**Comment by mgp25** [comment]
@transonly 

1. You are using outdated code (or at least constructor)
2. You are using a bad flow/sceipt behaviour
3. You are disconnecting to soon. Not polling enought.

When you check if its blocked or not it alwaus return a new password, and the old one you have won't work. If it's not blocked, then you are using a wrong password, or you are under a flagged network.

All this is explained in the wiki: https://github.com/WHAnonymous/Chat-API/wiki

GitHub Flavored Markdown: https://help.github.com/articles/github-flavored-markdown/
Basic Markdown: https://github.com/WHAnonymous/Chat-API/wiki/How-to-write-correctly-in-Github

**Comment by transonly** [comment]
Ok the code provided is just a simple thing i pulled from the web to check wether it sends a simple hello or whatever.

I've somewhat of a production environment  wherein i want whatsapp to send notifications and receiving photouploads. I allready had a working thing untill WA decided to block my number because it detected unhuman activity i think.

I'll revise it and use your latest release only for coding reference.
Also i hope that WA is not going to change things over and over again to block 'legitimate' use of their stuff.
What do you think? Is it advisable to really use it in production as a key feature?

**Comment by John127** [comment]
PHP >= 5.6 and you need to have some modules explained here.
https://github.com/WHAnonymous/Chat-API/wiki/Dependencies
