### ISSUE TITLE
Can't decrypt password in newer version.

### ISSUE THREAD

**Issue by John127** [WHAnonymous/Chat-API#1246]
I have two phone right now. One is nexus and another one is Samsung with Jelly Bean OS. I have two different WhatsApp numbers. I got pw file from Samsung phone and decrypted the password as you shown bash script and it worked fine on web too. On other side I decrypted pw file with Lollipop and marshmallow it decrypts the password but it doesn't work. Older version's pw is working fine whereas newer version's PW file doesn't seem to be worked even password got decrypted.
This error I get : 

```
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="9658430387"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>®ð¶ÒÁOtˆ•6ý{{²à$ó³</challenge>

tx  <response>¦êe£Ý¿:ÝÇ¨~Ð©zNßoÖë^ÖRYºmÝ²[Z</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>


Fatal error: Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\wa\src\Login.php:53 Stack trace: #0 C:\xampp\htdocs\wa\src\whatsprot.class.php(279): Login->doLogin() #1 C:\xampp\htdocs\wa\examples\index4.php(14): WhatsProt->loginWithPassword('LkKrfoE7eaFp4mT...') #2 {main} thrown in C:\xampp\htdocs\wa\src\Login.php on line 53
```
P.S : WhatsApp is turned off on that device as well. Problem is with newer version only.
Why ?

**Comment by mgp25** [comment]
Because maybe they changed the way to encrypt the password

**Comment by John127** [comment]
Can you please look into this matter ? Can you update the code ?

**Comment by assegaf** [comment]
@mgp25  have u noticed the new WA protocol 1.6 in new version of official client (previously 1.4 then 1.5, and now ... 1.6) ?
seem completely different.

**Comment by mgp25** [comment]
@assegaf yes, i notice it. API works the same, i'll do some updates when i have time

**Comment by John127** [comment]
Yup ! They did many changes.

**Comment by assegaf** [comment]
@mgp25 I wish I can help, seem only android , wphone still 1.5
