### ISSUE TITLE
autoReceipt question

### ISSUE THREAD

**Issue by John127** [WHAnonymous/Chat-API#1247]
If I don't want to receive messages  from others i.e mark as unread. Is this correct code? I want to receive when I use it from my phone.

I have also noticed that in the updated code I can not find these two arguments.
```
public function pollMessage($autoReceipt = true, $type = "read")
```
Older version Here : https://github.com/WHAnonymous/Chat-API/commit/ca05d898498e484ee8249eb8828ea48bcb45f8f0

```
$w->pollMessage(false);
```
or I need to use it multiple times like,
```
for($I=0;$i<=6;$i++)
{
        $w->pollMessage(false);
}
```

I checked this : https://github.com/WHAnonymous/Chat-API/issues/327
Still confusion.

And where should I suppose to put this code ? I mean like we do in simple $w->pollMessage(); to put everywhere. 

TY!

**Comment by 0xTryCatch** [comment]
You cannot prevent messages from being received. If you want to use it on your phone also you need to use a different number for the API.

**Comment by John127** [comment]
Then what are those 2 parameters ?
