### ISSUE TITLE
Code doesn't work after I installed encryption extensions.

### ISSUE THREAD

**Issue by John127** [WHAnonymous/Chat-API#1248]
Hello again,

I have installed encryption modules and it stops working. I don't know why. If I remove extensions it works perfectly except messages.

 Debug : http://128.199.72.136/examples/index4.php

```
PHP Information 
```
Here : http://128.199.72.136/

Enabled those modules still not working.

Any help ?
Thank You

**Comment by mgp25** [comment]
@John127 not API issue. You need to check whats happening at your side

**Comment by John127** [comment]
Well, I changed permission of src/ and examples folder to 777. 
```
chmod -R 777 examples/
chmod -R 777 src/
```
And now it started working but the messages are not showing properly.
```

rx  <message from="19514567713@s.whatsapp.net" type="text" id="6573F94DAEB30D799E0" offline="0" t="1448892173" notify="deshkarabhishek">
rx    <enc v="2" type="pkmsg">3΄�!��9�I5�9��pcj�q�e��e����o�O!L[�g���<���#�:Ny��Hd�Z��<�\�"B3 !/-�S��=�\�hB�`��e�!K�7�t>�$�J/"�r����_�'�Λ&Y����F[y�G(���0</enc>
rx  </message>
```

**Comment by estcap** [comment]
You don't have the encryption modules (at least not correctly). It should look like this:
```php
rx  <message from="XXXXXXXXX@s.whatsapp.net" type="text" id="XXXXXXXXX" t="1448891463" notify="XXXXXX">
rx    <enc v="1" type="msg">3
!Œmsdsgfgdfhgdhdfhÿx¸•³­}hæá
9²Ìˆ˜</enc>
rx  </message>

tx  <ack to="XXXXXXXXXXX@s.whatsapp.net" class="message" id="1XXXXXXXA" t="1448891463"></ack>


-> Decrypted Message: This is a test
```

**Comment by John127** [comment]
@estcap : So I get decrypted message like this  ? :

rx  <message from="XXXXXXXXX@s.whatsapp.net" type="text" id="XXXXXXXXX" t="1448891463" notify="XXXXXX">
rx    <enc v="1" type="msg"> This is a test
9²Ìˆ˜</enc>
rx  </message>

tx  <ack to="XXXXXXXXXXX@s.whatsapp.net" class="message" id="1XXXXXXXA" t="1448891463"></ack>

**Comment by John127** [comment]
@estcap : Okay man. It was the problem of fucking permissions. I had to set the permission to 777 in new centos. If I go back and change extension's permission to the 644 then it wont work.
