### ISSUE TITLE
how many WhatsApp sessions online I can have on a server?

### ISSUE THREAD

**Issue by israelArellano** [WHAnonymous/Chat-API#1251]
hello, in my company we have been dedicated to develop a software that manages companies WhatsApp messages. Everything was fine until we got to the line 20 on our server and WhatsApp started blocking the lines.

The development and creation process lasted two months and we did not block any line. Our intention is not to generate spam, simply organizing companies.

Can you help me?

**Comment by 0xTryCatch** [comment]
This API is for personal use only
