### ISSUE TITLE
onGetMessage() problem.

### ISSUE THREAD

**Issue by Jonathan313** [WHAnonymous/Chat-API#1252]
Hi,

First of all excellent work and thank you for sharing the knowledge with us.
So the problem is, I'm using the latest code. I have following program.

```php
<?php
set_time_limit(0);
error_reporting(E_ALL);
ini_set('display_errors', 'On');

require_once('../src/whatsprot.class.php');
require_once('../src/events/MyEvents.php');

$username = "**********";
$nickname = "********";
$password = "****************************"; // The one we got registering the number
$debug = false;

mysql_connect("localhost","root","JHKJGY&kjsd");
mysql_select_db("chat_db");

function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{

    mysql_query("insert into `chat_store` values('','$body','$from','$name','$time','$mynumber')");
}

$w = new WhatsProt($username, $nickname, $nickname, $debug);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage");

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!

for($I=0;$I<=5;i++)
{
	$w->pollMessage(); 
}
$w->disconnect();
```
So the problem with this code is I'm getting the only one contact's message at a time. I am not able to get the all contacts chat messages. 

The another issue is : Decrypted Message: Incomplete messages.
```
-> Decrypted Message: Incomplete message - /var/www/html/src/libaxolotl-php/protocol/PreKeyWhisperMessage.php - 43Message 8Mp/V6UH4hbcD could not be decrypted, sending retry. tx  <receipt id="8Mp/V6UH4hbcD" to="919769359081@s.whatsapp.net" type="retry" t="1448947551">
```

This happens most of the times. I don't know why. I have to delete .db file always. 
Some times this error.
```
-> Decrypted Message: Bad Mac!
Bad Mac!
No valid sessions - /var/www/html/src/libaxolotl-php/SessionCipher.php - 182Message Uerz+947c53Y9 could not be decrypted, sending retry.
```
And sometimes message is not mark as read. I sent message via blue stack and still on one tick moreover I didn't get message on API coz of decryption issue.

----------------- Same on the group message-------------------- But this one this syntax error may be....
Group messages are not visible. They are shown in encrypted text. But the normal personal messages are in plain text tho not a problem with that.
```xml
rx  <message from="19514567713-1448926128@g.us" type="text" participant="19514567713@s.whatsapp.net" id="A8DF196174602449E139" offline="0" t="1448962629" notify="cenas">
rx    <enc v="2" type="skmsg">3��� 	 Z���Ǫ���j�� N�"��|;���@�����pH����z^�"�������aGWs�-6�6��%H2aMNg_�3��1�NF��=�P�z��a}i�</enc>
rx  </message>

tx  <ack to="19514567713-1448926128@g.us" class="message" id="A8DF196174602449E139" t="1448962629"></ack>


Notice: Undefined property: MessageHandler::$v2Jids in /var/www/html/src/handlers/MessageHandler.php on line 437

Warning: in_array() expects parameter 2 to be array, null given in /var/www/html/src/handlers/MessageHandler.php on line 437
-> Decrypted Message: No keys for: 27686225 - /var/www/html/src/libaxolotl-php/groups/state/SenderKeyRecord.php - 35tx  <receipt id="A8DF196174602449E139" to="19514567713-1448926128@g.us" type="retry" t="1448962629">
tx    <retry v="1" count="1" id="A8DF196174602449E139" t="1448962629"></retry>
tx    <registration>�;	</registration>
tx  </receipt>
```

```
When I remove db file it works bit good but problem with some messages still there.
```

Check out the screenshot : http://i.imgur.com/Hy0TYxw.png

UPDATE : I have added ``` unlink("../src/wadata/axolotl-1746187248123.db"); ``` to the end of the program and It solves problem by 96 %. So everytime the db file will be removed automatically after disconnect. But this is not the solution. I guess.

Any help ?
Thank You

**Comment by Nakani** [comment]
Good afternoon , I am also searching for a solution to this problem , but I can send and receive , but not all phones, another question by chance you install those extensions it says on the documentation curve and protobuf ?

**Comment by Jonathan313** [comment]
@mgp25 : Any update guys ? I mean ETA ?

**Comment by mgp25** [comment]
ETA: update will arrive anyday from 2015 to 2017 

Regards

**Comment by mgp25** [comment]
It will arrive soon, but i can't say a concrete day, as i want to work 100% perfectly

**Comment by Jonathan313** [comment]
Thanks guys! Really appreciate your work!

**Comment by Nakani** [comment]
Good afternoon , I'm using this API , and found that some Feedback are however getting those that have [ tag: ProtocolNode : private ] = > enc is coming encrypted and others who well with the tag: ProtocolNode : private ] = > body is coming right if encryption know how to solve this issue?

**Comment by gi097** [comment]
I can say that this issue happened after 2.13.21. I spoofed an old Android client to this S40 version and messages arrive fine. When I change it to 2.13.27 (currently the latest build for Nokia), messages start to arrive empty. After digging and comparing some smali files, I found out that it is not hard and it is only a little issue in the body parsing (not related to encryption and/or decryption).
