### ISSUE TITLE
group message decryption fails in client.php (commit ref 2daef84)

### ISSUE THREAD

**Issue by mgsh** [WHAnonymous/Chat-API#1253]
Hi,

Thanks for the great work done under this project. While trying it out, I noticed an issue in group message decryption. Would appreciate any help to fix it.

I've attached the patches I tried. It does fix the issue for new groups created by new contacts. But for groups already created, the solution was to request participants to delete my number from their contacts list and add it again and recreate the groups with the participants.

##### Questions:
1. Is there an alternate way to recover from earlier group decryption failures without having to request my contacts to remove and add my number?
2. Are the `<receipt id= .. type="retry"...` (receipt-retry) messages expected to get certain responses, that WhatsApp is not responding with?
3. Isn't removing the dbs created in `src/wadata` expected to resolve "No key" and "No signedprekey" errors, or is it expected to get resolved as these cases show up with the use of "receipt-retries"?

##### Steps to reproduce:
Walk-through of what I tried (I've been using `examples/WA CLI Client/client.php` for testing):
(1) Without any patches on master (2daef84) branch:
 - contact creates new group (`##########-1448965267`) and sends a message on the group, results in fatal error: `PHP Fatal error:  Cannot access protected property WhatsProt::$retryCounter in src/handlers/MessageHandler.php on line 394`
 - full `client.php` output: [chat-api-with-no-patches.txt](https://github.com/WHAnonymous/Chat-API/files/48389/chat-api-with-no-patches.txt)

(2) Reverted to a clean setup (removed all dbs and also contact removed my number and added it again):
 - patch applied: [message-handler-1.patch.txt](https://github.com/WHAnonymous/Chat-API/files/48393/message-handler-1.patch.txt)
 - contact creates new group (`##########-1448961822`) and sends a message on the group, results in fatal error: `PHP Fatal error:  Call to a member function loadSenderKey() on null in src/libaxolotl-php/groups/GroupSessionBuilder.php on line 14`
 - full `client.php` output: [chat-api-with-patch-1.txt](https://github.com/WHAnonymous/Chat-API/files/48390/chat-api-with-patch-1.txt)

(3) Continued from step (2) (did NOT remove dbs and contact did NOT remove/re-add my number):
 - patch applied: [message-handler-2.patch.txt](https://github.com/WHAnonymous/Chat-API/files/48394/message-handler-2.patch.txt)
 - contact sends message on existing group (`##########-1448961822`), message decryption fails with error: `No keys for: 1856705047 - src/libaxolotl-php/groups/state/SenderKeyRecord.php - 35`
 - contact creates new group (`##########-1448961943`), works fine 👍
 - full `client.php` output: [chat-api-with-patch-2.txt](https://github.com/WHAnonymous/Chat-API/files/48391/chat-api-with-patch-2.txt)

(4) If continued from step(1) with patch-2 (did NOT remove chat-api dbs and contact did NOT remove/re-add my number). The behavior is the same even if I just remove the chat-api dbs (in src/wadata) and restart it.
 - patch applied: [message-handler-2.patch.txt](https://github.com/WHAnonymous/Chat-API/files/48394/message-handler-2.patch.txt)
 - contact sends message on existing group (`##########-1448965267`), message decryption fails with error: `No keys for: 487359727 - src/libaxolotl-php/groups/state/SenderKeyRecord.php - 35`
 - contact creates new group (`##########-1448965402`), message decryption fails with two errors: `No such signedprekey with id: 8798 - src/SqliteAxolotlStore.php - 203`, followed by `No keys for: 953341307 - src/libaxolotl-php/groups/state/SenderKeyRecord.php - 35`
 - full `client.php` output: [chat-api-with-full-patch.txt](https://github.com/WHAnonymous/Chat-API/files/48388/chat-api-with-full-patch.txt)

I've tried to summarize the steps with what I understood as relevant output in entirety (apologies if it's too verbose). Please let me know if you need any more information.

The contact was using whatsapp version 2.12.367 on android.

**Comment by mgp25** [comment]
@mgsh most of the issues are fixed in the next release which is going to be up today or tomorrow.

Send a pull requests for the fixes.

Regards
