### ISSUE TITLE
Numbers geht Blockes and blocked

### ISSUE THREAD

**Issue by cs8898** [WHAnonymous/Chat-API#1258]
Hey,
my numbers get all the time blocked...
Probably because i send too many pings vor MSG reuests, i added now a 2sec timeout and send a ping every minute, do you think thats OK.

Also i fetch my msgs by the getMessages() Funktion is that OK either?

PLZ help me because im really nerved about getting New sims and sending an E-Mail to the support.

**Comment by mgp25** [comment]
@cs8898 you dont need to send pings, the API doesnt automatically. If you spam you will get blocked. Use only for personal usage.

Have you checked what `getMessages()` does?

**Comment by cs8898** [comment]
Yeah its your Funktion...

**Comment by cs8898** [comment]
Or should i usw the event driven ones
