### ISSUE TITLE
WHATSAPP_USER_AGENT|WHATSAPP_VER problem

### ISSUE THREAD

**Issue by atanych** [WHAnonymous/Chat-API#1261]
Hi, 

Thank you for a good job.

After last commit (https://github.com/WHAnonymous/Chat-API/commit/4a176bfd453575f621a6a40218b1bf8b09e9d69b) we had problem with empty messages from whatsapp-daemon (your lib) to client (IPhone)

We rolled back to:
```
const WHATSAPP_VER = '2.13.9'; 
const WHATSAPP_USER_AGENT = 'WhatsApp/2.13.9 S40Version/14.26 Device/Nokia302';
```

and the problem fixed.
![1449065943210](https://cloud.githubusercontent.com/assets/10116909/11533070/de8b5c14-9918-11e5-882c-abffadba62ff.jpg)

**Comment by mgp25** [comment]
Closing the issue. For further help/support post debug log and code

Regards
