### ISSUE TITLE
onStreamErrorReceived: Data:ack

### ISSUE THREAD

**Issue by josemonino** [WHAnonymous/Chat-API#1262]
Hello, I'm getting this error after receiving this message. I updated the Chat-API code yesterday.

```
rx  <message from="9655532xxxx@s.whatsapp.net" type="text" id="1442504424-83" offline="3" t="1442504442" notify="Ø¯ÙÙŒÙÙ°ÙÙ°Ù‘ÙˆÙÙÙŒÙ‘Ù‹Ø¢ÙÙ’ÙŒÙ‘Ø¢ÙÙÙÙ‘Ø³">
rx    <enc v="1" type="msg">3
!¼¯(Æ¯j›æv÷QÈ]Ì1¼Pl„Ôo>—‚èJAt ".UÍDÝÔÏqYYìË¶lîìêŸ¦éÌÿA</enc>
rx  </message>

.
.
.

rx  <stream:error>
rx    <ack id="1442504424-83"></ack>
rx  </stream:error>
```

**Comment by mgp25** [comment]
@josemonino you are not sending ack. Don't open new issues if there are already answered ones

**Comment by josemonino** [comment]
Thanks @mgp25,

But how to send the ack? I'm using just your exampleFunctional.php and it is not sending any ack... sorry if it is too obvious.

Thanks again for sharing this code.
