### ISSUE TITLE
Service temporarily unavailable

### ISSUE THREAD

**Issue by joostwaaijer** [WHAnonymous/Chat-API#1264]
Hello guys,

I have an issue with the RegistrationTool. When i try to register a number with a provider who is not in the list of networkinfo.csv, i still can receive a sms with the code, but when i give the code and continue it gives me an error called "This service is temporarily unavailable please try again later." and i can't try again for 6 more hours. My question is, can i safely add a new record to the networkinfo.csv and expect it to work? or do I have to do something else?

Here are the details:

Provider: AH Mobiel
MCC: 204
MNC: 12

Normally this one would connect to the KPN/Telfort, which is the network they use.

Is there a way to fix this or do i need to get a different provider who is in this list?

**Comment by mgp25** [comment]
You don't need `networkinfo.csv`. It's not an error, it's info: `This service is temporarily unavailable please try again later`

The service is not available retry later

**Comment by CreaDEV** [comment]
i have the same problem and not only today. Last week i have had the same problem i cant register numbers?

Everytime comes the message: This service is temporarily unavailable please try again later
