### ISSUE TITLE
How can i get timestamp - the release time of the app (S40)

### ISSUE THREAD

**Issue by Zedits22** [WHAnonymous/Chat-API#1267]
Hi.
Thanks for all!
I have question...
wiki: "$timestamp it's the release time of the app, it's inside the app. Changes in every version."
How can i get timestamp - the release time of the app (S40)?

 i have WhatsApp_2_13_22.jar for S40. 

Thanks

**Comment by mgp25** [comment]
Take the value from https://github.com/WHAnonymous/Chat-API/blob/master/src/Constants.php
