### ISSUE TITLE
Error Whatsapp OldVersion

### ISSUE THREAD

**Issue by ricardoperovano** [WHAnonymous/Chat-API#1268]
I'm getting the following error when trying to get password:
"{\"status\":\"fail\",\"reason\":\"old_version\"}"

I'm using the lastest version of wart and trying with the lastest version of registerTool.php!
Does anybody know what could it be ?

**Comment by modsfabio** [comment]
Same proble here

**Comment by mgp25** [comment]
Not WART repo

**Comment by mgp25** [comment]
Issue is invalid without debug log. Post full debug for support.

Regards
