### ISSUE TITLE
Could not send a message the second time.

### ISSUE THREAD

**Issue by josiahking** [WHAnonymous/Chat-API#1271]
Hello, i am using the lastest version of WART.
After retrieving my password for the first time, i successfully sent a message to a friend using Chat-API library.
But when i try to send to another phone number it didn't send, and was having a login failure exception thrown.
After i tried to get a new password with WART tool i got the message:
{'status':'fail','reason':blocked'}.

**Comment by ricardoperovano** [comment]
same problem here

**Comment by 0xTryCatch** [comment]
It means you did something wrong and WhatsApp blocked your number. Not an API issue.

**Comment by josiahking** [comment]
0xTryCatch is right.
I used the check credentials method to check and discovered the account is blocked.
Is there anyway to unblock a number without loginwithpassword?
because the phone number is block, login with password doesn't work.
Since the account is block how else can it be unblock?
