### ISSUE TITLE
Stopped working over Night

### ISSUE THREAD

**Issue by fdrechsler** [WHAnonymous/Chat-API#1272]
Hey Guys,

```
loginWithPassword
```
returns:
```
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

Block Checker returns:

```
Wrong identity. 
Array
(
    [cc] => XX
    [in] => XXXXXXXX
    [id] => XXXXXX
    [lg] => XX
    [lc] => XX
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)

```  

Yesterday everything was working just fine.

Any Suggestions?

Greetings
Florian 

P.S. Really appreciate your work :)

**Comment by 0xTryCatch** [comment]
You are using the wrong identity, register the number again,

**Comment by fdrechsler** [comment]
Do you know why this happened? Because yesterday it was working fine (System ran flawless for over 5 months!)

**Comment by 0xTryCatch** [comment]
You are using an outdated version of the API.

**Comment by fdrechsler** [comment]
Ok, so Solution is: Updating API, Running the Register Tool Again, Putting the new Password in my Config => Solved?

**Comment by fdrechsler** [comment]
Updated API => Solved. Thanks!
