### ISSUE TITLE
I have a problems

### ISSUE THREAD

**Issue by wiskillo** [WHAnonymous/Chat-API#1273]
I don't if the new update is the problem, but my system was down when i try send message and check my number and return 

#################### # # # WA Block Checker # # # #################### Username (country code + number without + or 00): Array ( [cc] => 52 [in] => 1xxxxxxxxxxxxx [id] => ©$².ê`nø uÂe¥Ýt«=¡5Ò [lg] => es [lc] => MX ) stdClass Object ( [status] => fail [reason] => old_version )

**Comment by mgp25** [comment]
You are using an outdated version of the API. Please before open a new issue, ALWAYS check if you are using latest code
