### ISSUE TITLE
Update Whatsappi but have a mistake

### ISSUE THREAD

**Issue by wiskillo** [WHAnonymous/Chat-API#1274]
i have a trouble with file Login.php in line 63 ... and i can't run correctly ... can you help me please

```javascript
          if (empty($this->parent->getAxolotlStore()->loadPreKeys()))
          {
            $this->parent->sendSetPreKeys();
            $this->parent->logFile('info', 'Sending prekeys to WA server');
          }
```

**Comment by mgp25** [comment]
Where is the error / debug log?

**Comment by wiskillo** [comment]
[04-Dec-2015 18:38:41 America/Mexico_City] PHP Fatal error:  Can't use method return value in write context in /home/taenetcom/public_html/v/src/Login.php on line 63

**Comment by 0xTryCatch** [comment]
Read the wiki!!
