### ISSUE TITLE
Checking if the number exists

### ISSUE THREAD

**Issue by thetorment** [WHAnonymous/Chat-API#1277]
I've been trying to check if a number exits or not and this is the url I used:
https://v.whatsapp.net/v2/exist?cc=**&in=*********&id=%**%DC%E7%**%C*%A8%**%26%**%4F%35%**%B1%69%AF%**&lg=es&lc=ES

In order to get the ID I used this code:
```
include "token.php";
$t = generateRequestToken('34', '666554433', 'Android'); //'34', '666554433'
echo strtolower(urlencode(sha1($t, true)));
```

The result is different than the one I got from WART and the url is not working it says:
{"status":"fail","reason":"incorrect","sms_length":6,"voice_length":6}

I tried my own number with no luck.

All I want to do os how to check if the number exists and how to get proper ID.

Thanks.

**Comment by mgp25** [comment]
@thetorment its explained in the wiki

**Comment by thetorment** [comment]
Yes its explained in the wiki but as I said it doesn't work for me and I included the reposne.
