### ISSUE TITLE
Correcto flow

### ISSUE THREAD

**Issue by wragnar** [WHAnonymous/Chat-API#1280]
So, I´m managing not to be banned by whatsapp again, and I what to make the things as correct as posible.
I´m not going to send a message to anyone that has not contact me, so this way i supose that i´m in they adressbook.
i´m a bit confusing with presence suscription, because i what to check if the phone number i send the message is still in whatsapp.
My script read from a database that i wrote a message for a contact, and check if the contact is sync, otherwise it sync it. but how can i check if the nuber i whant to send a message exists in whatsapp.

This is because mi script cant try to send a message to a number that i receive a message a month ago, so i need to check if the number is the same, and exists, because if a send messages to an unexisting number in whatsapp i will be banned.

Thanks and sorry for my english

**Comment by mgp25** [comment]
Presence subscription is not the same as sync. It's explained in the wiki how its done and which event do you need to use.

By the way, if you are sending messages to people that already have your number, why are you sending messages to non existing users?

This API is only for personal usage.

Regards

**Comment by wragnar** [comment]
Someone send me a message and when they send me a message i sync the contact, but 2 weeks later i have a reply to this user, so i whant to know if the user that send me the message already exists.

I use the script for personal use.

**Comment by mgp25** [comment]
@wragnar Check the wiki and example codes.

Regards

**Comment by wragnar** [comment]
A friend that is in other country send me a message asking to contact when i see something in my country, but if he change the number and this number is down from whatsapp i send a message to a non existing number in whatsapp

Checking the wiki i found this:
public function onPresenceUnavailable( $mynumber, $from, $last )
{
  echo "Last seen of $id: ".gmdate("H:i:s", $last);
}

but i want to know how can i implement it previous to send a message, to stop sending it.

**Comment by wragnar** [comment]
if a number is not in whatsapp, what should return onPresenceUnavailable function ?

**Comment by mgp25** [comment]
As i said before, presence subscription is not sync, there is a section only about sync which is explained all the procedure.

And remember to quote properly code.

Regards

**Comment by wragnar** [comment]
So i understand that i have to check with:

<blockquote>function onSyncResult($result)
{
    foreach ($result->existing as $number) {
        echo "$number exists<br />";
    }
    foreach ($result->nonExisting as $number) {
        echo "$number does not exist<br />";
    }
    die();//to break out of the while(true) loop
}
</blockquote>

but is it correct so sync the contact everytime i send him a message?

**Comment by mgp25** [comment]
No, as explained in the wiki, you only need to sync the user once, if the user has removed his account you will receive a notification.

**Comment by wragnar** [comment]
So i sync the number and it exists, but how i receive the notification if the user remove his account a week later?

onsyncresult or on........


Every time you answer you as me to look in the wiki, but i think that everyone is not able to understand correctly what says the wiki, so it a good comment to ask me to look in the wiki, but if i am asking this here is because i didnt understand this only looking in the wiki.

**Comment by wragnar** [comment]
closed?   thanks a lot

**Comment by mgp25** [comment]
As said in #556 (have you read it?) everything its in the wiki and before opening a new issue, you should look the other issues. I guess i have answered +20 of them (related to sync).

Also there is an example in `examples` folder, run it and check it, its the fastest way to check it and learn.

There is an event that captures notifications, use that event.

Regards

**Comment by wragnar** [comment]
I use onProfilePictureChanged and onProfilePictureDeleted but searching for it in the wiki i´m not able to guess the funcion that captures notification about the number deleted.  (   :-(  all the wiki is in english )

**Comment by mgp25** [comment]
@wragnar english is an universal language, im Spanish.

This is the event you need: `onNumberWasRemoved`

**Comment by wragnar** [comment]
Thanks.

El 7 de diciembre de 2015 0:18:41 CET, mgp25 <notifications@github.com> escribió:
>@wragnar english is an universal language, im Spanish.
>
>This is the event you need: `onNumberWasRemoved`
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WHAnonymous/Chat-API/issues/1280#issuecomment-162365826


A. Villaescusa Ealo
