### ISSUE TITLE
Messages are not received

### ISSUE THREAD

**Issue by Medanaresh** [WHAnonymous/Chat-API#1283]
I have been using your chat API for about a month and it’s working fine. 
Now when I changed the number am not able to send/receive to any number except the number that I’ve already used.

**Comment by Medanaresh** [comment]
<br />
<b>Fatal error</b>:  Uncaught exception 'LoginFailureException' in C:\xampp\htdocs\hbrani\src\whatsprot
.class.php:2263
Stack trace:
#0 C:\xampp\htdocs\hbrani\src\whatsprot.class.php(553): WhatsProt-&gt;doLogin()
#1 C:\xampp\htdocs\hbrani\examples\ajaxDemo\socket.php(151): WhatsProt-&gt;loginWithPassword('vnwHQDgmHnpzfEP
...')
#2 {main}
  thrown in <b>C:\xampp\htdocs\hbrani\src\whatsprot.class.php</b> on line <b>2263</b><br />

**Comment by 0xTryCatch** [comment]
That's not a debug log but a stack trace. Anyway, looks like your number is blocked.

**Comment by Medanaresh** [comment]
Thanks for responding. How much time it takes to unblock my number, and also are you provide any license for commercial use.

**Comment by mgp25** [comment]
Personal usage only. Number will remain blocked.

**Comment by Medanaresh** [comment]
Sorry for asking the same question again.. please advise me, where we get the license for commercial use, or  you have any idea please help me.

**Comment by 0xTryCatch** [comment]
There is none
