### ISSUE TITLE
Fatal error: Can't use method return value in write context in Chat-API/src/Login.php on line 63

### ISSUE THREAD

**Issue by renanhenrique** [WHAnonymous/Chat-API#1284]
Hi guys, any clue on this ?

Fatal error: Can't use method return value in write context in /home/www/Chat-API/src/Login.php on line 63

**Comment by mgp25** [comment]
Have you read the wiki or checked in the closed issues?

**Comment by renanhenrique** [comment]
PHP >= 5.6 is required

Thanks and sorry.
