### ISSUE TITLE
Dont want to show the debug message

### ISSUE THREAD

**Issue by rohitashv** [WHAnonymous/Chat-API#1285]
Hello Friends

I want to send messge using the following code :

       $username = $get_list['userid'];
	$password = $get_list['password'];
	$nickname = 'SG'; 
	$debug = "false";
	$w = new WhatsProt($username, $nickname, $debug);
	$w->connect();
	$w->loginWithPassword($password);
	$s= $w->pollMessage();

It shows the message in xml format

I dont want to show this message just want to store it into a variable. How can I store it ?

**Comment by mgp25** [comment]
Use events, explained in the wiki.

Regsrds
