### ISSUE TITLE
How to convert the xml response into array

### ISSUE THREAD

**Issue by rohitashv** [WHAnonymous/Chat-API#1286]
Hello

I am getting the response as follow:

tx  <stream:features><br />tx    <readreceipts></readreceipts><br />tx    <groups_v2></groups_v2><br />tx    <privacy></privacy><br />tx    <presence></presence><br />tx  </stream:features><br /><br />
tx  <auth mechanism="WAUTH-2" user="9195256709">>��9195256709<�C�*�2�g���p��B1449656222</auth><br /><br />
rx  <start from="s.whatsapp.net"></start><br /><br />
rx  <stream:features></stream:features><br /><br />
rx  <challenge>������3(]��kX�Л֌</challenge><br /><br />
tx  <response>7��:�g�Ԯ�S�}5��ִ�a�x��i��
틧�</response><br /><br />
rx  <success t="1449656375" props="4" kind="free" status="active" creation="1449574308" expiration="1481110308">>j���5?x�v��S g��</success><br /><br />
tx  <presence name="SG"></presence><br /><br />
tx  <message to="9195256709@s.whatsapp.net" type="text" id="0491O2vzlf/60" t="1449656223" notify="SG"><br />tx    <body></body><br />tx  </message><br /><br />
rx  <ib from="s.whatsapp.net"><br />rx    <offline count="0"></offline><br />rx  </ib><br /><br />
rx  <presence from="9195256709@s.whatsapp.net"></presence><br /><br />
rx  <ack from="9195256709@s.whatsapp.net" class="message" id="0491O2vzlf/60" t="1449656375"></ack><br /><br />

How can I get the values of tags

**Comment by mgp25** [comment]
#1285
