### ISSUE TITLE
Problem with item-not-found

### ISSUE THREAD

**Issue by batman2010** [WHAnonymous/Chat-API#1287]
good afternoon, I have the error 404 "item-not-found", but I could not remove it, I used the sendPresenceUnsubscription method, however, it has not worked. Can you help me? The problem is that this routine does not stop, and try again and again.

< iq id="9" type="get" xmlns="w:profile:picture" to="5215215548101060@s.whatsapp.net">
    < picture type="image"></ picture>
< /iq>

< presence from="5215215548101060@s.whatsapp.net" type="unavailable" last="none"></presence>
< iq from="5215215548101060@s.whatsapp.net" type="error" id="9">
    < error code="404" text="item-not-found"></error>
< /iq>

  < iq id="11" type="get" xmlns="w:profile:picture" to="5215215548101060@s.whatsapp.net">
    < picture type="image"></picture>
  < /iq>

  < iq from="5215215548101060@s.whatsapp.net" type="error" id="11">
    < error code="404" text="item-not-found"></error>
  </ iq>

Thanks for your time

**Comment by mgp25** [comment]
The user hasnt  profile picture. Read closed issues

**Comment by batman2010** [comment]
Thanks a lot for your time, the problem I have is that the phone number 5215215548101060, does not exist and can not erase from my list, intinté with the following code but keeps repeating the same mistake.

$phone_arr[0]= 5215215548101060;
$w->sendSync($phone_arr);

$w->sendPresenceSubscription(5215215548101060);
sleep(2);

$w->sendPresenceUnsubscription(5215215548101060);
sleep(5);


I saw that after repeating this mistake for several hours I WhatsApp blocks line.

Thank you very much for your excellent work.
