### ISSUE TITLE
Error While Connecting(not-authorized) to whatsapp

### ISSUE THREAD

**Issue by 90navjot** [WHAnonymous/Chat-API#1288]
After execute File return Like this

```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="919914500270"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>Û,ö½òÒzGéò„õr‹£¥x</challenge>

tx  <response>€Ê¦"cÜQGhæ¨s^æAŒkÛÄ¤¼Ë,Z!<Ì¾</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by Jonathan313** [comment]
Post your code.

**Comment by 90navjot** [comment]
require_once 'src/whatsprot.class.php';
$username = "91**********0"; //Mobile Phone prefixed with country code so for india it will be 91xxxxxxxx
$password = "oPLm**********c/bY=";
 
$w = new WhatsProt($username, 0, "DjPunjab", true); //Name your application by replacing "WhatsApp Messaging"
$w->connect();
$w->loginWithPassword($password);
$target = '919**********2'; //Target Phone,reciever phone
$message = 'Test Msg';
 
$w->SendPresenceSubscription($target); //Let us first send presence to user
$w->sendMessage($target,$message); // Send Message

**Comment by mgp25** [comment]
Your number is blocked.

Regards

**Comment by 90navjot** [comment]
No,its working on mobile

**Comment by mgp25** [comment]
@90navjot that's why then, you are swithcing from mobile to API (password changes), or possibility is that your network is blocked

**Comment by 90navjot** [comment]
i generate a new password but its not working,if network is blocked any other method to connect to the whats app
