### ISSUE TITLE
Blocked trying to register at first time

### ISSUE THREAD

**Issue by acubino** [WHAnonymous/Chat-API#1289]
Dear.

This is my first attemp with Chat-API. I buy a new spanish lebara card yerday for testing purposes. First trying to register with http://www.watools.es/pwd.html, i received the message but i put the code wrong with "-" i see the error today. 

Before this error, i trying to register using the example, the PHP files are the latest from Github, but are allowed in OVH France, the IP of the server is only for me. When i try to register use the example say the error:    
``` 
[status] => fail
[reason] => no_routes
[retry_after] => 3600
```
Today at first hour, y try to register using watools, put the phone and receive the sms (the second sms i receive with this card), the JSON of the Watools page say:
```json
 "{"status":"fail","reason":"blocked"}".
```
I only try to register and only receive 2 sms. I think the phone are blocked by use a bad IP, like OVH (because probably they know that are server IP) or inclusive the watools service. Is the watools service safe?.

I just blocked only for the issue for put the code as "NNN-NNN" instead of "NNNNNN"?.

Thanks a lot.

**Comment by mgp25** [comment]
@acubino Maybe that mobile provider is blocked by WhatsApp, use WART and `registerTool.php` to check if it works, if not, the mobile provider is blocked.

And yes, that website is safe to use.

Regards

**Comment by acubino** [comment]
The provider is Lebara, the card is bought on Mediamarkt yesterday. Really is possible to are blocked one provider in spain?, Lebara don't offer free cards and don't offer virtual numbers too. I think this is not very inteligent buy this cards for spam.

At last, the blocked card is forever, days, weeks ...? Because i don´t know if go to buy a new one.

Thanks for your time.

**Comment by TobiM93** [comment]
Hi I got the same Error with  Lebara Switzerland -> SMS Code arrives but Number is instant blocked ! Did you find an solution ?
