### ISSUE TITLE
"Can't use method return value in write context"

### ISSUE THREAD

**Issue by DarkAllMan** [WHAnonymous/Chat-API#1290]
Dear Support,

"PHP Fatal error:  Can't use method return value in write context in Chat-API-master/src/Login.php on line 63"

I have looked over this message in the issues. It seems I am missing maybe a depency or is it something else. I am on PHP 5.6 and as far as I can see I'm not missing any depencies... Please help me in finding the solution.

PHP Fatal error:  Can't use method return value in write context in Chat-API-master/src/Login.php on line 63

**Comment by DarkAllMan** [comment]
Is this related to SQLite?

mod_fcgid: stderr: PHP Fatal error: Uncaught exception 'PDOException' with message 'could not find driver' in /Chat-API-master/src/SqliteAxolotlStore.php:53

**Comment by mgp25** [comment]
Make sure you have all extensions installed and you are running php 5.6.

You can see version running this command:
```
php -v
```

and modules/extensions:
```
php -m
```

`PDOException` its because of PDO sqlite. You dont have installed `pdo_mysql`

Regards

**Comment by DarkAllMan** [comment]
I solved the PDO SQLite .. but the error still appears
It would seems its related to this: Login.php line 63
```
if (empty($this->parent->getAxolotlStore()->loadPreKeys()))
```
Prior to PHP 5.5, the function empty() can only be used on variables, not return values
I tested it by changing above line to:
          $loadPreKeys = $this->parent->getAxolotlStore()->loadPreKeys();
		  if (empty($loadPreKeys))
		  
After this change I no longer got the error!
