### ISSUE TITLE
unable to add multiple participant to group

### ISSUE THREAD

**Issue by mouhammad-zd** [WHAnonymous/Chat-API#1291]
Hello ! i am trying to add multiple participant in same time to a group and the wonderful things that happened is that the api return that members has been added when on reality no member has been added

this is the log

```
tx&nbsp;&nbsp;&lt;iq id="a8QxTW/nCJFd0" type="set" xmlns="w:g2" to="yyyyyyyyy@g.us"&gt;
<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;add&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;participant
 jid="zzzzzzzzzz@s.whatsapp.net"&gt;&lt;/participant&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp
;&lt;participant jid="xxxxxxxxxxx@s.whatsapp.net"&gt;&lt;/participant&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp
;&lt;/add&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;iq from="yyyyyyyy@g.us" type="result" id="a8QxTW/nCJFd0"&gt;<br />rx
&nbsp;&nbsp;&nbsp;&nbsp;&lt;add&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;participant jid="xxxxxxxx
@s.whatsapp.net"&gt;&lt;/participant&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;participant jid
="zzzzzzzzzz@s.whatsapp.net"&gt;&lt;/participant&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;/add&gt;<br
 />rx&nbsp;&nbsp;&lt;/iq&gt;
```

what is the problem

And i want to add some suggestion on some enhancement for api , if you can each time you want to add participant to a group check for group members and abort operation if member is already in group . I don't know if you can add this logic to each add participant request or this need all times a customized code

hope my issue is new and when solved can help and save someone day . Thanks in advanced for any regards !

**Comment by mgp25** [comment]
@mouhammad-zd the API provides all the functionality and is the user who need to check that, not the API itself, you should create a database or something storing all participants. 

Participants must be added one by one. You only can add multiple planticipants when creating the group

Regards
