### ISSUE TITLE
sendMessageVideo problem

### ISSUE THREAD

**Issue by enriv** [WHAnonymous/Chat-API#1292]
hi, im trying to send a video, this works fine for me, but once i send te video it keeps loading and i want to add a image at the same time and not work. this is my code. 
```php
$w->connect();
$w->loginWithPassword($password);
 $w->SendPresenceSubscription($target);
	  $w->sendMessageVideo($target, $pathToVideo, false);	
  $w->sendMessageImage($target, $pathToImage,false); 
```

please help

**Comment by mgp25** [comment]
@enriv poll messages and wait the video to be sent, don't close connectiom keep polling messages.

**Comment by enriv** [comment]
the video is sent, te image is not, and i change the order like this :
$w->connect();
$w->loginWithPassword($password);
 $w->SendPresenceSubscription($target);
  $w->sendMessageImage($target, $pathToImage,false); 
$w->pollmessage();
      $w->sendMessageVideo($target, $pathToVideo, false);  


and know the image is sent but not the video

**Comment by mgp25** [comment]
in a while loop...

**Comment by enriv** [comment]
Did you mean like this? 

$w->connect();
$w->loginWithPassword($password);
$w->SendPresenceSubscription($target);
 
while($w->pollmessage()){
$w->sendMessageImage($target, $pathToImage,false);
$w->sendMessageVideo($target, $pathToVideo, false);
}

**Comment by mgp25** [comment]
Is that hard to quote properly the code?

```php
while(true)
{
   $w->pollMessage();
}
```

**Comment by enriv** [comment]
thank you man, and sorry for bother you, i have one day working whit this

**Comment by enriv** [comment]
and if i want to do the massive thing, i want to know that it is posible, just that

**Comment by mgp25** [comment]
no

**Comment by enriv** [comment]
thank you
