### ISSUE TITLE
Running Chat-API as a daemon

### ISSUE THREAD

**Issue by unicast** [WHAnonymous/Chat-API#1294]
I'm looking for possibility to run Chat-API as a daemon with REST-interface, are there any ready-to-go solutions? If not, could you tell me your suggestions (libraries, architecture and so on) how to do that?

**Comment by mgp25** [comment]
@unicast maybe in the future we'll add REST-API support. If you want send a pull request when you have the class/module prepared.

Regards

**Comment by david-perez** [comment]
What do you mean by running it as a daemon with a REST-interface?
