### ISSUE TITLE
Server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by akramqalalwa** [WHAnonymous/Chat-API#1295]
Whenever I try to get my WhatsApp password I don't get anything, so I moved to check the console for errors, so I noticed that the server responds with error 404, which I think is the cause of problem, could you fix it please ?
![5555](https://cloud.githubusercontent.com/assets/11869771/11767840/05e1eda6-a1c4-11e5-9157-0d7f3ecc713d.PNG)

**Comment by mgp25** [comment]
Not API issue.

Regards
