### ISSUE TITLE
Is it possible to check who viewed your profile ?

### ISSUE THREAD

**Issue by lambasoft** [WHAnonymous/Chat-API#1296]
I've seen third party applications, that runs on android ( whatsapp plus ) where the app can tell you when someone checks your profile.

I'm very interested to know the logic behind this app.
Is it available in the API ? How is it possible ? Does WhatsApp stores any files on the mobile of whom you checked his profile ?

Thanks

**Comment by mgp25** [comment]
@lambasoft is not possible

Regards

**Comment by evilqubit** [comment]
maybe those apps track the image they fetch it from whatsapp and store it somewhere else where they can track it

**Comment by evilqubit** [comment]
maybe when u upload an image with this app they can inject some code that will trigger some url
