### ISSUE TITLE
Error 404 item-not-found, is repeated again and again

### ISSUE THREAD

**Issue by batman2010** [WHAnonymous/Chat-API#1297]
Hi! I have the error 404 "item-not-found", but I could not remove it, I used the sendPresenceUnsubscription method, however, it has not worked. Can you help me? The problem is that this routine does not stop, and try again and again.

```xml
< iq id="9" type="get" xmlns="w:profile:picture" to="5215215548101060@s.whatsapp.net">
    < picture type="image"></picture>
< /iq>

< presence from="5215215548101060@s.whatsapp.net" type="unavailable" last="none"></presence>
< iq from="5215215548101060@s.whatsapp.net" type="error" id="9">
    < error code="404" text="item-not-found">< /error>
< /iq>

 < iq id="11" type="get" xmlns="w:profile:picture" to="5215215548101060@s.whatsapp.net">
    < picture type="image">< /picture>
  < /iq>

  < iq from="5215215548101060@s.whatsapp.net" type="error" id="11">
    < error code="404" text="item-not-found">< /error>
  < /iq>
```

Thanks a lot for your time, the problem I have is that the phone number 5215215548101060, does not exist and can not erase from my list, intinté with the following code but keeps repeating the same mistake.
```php
$phone_arr[0]= 5215215548101060;
$w->sendSync($phone_arr);

$w->sendPresenceSubscription(5215215548101060);
sleep(2);

$w->sendPresenceUnsubscription(5215215548101060);
sleep(5);
```

I saw that after repeating this mistake for several hours I WhatsApp blocks the line.

Thank you very much for your excellent work.

**Comment by mgp25** [comment]
@batman2010 please next time remember to quote properly the code and debug log.

This was also answered in other issues, remember to check them before opening a new issue.

If the user doesnt have set a profile image, 

```xml
    <error code="404" text="item-not-found"></error>
```

is returned

Regards
