### ISSUE TITLE
No multimedia can be sent

### ISSUE THREAD

**Issue by akramqalalwa** [WHAnonymous/Chat-API#1298]
I noticed that when I send an image, video or audio it processes it but actually I don't receive on WhatsApp, although it's capable to send text messages normally. I don't know where is the problem !

**Comment by mgp25** [comment]
@akramqalalwa if you dont post code and debug log, ill consider this issue invalid

**Comment by akramqalalwa** [comment]
![capture](https://cloud.githubusercontent.com/assets/11869771/11815551/dc1a3cf2-a354-11e5-812e-c1332a6ef5e3.PNG)
Why i these files didn't transfer ?

**Comment by mgp25** [comment]
I dont know what is that. Please post code and debug log for further support.

Regards

**Comment by estcap** [comment]
@akramqalalwa You might want to look at this issue https://github.com/WHAnonymous/Chat-API/issues/781  , but you should post both code and debug in order to get help
