### ISSUE TITLE
WA PW extractor

### ISSUE THREAD

**Issue by jmsx** [WHAnonymous/Chat-API#1309]
"couldn't read Whatsapp files. Are you root?"

I've granted permissions Root but I still showing this message. Help

**Comment by mgp25** [comment]
@jmsx very soon ill release something to get password easier :smile: 

I'll tell you when it's ready

**Comment by jmsx** [comment]
One question I'm developing an android application which is connected to a server using your API, I wonder how my app get the password directly to the server to send it. Regards, Thanks in advance.

**Comment by mgp25** [comment]
@jmsx check the wiki for more info, you will find everything there

Regards
