### ISSUE TITLE
Number gets blocked for no reason.

### ISSUE THREAD

**Issue by Jonathan313** [WHAnonymous/Chat-API#1310]
Hello Again,

I have noticed that the number gets automatically blocked by the WhatsApp for no reason! I verified the phone number and sent a message to myself and got blocked. Also I tried with another number and the same result. Sending a single message is not a spam I guess.

Points to be noted : 
======================================================================
-> I have 3 numbers running on same VPS. Will it create any problems if running simultaneously ? Not spamming though.
-> One number is working perfectly but when I use other numbers on same machines they got blocked.
-> Numbers are of USA and sending message to my Indian friend. Will it create any problem ? One number is of Indian and it doesn't get blocked yet. And yes my friend has not reported spam.

This was the script.

```
<?php
error_reporting(E_ALL);
ini_set('display_errors', 'On');
require_once('../src/whatsprot.class.php');

$username = "19492595089";
$nickname = "Jonathan";
$password = "PCDpakJAE0SmZKLpWHwilnQ5PhM="; // The one we got registering the number
$debug = true;

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!
	$dst = '91'.'9979559211';
	$msg = 'Hello from Test!;
	$w->sendMessage($dst , $msg);
$w->disconnect();
```

**Comment by mgp25** [comment]
@Jonathan313 that script is completly wrong. Read wiki.

You are not syncing, subscribing, composing, waiting and you are disconnecting to soon

**Comment by Jonathan313** [comment]
@mgp25   Problem was with new code. I tried to used old code and worked like a charm. I must use old code. Thanks btw :)
