### ISSUE TITLE
reciving messsages 

### ISSUE THREAD

**Issue by ahmedstack** [WHAnonymous/Chat-API#1312]
I want to make an retrieve messages from WhatsApp server every 2 seconds. I am using this jQuery function :

```jquery
          setInterval(function(){   
                $.post("recevie_message.php",{},function(data){

                       console.log(data);
                       $arr=JSON.parse(data);
                       $.each($arr,function(index,value){
                              console.log(value.body);
                              var templateResponse = Handlebars.compile( $("#message-response-template").html());
                              var contextResponse = {response:value.body};
                   $('.chat-history').append(templateResponse(contextResponse));

                        });
          },2000);
```

and the PHP code:
```php
<?php
  include_once('checkUserSession.php');
  $w=$task->connectToServer();
 // header ('Content-Type: text/html; charset=UTF-8'); 
  $username= $task->getPhoneNumber();
  $password = $task->getWhatsappPassword();
  $msg = array();
  $i=0;
  function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
   $GLOBALS['msg'][$GLOBALS['i']]=array("from"=>$from,"body"=>$body);
   $GLOBALS['task']->saveMessage($body,'f','t',$from);
   $GLOBALS['i']++;
}


      include_once('Chat-API-master/src/events/MyEvents.php');
      $events = new MyEvents($w);
      $w->eventManager()->bind("onGetMessage", "onMessage");

      $w->pollMessage();
      echo json_encode($msg);
      $w->disconnect();
```

The problem is that I am getting loginFaulierException at many calls (not all of them). Is there is a better way to receive messages or in other words how does the WhatsApp native app works?

**Comment by mgp25** [comment]
@ahmedstack `loginFailureException` means the account is blocked or you are using a wrong number/password

There are example that will help you with this. The best way in the API is to `pollMessage()` in a for o while loop and set events to capture the data.

WhatsApp aplication is just an open socket and it receives data. If you consider this as answered close the issue. If you still have any doubt, let me know.

Regards

**Comment by ahmedstack** [comment]
the loginFailureException does not occur all the times,  that is , I may get  loginFailureException in one call and then get successful in another call (same number and password )  ,so the number is not blocked 
and this is happens even if I open recive_messages.php and refresh it manually

**Comment by mgp25** [comment]
@ahmedstack post full debug log

**Comment by akashrajan** [comment]
In my case after login failure my number got blocked. I tried old script it's working good with no problem!
