### ISSUE TITLE
Should I send a sendGetClientConfig or sendClientConfig on first login

### ISSUE THREAD

**Issue by moyamo** [WHAnonymous/Chat-API#1316]
[The wiki page](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#fist-login) says that I should send sendGetClientConfig on first login.

[The code](https://github.com/WHAnonymous/Chat-API/blob/master/examples/Simple%20CLI%20client.php) says I should send sendClientConfig on first login.

What should it be?

**Comment by mgp25** [comment]
@moyamo `sendGetClientConfig`
