### ISSUE TITLE
Problem with sync contacts 

### ISSUE THREAD

**Issue by adamchick** [WHAnonymous/Chat-API#1317]
when i try to sync new contact, script takes long time to load and dosn't return any thing  only error server temperary 503 error!. i am using the same of the example code  of sync contact.
please help me to resolve this problem

**Comment by mgp25** [comment]
@adamchick if you dont post full debug log and script code, we can't help you

**Comment by adamchick** [comment]
set_time_limit(30);

error_reporting(E_ALL);
ini_set('display_errors', 1);
require "whatsapi/src/whatsprot.class.php";

$numbers=array('79375883010','967774541452');

$username = ""; // my number
$identity=strtolower(urlencode(sha1($username,true)));
$w = new WhatsProt($username,$identity,"mezab.net",true);
function onSyncResult($result)
{
    foreach ($result->existing as $number) {
       echo "number exist " . $number;
    }
    foreach ($result->nonExisting as $number) { 
    echo "number dosnt exist  " . $number;
    }
   die(); //to break out of the while(true) loop
} 

$w->eventManager()->bind('onGetSyncResult', 'onSyncResult');
$w->connect();
$password = ""; // my pass
$w->LoginWithPassword($password);
$w->pollMessage();
$w->sendGetServerProperties();
$w->pollMessage();
$w->sendSync($numbers);  
while (true) {
    $w->pollMessage();  
}
$w->disconnect();

**Comment by murderer99** [comment]
Looks like the problem is in this code

    while (true) {
        $w->pollMessage();
    }

it's no exit from `while`

**Comment by adamchick** [comment]
This script work fine once every one hour nearly for my number!!... rest of the time does not work  i don't know why!?

**Comment by mgp25** [comment]
`503 error` its because of the while loop, check it

Regards

**Comment by adamchick** [comment]
Thank you to replay! problem is resolved.
