### ISSUE TITLE
Error: could not find driver...

### ISSUE THREAD

**Issue by KevinChanK** [WHAnonymous/Chat-API#1321]
I set in examples/whatsapp.php:-
```php
$config['xxx'] = array(
    'fromNumber' => '852xxxxx',
    'nick' => "xxxx",
    'waPassword' => "xxxx=",
    'email' => 'xxxx@gmail.com',
    'emailPassword' => 'xxxxx'
);
```
And it show "Error: could not find driver", anyone can help me? 
Thanks a lot.

**Comment by Kirschn** [comment]
You just have to enable the "pdo_mysql" extension in the php.ini :)

**Comment by KevinChanK** [comment]
thanks a lot, but now get another error: 
Error: There was an error with the AJAX request. XML/Json format is bad

thank you very much..

**Comment by amprodes** [comment]
???
