### ISSUE TITLE
Error: There was an error with the AJAX request.  

### ISSUE THREAD

**Issue by KevinChanK** [WHAnonymous/Chat-API#1324]
I still get 2 errors on "Chat-API/examples/whatsapp.php"...

Please kindly help me......

Error: There was an error with the AJAX request. XML/Json format is bad.
Error: No config settings for user could be found

Thank you very much......

**Comment by Jonathan313** [comment]
This is not the programming forum where you post questions related to the programming code. This is WHAnonymous/Chat-API  GitHub where you have to post problems related to the API not programming code related.

**Comment by mgp25** [comment]
@KevinChanK you have answered yourself:

```
 Error: No config settings for user could be found
```

Edit the file and use your data

Regards
