### ISSUE TITLE
how to fix <system-shutdown></system-shutdown>

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#1325]
Trying to create a group and getting this error. What can be done?
Before the error group creation was successful. After the error cannot create groups anymore even with the same method as before. To be more precise, how can I get rid of it?

**Comment by yanelev** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="31xxxxxxxxxx"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>[¦¦;0Y¦}s`=-\0u5¦e</challenge>

tx  <response>ywm?¦¦U¦5¦s3B¦8t¦N¦i"¦la¦¦8¦¦y¦</response>

rx  <success t="1450992437" props="4" kind="free" status="active" creation="1450992318" expiration="1482528318">¦¦
¦¦¦_¦¦¦¦%¦¦2¦/w</success>

tx  <presence name="0"></presence>

tx  <iq xmlns="w:g2" id="1" type="set" to="g.us">
tx    <create subject="simplecheck54">
tx      <participant jid="31xxxxxxxxxx@s.whatsapp.net"></participant>
tx      <participant jid="31xxxxxxxxxx@s.whatsapp.net"></participant>
tx      <participant jid="31xxxxxxxxxx@s.whatsapp.net"></participant>
tx    </create>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="31xxxxxxxxxx@s.whatsapp.net"></presence>

rx  <stream:error>
rx    <system-shutdown></system-shutdown>
rx  </stream:error>

ConnectionException Object
(
    [message:protected] => Connection Closed!
    [string:Exception:private] =>
    [code:protected] => 0
    [file:protected] => src/whatsprot.class.php
    [line:protected] => 277
    [trace:Exception:private] => Array
        (
            [0] => Array
                (
                    [file] => src/whatsprot.class.php
                    [line] => 1737
                    [function] => pollMessage
                    [class] => WhatsProt
                    [type] => ->
                    [args] => Array
                        (
                        )

                )

            [1] => Array
                (
                    [file] => src/whatsprot.class.php
                    [line] => 1082
                    [function] => waitForServer
                    [class] => WhatsProt
                    [type] => ->
                    [args] => Array
                        (
                            [0] => 1
                        )

                )

            [2] => Array
                (
                    [file] => cg.php
                    [line] => 95
                    [function] => sendGroupsChatCreate
                    [class] => WhatsProt
                    [type] => ->
                    [args] => Array
                        (
                            [0] => simplecheck
                            [1] => Array
                                (
                                    [0] => 31xxxxxxxxxx
                                    [1] => 31xxxxxxxxxx
                                    [2] => 31xxxxxxxxxx
                                )

                        )

                )

            [3] => Array
                (
                    [file] => cg.php
                    [line] => 170
                    [function] => createGroup
                    [args] => Array
                        (
                            [0] => Array
                                (
                                    [0] => 31xxxxxxxxxx
                                    [1] => 31xxxxxxxxxx
                                    [2] => 31xxxxxxxxxx
                                )

                            [1] => 31xxxxxxxxxx
                            [2] => 0
                            [3] => ???????
                            [4] => 0
                            [5] => xxxxxxxxxxxxxxxxxxxx
                            [6] => simplecheck
                            [7] => someone
                            [8] => simplecheck
                            [9] => 31xxxxxxxxxx
                            [10] => 31xxxxxxxxxx
                        )

                )

        )

    [previous:Exception:private] =>

**Comment by Jonathan313** [comment]
Post your code.

**Comment by mgp25** [comment]
It's not an issue, WhatsApp can `shutdown-system` but if you retry it will work again.

Regards
