### ISSUE TITLE
catch sync backoff error.

### ISSUE THREAD

**Issue by awpsniper** [WHAnonymous/Chat-API#1327]
Hello,

Obviously when we try to sync more time it will be disabled by WhatsApp ! Now is there any way to catch that error and print it out ? Because it shows blank page is debug is turned off.

Thanks!

**Comment by 0xTryCatch** [comment]
Show debug log

**Comment by awpsniper** [comment]
```
 <iq from="919914779918@s.whatsapp.net" type="error" id="1">
rx    <error code="501" text="feature-not-implemented" backoff="3600"></error>
rx  </iq>
```
I know I should try after 1 hour. But the thing is I don't want to see blank page. Is there any way to catch this error so that I can display like "Please try after  1 hour"

**Comment by mgp25** [comment]
@awpsniper use event system, explained in the wiki

Regards

**Comment by awpsniper** [comment]
@mgp25  There is no such a event called "onsyncFail"
