### ISSUE TITLE
Read receipt

### ISSUE THREAD

**Issue by gleichnerv** [WHAnonymous/Chat-API#1328]
hi there,
I'm trying to manual send a read receipt.
I disabled autoreceipt setting enableReadReceipt(false) but now how can I send the blue double tick?

And again, I should send the read receipt for every message or just one for the last received message?
Thanks

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L2815

Received - normal receipt
Read - read receipt (blue double tick)

**Comment by gleichnerv** [comment]
Sorry, I'm here again,
in my db I store only messageid, text, contactnumber.

How do I valorize sendReceipt parameters?

I made some tests using  
```
sendMessageRead($number . "@s.whatsapp.net", $waid)
```
It works but I need to "read" each message that don't seem the right way

**Comment by gleichnerv** [comment]
I don't understand how to use sendReceipt function.
How do I create $node?

And if I have many unread messages what should I do?
The app seem to send a single read receipt attaching an array containing the read messages. 
How to do that?
