### ISSUE TITLE
Get profile picture - error 404

### ISSUE THREAD

**Issue by ddfrreire** [WHAnonymous/Chat-API#1330]
Hi, after last update returns error when request get profile picture
```
rx  <iq from="557591641213@s.whatsapp.net" type="error" id="1">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>
```

**Comment by mgp25** [comment]
@ddfrreire that means that the user doesnt have  profile picture

Regards

**Comment by ddfrreire** [comment]
Saw this in the wiki, but the user has profile picture. I did a test with my whatsapp that have profile picture and response error 404.

**Comment by mgp25** [comment]
@ddfrreire thats weird, try subscribing the user first

**Comment by ddfrreire** [comment]
@mgp25  I tried subscribes of user but show same problem, I noticed that source of images changed after last update api or coincidence changes of WhatsApp system.  Now, receives not only jpg, others times images was received corrupted.  The result is like #1337. 

```
ÿØÿàJFIFHHÿáLExifMM*‡i& € €ÿí8Photoshop 3.08BIM8BIM%ÔŒÙ²é€	˜ìøB~ÿÀ€€"ÿÄ	
ÿÄµ}!1AQa"q2‘¡#B±ÁRÑð$3br‚
```

Regards

**Comment by ddfrreire** [comment]
@mgp25 I put of version to previous chat-api pictures profile receives normally, but put of latest version doesn't receives pictures profile.

**Comment by mgp25** [comment]
@ddfrreire this will be fixed in the next commit.

Regards

**Comment by ddfrreire** [comment]
ok @mgp25 thank you. 

Reagards

**Comment by mrjoebudi** [comment]
Fatal error: Can't use method return value in write context in C:\xampp\htdocs\Chat-API\src\Login.php on line 64
....help...for this error

**Comment by ddfrreire** [comment]
@mrjoebudi install a version latest of php > 5.6. 

Reagards
