### ISSUE TITLE
There is an issue with reading messages please check if it works on your side.

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#1333]

**Comment by javier-igneoma** [comment]
Me too. I tested with the old src files and the new. Suddenly from today (for me) is not working on receiving messages. It can read status and also send messages. But not read. I hope this help to figure it out.

**Comment by 0xTryCatch** [comment]
Post debug log

**Comment by yanelev** [comment]
[debug.txt](https://github.com/WHAnonymous/Chat-API/files/73818/debug.txt)

**Comment by yanelev** [comment]
[debug.txt](https://github.com/WHAnonymous/Chat-API/files/73821/debug.txt)

**Comment by yanelev** [comment]
0xTryCatch any forecast for solving the issue? Do you need some more information?

**Comment by weerdm** [comment]
This can not be fixed, you should use the newest version of the API and enable encryption. A couple days ago every WhatsApp-client that didn't support encryption was forced to update to the latest version. This was probably a preparation to disable non-encrypted messages.

**Comment by alxhotel** [comment]
So are you saying the problem is that we don't have PHP Protobuf and Curve25519 installed ?

**Comment by sector8nl** [comment]
Yes that't the problem. It is now required to have those dependencies.

**Comment by weerdm** [comment]
Yes that's the problem. It is now required to have these dependencies installed.

**Comment by JJF2** [comment]
Any idea how to get dll dependencies for windows?
