### ISSUE TITLE
Whatsappi api + phone

### ISSUE THREAD

**Issue by christiancannata** [WHAnonymous/Chat-API#1336]
Is it possible use my whatsapp account with my web-app and with my phone?
Actually i must request a new code every time I would use my web app and every time I would reuse whatsapp in my iPhone.

Thanks

**Comment by mgp25** [comment]
@christiancannata you can, but not at the same time, you need to extract the password from your device and use that password with the API.

Info about how to extract password from device: https://github.com/WHAnonymous/Chat-API/wiki/Extracting-password-from-device
