### ISSUE TITLE
Getting strange messages

### ISSUE THREAD

**Issue by victorscatolon** [WHAnonymous/Chat-API#1338]
Yesterday I was usually using the Chat-API, however, today when I went to use the messages I get are coming strange, and I do not sending anything, he gets the following message:
![capturar](https://cloud.githubusercontent.com/assets/11843723/12037428/f7ac82b8-ae35-11e5-93f2-5a0bfc52154a.PNG)
Why is that?
Sorry for the English, I am Brazilian, I'm using google translate.
I'm using Windows Wamp.

**Comment by Jordyderuijter** [comment]
See: https://github.com/WHAnonymous/Chat-API/issues/1333

**Comment by mgp25** [comment]
WhatsApp is forcing to all users to use end to end encryption, please read closed issues and install dependencies, more info in the wiki.

Regards
