### ISSUE TITLE
The autoloader expected class "Curve" to be defined in file 

### ISSUE THREAD

**Issue by Jordyderuijter** [WHAnonymous/Chat-API#1339]
After installing the PHP extensions PHP Protobuf and Curve25519 to enable encryption, I got the following error:

The autoloader expected class "Curve" to be defined in file "../vendor/whatsapp/chat-api/src/libaxolotl-php/ecc/Curve.php". The file was found but the class was not in it, the class name or namespace probably has a typo.

Can anyone tell me why this error is being shown?
After removing the following if-statement in the stated file the error is not being shown anymore:

"if(!class_exists("Curve")){"

Greetings,
Jordy de Ruijter

**Comment by ogerik** [comment]
Same here, worked when i remove the if check mentioned by @Jordyderuijter
