### ISSUE TITLE
ProtobufMessage not found (dep installed)

### ISSUE THREAD

**Issue by tim-hanssen** [WHAnonymous/Chat-API#1340]
Hey Guys,

I'm getting this error after installing the latest build:

`PHP Fatal error:  Class 'ProtobufMessage' not found in /data/www/project/vendor/whatsapp/chat-api/src/libaxolotl-php/state/pb_proto_LocalStorageProtocol.php on line 12`

I checked my phpinfo:
```
protocolbuffers

PHP Protocol Buffers Extension
Protocol Buffers Support	enabled
Version	0.2.5
```

So that looks right? Any suggestions?

**Comment by ogerik** [comment]
Have you installed this extension https://github.com/allegro/php-protobuf ? 
I used that one and it worked, this is what my PHP says:

**php -i**
```
protobuf

Version => 0.9
```

**Comment by yairnet** [comment]
download
unzip
phpize
./confiure
make
make install
add on php.ini
extension=curve25519.so
extansion=protobuf.so


:( what now?

**Comment by mgp25** [comment]
@tim-hanssen @yairnet make sure its loaded correctly, to make sure run this command:

`php -m`

And check if `protobuf` and `Curve25519`

Regards

**Comment by yairnet** [comment]
thx :+1:

**Comment by tim-hanssen** [comment]
That fixt it for this error!

PHP Fatal error:  Cannot redeclare class Log in /data/www/chat-api/src/libaxolotl-php/logging/Log.php on line 4

Now it looks like the log class is loaded twice?
