### ISSUE TITLE
Read message error

### ISSUE THREAD

**Issue by systemreggae** [WHAnonymous/Chat-API#1341]
I'm trying to recive a message and the "pollMessage" method generate a exception
When I send a message all its ok

This is the text on read message and it is important to say that doublecheck its not marked from the origin

<message from="number@s.whatsapp.net" type="text" id="5F2BCCDD238982C4EA1E" t="1451411783" notify="Usuario">
rx    <enc v="2" type="pkmsg">3!{▒|b▒▒3▒▒{▒O▒=▒▒UϏ▒▒|▒D▒Z▒*y▒(s▒d261!▒▒1▒▒▒▒r ▒/"B3!▒><▒̋▒f▒▒▒▒▒,#(:▒▒d▒X"▒~_▒jFhlc-"▒P▒P▒▒ؘ(▒0▒ɋ</enc>
rx  </message>

**Comment by mgp25** [comment]
@systemreggae damn, please, read closed issues! #1333
