### ISSUE TITLE
Enc v1 for iOS devices

### ISSUE THREAD

**Issue by dishark** [WHAnonymous/Chat-API#1343]
Hey guys i'm getting this error while trying to send messages to an iOS device.

````
<receipt from="----@s.whatsapp.net" type="error" id="c6c4efda7642a777d5f643" t="1451424605">
     <error type="enc-v1"></error>
</receipt>
````

The recommended encryption extensions are all set. Android and web are working perfectly. I'm running the `3.0` version of the Chat-API.

**Comment by weerdm** [comment]
I get the same error when sending messages to an IOS device:

`<receipt from="**@s.whatsapp.net" type="error" id="dc307f6ec6d4d7896ad300" t="1451428377">
     <error type="enc-v1"></error>
</receipt>`

**Comment by p031985s** [comment]
hi there...

i get this response from IOS and from Android, response only from Windows Phone Works.

2015-12-29 17:43:21<-<message from="573xxxxxxxxx@s.whatsapp.net" type="text" id="39272E43D884FFFD852" t="1451429004" notify="MP">
2015-12-29 17:43:21<- <enc v="1" type="pkmsg">3!4§g ³ãd4Hl| y„³º9—í‘Ä¬éå³Qu!Ž9{TóŠ†œÙóp§|µ¥tÚo¹ÿƒÑý(ý¤pQ²1"B3 !¿­ß°ã4Ïˆ‰2ÄûuË¦%Ë¼ó9Ìîul‘X"ë’ µcvÊÃ „g?P»%iÈõ‹PÁ(Œáï¬0¾ì¿</enc>
2015-12-29 17:43:21<-</message>

**Comment by p031985s** [comment]
2015-12-29&nbsp;17:43:21<-&lt;message from="573206439537@s.whatsapp.net" type="text" id="39272E43D884FFFD852" t="1451429004" notify="Mafe Phone"&gt;<br />2015-12-29&nbsp;17:43:21<-&nbsp;&nbsp;&lt;enc v="1" type="pkmsg"&gt;3!4§g
³ãd4Hl|
y„³º9—í‘Ä¬éå³Qu!Ž9{TóŠ†œÙóp§|µ¥tÚo¹ÿƒÑý(ý¤pQ²1"B3
!¿­ß°ã4Ïˆ‰2ÄûuË¦%Ë¼ó9Ìîul‘X"ë’
µcvÊÃ „g?P»%iÈõ‹PÁ(Œáï¬0¾ì¿&lt;/enc&gt;<br />2015-12-29&nbsp;17:43:21<-&lt;/message&gt;

**Comment by weerdm** [comment]
Now it suddenly works at my side. Changed nothing.. No more errors and the messages arrive on my phone just fine.

**Comment by dishark** [comment]
@p031985s Hello! Did you install the encryption extensions?

Run `php -m` to make sure both __protobuf__ and __curve__ are being loaded! And please, let's keep this issue about the iOS platform if you don't mind.

Let's us know if it worked for you.

**Comment by dishark** [comment]
@weerdm Did you think whatsapp changed something in its end? I'll try it again.

**Comment by p031985s** [comment]
Hi there...

do you know if protobuf and curve works on Windows PHP?

Thank you.

**Comment by weerdm** [comment]
I really have no idea to be honest, I am looking at the script right and I noticed a little change I made. After sending a message I've added some more `pollMessage()` calls. I'm calling it 3 times now. Not sure if this is coincidence or the solution to the enc error. Let me know :)

**Comment by dishark** [comment]
In your `Constants.php`. How is set your `TIMEOUT_SEC`?

Mine is:
````
const TIMEOUT_SEC = 2;
````

And it works now. Gotta find out a way to get a little bit faster though

**Comment by weerdm** [comment]
Yes also 2 seconds, like always. Now its working again without changing anything, very strange.

**Comment by dishark** [comment]
Well every first message that is sent is done by using enc v1 and then to the next it uses v2 then the error shows up. Can you verify if it happens there as well?

**Comment by weerdm** [comment]
Ah yes you are right! I started the script, sent some messages and they are all arriving just fine. Then after I receive a message back from my phone I can no longer send messages to the phone. In my case that's the moment when the `<error type="enc-v1"></error>` (not v2) error occurs.

**Comment by ludufre** [comment]
Following this issue...

**Comment by dishark** [comment]
Great update @weerdm, thank you. I'll be checking it later on a fork and PR this if no one else does.

**Comment by Jordyderuijter** [comment]
Same problem here. Do you guys know which event is being called when this error occurs?

**Comment by WalterM404** [comment]
I have the same problem. Is there a permanent fix sheduled? The fix from @weerdm is a temporary i suppose? Thnx and a great new year guys.

**Comment by mgp25** [comment]
@WalterM404 It's working fine, download latest commits

Regards
