### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by victorscatolon** [WHAnonymous/Chat-API#1344]
The system is only sending messages, it does not receive or send information that the message has been read.Used windows and tava not getting due to the encryption, it worked yesterday, but today already stopped. Then went pro linux, wanted to know how do I install and run again?
Must know how to install the curve and protobuf, I tried but I could not, I use Ubuntu.

**Comment by mgp25** [comment]
Please, read the wiki before open a new issue: https://github.com/WHAnonymous/Chat-API/wiki/Dependencies

**Comment by victorscatolon** [comment]
I installed the curve and protobuf but still the error persists.

**Comment by mgp25** [comment]
@victorscatolon can you paste here the result of this command? `php -m`

**Comment by victorscatolon** [comment]
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by mgp25** [comment]
You see? You dont have enabled the extensions, check your php.ini and add them

**Comment by victorscatolon** [comment]
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 8 attempt to write a readonly database' in /var/www/html/src/SqliteAxolotlStore.php:118 Stack trace: #0 /var/www/html/src/SqliteAxolotlStore.php(118): PDOStatement->execute(Array) #1 /var/www/html/src/SqliteAxolotlStore.php(124): axolotlSqliteStore->storePreKey(3315785, Object(PreKeyRecord)) #2 /var/www/html/src/whatsprot.class.php(330): axolotlSqliteStore->storePreKeys(Array) #3 /var/www/html/src/Login.php(66): WhatsProt->sendSetPreKeys() #4 /var/www/html/src/whatsprot.class.php(280): Login->doLogin() #5 /var/www/html/examples/ok.php(18): WhatsProt->loginWithPassword('br2E6BvukQZMuwY...') #6 {main} thrown in /var/www/html/src/SqliteAxolotlStore.php on line 118

**Comment by mgp25** [comment]
@victorscatolon im starting to thing you dont read the errors you got and search for yourself, because thats not an API issue, please next time try using google before, google is your friend.

Set write privileges to axolotl.db

Regards

**Comment by victorscatolon** [comment]
Sorry, I could pass me please whitelist?
It worked.
