### ISSUE TITLE
Can not receive messages

### ISSUE THREAD

**Issue by CristianOspina** [WHAnonymous/Chat-API#1345]
From today I can not receive messages.
In debug mode this is what I get:
```
rx  <chatstate from="YYXXXXXXXXXX@s.whatsapp.net">
rx    <composing></composing>
rx  </chatstate>

rx  <message from="YYXXXXXXXXXX@s.whatsapp.net" type="text" id="B56B775602FDFB48
3D5" t="1451441747" notify="NICKXXX">
rx    <enc v="2" type="pkmsg">3↕!♣ë╘vBúí↕├Q¬º└↔½S◄Å▓åé╔v♂,∙ô┼├Pⁿûj→!♣ô√ç╒+á╣╖ei░
íM¡¡↔¢yr↕çα3ß☻OMÑ→►1♥"B3
╔▀%úS   ÆOï╗ü♣É(»O0≈çÄ♦</enc>ñ┬│ΩX►♣↑ "►'mΘ╡É>vj7┼
rx  </message>

<message from="YYXXXXXXXXXX@s.whatsapp.net" type="text" id="B56B775602FDFB483D5"
 t="1451441747" notify="NICKXXX">
  <enc v="2" type="pkmsg">3↕!♣ë╘vBúí↕├Q¬º└↔½S◄Å▓åé╔v♂,∙ô┼├Pⁿûj→!♣ô√ç╒+á╣╖ei░íM¡¡
↔¢yr↕çα3ß☻OMÑ→►1♥"B3
╔▀%úS   ÆOï╗ü♣É(»O0≈çÄ♦</enc>ñ┬│ΩX►♣↑ "►'mΘ╡É>vj7┼
</message>
```
But never the "onGetMessage" event runs. And the message only gets one gray check mark, no two and no blue.

It was working all right, I have not changed anything.
I dont need to know the content of the message, but I need to know when and from that number comes.

What could have changed? What can I do?
Regards.

**Comment by Mishalml007** [comment]
#cristianOspina# 
It seems that Whatsapp have updated the encryption version. But it does matter only for the message content, you can easily get the sender name and number. This can be achieved in 2 ways either by native events (its working fine for me) or through looping getMessages() function 

for eg: 

$w = new WhatsProt(details);
 $w->connect();
$w->loginWithPassword('password');
  while ($w->pollMessage()) {
                $messages = $w->getMessages();
                           foreach ($messages as $msg) {
                             $i++;
                                $mis[$i]['from'] = $msg->getAttribute("from");
                                $mis[$i]['time'] = $msg->getAttribute("t");
                                $mis[$i]['name'] = $msg->getAttribute("notify");
                                $mis[$i]['type'] = $type;
                            }
   }
print_r($mis);

try this

**Comment by awpsniper** [comment]
@Mishalml007 : You must be using the older version. I tried with newer code and doesn't work I got banned !

**Comment by Mishalml007** [comment]
No, I am using the latest Chat-Api, For me except the message content all other attributes are recording

**Comment by CristianOspina** [comment]
@Mishalml007 @awpsniper  Works for me with the newer code. But how can I make for the message is marked as read, because otherwise it will always be there, and always I will iterate the same message.

**Comment by awpsniper** [comment]
@CristianOspina : No. Once you read the message, the blue tick will be sent automatically. I had no problem with that!

**Comment by Mishalml007** [comment]
@CristianOspina you don't need any extra code for that, and the blue ticks won't appear because of the encryption problem, for whatsapp, the message is still unread because of lack of decryption key, if you send an image as message, you will get blue ticks, as no encryption is applied, Message is encrypted for only personal text messages, not in group message aswell

**Comment by awpsniper** [comment]
@Mishalml007 : Well your home page link doesn't work :P
http://www.mishalpm.com/home

**Comment by Mishalml007** [comment]
@awpsniper oh thanks for that feedback ...

**Comment by mgp25** [comment]
You need to install dependencies, please read the wiki: https://github.com/mgp25/Chat-API/wiki/Dependencies

And for God's sake, check other issues before opening new ones

**Comment by kartikkapatel** [comment]
i'm using latest code of repository now i'm facing same problem. i get message in debugging mode bt but actual event not work ongetmessage  not getting message.
here is output :

**Comment by mgp25** [comment]
@kartikkapatel read!
