### ISSUE TITLE
Unable to Decrypt message since 2 days

### ISSUE THREAD

**Issue by iwtglobal** [WHAnonymous/Chat-API#1346]
Dear team

My Whatsapp was working fine two days ago, But since las 2 days We are not able to read message. Please check below code and respose.

PHP CODE

$w = new WhatsProt($username, $nickname, $nickname, $debug);
$events = new MyEvents($w);
$w->eventManager()->bind("onGetMessage", "onMessage"); 
$w->eventManager()->bind("onSendMessage", "sndMessage"); 

$w->connect(); // Connect to WhatsApp network

$w->loginWithPassword($password); // logging in with the password we got!
$i=1;
while($i<5)
{
$w->pollMessage();
$msgs = $w->getMessages();
print_r($msgs);
 foreach ($msgs as $m) {
    # process inbound messages
  echo "printing";
  $m->NodeString("");
  }
 $i++;
}

$w->disconnect();

RESPONSE of Whatsapp

[0] => ProtocolNode Object
        (
            [tag:ProtocolNode:private] => message
            [attributeHash:ProtocolNode:private] => Array
                (
                    [from] => 918006755556@s.whatsapp.net
                    [type] => text
                    [id] => 7D585A3CCAC0F208530
                    [offline] => 3
                    [t] => 1451459624
                    [notify] => Just Pay World
                )

            [children:ProtocolNode:private] => Array
                (
                    [0] => ProtocolNode Object
                        (
                            [tag:ProtocolNode:private] => enc
                            [attributeHash:ProtocolNode:private] => Array
                                (
                                    [v] => 2
                                    [type] => pkmsg
                                )

                            [children:ProtocolNode:private] => 
                            [data:ProtocolNode:private] => 3!ÓK›#@Û–Ñ­ö

**Comment by sanjayradadiya91** [comment]
dear team,
i have also faced this type of issue so can we have any solution for message decrption

**Comment by Mishalml007** [comment]
Waiting for a solution. facing same issues

**Comment by Mishalml007** [comment]
Hi ...Any solution to this issue, i have tried all possible ways from the wiki for receiving messages

**Comment by horaceho** [comment]
Which part of Wiki to read? `onGetMessage` was broken not long ago....

**Comment by mgp25** [comment]
@horaceho dammit, install dependencies,  thats it, to decrypt messages you need PHP protobuf and Curve extensions

**Comment by mrjoebudi** [comment]
try this man,how to compile extention on windows
http://blog.benoitblanchon.fr/build-php-extension-on-windows/

**Comment by horaceho** [comment]
Thank you! Works well now.
