### ISSUE TITLE
New code received by sms but temporarily_unavailable response on codeRegister all the time

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#1347]
Hi,

Since last month I've started seeing this behavior in the registration process:
1.- registration code is requested by sms
2.- new code is received by sms
3.- temporarily_unavailable is received on codeRegister

Here are the parameters sent:

```
(
    [cc] => 1
    [in] => <<<masked>>>
    [id] => ƒÕ:_¯™2wùi] nÝÈzˆcå <--- this is the identity used in the code request
    [code] => 151518
)
```

Here is the response received:

```
(
    [status] => fail
    [reason] => temporarily_unavailable
    [retry_after] => 3600
)
```

The response is always the same. I'm using code from November 11th. Code from today never get even the new code.

Thanks for your help.
Regards.

**Comment by 0xTryCatch** [comment]
This happens when using virtual numbers, are you?

**Comment by mgp25** [comment]
@hgc2002 mostly like using virtual phone numbers.

**Comment by hgc2002** [comment]
it just worked for 3 numbers, failed at the fourth. I'll wait an hour as it requests.

**Comment by hgc2002** [comment]
One hour after, it worked once, failed on a second number and requests one hour waiting more. nice...

**Comment by breakerh** [comment]
Then use a real phone number? Not a virual one?
Just to test?

**Comment by hgc2002** [comment]
I need to have a stable way to do this, or to understand how it goes. Waiting for one hour wouldn't be an issue depending on the situation.
