### ISSUE TITLE
Various related to encryption

### ISSUE THREAD

**Issue by JJF2** [WHAnonymous/Chat-API#1348]
Hi friends,
as we already know, e2e encryption become mandatory.
Who, like me, is using this terrific api on windows, now is in trouble.
Anyone has an idea on how to compile proto and curve extension for win?

Second, to the api creators:
Is there a function or can you hint a simple modification ro src to temporary allow the receipt (obviously not decrypt) of the encrypted messages?

This allow me to be aware of incoming messages and resolve the repeating stream:error.
I'm also afraid that all these unreceived messages that stuck in queue may lead to a ban.

**Comment by mgp25** [comment]
@JJF2 

I dont know how to compile it for windows, maybe somewhere there is a guide or tutorial to do it.

Check `MessageHandler.php` you can modify it and send a receipt there.

Regards

**Comment by JJF2** [comment]
I'm not familiar with php nor C but I tryed to compile extension by my self after reading some guide but with no luck at the moment.

At the best i still have over ten exception thrown by NMAKE that seems to be related to some syntax in reader.c 

Thank you for the hint, I'll try.
