### ISSUE TITLE
message not read

### ISSUE THREAD

**Issue by amrdesign** [WHAnonymous/Chat-API#1349]
hello
when i receive message i cannot mark it as read

and get this

`Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!`

thank you

**Comment by mgp25** [comment]
@amrdesign where is the debug log?

**Comment by amrdesign** [comment]
nConnect number---> XXXXXXXXXXXX
onConnect socket---> Resource id #26
tx  <stream:features></stream:features>

tx  <auth user="XXXXXXXXXXXX" mechanism="WAUTH-2">Ópü!96560400068Ôý:L‚õüë[ßðPC¦O"=51451472976</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>p.RS Å|P÷ƒhÝq\d´</challenge>

tx  <response>úlŠ(Ùh!çð‡§h‡ÉkÁâÓ…:†»ÝáJz†žŠMä@-ÎV>Æ¹ëŽð1ûÁ Ød¦TsÇÑ}°{$ö¾¾D½@µ—;‹</response>

rx  <success t="1451472977" props="4" kind="free" status="active" creation="1426006239" expiration="1457542239">l¸!…áëô•Ã¨"À¿&b°ˆ</success>

tx  <presence name="" type="available"></presence>


Warning: array_fill(): Number of elements must be positive in /home/55/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 324

Warning: array_map(): Argument #2 should be an array in /home/55/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339

Warning: implode(): Argument must be an array in /home/55/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339

Warning: array_fill(): Number of elements must be positive in /home/55/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 324

Warning: array_map(): Argument #2 should be an array in /home/55/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339

Warning: implode(): Argument must be an array in /home/55/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339
tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <stream:error>
rx    <xml-not-well-formed></xml-not-well-formed>
rx  </stream:error>

get alive----------------

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/55/public_html/55/Whats-App/src/whatsprot.class.php:292 Stack trace: #0 /home/55/public_html/whatsapp2/index.php(129): WhatsProt->pollMessage() #1 /home/cleanweb/public_html/whatsapp2/index.php(118): keppAlive() #2 /home/55/public_html/whatsapp2/index.php(44): initialzeWhatsApp() #3 {main} thrown in /home/55/public_html/whatsapp2/Whats-App/src/whatsprot.class.php on line 292

**Comment by mgp25** [comment]
@amrdesign whats your code?

**Comment by UdayCTO** [comment]
Hi, I am also getting same error, here is a log file (I set debug flag to true & from Simple CLI Client.php, redirected output to file). Thanks for your help. 
UK
[log.txt](https://github.com/WHAnonymous/Chat-API/files/74795/log.txt)

**Comment by UdayCTO** [comment]
I am using latest version from GitHub and trying Simple CLI Client.php 
Thanks

**Comment by amrdesign** [comment]
$username = "xxxxxxxxx";
		$nickname = "";
		$password = "xxxxxxxx="; // The one we got registering the number
		//$debug = true;
		// May Contest
		$customerSubscriptionCode1 = "w";
		$customerSubscriptionCode1_screen = "W";
		$customerSubscriptionCode1_ar = "و"; //iconv("cp1256" ,"utf-8", "ك");//"ظƒ";
		//// Ramadan Contest


		$w = new WhatsProt($username, $nickname, true);
		//bind event handler
		//	$w->eventManager()->bind('onGetSyncResult', 'onSyncResult');
		$w->eventManager()->bind("onGetMessage", "onGetMessage");
		$w->eventManager()->bind("onGetRequestLastSeen", "onGetRequestLastSeen");
		$w->eventManager()->bind("onConnect", "onConnect");

		$wai = new WhatsAppAI();
		initialzeWhatsApp();
		//sendMessageToContest($contestantNo);





		function initialzeWhatsApp()
		{
				global $w;
				global $password;
				echo "initialzeWhatsApp--->>>>>>>>>>>>>>>>>>>>>>" . "<br/>";

				$w->connect();
				$w->loginWithPassword($password);
				$w->pollMessage();

				keppAlive();

		}

		function keppAlive()
		{
				echo "get alive----------------<br/>";
				global $w;

				for ($i = 0; $i <= 7; $i++)
				{
						$w->pollMessage();
						sleep(3);
				}

				echo date('H:i:s');
				//die();


		}


		// prepare welcome message
		function welcomeMessage($twcode)
		{
			$welcome = " 1- تم الاشتراك بخدمة الواتس اب الإخبارية لموقع توريزمووورلد\n";
            $welcome .= " 2- هذه الخدمة للتواصل معكم بأخر المواضيع لمجلة توريزمو ماغ وأخر العروض الحصرية لموقع توريزمو وورلد (عالمك للترفيه)  \n";
            $welcome .= " 3- قم بحفظ الرقم داخل قائمة الاسماء لديك حتى تصلك الأخبار حصرية \n";
            return $welcome;
		}
		// prepare message2
		function deefualtMessage()
		{
				//global $customerSubscriptionCode1;
				global $customerSubscriptionCode1, $customerSubscriptionCode1_ar, $customerSubscriptionCode1_screen;
				//global $customerSubscriptionCode2, $customerSubscriptionCode2_ar, $customerSubscriptionCode2_screen;
				$message2 = " توريزمووورلد عالمك للترفيه\n";
                $message2 .= " نظام البيع والحجز الإلكترونى الأول من نوعه \n";
                $message2 .= " أسهل وسيلة حجز للمرافق الترفيهية والسياحية\n";
                $message2 .= " للتحميل مجاناً أضغط الرابط\n";
                $message2 .= "http://goo.gl/1UcVco"."\n";
                $message2 .= "للإشتراك بخدمة الواتس اب الاخبارية قم بارسال حرف \n";
                $message2 .= "$customerSubscriptionCode1 أو $customerSubscriptionCode1_ar";
                $message2 .= "\n-----------------------------\n";
                return $message2;
		}
		function registeredContestsMessage()
		{
				$message = "هذا الرقم مشترك فى الخدمه من قبل " . "\n";
				return $message;
		}


		/**
		 * Register this method foronGetMessage Event
		 */
		function onGetMessage($phone,
				// The user phone number including the country code.
				$from, // The sender JID.
				$msgid, // The message id.
				$type, // The message type.
				$time, // The unix time when send message notification.
				$name, // The sender name.
				$message) // The message.
		{
				echo "onGetMessage------------------->" . $phone . '<br/>';
				echo "onGetMessage------------------->" . $message . '<br/>';
				// echo
				$from = explode('@', $from);
				global $w, $wai;
				global $customerSubscriptionCode1, $customerSubscriptionCode1_ar;
			//	global $customerSubscriptionCode2, $customerSubscriptionCode2_ar;

				$w->pollMessage();
				sleep(1);
				$w->sendPresenceSubscription($from[0]);
				$w->pollMessage();
				sleep(1);
				$w->sendMessageComposing($from[0]);
				sleep(1);
				$w->pollMessage();
				$w->sendMessagePaused($from[0]);
				$w->pollMessage();

				// check if contests already registered
				$twcode = time();
				
				if ($message == $customerSubscriptionCode1_ar)
				{
						$status = $wai->insertContestIntoDB($from[0], $name, $twcode, 'news');
						if ($status)
						{
								$w->sendMessage($from[0], 'شكرا ' . $name . "\n" . welcomeMessage($twcode));
						}
						else
						{
								$w->sendMessage($from[0], 'هذا الرقم مشترك فى الخدمه من قبل');
						}
						// store contests into  tw_wasup_customers table
						//$wai->insertContestIntoDB($from[0], $name);
				}
				elseif ($message == $customerSubscriptionCode1 || strtolower($message) == $customerSubscriptionCode1)
				{
						$status = $wai->insertContestIntoDB($from[0], $name, $twcode, 'news');
						if ($status)
						{
								$w->sendMessage($from[0], 'شكرا ' . $name . "\n" . welcomeMessage($twcode));
						}
						else
						{
								$w->sendMessage($from[0], 'هذا الرقم مشترك فى الخدمه من قبل');
						}
				}
				// Ramdan Contest


				//
				else
				{
						$w->sendMessage($from[0], deefualtMessage() . "\n" . "تم ارسال الرسالة في  : " .
								date('H:i'));
				}

		}
		/**
		 * Register this method onPresenceReceived Event
		 */
		function onPresenceReceived($username, $from, $type)
		{
				$dFrom = str_replace(array("@s.whatsapp.net", "@g.us"), "", $from);
				if ($type == "available")
						echo "<$dFrom is online>\n\n";
				else
						echo "<$dFrom is offline>\n\n";
		}

		/**
		 * Register this method onGetRequestLastSeen Event
		 */
		function onGetRequestLastSeen($phone, $from, $msgid, $sec)
		{

				echo '<br/>';
				echo "onGetRequestLastSeen-->" . $sec;
				echo '<br/>';

		}
		/**
		 * Register this method onConnect Event
		 */
		function onConnect($mynumber, $socket)
		{
				echo "onConnect number---> " . $mynumber . "<br/>";
				echo "onConnect socket---> " . $socket . "<br/>";

		}

**Comment by jonofe** [comment]
Same problem for me. 
Seems, that the messages received from WA servers are not decrypted correctly.
They are not ACKed, i.e. no second arrow appears in the adroid client.
It worked at least until yesterday evening. And this morning I experienced this error. I was using it already for several weeks without a problem.

Here is my test code:

#!/opt/php5/bin/php
<?php
require_once __DIR__ . '/../config/config_eib.php';
require_once __DIR__ . '/vendor/autoload.php';
require_once 'vendor/whatsapp/chat-api/src/events/MyEvents.php';

date_default_timezone_set("Europe/Berlin");

$username = '#############';
$password = '############################';
$nickname = "Home";    // Your nickname, it will appear in push notifications
$debug    = true;  // Shows debug log, this is set to false if not specified

$contacts = array();
foreach ($whatsapp_contact as $name => $number)
{
	$contacts[]=$number;
}

// Create a instance of WhatsProt class.
$w = new WhatsProt($username, $nickname, $debug, $log);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents); //You can also pass in your own array with a list of events to listen too instead.
$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!
$w->sendGetPrivacyBlockedList(); 

$message = "Hallo world";
$w->sendMessageComposing('#############'); // Send composing
$w->sendMessagePaused('#############'); // Send paused
$w->sendMessage('#############', $message);
while ( true )
{
	$w->pollMessage();
	if (time()%60 == 0) $w->sendPing();
	sleep(1);
}

function received_whatsapp_message($mynumber, $from, $id, $type, $time, $name, $body)
{
	global $whatsapp_commands, $whatsapp_contact,$eib_msg_queue;
	echo "Received Whatsapp Message\nMy Numer: $mynumber\nFrom: $from\nID: $id\nType: $type\nTime: $time\nName: $name\nBody: $body\n\n";

}

?>

**Comment by breakerh** [comment]
@amrdesign  where is your sendPing()?
Because i think that's the bottleneck. The connection closes because you don't show you're alive.
Only pollMessage() didn't do it for me.

**Comment by amrdesign** [comment]
@breakerh where i have to send ping ??

**Comment by breakerh** [comment]
here a simplified version of my script:
```
while($w->pollMessage());
	$w->sendPing();
	$x=10;
	$z = 1;
	while (1) {

		if($z>$x){
			$w->sendPing();
			$z=1;
		}
		$z++;

		$sending = $db->get_record_by_search('****',array(
			'tome'=>0,
			'isnew'=>1
		));

		foreach($sending as $s){

			$c = $db->get_record_by_ID('WA_contacts','id',$s['contact']);

			if($s['type']==1){
				$w->sendMessage($c['number'], $s['message']);
			}else if($s['type']==2){
				$w->sendMessageImage($c['number'], $s['filename']);
			}else if($s['type']==3){
				$w->sendMessageVideo($c['number'],$s['filename']);
			}
		}
		$w->pollMessage();
		$msgs = $w->getMessages();
		foreach ($msgs as $m) {

			if ($m->getAttribute("type") == 'text')
			{
                            //do something
			}

		}

	}

```

**Comment by jonofe** [comment]
The ping() is not the problem. I send a ping and have the same error. It occurs after some time and especially, when you send a message from your phone to your API client. And I do not get the unencrypted message on an onGetMessage event.

**Comment by breakerh** [comment]
You have to get the node and get the decrypted message from there.
(with get getMessages() this is doable)

And oke no ping problem.. Hmm which version do you guys run?

**Comment by jonofe** [comment]
I just saw the getMessages() in your code. I do it only via pollMesage() and in the MyEvents.php I have a function like this:

public function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
{
	    echo "\nMessage from $name:\n$body\n";
	    received_whatsapp_message($mynumber, $from, $id, $type, $time, $name, $body);
}

and the event "onGetMessage" is uncommented in MyEvents.php.
Thought I saw it in that way in the documentation.

I just added the getMessages() into my code, but nothing happens. Do I have to do changes to the MyEvents.php or anywhere else?

**Comment by amrdesign** [comment]
i think the connection is closing 
============================================
tx  <stream:features></stream:features>

tx  <auth user="XXXX" mechanism="WAUTH-2">/ó˜R96560400068c«ÇS¦Ðd0{³‘?ÇþBK‰j|ú1451478616</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>O=såâ¨àYŠ­ x:ÉBN}ë</challenge>

tx  <response>ójÁG.°÷.óÐgzý¬¹í`Li}q%›b„tuê5µ³v»¿…ÜÞÉœ: †âñ¡AkÁ–xÔ^( ÿYùÒ$R9È…zm‹ˆÇŒ™R</response>

rx  <success t="1451478617" props="4" kind="free" status="active" creation="1426006239" expiration="1457542239">OŒ\ž_>ÍµËf/—Îfë³•Å</success>

tx  <presence name="" type="available"></presence>


Warning: array_fill(): Number of elements must be positive in /home/cleanweb/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 324

Warning: array_map(): Argument #2 should be an array in /home/cleanweb/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339

Warning: implode(): Argument must be an array in /home/cleanweb/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339

Warning: array_fill(): Number of elements must be positive in /home/cleanweb/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 324

Warning: array_map(): Argument #2 should be an array in /home/cleanweb/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339

Warning: implode(): Argument must be an array in /home/cleanweb/public_html/whatsapp2/Whats-App/src/BinTreeNodeWriter.php on line 339
tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <stream:error>
rx    <xml-not-well-formed></xml-not-well-formed>
rx  </stream:error>


Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /home/cleanweb/public_html/whatsapp2/Whats-App/src/whatsprot.class.php:292 Stack trace: #0 /home/cleanweb/public_html/whatsapp2/t2.php(25): WhatsProt->pollMessage() #1 {main} thrown in /home/cleanweb/public_html/whatsapp2/Whats-App/src/whatsprot.class.php on line 292

**Comment by jonofe** [comment]
@amrdesign: yes, the question is why. I suppose, it's because the messages you send from your phone are not acknowledged. With getMessages() sometimes I can see, that something is received, but still encrypted. I can't see the message body... Do I need to call $w->getAttribute('something') to get the message?

**Comment by breakerh** [comment]
@jonofe  find composer.json.. There should be the version:
```
{
    ....
    "name": "whatsapp/chat-api",
    "version": "2.5.2",
    "description": "The PHP WhatsApp library",
    ....
}
```
And i didn't bind the ongetmessages.
i just used this:
```
$msgs = $w->getMessages();
		foreach ($msgs as $m) {
```

So images are stored in a que and everytime i call getmessages it return the que and clears it. :)

**Comment by jonofe** [comment]
okay, version found: v2.5.5.4
I implemented it according to the Documentation on:
https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation (see section "RECEIVING MESSAGES" on that page)

Where did you find the documentation on this getMessages() method? Nevertheless it does not work for me at this moment. :(

**Comment by breakerh** [comment]
in examples/Simple CLI Client.php

**Comment by Anderuimm** [comment]
I noticed now that there are some tools required for full operation (Protobuf and curve25519) but I have no idea how to implement them in my Ubuntu-Apache server.

Can someone give me a "how to update it correctly for dummyes"?

It fixes the "not read messages" issue too?

**Comment by jonofe** [comment]
okay, problem finally solved.

Was a good hint regarding the two modules protobuf and curve25519. 
I had already compiled and installed them, since I started using this API, but now I had to realize, that they were not activated in php.ini. And maybe WA switched something last night, that I really need these two modules. ;) After adding the two lines 

extension=protobuf.so
extension=curve25519.so

it works like a charme.

**Comment by jonofe** [comment]
@Anderuimm:

Download and compile the two modules as mentioned in the docs.
Add the two entries to the php.ini. restart apache, then it should work.

**Comment by breakerh** [comment]
@jonofe  indeed they enforced end to end encryption. But i didn't think that was the problem. After all it was. Thank you for making that clear :)

Have a great day!

**Comment by Anderuimm** [comment]
@jonofre thanks for the advice, but as I say I need a "how to for dummies" because I don't have any idea how to do it.

Questions about the extensions:
Is i use a precompilled .so files it will work? 
   If yes, can you attach it here?
   If not, need I to compile it directly on my Apache server?
     If yes, how to do it?

**Comment by breakerh** [comment]
@Anderuimm  here is a simple example with memcache
http://www.script-home.com/php-tutorial-phpize-using-method.html

Download the module.
Extract it
go into the directory (using ssh)
the do the following commands
phpize
./configure
make
make install

If you setup your php correctly this will work.

**Comment by Anderuimm** [comment]
@breakerh TYVM, I'll try it.

**Comment by jonofe** [comment]
thanks to all for the discussion which solved the problem very quickly.
@Anderuimm: if you still have questions, son't hesitate to ask. ;-)
Wish you a happy new year 2016 ...

**Comment by rialsoft** [comment]
hello @jonofe i was try to compile https://github.com/allegro/php-protobuf but i get error message 'requires protobuf extension installed to run', then i try to install php-protocolbufffer from https://github.com/chobie/php-protocolbuffers and add extension=protocolbuffers.so in php.ini, but i getting same error :'(. 
how to install protobuf extension?

**Comment by alesantosp** [comment]
@rialsoft you need to install protobuf first from https://github.com/google/protobuf/
basically you what you need to do is:
autogen.sh
configure
make
make install

**Comment by jonofe** [comment]
I followed the docs of Whatsapp API here

https://github.com/WHAnonymous/Chat-API/wiki/Dependencies

download, extract and then:

phpize
./configure
make
sudo make install

And as I found out today, I had to add the two lines to my php.ini as mentioned above.
Hope that helps ...
