### ISSUE TITLE
I am receiving an encrypted when used pollMessage

### ISSUE THREAD

**Issue by jaylabade** [WHAnonymous/Chat-API#1350]
Hi,

I want to receive whatsapp messages and store them in database or text file separated by fields.
But when used pollMessage with debugging set true, I received encrypted message with tag <enc v="2" type="pkmsg">.

Can you please check this and suggest possible solution.

**Comment by mgp25** [comment]
@jaylabade install dependencies, check closed issues before opening new ones, and remember there is a wiki with documentation too.

You need to install dependencies.

Regards
