### ISSUE TITLE
onGetProfilePicture image also encrypted

### ISSUE THREAD

**Issue by breakerh** [WHAnonymous/Chat-API#1351]
Due to recent changes on end to end encryption some things changed offcourse.
I managed to fix images and other media and everything works as it should.

The only problem i have is that profile pictures are not decrypted..
I was looking into the decryption but as far as i can see you need vars you don't have with the profile picture right?

Could someone kick/point/guide me in the right direction or provide a working code for it?

If i happen to find a solution i will also put it here :)

Thanks in advance!

**Comment by PunitSaharan** [comment]
hi we have an issue in new update

Logged in user frequently going online offline. We are receving this problem form last 2-3 days when we send Message to user its going online offline. Before this update it was working fine.Please tell me any solution.

Thanks

**Comment by breakerh** [comment]
I do not experience this problem. So i think that it has to do with your own code.
We do not show the online status on our frontend. But in the backend it's all working fine.

**Comment by PunitSaharan** [comment]
we just dowanlod the new zip file of chat API. Don't make any changes but its giving this problem.
