### ISSUE TITLE
Logged in user frequently going online offline when trying to send message

### ISSUE THREAD

**Issue by PunitSaharan** [WHAnonymous/Chat-API#1352]
hi we have an issue in new update

Logged in user frequently going online offline. We are receving this problem form last 2-3  days when we send Message to user its going online offline. Before this update it was working fine.Please tell me any solution.

Thanks

**Comment by FrancYescO** [comment]
Something changed in WhatsApp protocol, my responder that was working well from months (witouth any ChatApi update) today just keeps crashing when receive a message

**Comment by breakerh** [comment]
@FrancYescO read #1333 ...
You have to install 2 library's for it..

**Comment by PunitSaharan** [comment]
Please mention wich 2 library's  we should install to fix this problem. thanks

**Comment by breakerh** [comment]
Seriously.. Do you guys even read? (not being mean.. Just perplex.. haha)

On the homepage:
**Requires:** PHP Protobuf and Curve25519 to enable end to end encryption

**Comment by PunitSaharan** [comment]
it says optional there... that meant its not necessary.

**Comment by FrancYescO** [comment]
@PunitSaharan if you read, from yesterday necessary. going to install ... thanks @breakerh

**Comment by breakerh** [comment]
@FrancYescO  You are most welcome :)

**Comment by PunitSaharan** [comment]
@breakerh  Many Thanks :+1:

**Comment by PunitSaharan** [comment]
@breakerh  @FrancYescO  M not able to install these  library's on xamp (window) . I know its very baisc but m not able. please help me.Thanks

**Comment by FrancYescO** [comment]
@PunitSaharan idk how to help you, try to ask in respective repository. i'm using it on unix and got no issue to compile and install library on mine raspberry.

but now i stuck in the same issue, probably i need some e2e "inizialization" to get ChatApi working again... just searching around...

**Comment by breakerh** [comment]
I have no idea how to compile them to dll extensions.. i think your only option is google or stackoverflow..

**Comment by PunitSaharan** [comment]
@breakerh  you are not using window?

**Comment by FrancYescO** [comment]
My responder script is from the base of exampleFunctional.php now i installed the e2e library and my script is not crashing anymore, also it mark as read messages with pollMessage(); but not process it... turning debug on seems to correctly decrypt the message, but i cannot process it like in the example script something probably need to be changed to get the decrypted message.

someone can at least confim me that exampleFunctional.php is still a good example?
