### ISSUE TITLE
Connection is closed after a minute.

### ISSUE THREAD

**Issue by mylogin** [WHAnonymous/Chat-API#1353]
a few days ago it worked, but now my script and example scripts crashes. According to my observations, the connection is dropped exactly one minute of work.

Script: Chat-API-master\tests\whatsapp.php
Log:
[] Logging in as 'Acc1' (11111111111)
tx  `<stream:features>``</stream:features>`

tx  `<auth user="11111111111" mechanism="WAUTH-2">``</auth>`

rx  `<from s.whatsapp.net="">``</from>`

rx  `<stream:features>``</stream:features>`

rx  `<challenge>``</challenge>`

tx  `<response>``</response>`

rx  `<success t="..." props="4" kind="free" status="active" creation="..." expiration="...">``</success>`

tx  `<presence name="Acc1" type="available">``</presence>`

tx  `<iq id="01" xmlns="jabber:iq:privacy" type="get">`
tx    `<query>`
tx      `<list name="default">``</list>`
tx    `</query>`
tx  `</iq>`

tx  `<iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">`
tx    `<config>``</config>`
tx  `</iq>`

[] Listen mode:
rx  `<message from="22222222222@s.whatsapp.net" type="text" id="..." offline="3" t="..." notify="Acc2">`
rx    `<enc v="1" type="pkmsg">``</enc>`
rx  `</message>`

Array
(
    ...
)
rx  `<message from="22222222222@s.whatsapp.net" type="text" id="..." offline="3" t="..." notify="Acc2">`
rx    `<enc v="2" type="pkmsg">``</enc>`
rx  `</message>`

Array
(
   ...
)
rx  `<ib from="s.whatsapp.net">`
rx    `<offline count="2">``</offline>`
rx  `</ib>`

rx  `<presence from="11111111111@s.whatsapp.net">``</presence>`

rx  `<iq from="11111111111@s.whatsapp.net" type="error" id="1">`
rx    `<error code="404" text="item-not-found">``</error>`
rx  `</iq>`

rx  `<iq from="s.whatsapp.net" type="error" id="02">`
rx    `<error code="404" text="item-not-found">``</error>`
rx  `</iq>`

rx  `<stream:error>`
rx    `<ack id="...">``</ack>`
rx  `</stream:error>`

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in D:\www\Chat-API-master\src\whatsprot.class.php:292
Stack trace:
#0 D:\www\Chat-API-master\tests\whatsapp.php(81): WhatsProt->`pollMessage()
#1 {main}
  thrown in D:\www\Chat-API-master\src\whatsprot.class.php on line 292

**Comment by PunitSaharan** [comment]
hi we have an issue in new update

Logged in user frequently going online offline. We are receving this problem form last 2-3 days when we send Message to user its going online offline. Before this update it was working fine.Please tell me any solution.

Thanks

**Comment by breakerh** [comment]
@mylogin include the 2 modules that can be found in the readme file (protobuff and curve).
That should eliminate the problem.

**Comment by AzizYosofi** [comment]
@breakerh How to include these modules ?
they didn't loaded automatically !

**Comment by mgp25** [comment]
Documentation in the wiki: https://github.com/WHAnonymous/Chat-API/wiki
