### ISSUE TITLE
New mesage not read and not showing

### ISSUE THREAD

**Issue by cainerland** [WHAnonymous/Chat-API#1354]
for the first synced contact message is recieved ok , but for a new conact , its not delivering

**Comment by breakerh** [comment]
Do you get an error in your script?
Does the sender get 2 checks? do they get blue?

More info please

**Comment by estcap** [comment]
@cainerland Plase post log and code

**Comment by AzizYosofi** [comment]
I have the same problem , Chat-API can recieve image and voice messages but for txt messages not 
even no deliver notification
