### ISSUE TITLE
Log class redeclare

### ISSUE THREAD

**Issue by tim-hanssen** [WHAnonymous/Chat-API#1355]
Hej All,

After getting to work with Encryption, i got this error loading the class:

PHP Fatal error: Cannot redeclare class Log in /data/www/chat-api/src/libaxolotl-php/logging/Log.php on line 4

Any suggetions?

**Comment by breakerh** [comment]
Do you have any code?
Because looks like you loaded the file twice or you have a collision on 2 separate classes.

**Comment by tim-hanssen** [comment]
I didnt change anything on the chat-api code. I looked at the composer auto-load file, but I can only find this file listed as Log class.

**Comment by dishark** [comment]
The obvious suggestion here would be to rename/namespace your Log class.

**Comment by tim-hanssen** [comment]
Ins't is strange that the ;baxolotl-php by default isn't namespaced?

**Comment by tim-hanssen** [comment]
Adding namespace AxolotlLogger; in the top of the Log.php file, and adding a / before the extended AxolotlLogger fixes it.
