### ISSUE TITLE
decryption malfunctions regarding profile pictures & profile photo's

### ISSUE THREAD

**Issue by breakerh** [WHAnonymous/Chat-API#1362]
I have experienced that sometimes images can't be decrypted..
(i updated the code to the new, including the decryption bug fix).

So profile pictures show up like this (http://showoffimports.nl/sandbox/whatsapp/pictures/31613923396@s.whatsapp.net.jpg)
And thumbnail images work, but the full images not (i know #1337 )

Here the error

-> Decrypted Message: Incomplete message. - /xxxxx/whatsapp/Chat-API-master/src/libaxolotl-php/protocol/WhisperMessage.php - 76Message 81917094D2FE5281F0F could not be decrypted, sending retry.

It only occurs on some cases..When the image is pushed through whatsapp and the 'new' file is send again it does work.. weird..

**Comment by breakerh** [comment]
#1359 fixes this issue! But without changing core files you will have to work with nodes instead of the event handlers..

**Comment by mgp25** [comment]
@breakerh use `onGetImage` event `$file` var to get the image data

Regards

**Comment by breakerh** [comment]
Oke thanks, i allready changed everything to the node way :P
Have to say, you get a lot more data. so i actually like it more haha,

But thanks :)

**Comment by gaurav-stepin** [comment]
Hello Mate 
I have same issue as you have face already 

I use whatsapp chat api 
examples/exampleFunctional.php
 
But i get the corrupted image please help me if you have solution mate.
