### ISSUE TITLE
: socket_connect(): unable to connect [110]: Connection timed out in 

### ISSUE THREAD

**Issue by yairnet** [WHAnonymous/Chat-API#1364]
PHP Warning:  socket_connect(): unable to connect [110]: Connection timed out in /home/bot/vendor/whatsapp/chat-api/src/whatsprot.class.php on line 169

i have more bots runs but if i close and try new connect have this error
i try more server i think its global problem?

**Comment by yairnet** [comment]
This failure on servers Whatsap ..

**Comment by p031985s** [comment]
Hi there...

Whats APP is offline in all over the world.

**Comment by yairnet** [comment]
It looks like a DDOS attack on server connect
It works intermittently
