### ISSUE TITLE
Keep alive

### ISSUE THREAD

**Issue by AnanasPie** [WHAnonymous/Chat-API#1367]
Hi all,

I know that a lot of people have asked how to keep the bot online. But i have a special problem.
I ping the server every 100 to 300 sec. Nevertheless after some hours i can see in the whtasapp that my bot is ofline, but the sockets to the server is open and works good.

Anyone have any suggestions how to stay online ??

**Comment by mgp25** [comment]
@AnanasPie you dont need to send ping, API does that automatically. You need to check the debug log and solve that, the socket we use in the API doesnt detect when the stream has ended or connection is lost, you need to code your own solution by now.

Regards
