### ISSUE TITLE
Enc v2 for iOS devices

### ISSUE THREAD

**Issue by kacipbuah** [WHAnonymous/Chat-API#1368]
Hello guys i'm getting this error while trying to receive messages from an IOS device.
I'm running the 3.0 version of the Chat-API.
Incoming messages are encrypted.
The messages do not arrive and it gives me an error as below:

```xml
rx  <message from="60129******@s.whatsapp.net" type="text" id="A593113E3AA53E75AC1" t="1451681136" notify="Izwan Che Soh">
rx    <enc v="2" type="pkmsg">3!▒ؿ▒▒P▒▒3▒RvՕ▒4q`▒F▒To}▒▒▒▒▒▒3!▒▒▒▒▒▒{~i\ӄ▒▒<▒ ▒n▒`▒M;K"U▒
*"B3
!E▒\S"7▒Ç▒▒[▒k8▒}B/▒▒▒ N"▒4z0▒▒ļ▒[▒p▒N▒&D▒远▒(▒0×▒</enc>
rx  </message>
```

**Comment by mrjoebudi** [comment]
plz try read first other issues, get the same problem, try this link... okay ..!!!
https://github.com/WHAnonymous/Chat-API/issues/1343
