### ISSUE TITLE
Got banned after requesting last seen.

### ISSUE THREAD

**Issue by awpsniper** [WHAnonymous/Chat-API#1371]
Hello,

My number got banned after I used requesting last seen. I've been using new code for my custom WA Client  since 3 days. It worked fine for 3 days but today suddenly it got banned.

Here is the code :
```
//Basic login code...
// I have total 5k+ contacts so syncing before requesting last seen.
$w->sendSync($arr_numbers);
while(1)
{

 	 $w->pollMessage();
//getting all number one by 1 and sending sendPresenceSubscription
  for($i=0;$i<$count_arr;$i++)
  {
    $w->sendPresenceSubscription($arr_numbers[$i]);
  }

  $w->pollMessage();

  sleep(5);
}

$w->disconnect();
```

Shoot me if I have done wrong something wrong.

**Comment by wragnar** [comment]
the send presence is inside the while(1) so you are constantly sending presencr suscription

**Comment by awpsniper** [comment]
Look at sleep(5);

**Comment by mgp25** [comment]
@awpsniper you are checking as you have said 5k contacts, are you are sending presence to all of them, thats why, a loop with always 5 seconds, this flow isnt like an app should be and very extrange behaviour. So what i have told you is completly wrong, you need to do it like an human would do.

Regards
