### ISSUE TITLE
Serialization of 'Closure' is not allowed

### ISSUE THREAD

**Issue by rahul3883** [WHAnonymous/Chat-API#1372]
i am getting this error : Serialization of 'Closure' is not allowed

i have different parts of code in different functions

eg.

function initialize($username, $password, $nickname){
session_start();
date_default_timezone_set('Asia/Kolkata');
$debug = false;
require '/src/whatsprot.class.php';
require '/src/events/MyEvents.php';
$_SESSION['w'] = new WhatsProt($username, $nickname, $debug);
}

likewise, i have other functions to bind events to event manager, to connect and login, to send message, disconnect, etc.

and then i am calling them in series like
function send_message(){
$this->initialize($username, $password, $nickname);
$this->bind_events();
$this->login($password);
$this->send($target, $msg);
$this->disconnect();
}

this error comes but everything seems working fine.

what this error says? and how to solve it?

**Comment by 0xTryCatch** [comment]
You can't serialize WhatsProt, use a different approach
