### ISSUE TITLE
Set client-type to Windows Phone?

### ISSUE THREAD

**Issue by dennobaby** [WHAnonymous/Chat-API#1373]
Hi,

is it possible to set the client type to Windows 10? My research shows, that for the moment windows 10 client doesnt use Encryption, so this could be a temporary workaround for users without ability to use encryption.

**Comment by mgp25** [comment]
You can, but i don't recommend it

Regards

**Comment by dennobaby** [comment]
Would maybe someone explain how to do this / how to get the needed information for constants.php? I would like to test this...
