### ISSUE TITLE
How to know if user changed status?

### ISSUE THREAD

**Issue by rahul3883** [WHAnonymous/Chat-API#1374]
should i use <code>sendGetStatuses($numbers)</code> every time i log in or there is a way to know if <b>user changed his/her status</b>?

**Comment by mgp25** [comment]
@rahul3883 you will receive a `notification` node, that will tell you if the status has changed

Regards

**Comment by rahul3883** [comment]
@mgp25 is there any event for that? like for profile picture, <code>onProfilePictureChanged</code>
