### ISSUE TITLE
Question about presence subscription

### ISSUE THREAD

**Issue by yoni1306** [WHAnonymous/Chat-API#1379]
Hey guys,
In the following section in the wiki (https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#presence-subscriptionunsubscription) it is written "There is no limit of how many users you can track with presence subscription." and I have a question about that statement - 
1. Does parallel presence subscriptions for multiple numbers using single channel works? My guess is that WA won't allow it because it's an action that a normal user can't do.
2. If it does work, what is the max subscriptions limit per channel?

Thanks in advance.

**Comment by mgp25** [comment]
@yoni1306 

I dont understand 1), if you mean if you can send presence subscription to more than one contact, yes.
2) i dont know and i dont want to know it

If you try to monitorize or similar, you number will be blocked, use it only for personal usage

Regards

**Comment by yoni1306** [comment]
I meant if is it possible to send presence subscription to "X" contacts (each one in a different process on my PC) from my number, at the same time like in parallel.

**Comment by estcap** [comment]
@yoni1306 you mean several scripts connected at the same time with the same number? Everything should be done sequentialy with only one instance of this API running at the time. If not, you would be risking appearing as several phones with same number. You can send presence subscription to X number of contacts sequentially.

**Comment by yoni1306** [comment]
@estcap alright, and with several scripts where each script uses a different number for subscriptions? Does whatsapp check if there's more than one referrer from the same IP?

**Comment by estcap** [comment]
@yoni1306 If I inderstand you correctly, you are asking if several scripts, with different numbers, can run under the same IP. If that is your question, then the answer is yes (You can arrive to this conclussion thinking of several mobile phones connected through the samw WIFI signal in a pub using Whatsapp.)
All of this is considering that you wrote the scripts taking into account good behaviour, and do not SPAM or violate Whatsapp's EULA. Take in mind that of course Whatsapp has the right to ban your IP if detects massive bad behaviour though.

**Comment by yonikix** [comment]
Well said @estcap, that's exactly what I thought but I still wanted a validation so thanks for that.
Of course it has to be well managed in order to stay under the radar.
