### ISSUE TITLE
sendPresenceSubscription doesnt work

### ISSUE THREAD

**Issue by JohnJexon** [WHAnonymous/Chat-API#1380]
Hello,

I have migrated to the latest code. Installed all the extension as you said that those are not optional anymore. This code is working in older code but not working in newer code. Here is the code I'm using.

```php
//Login in user and bind event
function onPresenceAvailable($username, $from)
{
   echo "<$dFrom is online>\n\n";
}
$wa->sendSync($contacts);
while(1)
{
  foreach($numbers as $number)
  {
      $wa->sendPresenceSubscription($number);
  }

  sleep(360);
}
$wa->disconnect();
```

Debug log : 

-> It sucks on this for each and every contact I dont know why even that contact is online.
```xml
 <presence type="subscribe" to="HIDDEN@s.whatsapp.net"></presence>
```
->For 1-2 contacts it sucks on this :
```xml
<presence from="HIDDEN@s.whatsapp.net" type="unavailable" last="deny"></presence>
```
Conclusion is it doesn't detect weather user is online. This code is working fine on older version of code.

Thank You!

**Comment by mgp25** [comment]
@JohnJexon you need to `pollMessage()`

for example... 

```php
  foreach($numbers as $number)
  {
      $wa->sendPresenceSubscription($number);
      $wa->pollMessage();
  }
```

**Comment by JohnJexon** [comment]
@mgp25 : Thank you sir. It is necessary to send ```$w->sendPresenceUnsubscription($to)``` before ```$wa->sendPresenceSubscription($to);``` ?

**Comment by JohnJexon** [comment]
@mgp25  : Still same problem stuck on the same problem. Using latest code. It works for like 1-2 hour but then it doesn't work.

```
 <presence type="subscribe" to="HIDDEN@s.whatsapp.net"></presence>
```
