### ISSUE TITLE
Double messages send

### ISSUE THREAD

**Issue by WalterM404** [WHAnonymous/Chat-API#1381]
Guys,

Sometimes - i don't see a pattern - is the message from the API to the phone double send. The phone user gets then 2 times the message: "Hello, how are you" for example, but that message is just one time send. In de database, is it also standing two times.. It happens on both iOS and Android.

Any idea?

**Comment by mgp25** [comment]
@WalterM404 send your code and debug log, if you dont post that, this issue is invalid and will be closed

**Comment by josiahking** [comment]
You should check your code for string concatination and also loop before send.

**Comment by rogobob** [comment]
@WalterM404 see this issue: #1194
