### ISSUE TITLE
Messages receiving encrypted in newest release

### ISSUE THREAD

**Issue by archonkulis** [WHAnonymous/Chat-API#1384]
Hi,

Can't figure out, why messages are received encrypted -> http://prntscr.com/9lvn73

I checked other issue, where you said, you have fixed it in latest release, but I already have installed your latest release.

Do I have something missing here? Maybe WhatsApp updated their API? What else information you need from me?

**Comment by mgp25** [comment]
@archonkulis thats because you haven't read the readme or even the wiki! Please, read everything before posting a new issue!

You need to install 2 extensions: https://github.com/WHAnonymous/Chat-API/wiki/Dependencies
`Curve25519` and `protobuf`

**Comment by mrjoebudi** [comment]
How compile extention on windows here try this link, 
http://blog.benoitblanchon.fr/build-php-extension-on-windows/
