### ISSUE TITLE
Question: Is current current app supporting WA 1.6 stable?

### ISSUE THREAD

**Issue by rogobob** [WHAnonymous/Chat-API#1385]
Hello guys,

I see there are a lot of changes recently regarding WA 1.6. Is this new release stable and finished or is it better to use a previous version for now?

I've got a small suggestion if you have time to do so:
Whenever applicable after a major update mention changes in the code that might affect the way users use the application. For example, the 1.6 release changes the doLogin function to internally also call sendGetPrivacyBlockedList() and sendGetClientConfig(), so people who manually made these calls before should not do that now (as I see).

Awesome work, you don't stop working even on holidays :)

**Comment by mgp25** [comment]
@rogobob Yes, this new version which uses WA 1.6 protocol is stable and finished, and it's recommended.

Keep in mind that this will require the installation of two extensions: 

- [PHP Protobuf](https://github.com/allegro/php-protobuf)
- [Curve25519 PHP](https://github.com/mgp25/curve25519-php)

If you have already installed these extensions, you can use the latest versions without any problem.

That's right, WhatsApp always call `sendGetPrivacyBlockedList()` and `sendGetClientConfig()` when logging in, so we made it by default, so users that did this manually can remove it.

Regards

**Comment by rogobob** [comment]
@mgp25 Thank you.

I also noticed waitForServer() calls are removed from many functions like sendGetStatuses() and sendGetProfilePicture(). Does it mean I should call waitForServer() myself or it should not be called at all?

**Comment by mgp25** [comment]
@rogobob nop, you dont need to call that function. `waitForServer` waits for server response to continue, but most of the requests doesnt require to wait, so in the ones that are not required we have removed them, and makes the API way faster as it doesnt has to wait
