### ISSUE TITLE
Question: onGetImage() and onGetAudio() correct flow

### ISSUE THREAD

**Issue by estcap** [WHAnonymous/Chat-API#1387]
In my closed issue https://github.com/WHAnonymous/Chat-API/issues/1337 , I can read

> Thanks for your update. So in my understanding $file will sometimes contain the file name (oibasd.jpg) and sometimes the decrypted image content in-case the message is encrypted?

to what @mgp25 responds with an overwhelming 
> yup

This statement confused me a bit. So far I tested and ```$file``` from ```onGetImage()``` contains raw image data every time.
Is it the same with ```onGetAudio()``` and its ```$file``` contains the raw Audio file? Is there any case in which ```$file``` does NOT contain image data and I should use the old $url to get the image? Is there any API method to check this to cover all possible cases?

Thanks, once more, for your amazing job with this API.

Regards,

**Comment by mgp25** [comment]
@estcap i hven't tested with audio files or videos, i haven't changed the events related to it too, so it remains as always, only image has changed at least in the API

Regards
