### ISSUE TITLE
Error: Sending message

### ISSUE THREAD

**Issue by ratasxy** [WHAnonymous/Chat-API#1394]
Hi,

I can read correctly the messages (protobuf and curve) but when sending messages get:

```xml
rx  <receipt from="xxxxxx@s.whatsapp.net" type="error" id="4660201353f54d2576cc21" t="1451953413">
rx    <error type="enc-v1"></error>
rx  </receipt>
```

**Comment by Jonathan313** [comment]
Working fine here. Make sure you read wiki carefully and use code accordingly.

**Comment by cmtyu** [comment]
@ratasky could you share me how to install protobuf and curve please ? I still unable to solve encrypted messages..tks a lot my friend

**Comment by rogobob** [comment]
@ratasxy I have the same issue. If I force plaintext like mentioned here: #1343 it works, but this is not a permanent solution. I also tried to delete the axolotl database file, and it started working for one message. The second message did not get sent again

**Comment by feltkamptv** [comment]
Suddenly I have the same issue with iOS devices, Android seems to work fine.
```
rx  <receipt from="31622916894@s.whatsapp.net" type="error" id="ae1aa73ff3c15dc7239344" t="1452094090">
rx    <error type="enc-v1"></error>
rx  </receipt>

tx  <ack to="31622916894@s.whatsapp.net" class="receipt" id="ae1aa73ff3c15dc7239344" type="error"></ack>
```

**Comment by mgp25** [comment]
Fixed: https://github.com/WHAnonymous/Chat-API/commit/55e6b37685df52d60370f1a440fd97645d773379

**Comment by feltkamptv** [comment]
@mgp25 Nice job, thanks!
