### ISSUE TITLE
ProccessNode never gets called by pollMessage

### ISSUE THREAD

**Issue by PedroGabriel** [WHAnonymous/Chat-API#1395]
Hello,
I'm a old user and it always worked.
Using PHP 5.6 running via CLI
Just downloaded newest version from composer

made a short version of my code for testing, look at this:
```php
<?php
set_time_limit(0);
require_once 'src/whatsprot.class.php';
require_once 'src/events/MyEvents.php';

$user = array(
    'username'=>'5511952******',
    'password'=>'***',
    'nickname'=>'jbot'
);
$debug = false;

echo "Logging in as '{$user['nickname']}' ({$user['username']})\n";
$w = new WhatsProt($user['username'], $user['nickname'], $debug);
$w->connect();
$w->loginWithPassword($user['password']);
echo "Connected!\n\n";

$pn = new ProcessNode($w);
$w->setNewMessageBind($pn);

while(1){
    $w->pollMessage();
}

class ProcessNode
{
    protected $wp = false;
    public function __construct($wp){
        $this->wp = $wp;
        echo "Constructor\n";
    }
    public function process($node){
        echo "Process\n";
    }
}
?>
```

Constructor gets called, message gets received and read but "Process" never got called.

Even with `examples/exampleFunctional.php` it worked.

When I set it to use `$w->eventManager()->bind` at `onGetMessage` to get new messages it works, but there's no `$node` and I need it :'(

I don't see a reason to be not working.

Any clue? Thanks.

My PHP extension list is:
```
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
curve25519
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
protobuf
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

Thanks!

## UPDATE
Just noticed that if I change my loop to:
```
while(1){
    $w->pollMessage();
    $msgs = $w->getMessages();
    foreach($msgs as $m)
        $pn->process($m);
}
```

it works like before (node into the function directly)

There's  anything I'm doing wrong? this is the new away of doing this? Thanks once again.

**Comment by PedroGabriel** [comment]
Also: Camera photos take on the fly are not getting decrypted? (it's the only encrypted media I think)

**Comment by mgp25** [comment]
@PedroGabriel yes, its like you have said: 

```php
while(1true){
    $w->pollMessage();
    $msgs = $w->getMessages();
    foreach($msgs as $m)
        $pn->process($m);
}
```

What do you mean by `Also: Camera photos take on the fly are not getting decrypted? (it's the only encrypted media I think)`

**Comment by PedroGabriel** [comment]
When you open your camera and take a picture (via whatsapp camera), it comes as a .enc type and I can't find any away to get the decrypted image.

Just uploading any image works because it is not encrypted.
