### ISSUE TITLE
Is this approach reliable way to check online statuses of 100+ person?

### ISSUE THREAD

**Issue by Rexota** [WHAnonymous/Chat-API#1398]
I'll check 100+ phones online&offline statuses with this approach. Is this a good way or WA will detect this unusual?

Thank you.

    while(true) {
        $phones = get_phones();
	    $wa->pollMessage();

	    for($i=0; $i < count($phones); $i++) {
		   $phone = $phones[$i];
		   $wa->sendPresenceSubscription($phone);
               //I set random wait for every user, is this necessary?
		  sleep(rand(1,4));
	    }

  	    $wa->pollMessage();
        //random wait for next check
        sleep(rand(5, 9));
    }

**Comment by mgp25** [comment]
You can try it, but i only recommend use this API for personal usage

**Comment by Rexota** [comment]
Thanks.
