### ISSUE TITLE
unauthorized ban

### ISSUE THREAD

**Issue by AnanasPie** [WHAnonymous/Chat-API#1401]
Hi all,

I use that chat - api more than 3 months and everything worked perfect.
But yesterday i got banned for my number.
So today i have changed to new one, and i get ban again after some seconds only.
Anyone has idea why this happend? and how can i avoid it?

**Comment by alxhotel** [comment]
Same IP ?

**Comment by AnanasPie** [comment]
I think but i want to be sure.. Is there any other option ??

**Comment by JohnJexon** [comment]
If same IP then it will be banned again
