### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by rabrux** [WHAnonymous/Chat-API#1403]
Two or three weeks ago the code go well, but I was using the 2.5.5.4 version of chat-api.

The error is:
```
Fatal error: Uncaught ConnectionException: Connection Closed! in /home/rsalvador/Bot/Whats/vendor/whatsapp/chat-api/src/whatsprot.class.php:292
Stack trace:
#0 /home/rsalvador/Bot/Whats/src/Bot.php(34): WhatsProt->pollMessage()
#1 {main}
  thrown in /home/rsalvador/Bot/Whats/vendor/whatsapp/chat-api/src/whatsprot.class.php on line 292
```

And when I send messages to the number that is configurated into the code, the messages are not recovered with pollMessage() function.

**Comment by rabrux** [comment]
I patch the error on onDisconnect() event... in this the function the code reconnect to WhatsApp, but the messages still unrecovered.

**Comment by mgp25** [comment]
@rabrux post debug log

**Comment by rabrux** [comment]
solved, its my php version, works well on php 6... but not on 7.
Thank you.
