### ISSUE TITLE
how to parse received emojis?

### ISSUE THREAD

**Issue by zzeebbii** [WHAnonymous/Chat-API#1406]
Hello,
I was looking through wiki and issues but I found solution only for sending emojis but I want to do the reverse. I want to parse emojis which are received in messages. I didn't find any solution. Can any of you please help me. I'm stuck here. Right now I'm using following code and it is translating some emojis of WhatsApp but not all. I'm storing emojis in MySQL database and I've changed table collation to UTF8mb4.

```
$data = preg_replace_callback('/\\\\u([0-9a-fA-F]{4})/', function ($match) {
        return iconv('UCS-4LE', 'UTF-8', pack('V', hexdec($match[1])));
    }, $body);
```

**Comment by mgp25** [comment]
Hello,
not API issue. I just checked, and there is a lot of solutions searching in google

Regards
