### ISSUE TITLE
ecibir mensajes whatsapapi

### ISSUE THREAD

**Issue by draffe** [WHAnonymous/Chat-API#1408]
Hello Friend
I 'm trying to do some things with your api .

  but there is something I can't do and receive SMS

You can help me please

**Comment by mgp25** [comment]
@draffe i dont understand you.

If you are talking about SMS (registration), use `registerTool.php` using the latest API code.

If you are talking about WhatsApp messages, make sure you have installed all dependencies and extensiones, more info. here: https://github.com/mgp25/Chat-API/wiki/Dependencies

You can find more documentation about the API here: https://github.com/WHAnonymous/Chat-API/wiki

And examples: https://github.com/WHAnonymous/Chat-API/tree/master/examples

Regards

**Comment by draffe** [comment]
excuse my English.

I am trying to receive incoming messages and failed to perform

This is the code I use

$ w = new WhatsProt ( $ username , $ nickname , $ debug) ;
$ w- > connect ();

// Now loginWithPassword SENDS Nickname and function ( Available ) Presence
$ w- > loginWithPassword ( $ password) ;

 
$ w- > Eventmanager () -> bind ( " onGetMessage ", " onGetMessage ");
 
 
 while ( $ w- > pollMessage ());

**Comment by mgp25** [comment]
@draffe read my comment above + you need to bind the event to a function

**Comment by draffe** [comment]
yes 
i have this 

 function onGetMessage( $mynumber, $from, $id, $type, $time, $name, $body )
{
     echo "Message from $name:\n$body\n\n";
}

but i dont see de message

**Comment by mgp25** [comment]
Again, have you read my comment? have you installed the extensions?
