### ISSUE TITLE
Incoming messages Encrypted

### ISSUE THREAD

**Issue by jnoliver2** [WHAnonymous/Chat-API#1411]
My implementation had been receiving texts well until 4 days ago when I started getting encrypted messages
```
<message from="2xxxxxxxxx@s.whatsapp.net" type="text" id="178701532C52EEA8BC8" offline="2" t="1452086535" notify="xxxxxxx">
  <enc v="2" type="pkmsg">3!?Jy???."??T?w?F??%x&A|(!???}_?I?yQ????Z?&x8?B?????|?A"B3
!Jds?h҈@???C9??r/?"-EB?L?"DzC????2D?⛡R?y???~?/(??V0???</enc>
</message>
```

That is the output from print($m->NodeString("") . "\n") in the exampleFunctional.php.
Message sending is OK.I have changed my number updated code to the latest but still getting the same.

I have tried the Yowsup python library with my credentials and the demo echo client works fine.

Any hints?

**Comment by JohnJexon** [comment]
Have you installed all the dependencies explained in wiki ? 
This php extensions should be installed. If installed then show the output by following command.
```
php -m
```

PHP Protobuf
Curve25519 PHP
```
https://github.com/WHAnonymous/Chat-API/wiki/Dependencies
```

**Comment by panjipramana** [comment]
How to install extensions php (Protobuf & Curve25519 )  on XAMPP windows??

**Comment by panjipramana** [comment]
how to install extensions Protobuf & Curve25519  on xampp windows??
