### ISSUE TITLE
(minor) PHP version

### ISSUE THREAD

**Issue by sanderdekkers** [WHAnonymous/Chat-API#1414]
Your wiki states PHP 5.6 or greater is required. As Ubuntu 14.04 LTS is quite commonly used, and has 5.5 as default version, I tried to install (and compile the 2 required extensions) anyway, all seems to be working fine.

I might have missed something though, but lowering the requirement to 5.5 seems fair to me.

    PHP Version 5.5.9-1ubuntu4.14
    ...
    curve25519 support	enabled
    ....
    protobuf  Version	0.9

**Comment by mgp25** [comment]
It is, byt we have said that concrete version so people dont get confused.

Regards
