### ISSUE TITLE
Crash and stop session lasted version.

### ISSUE THREAD

**Issue by fullmovil** [WHAnonymous/Chat-API#1415]
Hello,
Please your help me with next error. Thanks.

#0 /usr/src/chat_1/src/handlers/IqHandler.php(266): SessionBuilder->processPreKeyBundle(Object(PreKeyBundle))
#1 /usr/src/chat_1/src/whatsprot.class.php(2339): IqHandler->Process()
#2 /usr/src/chat_1/src/whatsprot.class.php(2048): WhatsProt->processInboundDataNode(Object(ProtocolNode))
#3 /usr/src/chat_1/src/whatsprot.class.php(303): WhatsProt->processInboundData('???.F??????????...')
#4 /usr/src/chat_1/src/whatsprot.class.php(1773): WhatsProt->pollMessage()
#5 /usr/src/chat_1/src/whatsprot.class.php(408): WhatsProt->waitForServer('0f')
#6 /usr/src/chat_1/src/whatsprot.class.php(2142): WhatsProt->sendGetCipherKeysFromUser('573122644885', true)
#7 /usr/src/chat_1/src/whatsprot.class.php(2048): WhatsProt->processInboundDataNode(Object(ProtocolNode))
#8 /usr/src/chat_1/src/whatsprot.class.php(303): WhatsProt->processInboundData('??q??N`??$???O:...')
#9 /usr/src/chat_1/src/whatsprot.class.php( in /usr/src/chat_1/src/libaxolotl-php/SessionBuilder.php on line 154

Please help me!!! is urgent!!

**Comment by JohnJexon** [comment]
Post your code.

**Comment by mgp25** [comment]
Invalid: No code or debug posted
