### ISSUE TITLE
sendSetPreKeys if i used WART to register number

### ISSUE THREAD

**Issue by wasimjee** [WHAnonymous/Chat-API#1416]
As if i used WART to register new number, and WART doesn't have function for sending PreKeys after registration.

So how can i update the keys later.

i am trying to update the keys and its giving error.

**Comment by JohnJexon** [comment]
No problem here. Just tested and working.

**Comment by wasimjee** [comment]
Getting this:

    rx <iq from="s.whatsapp.net" type="error" id="1452138005-2">
    rx   <error code="406" text="not-acceptable"></error>
    rx </iq>

**Comment by wasimjee** [comment]
I am using C# , as i have ported PHP.

Successful in sendGetCipherKeysFromUser() but not in sendSetPreKeys()

**Comment by JohnJexon** [comment]
Have you updated the code ?

**Comment by wasimjee** [comment]
You mean PHP to c#?

**Comment by JohnJexon** [comment]
I meant latest PHP code.

**Comment by wasimjee** [comment]
ya, but not all the functions yet, not getting much time

**Comment by mgp25** [comment]
Delete .db and retry again
