### ISSUE TITLE
onGetMessage not fire

### ISSUE THREAD

**Issue by nnuridin** [WHAnonymous/Chat-API#1418]
I send message from tablet on android, my script win php not work (onGetMessage)?, but if send from nokia (windows phone) onGetMessage is work? please help

require_once "config.php";
require_once 'bin/whatsprot.class.php';

function onGetMessage($mynumber, $from, $id, $type, $time, $name, $body) {
	
	var_dump($body);
	
}

$w = new WhatsProt( $P["wa"]["user"], $P["wa"]["nic"], false );

$w->connect();
$w->loginWithPassword( $P["wa"]["pwd"] );

$w->eventManager()->bind("onGetMessage", "onGetMessage");
$w->sendActiveStatus();

$time = time();
while ( true ) {

	$w->PollMessage();

	if( $time + 30 <= time() ){
	    $w->sendPing();
	    $time = time();
	}

}

**Comment by nnuridin** [comment]
in android sended messages double tick and read

**Comment by mgp25** [comment]
@nnuridin read closed issues
