### ISSUE TITLE
Images can't be decrypted

### ISSUE THREAD

**Issue by BjHelm** [WHAnonymous/Chat-API#1419]
Hello,

I have a problem with recieving images. I can read any textmessages but i can't work with images.
It looks like pictures are encrypted aswell. I'm trying to get the picture using file_get_contents but the the pictures is encyrpted aswell and i don't know how to decrypt it.

tx  stream:features /stream:features

tx  auth user="number" mechanism="WAUTH-2" �/\number.���h@�Z^�˱T�(�1452151411 /auth

rx  from s.whatsapp.net="" /from

rx  stream:features /stream:features

rx  challenge �K4+�& ����XY�m �/challenge

tx   response �A�wk&��Q� c�bG��z�/�Ny�+S������J�D��SV���O�"�IǛ��.vZ|L�]YB�^��� /response

rx  success t="1452151412" props="4" kind="free" status="active" creation="1425391689" expiration="1456927689" �t�in"���M��c��L� /success

tx  presence name="Musterhausen" type="available" /presence

tx  iq id="01" xmlns="jabber:iq:privacy" type="get"
tx    query
tx      list name="default"  /list
tx    /query>
tx  /iq

tx  iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net"
tx    config /config
tx  /iq

rx  message from="number@s.whatsapp.net" type="media" id="4FA7908F5FF02C3D3222" offline="0" t="1452151409" notify="  "
rx    enc v="2" type="msg" mediatype="image" 1923 byte data /enc
rx  /message

-> Decrypted Message: HEX:0a6a68747470733a2f2f6d6d693435392e77686174736170702e6e65742f642f6c4749376a5a5a566f77636976726e65576c754b4946614f456e452f4173455867585649777957496e4f65724e644b5f68735133576670684d5467504e4d5a756f4c676872595a4f2e656e63120a696d6167652f6a706567222029d5522f2a16694824739501bc46b942cc32b9f7cd7beeda3192c69366845e6228edf3074220a7318bdda0ea22e6ca50f14954ac97420125b37fe1cb87736b07d7850f219f778201cc0cffd8ffe000104a46494600010100000100010000ffdb00430006040506050406060506070706080a100a0a09090a140e0f0c1017141818171416161a1d251f1a1b231c1616202c20232627292a29191f2d302d283025282928ffdb0043010707070a080a130a0a13281a161a2828282828282828282828282828282828282828282828282828282828282828282828282828282828282828282828282828ffc00011080053002e03012200021101031101ffc4001f0000010501010101010100000000000000000102030405060708090a0bffc400b5100002010303020403050504040000017d01020300041105122131410613516107227114328191a1082342b1c11552d1f02433627282090a161718191a25262728292a3435363738393a434445464748494a535455565758595a636465666768696a737475767778797a838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae1e2e3e4e5e6e7e8e9eaf1f2f3f4f5f6f7f8f9faffc4001f0100030101010101010101010000000000000102030405060708090a0bffc400b51100020102040403040705040400010277000102031104052131061241510761711322328108144291a1b1c109233352f0156272d10a162434e125f11718191a262728292a35363738393a434445464748494a535455565758595a636465666768696a737475767778797a82838485868788898a92939495969798999aa2a3a4a5a6a7a8a9aab2b3b4b5b6b7b8b9bac2c3c4c5c6c7c8c9cad2d3d4d5d6d7d8d9dae2e3e4e5e6e7e8e9eaf2f3f4f5f6f7f8f9faffda000c03010002110311003f00c4d4bc6b2dcdeb5dda432dd5944a70b129c6cf977127fc474c7bd52d4759b2bb47fb1ccb739897cb594042926e6c3138e881576939e011c64579d41a82c265f2a4b88d63e420651bf27072d9ec48ec4f5e475a6df5d19e5f3402acc87ef31c93e8a4fd47f934f99b1729e87f0f6e08f11ff114796403660038e9cf5239cf3ede95e91278834b5c6dbf8242490044de613819e8b935e6bf0f6d756b4f3a69ed351b7b69d4089522d8d2311b8b216031c027e520e3d706bb3b1d226f145b5bea506a6f0db34fe6262005ca8ca9e49c73cf241c127ad691219c5f8b3537bed616357631b3a155d8c3049c771e848fc2b6f40f11182dd1c5bddcc1502aa47f36d53c8cae727a1f9881d6b33c71e0dd574e797535ba82e2ca37550f3ca913229e06eddb531920673d48381938af6f6afa4a19e5f1178792590ec647b90f823a82154f238e7fc97aa63d2c6f5b695e2dd5752826d5ade76b69364572be6ac492441ce5590119e19bb7209f6ae9ef3c172eb4b6e35dd419e14749de080303e62b1202c8c4b0500919003727e61922bb24a900a12b13730bc3fe16d33405234d8e64247cfba7760e700162a4eddc703271935b25703802a5c5319b009c5342317c51a38d7b42bdd32497ca8ee5361711ab91ce7203023b75ea3a820e0d796c3f053ecf71248baf0546ced55b40368f4e5cfa7a57b23c99c81f7876ef50e496208cf7c77a3463572e29f4152291c8cfe555c483919c91d47a537cdf979ca03dcfa9e3fc8a571589e49c2b6c1c31048fc3ff00d62a9992e1c36d8c03827390c323191d467be3e9ce3bd876c444b672067a67a7b53b7673c8eb8346e32a6d7c31562013b989ff00f57b53ce146371eb524bb4a924647a75a819b3f755b1f4a6808029982925d7043639c9c7ae3a7d39ab0642ae141e319c74e6abf981400a41239c74c0e7f0a5b63e60259485e8093f787a8a902cc526e249ddf88e318a90bf503938aaf24c9190ac70cd9da3d4ff008d41310a387753c93dc9fcfebd3e94f601cd36f21b6f4639dd9040191c7f9ef514f304da0a03ecc718a8c4b8662ca555085c804649ef8ebfe7eb4d8c2c84a11b863773c1fc703ebf950325894a92589e46719e054a2458906ee074e94d4c63dbf9d46e0172aceb83d80fd28246c28ff6879de457047cbc7dd19e83f0ebebf40053e62b24a1371dc013d7a76feb4c9a710c630a491c2a8a8a5219812f800e4607518eb40c7484aa08f7150c42a9c607d0739a74441660a3e4ec4e39aa72bc85db7c7f29c6d6c8c9e7ff00af562170cbbb3866eb8e7a1c50864c49c119e28eaa33eb4514c92839cde3838c15e78fad25e71149fed38073e94515252239156dece710a850b8c0c7b0ab8be9e807f5a28a6819ffd9 tx  <iq id="03" xmlns="w:m" type="set" to="s.whatsapp.net">
tx    ack url="https://mmi459.whatsapp.net/d/lGI7jZZVowcivrneWluKIFaOEnE/AsEXgXVIwyWInOerNdK_hsQ3WfphMTgPNMZuoLghrYZO.enc" /ack
tx  /iq

tx  receipt type="read" to="number@s.whatsapp.net" id="4FA7908F5FF02C3D3222" t="1452151409" /receipt

rx  ib from="s.whatsapp.net"
rx    offline count="1" /offline
rx  /ib

rx  presence from="number@s.whatsapp.net" /presence

Array
(
   
                    [0] => ProtocolNode Object
                        (
                            [tag:ProtocolNode:private] => message
                            [attributeHash:ProtocolNode:private] => Array
                                (
                                    [from] => number@s.whatsapp.net
                                    [type] => media
                                    [id] => 4FA7908F5FF02C3D3222
                                    [offline] => 0
                                    [t] => 1452151409
                                    [notify] => 
                                )

                            [children:ProtocolNode:private] => Array
                                (
                                    [0] => ProtocolNode Object
                                        (
                                            [tag:ProtocolNode:private] => enc
                                            [attributeHash:ProtocolNode:private] => Array
                                                (
                                                    [v] => 2
                                                    [type] => msg
                                                    [mediatype] => image
                                                )

                                            [children:ProtocolNode:private] => 
                                            [data:ProtocolNode:private] => 3
![������pq҅K-P#���Ⓝ�L�q �Od"�2���U�Q�;d��T���ں���g"�K�"6���o�ĳ�z��c��J�If��3u��-]���E)����Q�_3J��/"胶'1��,WOl�Ii!#��%��m�k�B�<� ��J�?eA}h�J
D-,�\C�C�=���VPJצ�ڏ�T��^�AzRa��O/�v��vU^`g�}+�a��b�YwU�^���|�+}
Sax��<�����&���$3����Z��iL�9�f
`n�ȝ���v�n�奼ˇ�<�)]�.i�/�$S@G�̓��n�\B���N,h�zoi#��:O[-���3�I���E)�4��<��@)z!���q�;���I���t�D5�RU3�Ĭ�bT�i>��-��?�:^���ݼS ��A悯5�4<��kp�nc0����
�,�(T@nlγ��ը;U��ּ��=FMG����Ľ�,�vM�Vlg�����rG�Zb�#�ܨj1zp�4��l�X�t&��?��I'oA��L�/�m:@����^��8<�p�Ï�?�ۧuF4̹�G����"5:�%��L�v�� ;�%,Bg��(����)4݉��x�xC>^ܲU��U��9&���J�g@R�0M&dd+O����;��ɎA��i��ȉ��
c����b\��Y�A����RC��i�K:H..E�
��1YG�6����~ٶ��z�����DE�2-V��Mw���ݱ�M7p�um��l�B�9u<�h������l�K^{����s8��n��P�2f��`\�끛�֎�!��`=2"�GOߩHmh�8��]ؐO,�͔���0���ٻ�|�!7��w1�?s�j����l<	S)]�����(c��~T��L1�|�	���G'�/|eu�
�EP9&h0�����8���#��gO}�!ve,�|5/,��(�Nc���k�V����ˇ�)���f���+Xi��vqwx;_e,(��S@��@�i��lF�&Z1��ucKUL"O߸IZSKwǪ��S���yi�:c�B��m�>�L�z��E#��۹w+8W�q���v��D�]�*'9�"Ij���@+%���|�h���k������?�yӥ�J��	��xH�aBj�f����2��T�鏺�y���"g�E�e��?��Z�6�r���B�����F�%��4'��I�l>�V}`�����4�}	���4������Jm6�4�)Ggq]l�b����aR��5�3
����Yz$s5��A�F�"�^/d֙��1���HE�����	B�/��\J3k�˒��Q<|� �yX��қ��8M����w�oP2�u�!le���σ��+5��l�j�Wd�J��B�aa�D����w��\# �.�{�Uiǅ8nCU��������m{f
����S�IN}ՀRN�st��m���{�E�k}���֮�����,XBI�?mO�l���>'!�ߣ(��I�I4�x�L�Sg���V���$̚;�Jc�2�S�6� ������70�糙�N_���j�����i1a�q��:����3:I�
N!s������'���x���^
�aZ�el�
                                        )

                                    [1] => ProtocolNode Object
                                        (
                                            [tag:ProtocolNode:private] => media
                                            [attributeHash:ProtocolNode:private] => Array
                                                (
                                                    [size] => 129517
                                                    [caption] => 
                                                    [url] => https://mmi459.whatsapp.net/d/lGI7jZZVowcivrneWluKIFaOEnE/AsEXgXVIwyWInOerNdK_hsQ3WfphMTgPNMZuoLghrYZO.enc
                                                    [mimetype] => image/jpeg
                                                    [filehash] => 29d5522f2a16694824739501bc46b942cc32b9f7cd7beeda3192c69366845e62
                                                    [width] => 0
                                                    [height] => 0
                                                    [file] =>

Could u help with that issus.

Regards

**Comment by rogobob** [comment]
@BjHelm learn to read closed issues. See #1337 and #1362 and commit bc8006a90fe03acff8131cd657421a145dce5ba6
