### ISSUE TITLE
Composer fails

### ISSUE THREAD

**Issue by mark-sch** [WHAnonymous/Chat-API#1420]
> composer require whatsapp/chat-api

Using version ^3.1 for whatsapp/chat-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for whatsapp/chat-api dev-master -> satisfiable by whatsapp/chat-api[dev-master].
    - Can only install one of: whatsapp/chat-api[v3.1, dev-master].
    - Installation request for whatsapp/chat-api ^3.1 -> satisfiable by whatsapp/chat-api[v3.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by alxhotel** [comment]
Try:

`composer update`

**Comment by mgp25** [comment]
Its working here, if you find an error, send a pull request

Regards

**Comment by mark-sch** [comment]
composer update performed but the error still remains (Debian Jessie, latest updates)

**Comment by mark-sch** [comment]
The error occured when running composer inside a previously checked out git folder. So running from a new folder did the trick. Solved.
