### ISSUE TITLE
Get ACK when Poll Messages

### ISSUE THREAD

**Issue by marcelopitili** [WHAnonymous/Chat-API#1426]
```xml
rx  <stream:error>
rx    <ack id="gONVwspf8t271"></ack>
rx  </stream:error>
```

`Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:277
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 277`

My code
```php
while(true && $segundos<20) {
	$w->pollMessage();
	sleep(0.2);
	$segundos++;
}
```
Sincerely 
Marcelo

**Comment by mgp25** [comment]
Update to latest API code,

Regards

**Comment by marcelopitili** [comment]
Same error  with API updated

rx  <stream:error>
rx    <ack id="yUJh064lByVB4"></ack>
rx  </stream:error>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:299
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 299

**Comment by mgp25** [comment]
@marcelopitili post full debug log and quote it properly

Regards

**Comment by marcelopitili** [comment]
This is the full debug

rx  <iq from="s.whatsapp.net" type="result" id="0a" t="1452267494"></iq>

tx  <presence type="active"></presence>

rx  <stream:error>
rx    <ack id="yUJh064lByVB4"></ack>
rx  </stream:error>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:299
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 299

And this is the code that i use to poll messages

$segundos = 0;
while(true && $segundos<20) {
	$w->pollMessage();
	sleep(0.5);
	$segundos++;
	echo $segundos . "\n";
}

Please sorry if i do something wrong when posting

Sincerely Marcelo

**Comment by marcelopitili** [comment]
This is the full debug

rx  iq from="s.whatsapp.net" type="result" id="0a" t="1452267494"></iq

tx  presence type="active"></presence>

rx  <stream:error>
rx    ack id="yUJh064lByVB4"></ack
rx  </stream:error>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:299
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 299

And this is the code that i use to poll messages

$segundos = 0;
while(true && $segundos<20) {
$w->pollMessage();
sleep(0.5);
$segundos++;
echo $segundos . "\n";
}

Please sorry if i do something wrong when posting

Sincerely Marcelo

**Comment by mgp25** [comment]
@marcelopitili read this: https://github.com/WHAnonymous/Chat-API/wiki/How-to-write-correctly-in-Github

And post full debug log, **full**

**Comment by marcelopitili** [comment]
'''xlm
rx  <iq from="s.whatsapp.net" type="result" id="0a" t="1452267494"></iq>

tx  <presence type="active"></presence>

rx  <stream:error>
rx    <ack id="yUJh064lByVB4"></ack>
rx  </stream:error>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:299
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 299
```

**Comment by marcelopitili** [comment]
['''xlm]
rx  <iq from="s.whatsapp.net" type="result" id="0a" t="1452267494"></iq>

tx  <presence type="active"></presence>

rx  <stream:error>
rx    <ack id="yUJh064lByVB4"></ack>
rx  </stream:error>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:299
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 299
[```]

**Comment by marcelopitili** [comment]
```xlm
rx  <iq from="s.whatsapp.net" type="result" id="0a" t="1452267494"></iq>
```

**Comment by marcelopitili** [comment]
```
rx  <iq from="s.whatsapp.net" type="result" id="0a" t="1452267494"></iq>

tx  <presence type="active"></presence>

rx  <stream:error>
rx    <ack id="yUJh064lByVB4"></ack>
rx  </stream:error>

Fatal error: Uncaught exception 'ConnectionException' with message 'Connection Closed!' in C:\wa_fit\src\whatsprot.class.php:299
Stack trace:
#0 C:\wa_fit\enviar_y_recibir_fit.php(225): WhatsProt->pollMessage()
#1 {main}
  thrown in C:\wa_fit\src\whatsprot.class.php on line 299
```

**Comment by JohnJexon** [comment]
That spam lol

**Comment by JohnJexon** [comment]
Number is blocked I guess.

**Comment by marcelopitili** [comment]
It is not blocked beacuse log correctly.

**Comment by mgp25** [comment]
@marcelopitili if you dont post full debug log, i'll consider this issue as invalid and lock it.

You need to post **full** debug log, not only the error

Regards

**Comment by marcelopitili** [comment]
Sorry i dont know how to save full log and debug, can you tell me where to
see an example ?

2016-01-08 14:09 GMT-03:00 mgp25 <notifications@github.com>:

> @marcelopitili <https://github.com/marcelopitili> if you dont post full
> debug log, i'll consider this issue as invalid and lock it.
>
> You need to post *full* debug log, not only the error
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1426#issuecomment-170059106>
> .
>



-- 
*Marcelo Martínez*
Analista de Sistemas
*Arbo y Blanco 572*

*Resistencia - ChacoTeléfono: 0362 - 443 9450*

**Comment by mgp25** [comment]
@marcelopitili if you are using it in a server, copy and paste all debug output. If you are running in CLI all debug its in there.

regards

**Comment by marcelopitili** [comment]
im running in a windows 2008 command dos window and i can copy from the beggining, there another way? doing from windows 2008 command line ?

**Comment by marcelopitili** [comment]
this is the log

[2016-01-08 14:15:20] [INFO]: Connected to WA server
[2016-01-08 14:15:20] [INFO]: xxxxxxxxxxx successfully logged in
[2016-01-08 14:15:20] [ERROR]: Iq error with 1 id
[2016-01-08 14:15:20] [ERROR]: Iq error with 02 id
[2016-01-08 14:15:20] [ERROR]: Iq error with 03 id
[2016-01-08 14:20:51] [ERROR]: Stream error ack
[2016-01-08 14:20:51] [INFO]: Disconnected from WA server

**Comment by p031985s** [comment]
Hi there...

Do you have  PHP Protobuf and Curve25519?

**Comment by marcelopitili** [comment]
please let me install it and i will send full debug

2016-01-08 14:26 GMT-03:00 p031985s <notifications@github.com>:

> Hi there...
>
> Do you have PHP Protobuf and Curve25519?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1426#issuecomment-170064847>
> .
>



-- 
*Marcelo Martínez*
Analista de Sistemas
*Arbo y Blanco 572*

*Resistencia - ChacoTeléfono: 0362 - 443 9450*

**Comment by marcelopitili** [comment]
sorry i cant install thats extensions, i dont know how to do it.

You can close this issue and i will try from a linux in a few days

Sincerely.

**Comment by JohnJexon** [comment]
You should be blocked from this repo. Can't you read wiki ?  It's already mentioned that these extensions are required -_-

**Comment by marcelopitili** [comment]
Sorry

2016-01-08 14:48 GMT-03:00 JohnJexon <notifications@github.com>:

> You should be blocked from this repo. Can't you read wiki ? It's already
> mentioned that these extensions are required -_-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/1426#issuecomment-170072428>
> .
>



-- 
*Marcelo Martínez*
Analista de Sistemas
*Arbo y Blanco 572*

*Resistencia - ChacoTeléfono: 0362 - 443 9450*
