### ISSUE TITLE
Number is not blocked

### ISSUE THREAD

**Issue by JohnJexon** [WHAnonymous/Chat-API#1434]
Hello,

My number is not blocked but I get not-authorized error. I tried to change the IP still error remains the same. Error log. It was working good in previous version.

```xml
tx  <stream:features></stream:features>

tx  <auth user="8615391574254" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>üpV¸fžÑ‚Ø›ËO'õ</challenge>

tx  <response>¶WŒ’ã¦æ¸ÛbZpCÁÝ M[Xy'¼•¾úqì«W²RËlÎ ¼˜
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

I can send verification code but unable to login in. Changed my IP and did everything.

**Comment by mgp25** [comment]
@JohnJexon have you checked `blockChecker.php`? Send me an email with the identity used to register that number and the password, and i'll tell you if its blocked or not.

Anyway, it seems IP related (if not blocked)

Regards

**Comment by JohnJexon** [comment]
@mgp25 : Thank you ! I have sent email on : me@mgp25.com


Regards

**Comment by mgp25** [comment]
Use `registerTool.php` not WART

Regards
