### ISSUE TITLE
serialize whatsprot

### ISSUE THREAD

**Issue by andrekat** [WHAnonymous/Chat-API#1436]
hi guys .. im trying to parse my whatsprot to an new thread.
 eg:

```php
$thread = new myThread($this->WhatsProt);
$thread->start();
```

..... 

`$thread->start()` throws following exception:

"You cannot serialize or unserialize PDO instances"

I guess this exception is thrown while trying to serialize the AxlotlSqlliteStore.

Background of my function:

i need my already instanced whatsprot class in another thread ... to send messages from thread B.

regards

**Comment by mgp25** [comment]
Take a look at this: http://us.php.net/manual/en/language.oop5.magic.php#object.sleep

Regards
