### ISSUE TITLE
vCard with photo.

### ISSUE THREAD

**Issue by Jonathan313** [WHAnonymous/Chat-API#1437]
Hello,

Is there anyway to send vCard with photo ? I can see photo parameter in vCard.php file.

Thanks!

**Comment by JohnJexon** [comment]
I think it's not possible to set custom photo in vCard.

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/issues/190

**Comment by Jonathan313** [comment]
@mgp25  : Sir please check it's not working. Client is not able to receive it.
Debug log : 
```
tx  <message to="**************"@s.whatsapp.net" type="media" id="9baa79fb7ccb1f1d0b0159" t="1452682274" notify="**************">
tx    <media type="vcard">
tx      <vcard name=""> 445657 byte data</vcard>
tx    </media>
tx  </message>
```
