### ISSUE TITLE
probleme in receving messages

### ISSUE THREAD

**Issue by ahmedstack** [WHAnonymous/Chat-API#1441]
I have been using this code and it worked perfectly : 
```php
 include_once('checkUserSession.php');
  $w=$task->connectToServer();
  $first = $_POST['first']; 
  $msg = array();
  $new = array();
  function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
{
   
   $num = explode("@",$from);
   $GLOBALS['msg'][]=array("from"=>$num[0],"body"=>$body);
   $n=$GLOBALS['task']->saveMessage($body,'f','t',$num[0]);
   if ($n==1){$GLOBALS['new'][]=array("id"=>$num[0]);}
}

$numbers = array();
function onSyncResult($result)  {
    foreach ($result->existing as $number) {
                $n = explode("@",$number);
                $GLOBALS['numbers'][]=$n[0];
              }
        } 
  
  include_once('Chat-API-master/src/events/MyEvents.php');
  $events = new MyEvents($w);
  $w->eventManager()->bind("onGetMessage", "onMessage");
  $w->eventManager()->bind("onGetSyncResult", "onSyncResult");
  

  if ($first=='y'){
     $cData=json_decode($_POST['contact'],true);
     foreach ($cData as $c){
       $w->sendSync($c);
     }
 }
  
  $w->pollMessage();
  $w->disconnect();
```
but when I repalce the api with the latest update I am getting this error : 

```
<b>Warning</b>:  array_fill(): Number of elements must be positive in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>349</b><br />
<br />
<b>Warning</b>:  array_map(): Argument #2 should be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Warning</b>:  implode(): Argument must be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Warning</b>:  array_fill(): Number of elements must be positive in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>349</b><br />
<br />
<b>Warning</b>:  array_map(): Argument #2 should be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Warning</b>:  implode(): Argument must be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/whatsapp_project/Chat-API-master/src/whatsprot.class.php:299
Stack trace:
#0 /var/www/html/whatsapp_project/Chat-API-master/src/whatsprot.class.php(1781): WhatsProt-&gt;pollMessage()
#1 /var/www/html/whatsapp_project/Chat-API-master/src/whatsprot.class.php(476): WhatsProt-&gt;waitForServer('CB7AD12FF94BD08...')
#2 /var/www/html/whatsapp_project/Chat-API-master/src/handlers/MessageHandler.php(350): WhatsProt-&gt;sendRetry(Object(ProtocolNode), '96176592978@s.w...', 'CB7AD12FF94BD08...', '1452460096')
#3 /var/www/html/whatsapp_project/Chat-API-master/src/handlers/MessageHandler.php(256): MessageHandler-&gt;processEncryptedNode(Object(ProtocolNode))
#4 /var/www/html/whatsapp_project/Chat-API-master/src/handlers/MessageHandler.php(38): MessageHandler-&gt;processMessageNode(Object(ProtocolNode))
#5 /var/www/html/whatsapp_project/Chat-API-master/src/whatsprot.class.php(2354): MessageHandler-&gt;Process()
#6 /var/www/html/whatsapp_project/Chat in <b>/var/www/html/whatsapp_project/Chat-API-master/src/whatsprot.class.php</b> on line <b>299</b><br />
```

**Comment by mgp25** [comment]
@ahmedstack do you have all dependencies installed? Please read closed issues

**Comment by ahmedstack** [comment]
yes I have installed protbuf and curve and it was working perfectly before the latest update

**Comment by mgp25** [comment]
@ahmedstack post full debug log

**Comment by ahmedstack** [comment]
tx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
tx&nbsp;&nbsp;&lt;auth user="213669469852" mechanism="WAUTH-2"&gt;�y213669469852e���3h�c�Oq�36�'~1452462450&lt;/auth&gt;<br /><br />
rx&nbsp;&nbsp;&lt;from s.whatsapp.net=""&gt;&lt;/from&gt;<br /><br />
rx&nbsp;&nbsp;&lt;stream:features&gt;&lt;/stream:features&gt;<br /><br />
rx&nbsp;&nbsp;&lt;challenge&gt;l�_q��=�?VMJ*{jh��&lt;/challenge&gt;<br /><br />
tx&nbsp;&nbsp;&lt;response&gt;�����-��:������dˮ
Z�=��ń��`��7������#�`ц�o{$�Ղ��ר5�5�\�<�l�S�:
�wS&lt;/response&gt;<br /><br />
rx&nbsp;&nbsp;&lt;success t="1452462450" props="4" kind="free" status="active" creation="1449614010" expiration="1481150010"&gt;Oi)����������}[jɍ�&lt;/success&gt;<br /><br />
tx&nbsp;&nbsp;&lt;presence name="" type="available"&gt;&lt;/presence&gt;<br /><br />
<br />
<b>Warning</b>:  array_fill(): Number of elements must be positive in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>349</b><br />
<br />
<b>Warning</b>:  array_map(): Argument #2 should be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Warning</b>:  implode(): Argument must be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Warning</b>:  array_fill(): Number of elements must be positive in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>349</b><br />
<br />
<b>Warning</b>:  array_map(): Argument #2 should be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
<br />
<b>Warning</b>:  implode(): Argument must be an array in <b>/var/www/html/whatsapp_project/Chat-API-master/src/BinTreeNodeWriter.php</b> on line <b>363</b><br />
tx&nbsp;&nbsp;&lt;iq id="01" xmlns="jabber:iq:privacy" type="get"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;query&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&lt;list name="default"&gt;&lt;/list&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;/query&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
tx&nbsp;&nbsp;&lt;iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net"&gt;<br />tx&nbsp;&nbsp;&nbsp;&nbsp;&lt;config&gt;&lt;/config&gt;<br />tx&nbsp;&nbsp;&lt;/iq&gt;<br /><br />
rx&nbsp;&nbsp;&lt;message from="96176592978@s.whatsapp.net" type="text" id="CB7AD12FF94BD08CEA90" offline="3" t="1452462307" notify="ahmed mustafa"&gt;<br />rx&nbsp;&nbsp;&nbsp;&nbsp;&lt;enc v="2" type="pkmsg"&gt;3�ʤ!l�#�|�<�R�c�D���M8W����d��Pi!�f`�vm��j;֬�����mQ�yu�Şg�F$"R3
!=��+�	�>��EéA�-��F7f1���39N

**Comment by ahmedstack** [comment]
this is another example : 
tx  <stream:features></stream:features>

tx  <auth user="213669469852" mechanism="WAUTH-2">�-�1213669469852}ڂ%Fٸ�z> [$�I�_�1452463101</auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>?й~i=���=����kѐ�'</challenge>

tx  <response>�E@�n�)k��g�|�����ת��Lt�M�| |)Q'6�pfn�g��&8����=�(��^D1��o�Ĳ�Q���E�rHG</response>

rx  <success t="1452463103" props="4" kind="free" status="active" creation="1449614010" expiration="1481150010">��+��]�3>�����^A�n</success>

tx  <presence name="aa" type="available"></presence>

tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

tx  <iq id="03" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

rx  <message from="96176592978@s.whatsapp.net" type="text" id="CB7AD12FF94BD08CEA9C" offline="0" t="1452463097" notify="ahmed mustafa">
rx    <enc v="2" type="pkmsg">3�ʤ!l�#�|�<�R�c�D���M8W����d��Pi!�f`�vm��j;֬�����mQ�yu�Şg�F$"B3 !=��+� �>��EéA�-��F7f1���39N"P%ơ�">.��yhx�C~�d�(�Ǿr0��</enc>
rx  </message>

tx  <ack to="96176592978@s.whatsapp.net" class="message" id="CB7AD12FF94BD08CEA9C" t="1452463097"></ack>

-> Decrypted Message: No such signedprekey with id: 59883 - /var/www/html/whatsapp_project/Chat-API-master/src/SqliteAxolotlStore.php - 246Message CB7AD12FF94BD08CEA9C could not be decrypted, sending retry. tx  <receipt id="CB7AD12FF94BD08CEA9C" to="96176592978@s.whatsapp.net" type="retry" t="1452463097">
tx    <retry v="1" count="1" id="CB7AD12FF94BD08CEA9C" t="1452463097"></retry>
tx    <registration>8��L</registration>
tx  </receipt>

rx  <ib from="s.whatsapp.net">
rx    <offline count="1"></offline>
rx  </ib>

rx  <presence from="213669469852@s.whatsapp.net"></presence>

rx  <presence from="96176592978@s.whatsapp.net"></presence>

rx  <ack from="96176592978@s.whatsapp.net" class="receipt" type="retry" id="CB7AD12FF94BD08CEA9C"></ack>
