### ISSUE TITLE
Call to undefined function curve25519_private()

### ISSUE THREAD

**Issue by dinchu** [WHAnonymous/Chat-API#1442]
When using lines from phillipines like +86 183 2090 xxxx I get the error 

Fatal error: Call to undefined function curve25519_private() in /var/www/library
/wa/libaxolotl-php/ecc/Curve.php on line 16

when using lines from other countries it works okay. there's a new regional configuration that needs to be done with the lastest?

**Comment by dinchu** [comment]
Sorry y mean chinesse lines with prefix +86

**Comment by mgp25** [comment]
Please, search in the closed issues. Duplicate

Regards

**Comment by dinchu** [comment]
i searched on 10 last pages of closed issues and no one had my problem.

I opened this issue and closed my self

https://github.com/WHAnonymous/Chat-API/issues/1435

I though i had a problem with my installation but now i realize is not working okay with numbers registered in china

**Comment by dinchu** [comment]
@mgp25  can you reopen this issue? i'm trying to debug the issue. if i succeed will make a pull request

**Comment by mgp25** [comment]
@dinchu it seems you havent installed/loaded the extensions correctly, check if the version its okay.
