### ISSUE TITLE
cant recevie messages from new contacts 

### ISSUE THREAD

**Issue by ahmedstack** [WHAnonymous/Chat-API#1443]
I can not recevie messages from new contacts ubtil I sync the number ,,
As you stated , I can recevie message from new contacts if they started messaging.
 So what would be the problem? (note that my code is fully functional and I am  receving messages from synced contacts normally )

presence from="213669469852@s.whatsapp.net"> /presence>rx  
presence from="961XXXXXX@s.whatsapp.net" type="unavailable" last="deny">/presence>

**Comment by mgp25** [comment]
@ahmedstack you have answered yourself

Regards

**Comment by ahmedstack** [comment]
You have mentioned that I can receive messages from new numbers if they start messaging 
but this is not happening

**Comment by ahmedstack** [comment]
"If an user sendd you a message first, you can answer without syncing it. If you are going to send a message (without an started conversation), thrn you must sync it."
That is your comment

**Comment by 0xTryCatch** [comment]
Where is the debug log?

**Comment by ahmedstack** [comment]
this number is sync : 

message from="9617XXXXX@s.whatsapp.net" type="text" id="82AF54A9071D57E4DB3C" offline="0" t="1452534817" notify="ahmed mustafa">
rx    enc v="1" type="msg">3 !�,�~[��r&�O.�.��%��X��3*Yל"�?z��ɉ?��ƞ ���g!��</enc>
rx  /message>
tx  ack to="96176592978@s.whatsapp.net" class="message" id="82AF54A9071D57E4DB3C" t="1452534817"></ack>
-> Decrypted Message:hiiiiiiiا tx  <receipt type="read" to="96176592978@s.whatsapp.net" id="82AF54A9071D57E4DB3C" t="1452534817"></receipt>
96176592978@s.whatsapp.net hiiiiiiiii rx

This number is not sync but started messaging :  

  message from="316XXXXX@s.whatsapp.net" type="text" id="aGo0fRHW681LC" offline="0" t="1452534850" notify="Obaida Alaidy">
rx    enc v="1" type="pkmsg">3��!�R�~�=�fH�u)kZf%��������u��IX!�T�@-.�鱶a/��bNMeВ���ߘE?��|"B3 !�53^�� ���������%[]��o؀=�ky"���̤7�o�����G����4g�1(���0��</enc>
rx  </message>
tx  ack to="31687617873@s.whatsapp.net" class="message" id="aGo0fRHW681LC" t="1452534850"></ack>

-> Decrypted Message: No such signedprekey with id: 26213 - /var/www/html/whatsapp_project/Chat-API-master/src/SqliteAxolotlStore.php - 203Message aGo0fRHW681LC could not be decrypted, sending retry. tx  <receipt id="aGo0fRHW681LC" to="31687617873@s.whatsapp.net" type="retry" t="1452534850">
tx    retry v="1" count="1" id="aGo0fRHW681LC" t="1452534850"></retry>
tx    registration>���</registration>
tx  /receipt>

rx  message from="31687617873@s.whatsapp.net" type="text" id="aGo0fRHW681LE" offline="0" t="1452534875" notify="Obaida Alaidy">
rx    enc v="1" type="pkmsg">3��!�R�~�=�fH�u)kZf%��������u��IX!�T�@-.�鱶a/��bNMeВ���ߘE?��|"B3 !�53^�� ���������%[]��o؀=�ky"f����)��rx  </message>

tx  <ack to="31687617873@s.whatsapp.net" class="message" id="aGo0fRHW681LE" t="1452534875"></ack>
