### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by amec1234** [WHAnonymous/Chat-API#1444]
I updated my whatsapp api to 3.1 and now sending messages is working, but when i`m recieving messages i get this error

`Strict Standards: Only variables should be passed by reference in /Applications/..../exampleFunctional.php on line 23
PHP Strict Standards:  Only variables should be passed by reference in /Applications/.../exampleFunctional.php on line 23`

throughout. Does someone know what this means?

**Comment by estcap** [comment]
What is your PHP version?

**Comment by amec1234** [comment]
i solved this issue the stricts are gone. But now i get nothing when i´m recieving a message. Even the checkmarks are not turned blue and marked as read. Nothing happens. The array() is empty.

**Comment by mgp25** [comment]
@amec1234 post debug log + code for further support

Regards
