### ISSUE TITLE
Unable to get group images

### ISSUE THREAD

**Issue by cmunk** [WHAnonymous/Chat-API#1445]
So I have a script where images sent in PM works fine using onGetImage.

I also want to process images from groups, but I have been unable to get it to work. I have tried using onGetGroupImage but it never seemed to fire. 

I went into the code (`MessageHandler.php`)  and it seems maybe group images are not supported? Line 42: 
```php
if($this->node->getChild("enc") != null && $this->node->getAttribute("participant") == null) { // for now only private messages
```
So maybe group images are not decrypted? It would explain why the onGetGroupImage never fires. Am I right to assume this isnt implemented yet or am I doing something wrong?

Thank you.

**Comment by 0xTryCatch** [comment]
Group encryption is not yet implemented
