### ISSUE TITLE
How To Load Extension Properly

### ISSUE THREAD

**Issue by muzaffarhabibi** [WHAnonymous/Chat-API#1446]
I'm using XAMPP on my Win 8.1 64 bit for testing purposes. 
I've copied the extension dll's and added the following lines to c:\xampp\php\php.ini 

extension=php_curve25519_ts.dll
extension=php_protobuf_ts.dll

When I run php.exe on command prompt (with administrator privileges)
I got these error

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_curve
25519_ts.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_
protobuf_ts.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_proto
buf_ts.dll' - %1 is not a valid Win32 application.

Please advise me, what I did I do wrong?

**Comment by aal89** [comment]
Do you have a 32bit or 64bit XAMPP installation? All the DLLs are built for 32bit architectures.

**Comment by muzaffarhabibi** [comment]
Got it, i've uninstalled it and install the 32bit version. The extension loaded correctly and no startup error anymore. Another question is, i have this output : 
No such signedprekey with id: 9744444. I'll browse the wiki for more information since it is not the Appropriate topics. But any help will be appreciated :-)

**Comment by muzaffarhabibi** [comment]
All problem solved. Thanx to aal89 :100:

**Comment by aal89** [comment]
Nice :), whenever you get the no such signedprekey error again, try deleting your axolotl db in the wadata folder, upon login new keys will be generated and sent to the Whatsapp servers.

**Comment by alantva** [comment]
Is there any chance of them running on 64-bit Windows?

**Comment by aal89** [comment]
I'll ask the guy who compiled the binaries if he has any time building them for 64bit as well.

**Comment by alantva** [comment]
@aal89 Thank you.
