### ISSUE TITLE
Sent Messages not received

### ISSUE THREAD

**Issue by everyusernameistaken123** [WHAnonymous/Chat-API#1448]
Hi,

I know there were 2 issues opened a few days ago with the same problem.
There it was adviced to update the API... well, I try to descripe what I did:

I updatet API on 2016-01-08, sent one message (using the API) and it worked. Fine :)
But today, it didn't work. I don't receive the message on my mobile phone. Even with the upgrade in whatsprot.class.php from yesterday. The sender-number is not blocked by whatsapp or by me.

I fetched the debug-data, it looks fine to me. So what can be the reason?
```xml
> tx  <stream:features></stream:features>
> tx  <auth user="43688XXXXXX" mechanism="WAUTH-2">��+{43688XXXXXXd��>�Yc&�hk����1452521239</auth>
> rx  <from s.whatsapp.net=""></from>
> rx  <stream:features></stream:features>
> rx  <challenge>�M�%�\��9-�'Y������</challenge>
> tx  <response>�Ԩ����)�g����[q���<��?�(j7�~����C�/����0;N��k��k�d�P`��-��������></response>
> rx  <success t="1452521239" props="4" kind="free" status="active" creation="1445504335" expiration="1477040335">�4\>,]*4Q�|�'�Ԭ�</success>
> tx  <presence name="test" type="available"></presence>
> tx  <iq id="01" xmlns="jabber:iq:privacy" type="get">
> tx    <query>
> tx      <list name="default"></list>
> tx    </query>
> tx  </iq>
> tx  <iq id="02" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
> tx    <config></config>
> tx  </iq>
> tx  <message to="43664XXXXXX@s.whatsapp.net" type="text" id="82555cc4d7715547682697" t="1452521240" notify="test">
> tx    <body>mit zusatz infos geht das</body>
> tx  </message>
```
Thanks in advance!

**Comment by everyusernameistaken123** [comment]
According to https://github.com/WHAnonymous/Chat-API/issues/1443 I tried to save the sender-number as contact on my phone... But I don't receive a message sent from the API either?

**Comment by mgp25** [comment]
You are disconnecting too soon + ciphered message is required. Plaintext messages are not allowed.

Regards
