### ISSUE TITLE
Sending documents.

### ISSUE THREAD

**Issue by VanDevos** [WHAnonymous/Chat-API#1451]
Hello,

Is there any function to send documents such as pdf, doc ? I searched in API doc but I couldn't find.

Thanks!

**Comment by ducch** [comment]
Theoretically, you can.
Practically and officially - no. you cannot.

**Comment by mgp25** [comment]
We will add this eventually. No ETA.

Regards

**Comment by AloneMate** [comment]
@mgp25  Any updates ? 

Thanks!

**Comment by mgp25** [comment]
So much impatience
