### ISSUE TITLE
Messace could not be decrypted, sending retry

### ISSUE THREAD

**Issue by gleichnerv** [WHAnonymous/Chat-API#1452]
Sometimes I receive this error on image receive:
```xml
11-01-16 21:53:16 - rx  <presence from="393*********@s.whatsapp.net"></presence>


11-01-16 21:53:34 - rx  <message from="393*********@s.whatsapp.net" type="media" id="Z1b92DhOmmR34" t="1452545633" notify="*******">
rx    <enc v="2" type="msg" mediatype="image"> 3747 byte data</enc>
rx  </message>

11-01-16 21:53:34 - tx  <iq id="0b" xmlns="encrypt" type="get" to="s.whatsapp.net">
tx    <key>
tx      <user jid="393*********@s.whatsapp.net"></user>
tx    </key>
tx  </iq>

11-01-16 21:53:34 - rx  <iq from="s.whatsapp.net" type="result" id="0b">
rx    <list>
rx      <user jid="393*********@s.whatsapp.net">
rx        <registration></╗Y</registration>
rx        <type>♣</type>
rx        <identity>Ú^k26yt┴u¤Ë←♂e,←ô4aàdòfè¾ -╩▄ñ)↓</identity>
rx        <skey>
rx          <id>   </id>
rx          <value>%Åf0‗.└Êı@ ▄Á└e¬ld8rt5Pm§¢3÷s9!♣↕</value>
rx          <signature>>╚♦cz─üwG(∟.wGÕF░ä²P6ëdI6óÃ.5A¿¢<&©☻¼UéÖ ]^▒ïëÑÀ4fm Ýoñ↕├⌂¡♦</signature>
rx        </skey>
rx        <key>
rx          <id>·¨=</id>á÷ä┴        <value>■ëEm>©,×²·╝ Yý`¬V═↨i↔lû♦Ð</value>
rx        </key>
rx      </user>
rx    </list>
rx  </iq>

11-01-16 21:53:34 -
-> Decrypted Message: Bad Mac!
11-01-16 21:53:34 - No valid sessions - ....\src\libaxolotl-php\SessionCipher.php - 17811-01-16 21:53:34 - Message Z1b92DhOmmR34 could not be decrypted, sending retry.

11-01-16 21:53:34 - tx  <receipt id="Z1b92DhOmmR34" to="393*********@s.whatsapp.net" type="retry" t="1452545633">
tx    <retry v="1" count="1" id="Z1b92DhOmmR34" t="1452545633"></retry>
tx    <registration>r¯*¸</registration>
tx  </receipt>

11-01-16 21:53:34 - rx  <ack from="393*********@s.whatsapp.net" class="receipt" type="retry" id="Z1b92DhOmmR34"></ack>

11-01-16 21:53:34 - tx  <receipt type="read" to="393*********@s.whatsapp.net" id="Z1b92DhOmmR34" t="1452545633"></receipt>

11-01-16 21:53:34 - rx  <ack from="393*********@s.whatsapp.net" class="receipt" type="read" id="Z1b92DhOmmR34"></ack>

11-01-16 21:53:40 - tx  <receipt type="read" to="393*********@s.whatsapp.net" id="Z1b92DhOmmR34" t="1452545633"></receipt>

11-01-16 21:53:41 - rx  <ack from="393*********@s.whatsapp.net" class="receipt" type="read" id="Z1b92DhOmmR34"></ack>

11-01-16 21:54:42 - tx  <iq id="0c" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

11-01-16 21:54:43 - rx  <iq from="s.whatsapp.net" type="result" id="0c" t="1452545701"></iq>

11-01-16 21:54:44 - rx  <presence from="393*********@s.whatsapp.net" type="unavailable" last="deny"></presence>



```
The image is not received and despite of the "retry" receipt, the message is not retried and never arrives.

Why the api send the read receipt anyway?

Tried to delete .db but with no luck.

**Comment by gleichnerv** [comment]
Made further tests:
seems that the first image received after .db deletion causes the issue.

Updated to the last commit but it behave even worst.
Now it trow a fatal error on function getAttribute() and exit.
```xml

-> Decrypted Message: No such signedprekey with id: 48757 - ....\src\SqliteAxolotlStore.php - 246Message b9fj418SbOMc-349 coul
d not be decrypted, sending retry.

tx  <receipt id="b9fj418SbOMc-349" to="393*********@s.whatsapp.net" type="retry" t="1452550243">
tx    <retry v="1" count="1" id="b9fj418SbOMc-349" t="1452550243"></retry>
tx    <registration>15c5fe71</registration>
tx  </receipt>

rx  <ack from="393*********@s.whatsapp.net" class="receipt" type="retry" id="A5a18SbOMc+524"></ack>


Fatal error: Call to a member function getAttribute() on null in ....\src\handlers\MessageHandler.php on line 48
```

To flush the messages in queue I need to switch back to this 04a27c9 version

**Comment by v920749** [comment]
Call to a member function getAttribute() on null
                }
46
                if ($dec_node) {
47
                    $this->node = $dec_node;
48
                    $file_data = $dec_node->getChild("media")->getAttribute("file");
49
                }
50
            }
51
            else if ($this->node->getChild("enc") == null) {

**Comment by ibnubudir** [comment]
i got the same message error like that, but wait untul 1 minute , clear cache + try to Login  , its nurmaly recieve message ( decripted ) simple array
...in Chat-API2/tests/whatsapp.php ==>

if ($_SERVER['argv'][1] == '-l') {
    echo "\n[] Listen mode:\n";
    while (true) {
        $wa->pollMessage();
        $data = $wa->getMessages();
        if (!empty($data)) {
          // print_r($data);
			 echo json_encode($data);
			 
        }
        sleep(1);
		
    }
    exit(0);
}


respon ==> 
rx  <chatstate from="618123456789@s.whatsapp.net">
rx    <paused></paused>
rx  </chatstate>

rx  <message from="618123456789@s.whatsapp.net" type="text" id="1157DBFE0DF32277A586" t="1452588675" notify="Kapten Ibnubudir">
rx    <enc v="2" type="msg">330a2105f5008ecf1886711321ee60cf5cd4c2f1e604bbe136935a381726cf03cc74252f100118052250ba7a55e886decba9b1174942d437bb91373157d8ca50469f99950c844df6619e14b7f77c69c15ee4812027d3fc65b9c2d191f7b41b2e8046568c50c4efd7ae35ce06922c3bbe01a521a47efd9a0d98326db2020db66ab96e</enc>
rx  </message>

tx  <ack to="618123456789@s.whatsapp.net" class="message" id="1157DBFE0DF32277A586" t="1452588675"></ack>


-> Decrypted Message: Kapan muleh

tx  <receipt type="read" to="618123456789@s.whatsapp.net" id="1157DBFE0DF32277A586" t="1452588675"></receipt>

**Comment by mgp25** [comment]
@gleichnerv fixed in latest commit

Regards
