### ISSUE TITLE
onGetGroups() event showing error.

### ISSUE THREAD

**Issue by VanDevos** [WHAnonymous/Chat-API#1454]
Hello,

```onGetGroups() ``` event doesn't work since updated with latest version.

Code : 

```php
<?php
require_once('src/whatsprot.class.php');
require_once('src/events/MyEvents.php');
require_once('src/events/AllEvents.php');

$username = "****";
$nickname = "gary";
$password = "***"; 
$debug = true;

  public function onGetGroups($mynumber, $groupList)
     {
    	var_dump($groupList);
   }


// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);
$events = new MyEvents($w);
 $w->eventManager()->bind("onGetGroups", "onGetGroups");

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!



 for($i=0;$i<=5;$i++)
{
	$w->pollMessage();
 }	
$w->onGetGroups();
 for($i=0;$i<=5;$i++)
{
	$w->pollMessage();
 }

$w->disconnect();
```

The event is never get called. I don't know why but it shows an error. I have also uncommented the event in Events file. If I don't bind event and just call ``` $w->sendGetGroups();  ``` it works but in debug mode. It shows list of groups in debug mode. But event doesn't work. I have installed all dependencies. All other functions working fine. 
 Any help ?

**Comment by mgp25** [comment]
This is completly wrong: `$w->onGetGroups();`

There is no function called `onGetGroups()`, thats why is you are getting the error.

Regards

**Comment by VanDevos** [comment]
@mgp25 :  Sorry! due to copy paste I wrote that function. function is ``` sendGetGroups(); ```
This is giving me error.

**Comment by mgp25** [comment]
Can you paste debug log?

**Comment by VanDevos** [comment]
I dont get any logs. It says 500 internal server error. :/

**Comment by mgp25** [comment]
@VanDevos thats why then, its a problem at your server. Not API issue

Regards

**Comment by VanDevos** [comment]
Only for this event ?  Every events and functions working fine.

**Comment by VanDevos** [comment]
@mgp25  : Solved! I just removed ``` public ``` before function and it worked perfectly ! I don't know why but it's working after that only!
