### ISSUE TITLE
format_wrong

### ISSUE THREAD

**Issue by amrdesign** [WHAnonymous/Chat-API#1458]
Hello
i register new number when i test it in `blockChecker.php`

i see `[status] => fail [reason] => format_wrong`

#################### # # # WA Block Checker # # # #################### Username (country code + number without + or 00): 

```
Array (
 [cc] => 965 
[in] => XXXXXXX 
[lg] => ar 
[lc] => KW 
[id] => b�e�2_edtt�p��w��� 
[mistyped] => 6 
[network_radio_type] => 1 
[simnum] => 1 
[s] => 
[copiedrc] => 1 
[hasinrc] => 1 
[rcmatch] => 1 
[pid] => 163 
[extexist] => 1 
[extstate] => 1 )
 stdClass Object (
 [status] => fail 
[reason] => format_wrong ) 
```

thank you

**Comment by everyusernameistaken123** [comment]
Isn't it just 6 digits? You masked 7 "X"?

**Comment by mgp25** [comment]
@amrdesign bad number/provider. Just checked it
