### ISSUE TITLE
Error sending 

### ISSUE THREAD

**Issue by borjapu** [WHAnonymous/Chat-API#1459]
Hello , i'm having problems sending message with the new API 
``` php
PHP Fatal error:  Uncaught exception 'LoginFailureException' in /home/whatsapp2/public_html/Chat-API-master/src/Login.php:54
[Tue Jan 12 15:48:52 2016] [warn] mod_fcgid: stderr: #0 /home/whatsapp2/public_html/Chat-API-master/src/whatsprot.class.php(286): Login->doLogin()
[Tue Jan 12 15:48:52 2016] [warn] mod_fcgid: stderr: #1 /home/whatsapp2/public_html/cron_enviar_msg.php(19): WhatsProt->loginWithPassword('*************')
[Tue Jan 12 15:48:52 2016] [warn] mod_fcgid: stderr: #2 {main}
[Tue Jan 12 15:48:52 2016] [warn] mod_fcgid: stderr:   thrown in /home/whatsapp2/public_html/Chat-API-master/src/Login.php on line 54

```
But with the old API i can send. 
The problem was , with the old API i cant recive and with newest i cant send. 
Some help?, 
i use the same code in both APIS
```php
$w = new WhatsProt($datos_cuenta["telefono_cuenta"], $datos_cuenta["alias_cuenta"], $debug);
		$w->connect();
		$w->loginWithPassword($datos_cuenta["clave_cuenta"]); //--->this generate the error¡
```
thanks in advance

**Comment by mgp25** [comment]
@borjapu please post full debug log, it appear when you set `$debug` to `true`

**Comment by borjapu** [comment]
````console
tx  <stream:features></stream:features>

tx  <auth user="34663810022" mechanism="WAUTH-2"></auth>

rx  <from s.whatsapp.net=""></from>

rx  <stream:features></stream:features>

rx  <challenge>aa20bd4aede8266e03c58425edb326ebc7d7b89c</challenge>

tx  <response>ae7de9292ae5d7391654335a9c9d718c9ed2ad388669727e47213656750b3c7fca81f0a4d9b11fdd955de2efec2f4c94671e0ff45074729212abc749d61ed106a9500181c3a6c4ff1989bd716b</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```
it said not-authorized, but i receiving and sending(with the other API);

**Comment by mgp25** [comment]
@borjapu this could mean:

- You are using a wrong password for that number
- Your account is blocked. Try `blockChecker.php` to check if the number is blocked or not.

If it isn't blocked. I recommend you to register again that number with `registerTool.php`, we have recently update a lot of things, and since the last API version was using Nokia data and now Android ones, that could generate some errors.

Try all of this, and if you still have any problem, send me an email

Regards

**Comment by PriyankaIt** [comment]
i m downloading new chat-api-net-master and genrate password but when i login with that it throws error login failed
