### ISSUE TITLE
Encrypted message

### ISSUE THREAD

**Issue by cruizv** [WHAnonymous/Chat-API#1462]
Hola:
He actualizado a la última versión del ChatAPI y, con el siguiente código:
```php
$w = new WhatsProt($numero, $nombre, true);
$w->connect();
$w->loginWithPassword($pwd);

$w->sendSetProfilePicture(URL_PERFIL);

$pn = new ProcessNode($w, $number);
$w->setNewMessageBind($pn);

while(1) {
  $w->pollMessage();
}
```

Estoy obteniendo este resultado, entre otros mensajes:
```xml
rx  <message from="5195XXXXXX@s.whatsapp.net" type="text" id="2ED6FBCE90BDD0C3754" offline="3" t="1452638818" notify="CXXXX RXXX">
rx    <enc v="2" type="pkmsg">33122105d5eae71e5b0052ead0998652e331fe324142e50f742aed470532a49357bb9e7b1a2105b80bc85fc9b5194395f632f4674aa5cc99e3922181c3893e99c3b9b5a8dafa3a2242330a2105faf08fec074b3548612ba39d677ed6c11b6e551d62106054b7c5dbc27050666c101918002210307089569110144e28dffc1e5247930bd3029b32e491cf2228c4eec2f505308ca3f104</enc>
rx  </message>
```

Además, nunca entra a procesar los mensajes que sean solo texto con el ProcessNode, funciona únicamente con multimedia.

Gracias.
César

**Comment by mgp25** [comment]
@cruizv this is an international repository, i understand you, but most of the people not, please edit this issue and translate it to English.

Regards

**Comment by everyusernameistaken123** [comment]
hi mgp25, after you helped me with curve25519 I am back here ;)
Curve25519 and protobuf is included in my php, I even can send and receive messages.
But I still have the same problem like the thread-starter:
ProcessNode->process is never called. I can only receive messages with
$whatsprot->eventManager()->bind("onGetMessage", ...);

I would prefer the ProcessNode->process method due to my software architecture.

**Comment by everyusernameistaken123** [comment]
Oh, why became my message deleted?
I wanted to say that I have a similar issue, even with curve25519 and protobuf enabled (extension_loaded return 1). Receiving messages with a ProcessNode-instance doesn't work, just with the events "onGetMessage", "onGetImage" and so on.

**Comment by mgp25** [comment]
@everyusernameistaken123 don't you see you are commenting in a non-related issue?

**Comment by everyusernameistaken123** [comment]
Sorry, it's been a long day so I want to excuse myself if I am not getting it :(
But "Question" don't seem to me like "not related"? ;)
And I experience exact the same like the thread-starter: ProcessNode is not called. And I use the same setup with "setNewMessageBind", so I thought my issue would fit here?

**Comment by mgp25** [comment]
use events……
