### ISSUE TITLE
General question..

### ISSUE THREAD

**Issue by VanDevos** [WHAnonymous/Chat-API#1464]
Hello,
I have a general question. WhatsApp uses password to authenticate users isn't it ? So if there are some users on my network and I can see their traffic so is it possible to see their passwords using wireshark or something ? 

Thanks!

**Comment by 0xTryCatch** [comment]
No. The password is stored on the device only and no transmitted.

**Comment by VanDevos** [comment]
@0xTryCatch  : Then how WA checks the identity without password ?

**Comment by 0xTryCatch** [comment]
The device uses the password to calculate a secret which the server verifies.

**Comment by VanDevos** [comment]
So the secret always changes ?

**Comment by VanDevos** [comment]
That secret always remains same or it changes ?

**Comment by 0xTryCatch** [comment]
Ofcourse it changes otherwise it will be insecure. Bottom line: you cannot hack accounts.

**Comment by VanDevos** [comment]
Okay sir thank you so much. I can see WhatsApp has pw,key files in root folder. But there is a new messenger her in India called "Hike Messenger" which is becoming very popular and 80 % Indian people migrated to it. People says that it has more security over whatsapp however I checked  it's root folder as well as SD card folder I couldn't find any files are secure. They are in XML format and can be read. IDK why people saying that it's extremely secure.

**Comment by mgp25** [comment]
You want a secure app? Use Signal or Telegram
