### ISSUE TITLE
Question regarding Notification Nodes when type=contacts

### ISSUE THREAD

**Issue by estcap** [WHAnonymous/Chat-API#1465]
Hello! I have what might is a silly question after having used this api for some time,
So far I've ignored any ```<notification type="contacts">``` arriving to my script.
I didn't have any problems so far, but I would like to implement good behaviour regarding the ```add``` , ```update``` and ```remove``` notifications.

In the [Wiki](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#notification-nodes) I see the description and supposed behaviour the script should have for each ```type``` , but I don't see any event that can be defined when any notification arrives.

Looking through the wiki and searching [issues](https://github.com/WHAnonymous/Chat-API/issues/1280) , I know that ```onNumberWasRemoved``` is what I am looking for, but I cannot find information about this event in the wiki.

So far I've done all my script's behaviour through events. Is there an event I am missing or I should process the notification nodes directly?

Thanks!

**Comment by rogobob** [comment]
@estcap The events you are looking for are onNumberWasAdded, onNumberWasRemoved and onNumberWasUpdated. Those events handle the ```<notification type="contacts">``` node

**Comment by estcap** [comment]
@rogobob thanks for your response.
Correct me if I am wrong, but could it be that they are not documented in the Wiki? I can't find them in the list of events but I keep on finding mentions of these events on past issues. Where did you get them? Thanks!

**Comment by rogobob** [comment]
@estcap Correct, they are not in the wiki. Similarly to you I found mentions of them in the issues and decided to implement them, reading the source code and the issues. Apart from the wiki, issues and commits I always read the function definitions defined in AllEvents.php and if needed, where they are called.

**Comment by estcap** [comment]
@rogobob thanks for taking time and answering me, I found them in AllEvents.php, they seem pretty simple to implement and will do so.

@mgp25 I am curious, is there any reason for them to not appear on [Wiki](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#list-of-all-events) or just havent been added yet?

**Comment by mgp25** [comment]
@estcap haven't added yet, i still have many things to do..
