### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by hypertech** [WHAnonymous/Chat-API#1466]
Hi guys, is it possible to add curve25519 and protobuf extensions in windows?

**Comment by MattPorto** [comment]
Here have one session that says "Pre-Compiled extensions (Curve25519 and protobuf) for Windows users": https://github.com/WHAnonymous/Chat-API/wiki/Dependencies

**Comment by hypertech** [comment]
Thanks man ! 
Will try this out now

**Comment by hypertech** [comment]
What is the difference between "_ts" and "_nts" ?

**Comment by mgp25** [comment]
Read wiki and use google for the good of the humanity...

ts: thread safe

Regards

**Comment by hypertech** [comment]
thanks @mgp25 
i found answer and all work like a charm
