### ISSUE TITLE
I can't login with the client.php or Simple CLI client.php

### ISSUE THREAD

**Issue by MattPorto** [WHAnonymous/Chat-API#1467]
Hello! :)
Sorry, I don't have so much experience in PHP, then have a bit of patience with my issue.
When I try to login with a client.php with a already registered number (that I register with registerTool.php), the client.php script return a exception:

PHP Notice:  Undefined variable: nickname in /home/../client.php on line 56
PHP Fatal error:  Call to undefined method WhatsProt::codeRequest() in /home/../client.php on line 59

I think the script try to send a code request to whatsapp server, but my number is already registered. How can I login with a registered number? 

The Simple CLI client.php exception:

PHP Notice:  Undefined offset: 1 in /home/../Simple CLI client.php on line 24
USAGE: php Simple CLI client.php <number> 

Ej: php client.php 34123456789

How can I fix it?

**Comment by mgp25** [comment]
@MattPorto that script isnt updated, instead i recommend you to try other examples or try coding your own script.

More example scripts: https://github.com/WHAnonymous/Chat-API/tree/master/examples

Please, remember to quote properly, a guide: https://github.com/WHAnonymous/Chat-API/wiki/How-to-write-correctly-in-Github

Regards
