### ISSUE TITLE
Banned 3rd time

### ISSUE THREAD

**Issue by andrekat** [WHAnonymous/Chat-API#1468]
Hi guys its me again  - sorry for a further issue.
Short description:

i developed a whatsapp "support" hotline for my company. so if someone sends me a message, i answer them with further information and create a ticket in our CRM (i dont message anyone first, so i dont have to sync them, right?) 

first auth process:

	$this->WhatsApp = new WhatsProt($this->Config["PhoneNumber"], $this->Botconfig["Nickname"], false);
			
			$events = new MyEvents($this->WhatsApp, $this->Config, $db_server, $db_name, $db_username, $db_password);
			$events->setEventsToListenFor($events->activeEvents); //You can also pass in your own array with a list of events to listen too instead.

	
			$this->WhatsApp->connect();
			$this->WhatsApp->loginWithPassword($this->Config["Password"]);
			
			
			if($firstConnect) {
				$this->WhatsApp->sendGetPrivacyBlockedList(); // Get our privacy list
				
				$this->WhatsApp->sendGetClientConfig(); // Get client config
				
				$this->WhatsApp->sendGetServerProperties(); // Get server properties
				
				$this->WhatsApp->sendGetGroups(); // Get groups (participating)
				
				$this->WhatsApp->sendGetBroadcastLists(); // Get broadcasts lists
				
				$this->WhatsApp->sendStatusUpdate($this->Config["Status"]);
				
				$filename = "tmp-profile-".rand().".png";
				
				file_put_contents($filename, $this->Config["ProfilePicture"]);
				
				$this->WhatsApp->sendSetProfilePicture($filename);
				
				unlink($filename);
			}
			
			$this->WhatsApp->sendOfflineStatus();			

---------

after authenticating 1st time ->

	while(true) {
				
				$this->WhatsApp->pollMessage();
				
			}

i handle income messages by the "onGetMessage" event:

	if($this->whatsProt->hasRunningAction($from)){
			h_echo("Ignore message - contact has an running action");
		} else {
			h_echo("Handle income message for ".$name);
			
			$this->HandleIncomeMessage($from);
		}

i overrided whatsprot class with some static arrays, e.g. hasRunningAction (array with number, if user already contacted me - if user wrote already -> ignore input).

after about 5 hours - i get an loginexception (banned).
whats wrong with my workflow? any suggestions?

thanks!

**Comment by VanDevos** [comment]
```pollMessage();``` You will need to continuously pollmessages.

**Comment by andrekat** [comment]
@VanDevos : I already do that in a while(true) loop? 

Or what do you mean ?

**Comment by VanDevos** [comment]
After login in u have to pllmessage for 3-4 times using for loop.

**Comment by andrekat** [comment]
Do you mean like that:

$timer = 3;
for($i = 0; $i < $timer; $i++) {
    $this->WhatsApp->pollMessage();
}

But whats the difference between my while(true) loop - and this for loop? can you explain that?

thanks!

**Comment by VanDevos** [comment]
Post entire code.

**Comment by andrekat** [comment]
I already did in first post .. :confounded:

**Comment by VanDevos** [comment]
After 
```
 $this->WhatsApp->connect();
        $this->WhatsApp->loginWithPassword($this->Config["Password"]);

```
Use this : 
```
$timer = 3;
for($i = 0; $i < $timer; $i++) {
$this->WhatsApp->pollMessage();
}
```

**Comment by mgp25** [comment]
@andrekat we don't support people who uses API for commercial use, only personal usage.

Regards
