### ISSUE TITLE
ProtocolNode in MessageHandler not more "body" in child

### ISSUE THREAD

**Issue by brenodouglas** [WHAnonymous/Chat-API#1469]
Yesterday everything was working properly at this point is no longer running this line: https://github.com/WHAnonymous/Chat-API/blob/master/src/handlers/MessageHandler.php#L273

Substitutes:
```diff
- if ($node->hasChild('body')) {
+ if ($node->hasChild(0)) {
.....
.....
- $node->getChild('body')->getData()
+ $node->getChild(0)->getData()
```
And everything went back to normal operation.
I do not know if it's only happening to me, or if it was a change that whatsapp implemented in any response.

**Comment by MansourAlotaibi** [comment]
It happened to me too.

**Comment by estcap** [comment]
Do you have any kind of error when you run your script on debug mode?

**Comment by mgp25** [comment]
@brenodouglas i close this issue. If still happends to you, post full debug log

Regards

**Comment by brenodouglas** [comment]
@mgp25  I have not posted my debug log simply because there is no error does not happen any error, only informs that the message was received and will not fire the event 'onGetMessage' because it does not meet the above condition that changed.
