### ISSUE TITLE
codeRequest Response

### ISSUE THREAD

**Issue by ingrocha** [WHAnonymous/Chat-API#1471]
Sorry, im new in this im trying to use your api in cakePhp but i dont now how consume your response:
```
Array
(
    [method] => sms
    [in] => 123456789
    [cc] => 34
    [id] => 扴v??,g??bd=_
    [lg] => es
    [lc] => ES
    [sim_mcc] => 214
    [sim_mnc] => 000
    [mthod] => sms
    [token] => 80d7c58e1fe817d9a64b6717afdbab2b
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)

```

I tried to jsonenconde but i can i called from a $.get this is my code!!

this is on my **view**
```php
function enviar(){
			
			var datos=$('#RegitrerRegistrerForm').serialize();
			$.get("<?php echo $this->html->url(array('controller'=>'Messages','action'=>'Registrar')) ?>"
				var res = jQuery.parseJSON(data);
				});
		}
```

**In my Controller:**

```php
	public function registrar(){
			$vendor=App::path('Vendor');
			//$this->layout = false;

			if ($this->request->is('get')) {
				App::import( 'Vendor','Whatsapp/Registration');	
				$username = $_GET['data']['Regitrer']['Numero'];    // Your number with country code, ie: 34123456789
				$debug    = true;  // Shows debug log, this is set to false if not specified

				$identityExists = file_exists($vendor['0']."/Whatsapp/wadata/id.$username.dat");

				$w = new Registration($username, $debug);

				try{
					$w->codeRequest('sms');
					
				}catch (Exception $e) {

        			//echo $e->getMessage()."\n";
        			exit();
    			}

			}

	}
```

**Comment by VanDevos** [comment]
This is not API related issue.

**Comment by mgp25** [comment]
@ingrocha its an array object, anyway i recommend you to follow some php guides before playing with this API

Regards

**Comment by ingrocha** [comment]
I now is not a API problem but im asking for help pls, its looks like an array but when a i try to use it in java script y showme some errors because javascript gets it as a plain text!!! in cakephp its all arrays so i realy now how to use but i cant used here can you tell me please where i can study about this i have tried to many things but  can try to use json_encode, try to put in a variable but is the same i canot used

**Comment by mgp25** [comment]
@ingrocha i told you its a array object, if you use this API with other things then is not API related issue, in this cases is better to ask google.

Regards

**Comment by ingrocha** [comment]
I this this is a problem in the api i run your example **exampleRegister.php** using a number from mexico:

code

```php

<?php
/**
 * This is an example of how you can use the WhatsAPI to request a code
 * from the WhatsAPP server, register that code and retrieve your password.
 *
 * Once you have your password you will then be able to use it in
 * examplefunctional.php to actually send and receive messages.
 */
require_once '../src/Registration.php';

/*
 * Config data.
 */
$debug = true;
$username = '526671565282';   // Telephone number including the country code without '+' or '00'.

// Create an instance of Registration.
$w = new Registration($username, $debug);

// How to create an account __ONLY__ if you do not have a associated to our phone number.
// You can test your credentials with: $w->checkCredentials() (BUT ONLY ONLY IF YOU HAVE THE IDENTITY);

/*
 * First request a registration code from WhatsApp.
 *
 * @param $method
 *   Accepts only 'sms' or 'voice' as a value.
 * @param $countryCody
 *   ISO Country Code, 2 Digit.
 * @param $langCode
 *   ISO 639-1 Language Code: two-letter codes.
 *
 * @return object
 *   An object with server response.
 *   - status: Status of the request (sent/fail).
 *   - reason: Reason of the status (e.g. too_recent/missing_param/bad_param).
 *   - length: Registration code length.
 *   - method: Used method.
 *   - retry_after: Waiting time before requesting a new code.
 */
$w->codeRequest('sms');

```

i get this:

```
Array ( [cc] => 52 [in] => 6671565282 [lg] => es [lc] => MX [id] => ����qi0�o�h���\o�p [token] => 1qi2+pzrQ9XdCsSCxtCd++L9w78= [mistyped] => 6 [network_radio_type] => 1 [simnum] => 1 [s] => [copiedrc] => 1 [hasinrc] => 1 [rcmatch] => 1 [pid] => 8781 [rchash] => 2ca5231e5ff08898df5c107004da8204989d00da2c3b4d9f766b236209cc94de [anhash] => 9c02070f385a987a181bfbe5b5b58705 [extexist] => 1 [extstate] => 1 [mcc] => 334 [mnc] => 000 [sim_mcc] => 334 [sim_mnc] => 000 [method] => sms ) stdClass Object ( [status] => fail [reason] => blocked ) 
Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in C:\xampp\htdocs\Chat-API-master\src\Registration.php:314 Stack trace: #0 C:\xampp\htdocs\Chat-API-master\examples\exampleRegister.php(41): Registration->codeRequest('sms') #1 {main} thrown in C:\xampp\htdocs\Chat-API-master\src\Registration.php on line 314
```

its normal???

**Comment by mgp25** [comment]
`( [status] => fail [reason] => blocked )` means your number is blocked

**Comment by ingrocha** [comment]
Yes i now that but i canot put in a variable it shows me the error how can i get that variable!!!

**Comment by mgp25** [comment]
There is a beautiful wiki where it explains exactly how to deal with this, i guess you have not read this issue right? #556 

I invite you to read carefully the wiki: https://github.com/WHAnonymous/Chat-API/wiki
Read the event system functionality, you can bind a event to your own function, so you can print or do whatever you want to do with the received data.

Also you will find very useful examples in the `/examples` folder in the repository. You will find a lot of closed issues with examples too.

Regards

**Comment by ingrocha** [comment]
Ty for our help i read al de wiki but this dont sayhow cai get the reponse with out the error an traslate your api just print it

**Comment by mgp25** [comment]
@ingrocha i think you should check some PHP guides before asking this, what you are asking is not API related issue, is just basic php programming skills. (check try and catch)

Regards

**Comment by ingrocha** [comment]
I have solve the problem i just coment this from you fuction!!!

```php
throw new Exception
```

**Comment by mgp25** [comment]
@ingrocha WTF, you dont know even what you are doing, for God's sake!
