### ISSUE TITLE
curve25519 extension not working for windows 8

### ISSUE THREAD

**Issue by SnehalK12** [WHAnonymous/Chat-API#1473]
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\php\ext\php_curve25519_ts.dll' - %1 is not a valid Win32 application.
 in Unknown on line 0

**Comment by aal89** [comment]
See this [issue](https://github.com/WHAnonymous/Chat-API/issues/1446).

**Comment by mgp25** [comment]
Not API issue

**Comment by SnehalK12** [comment]
Yes its not api issue.. but for php_procol_buf.dll is working fine 
I have downloaded from http://windows.php.net/downloads/pecl/releases/protocolbuffers/
php_protocolbuffers-0.2.6-5.6-ts-vc11-x86.zip and its working fine..so where i can get curve25519 library....
