### ISSUE TITLE
using XAMPP in Windows, and in Windows Server.

### ISSUE THREAD

**Issue by wasimjee** [WHAnonymous/Chat-API#1475]
I am using the API in both , but unable to run.

Which PHP version should i use.

i tried with 5.2.17  in and its giving the following error on opening Login.php

    Parse error: syntax error, unexpected '[' in C:\Inetpub\vhosts\abctest.com\src\Login.php on line 57

even i tried with 5.3.29, 5.4.45, 5.5.30

**Comment by p031985s** [comment]
Hi there...

Requires: PHP Protobuf and Curve25519
PHP 6 and Above (I am not sure because it is not working on my server but with 5.6 solve the error on line 57)

**Comment by wasimjee** [comment]
@p031985s Can u help me in adding these two PHP protobuf and Curve dll ??
I mean where should i add in Xampp folder and what updates should i make in the files if any?

**Comment by p031985s** [comment]
Hi there...

Sorry, i do not have xammp, i use iis, but i will try later and i will answer.

**Comment by wasimjee** [comment]
@p031985s you on skype?

**Comment by mgp25** [comment]
Not API issue
