### ISSUE TITLE
sendSetPreKeys Results

### ISSUE THREAD

**Issue by wasimjee** [WHAnonymous/Chat-API#1492]
Earlier while using sendSetPreKeys() i was getting the following error

    rx <iq from="s.whatsapp.net" type="error" id="1452138005-2">
    rx   <error code="406" text="not-acceptable"></error>
    rx </iq>

the rechecked the codes and now after sending the prekeys through sendSetPreKeys() 
i am getting this result.

    rx <iq from="s.whatsapp.net" type="result" id="1452937433-2"></iq>

What does it mean, does it mean that the prekeys has been accepted by the Server?

or is there any method to get or check the prekeys from the server?

Please guide me.

**Comment by 0xTryCatch** [comment]
Use the code provided and everything will work
