### ISSUE TITLE
Error while receiving MSG with encrypted Picture

### ISSUE THREAD

**Issue by usinadeideia** [WHAnonymous/Chat-API#1496]
Hello everybody, 

I'm having trouble when I receive some messages,(file=https://mmi445.whatsapp.net/d/SdBwf1Mlc6zt7KCiHM1ur1aakOY/ApNwK1uI8ZhVWEDhAezTBUkObNYU5NDaWrJPX4DFQAD1.enc) Encrypted text messages get normal. How do I resolve to receive encrypted messages with image?

thank you

**Comment by mgp25** [comment]
Using events, `$file`  param

Regards
