### ISSUE TITLE
onPing problem

### ISSUE THREAD

**Issue by eduardobento** [WHAnonymous/Chat-API#768]
Hi,

I´m trying to use onPing event, but it never execute in the current API version. I had to change whatsprot.class.php to get the rx event. On line 2988 I added:
```php
			if (strpos($node->getAttribute("from"), Constants::WHATSAPP_SERVER) !== false)  {
                if (isset($this->nodeId['ping']) && ($this->nodeId['ping'] == $node->getAttribute('id'))) {
					$this->eventManager()->fire("onPing",
						array(
							$this->phoneNumber,
							$node->getAttribute('id')
						));
					$this->sendPong($node->getAttribute('id'));
				}
			}
```
And in the function sendPing() I changed the line:
```php
		$msgId = $this->createMsgId();
```
To this:

		$msgId = $this->nodeId['ping'] = $this->createMsgId();

It´s the only whay I see to resolve the problem, anybody have any problem like this ?

Thanks.

**Comment by WHAnonymous** [comment]
@eduardobento send a pull request
