### ISSUE TITLE
Function to change nickname?

### ISSUE THREAD

**Issue by lesander** [WHAnonymous/Chat-API#773]
Hello there,

First of all, thanks a lot for the Chat API! I've been it for a few days now, without any problems.
However, I'd like to change my number's nickname while being logged in to WhatsApp. I've searched the API documentation, but couldn't find anything. Is this possible?

Cheers,
Sander

**Comment by WHAnonymous** [comment]
@lesander 

Line 1709:
```php
    public function sendAvailableForChat($nickname = null)
```

You need to search in the code too!

**Comment by lesander** [comment]
Thanks @WHAnonymous. I guess I looked over that bit. I do think that the function's name is not quite representing it's purpose.
