### ISSUE TITLE
Trying to thread processing

### ISSUE THREAD

**Issue by 3gpvideos** [WHAnonymous/Chat-API#774]
Hello,

i am trying to thread the request response, as the attaching the images takes longer time, due to which all the other requests gets blocked/queued.

when i threaded it. there is a MAC mismatch issue..  like this:

```php
PHP Fatal error:  Uncaught exception 'Exception' with message 'MAC mismatch: 183 != 30' 
```

Any way to Solve this?

i this its due to the time takeing to load the image, and defered sending of the image makes it out of sync.

Let me know if any solution for this?

Thanks

**Comment by WHAnonymous** [comment]
You have exceeded the information you are sending / receiving.

**Comment by 3gpvideos** [comment]
No, it works when sending the simple text using the threads function or just normal text message.. 

but when i thread the function for image sending.. it takes atleast 30s to atatch the image from the url, within that time, the MAC mismatch happens..

any way to get the latest mac id or number? 
or
can you do a simple brief what does MAC do ? what's its purpose?

thanks
