### ISSUE TITLE
message verification code

### ISSUE THREAD

**Issue by manufuentescr** [WHAnonymous/Chat-API#775]
sorry if has no relation to the project

 days ago I get a whatsapp message with a verification code. Anyone know about this? There is a new method of verification? This will be false?

![img-20150601-wa0002](https://cloud.githubusercontent.com/assets/2752593/7921831/6d0b5aba-0865-11e5-88ba-a4ff56d5f136.jpg)

**Comment by CODeRUS** [comment]
Just for iphone where app can't detect incoming sms and activate automatically.
