### ISSUE TITLE
registerTool.php returns Warning: fgets() expects parameter 1 

### ISSUE THREAD

**Issue by myfranz** [WHAnonymous/Chat-API#777]
Hi,
can you help me?
When I open registerTool.php he returns this:

#################### # # # WA Register Tool # # # #################### Username (country code + number without + or 00):
Warning: fgets() expects parameter 1 to be resource, string given in /home/blablabla/registerTool.php on line 13
Type sms or voice:
Warning: fgets() expects parameter 1 to be resource, string given in /home/blablabla/registerTool.php on line 19
The provided phone number is not valid.

Thanks!!!

**Comment by rafaelkapela** [comment]
You must run via ssh: sudo php registerTool.php

**Comment by ducch** [comment]
no need for `sudo`. in fact, you shouldn't run this as root at all.

**Comment by WHAnonymous** [comment]
Its a CLI tool. You cant run it in browser

**Comment by anupam321** [comment]
$username = str_replace('+', '918011317370', trim(fgets(STDIN)));

I write this way but  this error arise  

#################### # # # WA Register Tool # # # #################### Username (country code + number, do not use + or 00):
Warning: fgets() expects parameter 1 to be resource, string given in /home/tmdynamicc/domains/tmdynamic.com/public_html/whatsapp/examples/registerTool.php on line 13
Wrong number. Do NOT use '+' or '00' before your number

**Comment by anupam321** [comment]
my country code is 91 and mobileno is 8011317370....when i write $username = str_replace('+', '918011317370', trim(fgets(STDIN)));  it returns  

#################### # # # WA Register Tool # # # #################### Username (country code + number, do not use + or 00):
Warning: fgets() expects parameter 1 to be resource, string given in /home/tmdynamicc/domains/tmdynamic.com/public_html/whatsapp/examples/registerTool.php on line 13
Wrong number. Do NOT use '+' or '00' before your number 


Type of warning...i also tried using 
$username = str_replace('+91', '8011317370', trim(fgets(STDIN)));
                 and
$username = str_replace('91', '8011317370', trim(fgets(STDIN)));

but not getting any result ..only warning message

link  :    http://tmdynamic.com/whatsapp/examples/registerTool.php




anupam

**Comment by WHAnonymous** [comment]
@anupam321 as its said in the previous comments, it's a CLI tool use it in terminal/cmd/console. You can run it via SSH or localhost. If you want a script that can run in a website, check `exampleRegister.php` and take it as reference
