### ISSUE TITLE
Error: There was an error with the AJAX request. XML/Json format is bad.

### ISSUE THREAD

**Issue by EgyptianM** [WHAnonymous/Chat-API#779]
hie there
I'm using whatsapp.php which in examples but I'm having this error when I select my number from the "From" dropdown list or press send.
Any help with that?
I searched and didn't find any answer although many people asked this question.
thank you in advane

**Comment by EgyptianM** [comment]
sorry I used a wrong password coz I logged in with my number with my phone so I needed I new password
registering my number again solved the issue :)
regards

**Comment by phoenix-blue** [comment]
Hi, 
I have here the same problem,  only after a few times registering my phone number I have the idea that this is not the problem. 
Are there maybe other points to check? 
Regards

**Comment by pptyasar** [comment]
How to get pass @EgyptianM
