### ISSUE TITLE
Can't update the chat avatar.

### ISSUE THREAD

**Issue by TriPSs** [WHAnonymous/Chat-API#784]
Every time i try to update the chat avatar the server stops end i have to restart it again.
Is this an bug in the API or in my code?

**Comment by WHAnonymous** [comment]
@TriPSs in your code. It's working. Show your debug and code

**Comment by TriPSs** [comment]
My code:
> private function updateAvatar ($avatar) {
>        $this->w->sendSetProfilePicture ( $avatar[ 'message' ] ); // Set our profile picture
>    }

Where message is the full url to the image, image is an square.
Now when i start he stops immediately because the change avatar is the first task to do 

Complete debug log:

==========06-06-2015 08:48==========
==================================
Starting server
Setup Database
Set listeners
Listeners set
Connect with whatsapp servers
Login
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="31647482654">\F4X\A3\FF31647482654\8B"q\D5k\88\AC*\AEv>\00\82\FF\E2*\A71433594920</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>\DB\DO\A7j\86\C3o\D4[\E2\E8_\F4\BD\FD\B3</challenge>

tx  <response>\DF O6\D9n\95\F2 aoCS\C3<\8D%z:|\8E\BA-\BF>\E1\BD|\A4\B1G</response>

rx  <success t="1433594920" props="4" kind="free" status="active" creation="1426971466" expiration="1458507466">\C02)FR\D0\A6\85@ګQߣ\AD\\E5H</success>

tx  <presence name="xxxxxxxxxx"></presence>

Login complete
tx  <iq id="1" xmlns="jabber:iq:privacy" type="get">
tx    <query>
tx      <list name="default"></list>
tx    </query>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="xxxxxxxxxx@s.whatsapp.net"></presence>

rx  <presence from="xxxxxxxxxx@s.whatsapp.net" type="unavailable" last="1433592140"></presence>

rx  <presence from="xxxxxxxxxx@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="xxxxxxxxxx@s.whatsapp.net" type="unavailable" last="1433594844"></presence>

rx  <iq from="31647482654@s.whatsapp.net" id="1" type="error">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="2" xmlns="urn:xmpp:whatsapp:push" type="get" to="s.whatsapp.net">
tx    <config></config>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="2" type="error">
rx    <error code="404" text="item-not-found"></error>
rx  </iq>

tx  <iq id="3" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="4" xmlns="urn:xmpp:whatsapp:sync" type="get">
tx    <sync mode="delta" context="background" sid="130780721200000000" index="0" last="true">
tx      <user>+xxxxxxxxxx</user>
tx      <user>+xxxxxxxxxx</user>
tx      <user>+xxxxxxxxxx</user>
tx      <user>+xxxxxxxxxx</user>
tx    </sync>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="3" type="result">
rx    <props version="4">
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="qr" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="audio" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="image_max_edge" value="1280"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="max_participants" value="101"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx    </props>
rx  </iq>

rx  <iq from="31647482654@s.whatsapp.net" id="4" type="result">
rx    <sync index="0" sid="130780721200000000" last="true" version="1433530199165015">
rx      <in>
rx        <user jid="xxxxxxxxxx@s.whatsapp.net">+31683598869</user>
rx        <user jid="xxxxxxxxxx@s.whatsapp.net">+31683207574</user>
rx        <user jid="xxxxxxxxxx@s.whatsapp.net">+31653508721</user>
rx        <user jid="xxxxxxxxxx@s.whatsapp.net">+31653160575</user>
rx      </in>
rx    </sync>
rx  </iq>

rx  <iq from="xxxxxxxxxx@s.whatsapp.net" id="1d" type="result">
rx    <picture id="1433371734" type="preview"> 4445 byte data</picture>
rx  </iq>

tx  <iq id="1e" type="get" xmlns="w:profile:picture" to="31615025961@s.whatsapp.net">
tx    <picture type="preview"></picture>
tx  </iq>

rx  <iq from="xxxxxxxxxx@s.whatsapp.net" id="1e" type="result">
rx    <picture id="1388331293" type="preview"> 3047 byte data</picture>
rx  </iq>

tx  <iq id="1f" type="get" xmlns="w:profile:picture" to="31642504370@s.whatsapp.net">
tx    <picture type="preview"></picture>
tx  </iq>

rx  <iq from="xxxxxxxxxx@s.whatsapp.net" id="1f" type="result">
rx    <picture id="1430336686" type="preview"> 4363 byte data</picture>
rx  </iq>

Updating server status
Startup complete server is running
==================================




He always does $this->w->pollMessage (); bevore every task he executes in the code.

**Comment by 0xTryCatch** [comment]
Can you show your PHP code please?

**Comment by TriPSs** [comment]
/**
     * Runs the server
     */
    private function run () {
        try {
            //Setup the query once for getting messages to send
            $querySend = $this->pdoDB->getConn ()->prepare ( $this->queryGetOutGoing );
            $querySend->bindparam ( ":companynr", $this->username, PDO::PARAM_STR );

            $time = time ();
            $keepRunning = true;

            while ( $keepRunning ) {
                $this->w->pollMessage ();

                if ( !$this->sendingMessage ) {
                    $querySend->execute ();

                    while ( $record = $querySend->fetch ( PDO::FETCH_ASSOC ) ) {
                        $this->sendingMessage = true;
                        switch ( $record[ 'type' ] ) {
                            case "block":
                                //To keep it clean handle blocking in other function
                                $this->blockContact ( $record );
                                break;

                            case "archiveContact":
                                $this->archiveContact ( $record );
                                break;

                            case "avatar":
                                $this->updateAvatar ( $record );
                                break;

                            case "deleteContact":
                                $this->deleteFromContacts($record[ 'target' ]);
                                break;

                            default:
                                //To keep it clean handle sending in other function
                                $this->sendMessage ( $record );

                        }

                        $queryDel = $this->pdoDB->getConn ()->prepare ( $this->queryDeleteMessage );
                        $queryDel->bindparam ( ":companynr", $this->username, PDO::PARAM_STR );
                        $queryDel->bindparam ( ":id", $record[ 'id' ], PDO::PARAM_INT );
                        $queryDel->execute ();

                    }

                    $this->sendingMessage = false;
                }

                if ( $time + 60 <= time () ) {
                    //Check every 60 sec the file
                    $keepRunning = $this->keepRunning ();
                } else if ( $time + 110 <= time () ) {
                    $keepRunning = $this->keepRunning ();
                    $this->w->sendPing ();
                    $time = time ();
                }
            }

            $this->updateServerFile ( "stop" );

        } catch ( Exception $e ) {
            $this->updateServerFile ( "stop-error" );
        }
    }

**Comment by 0xTryCatch** [comment]
Thanks, can you also post the URL of the image you are trying to set? I can try it from my side then.

**Comment by TriPSs** [comment]
I tryed it with the full url:
http://api.watermelon.nl/assets/companys/profile/1/avatar.png

And with:
assets/companys/profile/1/avatar.png

And with:

{root home} /assets/companys/profile/1/avatar.png

**Comment by TriPSs** [comment]
Could you reproduce the error?

**Comment by mgp25** [comment]
@TriPSs did you know that what you are doing is something we dont support? I have checked your website

**Comment by TriPSs** [comment]
Yes i know that, and i'm not asking any support for it. would just like to know how i could fix this or where i need to look.
