### ISSUE TITLE
Group ID Format

### ISSUE THREAD

**Issue by aymanrb** [WHAnonymous/Chat-API#785]
If I get this (20100XXXXXXX-1422863211) when I receive a message from a group as the `$from_group_jid` parameter ... what am I expected to use as the group id to send a message back to the group ?

I tried both: 
1- 20100XXXXXXX-1422863211
2- 1422863211

and it didn't work. Please advice the correct format and is there a method I need to call before using the `$this->SendMessage($gid, $msg);` method ?

**Comment by WHAnonymous** [comment]
@aymanrb `$w->sendMessage($gid, $msg);`

`sendGetGroups()`

**Comment by aymanrb** [comment]
Thanks @WHAnonymous but I was asking about the correct format for the $gid parameter cuz i tried both strings presented in my question and it did not work

**Comment by aymanrb** [comment]
Ok sorry for bothering you with such a silly question, this worked `20100XXXXXXX-1422863211` but I had another method that validates the number before actually calling the `sendMessage` method and that failed to validate the group id obviously :cry:
