### ISSUE TITLE
Check if there is any error and the message didn't send

### ISSUE THREAD

**Issue by foxpcteam** [WHAnonymous/Chat-API#787]
Hi,
how can i check if there is any error and the message didn't send?

i want to make "backup number" so if i will get some error i will try to send the message with other number.

i looked at FAQ but did not found any example where i can check id there was any error.

if ($any_error) {
my new code
} 

Thanks

**Comment by WHAnonymous** [comment]
Use events

**Comment by foxpcteam** [comment]
Hi,
can you please give some example (code)?

Thanks

**Comment by ducch** [comment]
It really depends, but check the [events wiki page](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#list-of-all-events). Consider `onGetError`, specifically.

**Comment by MoudiZd** [comment]
@foxpcteam  you can handle the error using the try catch

Regards !

**Comment by MoudiZd** [comment]
@ducch  The wiki is not clear enough and did not explain how to use each event it is just listing events and for some events it gives a small example so reading wiki really is not just enough

Regards !
