### ISSUE TITLE
How send messages to my service customers

### ISSUE THREAD

**Issue by steelrayx** [WHAnonymous/Chat-API#788]
I have a service with a 3000 customers. And need to send about 200-300 notification per day about some events (events like - need payment, small balance, out of space etc).
Before, I sended them sms messages, but it much cost for me. 
I tried to add it all to contact list of my service number, but it banned whatsapp on sending.
I think it like a spam to whatsapp engine.
Is there any way to use whatsapp in this purpose?

**Comment by 0xTryCatch** [comment]
No

**Comment by Iniro** [comment]
what if u get about 10 wpp accounts?
i need something similar

**Comment by 0xTryCatch** [comment]
You will be blocked, guaranteed.
