### ISSUE TITLE
Question: why emojis were left out from code?

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#789]
I've follow the last changes on the code and I can't find where emojis are processed right now. Some versions ago this was very clear. Can somebody help here?

**Comment by 0xTryCatch** [comment]
The idea is that people use utf-8 in their code which is the standard for quite some time now.

**Comment by WHAnonymous** [comment]
@hgc2002 its easy right now (utf8 bytes)

```php
$msg = "Hello \xF0\x9F\x98\x84 !";
```

http://apps.timwhitlock.info/emoji/tables/unicode

**Comment by hgc2002** [comment]
I see. Thanks guys!!!
