### ISSUE TITLE
Deleting groups

### ISSUE THREAD

**Issue by pankajhti** [WHAnonymous/Chat-API#791]
Sir,
i created 2 groups. each group containing 20 contacts. Now i want to delete one group.
how can i delete it. please help me.
Thank you

**Comment by infoquestsolutions** [comment]
You need to remove everyone from group and then leave group yourself. Then you can delete group.

**Comment by pankajhti** [comment]
thank you so much sir for replying
but how can i remove

**Comment by pankajhti** [comment]
using OnGroupsChatEnd()
 we can delete group or not

**Comment by WHAnonymous** [comment]
Read the wiki, it exists for some reason
