### ISSUE TITLE
how to check the expiration date

### ISSUE THREAD

**Issue by jacoboliveira** [WHAnonymous/Chat-API#792]
Hello my friends, I have a question: how to check the expiration date whatsapp.
Is there any function in api that shows the expiration date (example milliseconds) my whatsapp.
Thanks in advanced.

**Comment by WHAnonymous** [comment]
@jacoboliveira Use chat api, is the only updated code.

in the success node you will find expiration time, read the wiki for its event

**Comment by jacoboliveira** [comment]
Okay thanks @WHAnonymous
