### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by rcetrangolo** [WHAnonymous/Chat-API#794]
Hi all.

I went to https://github.com/venomous0x/WhatsAPI and saw the WhatsApp letter.
Could you explain us better the consecuences of that letter?

Are we breaking the law if we use 'WhatsAPI' (Chat-API)?
The problem was just the name? it seems not.
What is the future of the API/project? Do you continue to support it? If WA makes changes to its software, we can rest assured you'll incorporate them to the API?

I'll reallly appreciate a clear answer, the future is quite shady

**Comment by WHAnonymous** [comment]
@rcetrangolo read WhatsApp EULA and https://github.com/WHAnonymous/Chat-API#terms-and-conditions

**Comment by rcetrangolo** [comment]
I don't want to spam or massive marketing, I just want to use the API as a
kind of text IVR, so I need a minimum of certainty that the project won't
go down and you still supporting it.

You request for donations, right? what about to donate an ammount of money
in order to receive direct support in case of troubles? we can think about
it?

thank you
