### ISSUE TITLE
How to save identity when requesting sms code

### ISSUE THREAD

**Issue by momostafa** [WHAnonymous/Chat-API#799]
Hello,

I am using below code to request SMS code and I receive the code, but i can't get the ID "identity" variable to save it so i can use it in case i want to change the password.

Thanks for your help

```
$w = new WhatsProt($username, $nickname, $debug);

$option = $_POST["method"];
echo "Request Type: $option </br> \n";
echo "\r\n";

try {
    $result = $w->codeRequest(trim($option));
//$id = $result->id;
    echo "\nYour ID is: " . $result->id . "</br>";
} 
catch (Exception $e) {
echo "\r\n";
    echo $e->getMessage();
echo "\r\n";
}
```

**Comment by WHAnonymous** [comment]
Identity is automatically stored

**Comment by momostafa** [comment]
I know that they are stored in wadata folder in .dat but i want to be able to store them in my database
