### ISSUE TITLE
Keep receiving messages after blocked

### ISSUE THREAD

**Issue by berlan** [WHAnonymous/Chat-API#802]
As far as I am concerned, when Whatsapp blocks your number there's no possibility of sending anything else from there.

Also, by the way I am learning Whatsapp process, to receive new messages you need to have number's presence "alive", so that it connects to Whatsapp servers, and brings the new stored messages in there (answers to sent messages).

If blocked, is presence still alive? Could I keep receiving messages, but not sending anything from a blocked number?

Thank you in advance.

**Comment by WHAnonymous** [comment]
@berlan No, if you are bloced you can't receive messages neither login. If you have blocked an user, you wont receive any message anymore.
