### ISSUE TITLE
Detecting "User seen" status

### ISSUE THREAD

**Issue by PHPian** [WHAnonymous/Chat-API#809]
I wonder how we can find if the user has read a message. In essence, I am looking for an event that is equivalent to the double ticks becoming blue from gray.

**Comment by WHAnonymous** [comment]
@PHPian that event isn't done. If you want code yourself and make a pull request

**Comment by PHPian** [comment]
@WHAnonymous 
Trying out stuff, I actually found this to be working (or so I feel). The trigger is onMessageReceivedClient and the parameter $type = "read"  

Am I missing something.

**Comment by WHAnonymous** [comment]
@PHPian you are right, if the message is read, type will be equal 'read', but only if they have the read receipt enabled

**Comment by PHPian** [comment]
@WHAnonymous 
Thanks for reconfirming. Now, I tried to look for a "read receipt" feature on my WA on the phone. Don't see any. Where does one enable/disable it ?
