### ISSUE TITLE
Integration with Whatsapp Web

### ISSUE THREAD

**Issue by alxhotel** [WHAnonymous/Chat-API#811]
Hi !

Does this API have a support for Whatsapp Web ?

So, I would like to send and receive messages with Chat API, but also have the possibility of sending them through Whatsapp Web.

I guess, that requires a program to be running all the time, so that it can receive and send messages to the Web. And also have a method to pair it with the Web

Any ideas ? Is this planned ?

**Comment by 0xTryCatch** [comment]
WhatsApp Web will not be integrated because it is very time consuming and does not add much

**Comment by alxhotel** [comment]
It gives you a nice interface

**Comment by WHAnonymous** [comment]
@alxhotel No, if you want it, you can code it yourself, maybe i'll do it for me, you can also do it for you.

**Comment by alxhotel** [comment]
Ok, thanks
