### ISSUE TITLE
Request Last seen

### ISSUE THREAD

**Issue by modsfabio** [WHAnonymous/Chat-API#812]
When I do `$w->sendGetRequestLastSeen(NUMBER);` I don't get any answer to this function:
`onGetRequestLastSeen( $mynumber, $from, $id, $seconds )`

I have added the follwoing line: `$w->eventManager()->bind('onGetRequestLastSeen', 'onGetRequestLastSeen');`

I'm not getting a privacy error or anything. Just no response. Anyone an idea?

**Comment by WHAnonymous** [comment]
@modsfabio post debug + code
