### ISSUE TITLE
Sync workflow doubt

### ISSUE THREAD

**Issue by chcibelli** [WHAnonymous/Chat-API#813]
Im using the api to make a BOT thats answers question for some keywords.

When the user send any keyword i make the following steps:

1 - check in my database if i have the from number stored and also synced (just a field that store if i alread sendSync this)
2 - if dont, i use sendSync(array($number),null,3) to sync specific user one time
3 - if sendSync gets ok i store the user number and also flag as synced
4 - Then i answer with a message for the user based on the input keyword

Questions:
1 - is this workflow ok?
2 - i need/can  sendSync the user before each message? i was banned a few weeks ago (but then i wasnt syncing the numbers, just answering)
3 - I also need to sync again ALL my stored numbers on login?

Sorry but i cant get the answer reading the wiki and other issued. I was banned 

Thanks a lot for your help

**Comment by WHAnonymous** [comment]
1- Yes, but only syncs contacts once in the number life time
2- No, only once
3- No

If you send messages for personal usage only you wont be blocked
