### ISSUE TITLE
How to get all chat data history of a group with media (images. audios and videos)?

### ISSUE THREAD

**Issue by mohit-k-shrivastava** [WHAnonymous/Chat-API#816]
Hello Team,

I am using this api and able send and receive messages when logged in or when my chat session is active. 
I have created few groups and added member as well, also I became the group admin of all group. 
Now I want to read all old chat history of my group, but could not find any way to do that.

Request you to please help in this issue(with example). 

Thanks
Mohit

**Comment by WHAnonymous** [comment]
@mohit-k-shrivastava you can't, once you have received the messages you can't redownload them, WhatsApp server removes all messages once you get them. In the wiki you will find an instruction that will save all the messages in a database, so you can have your chat history.

**Comment by mohit-k-shrivastava** [comment]
Thanks
