### ISSUE TITLE
how to register a transmission in broadcasting?

### ISSUE THREAD

**Issue by jacoboliveira** [WHAnonymous/Chat-API#817]
I'm trying to register a broadcasting with a name and include some numbers to this transmission with a name, but I knew not which function to use in my phone have this option to create a broadcasting with a name and add the contacts, I wonder how this sendBroadcastVcard function, I would spend an example of what the parameters.
Thanks in advanced!

**Comment by WHAnonymous** [comment]
@jacoboliveira i don't understand your question. Anyways:

sendBroadcastVcard: https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L1930

How to create VCard: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#sending-vcards

Read wiki and check code before opening a new issue, everything it's already explained, check #556 for more info about how to search content in the repo. 

If you have any other issue, let me know
