### ISSUE TITLE
Cannot set up the Chat API

### ISSUE THREAD

**Issue by joseeloren** [WHAnonymous/Chat-API#818]
I tried "sudo composer require whatsapp/chat-api" with composer installed. I got: 

  Problem 1
    - The requested package whatsapp/chat-api No version set (parsed as 1.0.0) could not be found.
  Problem 2
    - The requested PHP extension ext-sqlite3 * is missing from your system.
  Problem 3
    - Installation request for whatsapp/chat-api ^2.5 -> satisfiable by whatsapp/chat-api[v2.5].
    - whatsapp/chat-api v2.5 requires ext-sqlite3 * -> the requested PHP extension sqlite3 is missing from your system.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

What's the problem? I installed sqlite3, but it didn't help me.

**Comment by joseeloren** [comment]
Update:

  Problem 1
    - The requested package whatsapp/chat-api No version set (parsed as 1.0.0) could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

I needed php5-sqlite package.

**Comment by WHAnonymous** [comment]
@joseeloren i'll check tomorrow, thx for noticing
