### ISSUE TITLE
Uncaught exception 'LoginFailureException'.

### ISSUE THREAD

**Issue by kuzevanoff** [WHAnonymous/Chat-API#819]
So i've regisrated my number. i'v got code. i'v done this code:
```php
$w->codeRequest('sms');
$code = 'here is my code';
```
Than in console i got password.
```
Array
(
    [in] => here is my in
    [cc] => here is my cc
    [id] => here is my id

    [lg] => ru
    [lc] => RU
    [sim_mcc] => here is my sim_mcc
    [sim_mnc] => ere is my sim_mnc
    [method] => sms
    [token] => here is my token
)
stdClass Object
(
    [status] => ok
    [login] => here is my login
    [pw] => Here is my pwd
    [type] => existing
    [expiration] => 1464606469
    [kind] => free
    [price] => 33,00 руб.
    [cost] => 33.00
    [currency] => RUB
    [price_expiration] => 1438378141
)
```

If i trying to send message, using my login and password i see smth like:

```
Fatal error: Uncaught exception 'LoginFailureException' in/src/whatsprot.class.php:2243
Stack trace:
#0 /src/whatsprot.class.php(541): WhatsProt->doLogin()
#1 /src/index.php(30): WhatsProt->loginWithPassword('2vyvSE4W3I+YtGC...')
#2 {main}
  thrown in /src/whatsprot.class.php on line 2243
```

I tryed with two diffrent numbers. But i have no success

**Comment by JRM93** [comment]
I have the same error, please provide with solution if possible

**Comment by WHAnonymous** [comment]
Please use example scripts, everything is working, if you still facing this error, post your script code here and i'll help you.

**Comment by kuzevanoff** [comment]
It's doesn't work!!!
Ok, so now i'v downloaded examples.
in file exampleRegister.php i'v configurated my phone and username.
Than i'v callde 
$w->codeRequest('sms');

I'v got a code via sms. 
Than i'v commented //$w->codeRequest('sms');

and i'v called $w->codeRegister('127678');

In console i HAVE NO debug messages.

if i remove comments from line with $w->codeRequest('sms'); 
And than my script is
$w->codeRequest('sms');
$w->codeRegister('127678');

I see some debug messages with my password. But if i using this password to do authentication - i'v error Uncaught exception 'LoginFailureException'. 

So fix it please
Regards.

**Comment by mgp25** [comment]
@kuzevanoff 

1. Quote code
2. Read wiki
3. Set debug to `true` in order to see debug log
4. Read 2. It seems you are doing it wrong

And use `registerTool.php` everything is explained in the wiki.

**Comment by kuzevanoff** [comment]
I'v retryed. It's doesn't work. Please before post your answer try to do it by yourself. 
After receving password my code is next
$username = "79...."; // Your number with country code, ie: 34123456789
$nickname = "....."; // Your nickname, it will appear in push notifications
$debug = true;  // Shows debug log

// Create a instance of WhastPort.

$w = new WhatsProt($username, $nickname, true);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword("I0Hy/XtK/pkEexKcZXvexLm/Q6Q="); 


But i've


Fatal error: Uncaught exception 'LoginFailureException' in /Users/.../Desktop/wh/src/whatsprot.class.php:2243
Stack trace:
#0 /Users/..../Desktop/wh/src/whatsprot.class.php(541): WhatsProt->doLogin()
#1 /Users/...../Desktop/wh/src/test.php(17): WhatsProt->loginWithPassword('I0Hy/XtK/pkEexK...')
#2 {main}
  thrown in /Users/....../Desktop/wh/src/whatsprot.class.php on line 2243

**Comment by mgp25** [comment]
@kuzevanoff of course i tried myself, i did that script too!

If you want, send me your credentials via mail, and ill tell whats happening with your account

Regards

**Comment by kuzevanoff** [comment]
i can do for you small screencast. Is it ok for u ?

**Comment by kuzevanoff** [comment]
I don't know why. I don't edited some code but now it's seems to be working..

It's a magic..
