### ISSUE TITLE
Constants > User Agent

### ISSUE THREAD

**Issue by momovil** [WHAnonymous/Chat-API#820]
Hi @mgp25 @CODeRUS, I'm activating the phone number with a Samsung S4 and WA PW Exctractor. I want to know if I can change the User Agent in the Constants file. I read there may be problems with the encription of messages when we change it. Which is the User Agent for a S4 Samsung GT- i9500 with Android 4.4.2. Thanks

**Comment by WHAnonymous** [comment]
@momovil you can change it, but it has nothing to do with the API, UA only takes action during registration as its http requests, once you are registered, UA is not used anymore. Nevertheless, you can change it.
