### ISSUE TITLE
Contact sync with delta & interactive fails most of the time, but not all

### ISSUE THREAD

**Issue by hgc2002** [WHAnonymous/Chat-API#822]
Since several days I've started receiving "nothing" (empty response) when I try to make a contact sync with delta and interactive options.

Here is an example of the request sent to server:
```xml
 <iq id="2" xmlns="urn:xmpp:whatsapp:sync" type="get">
    <sync mode="delta" context="interactive" sid="130801459640000000" index="0" last="true">
      <user>+12345</user>
      <user>+12345</user>
      <user>+12345</user>
      <user>+12345</user>
      <user>+12345</user>
      <user>+12345</user>
      <user>+12345</user>
    </sync>
  </iq>
```

(here +12345 is used to mask the real phones on this question)

And response is simply nothing. But then sometimes we got the right response. I've not changed anything in the code. This request is done after a login, then the sync and later a logout and stop. I do not cycle with this code.

Have somebody seen something like this?

Regards,
Herman.

**Update 1:** Still failing. There is nothing between succesfull login and the next sync, on the tracing. 
I'm trying now with a ping in the middle...

**Update 2:** Not working. Now changing the sendSync to last = false

**Update 3:** Ok, not conclusive. I've found several things, mixed in different ways.

First of all sending the ping request bloated the pipeline. Avoid doing this.

Without that, sometimes it looks like you have been blocked but wasap does not tell you anything. It simply stops responding to requests. next login fails and then you find it out.

But other times it works as usual (currently i'm using sendSync with last = false), I mean fine.

**Comment by hgc2002** [comment]
Still failing. There is nothing between succesfull login and the next sync, on the tracing. 
I'm trying now with a ping in the middle...

**Comment by hgc2002** [comment]
Not working. Now changing the sendSync to last = false

**Comment by hgc2002** [comment]
Ok, not conclusive. I've found several things, mixed in different ways.

First of all sending the ping request bloated the pipeline. Avoid doing this.

Without that, sometimes it looks like you have been blocked but wasap does not tell you anything. It simply stops responding to requests. next login fails and then you find it out.

But other times it works as usual (currently i'm using sendSync with last = false), I mean fine.

**Comment by WHAnonymous** [comment]
@hgc2002 it's working, i have tried right now:

```xml
rx  <iq from="00000000000@s.whatsapp.net" id="1" type="result">
rx    <sync index="0" sid="130802714700000000" last="true" version="1432630171102743">
rx      <in>
rx        <user jid="123456789@s.whatsapp.net">+123456789</user>
rx      </in>
rx    </sync>
rx  </iq>
```

code with default data:

```php
$w->sendSync(array('123456789'));
```

If you still have errors, let me know, but make sure to post the answer of the `iq` too, because it seems you are desconnecting to fast you don't get the answer from WA server, try this, right after calling `sendSync`

```php
while (1) {
$w->pollMessage();
}
```

**Comment by hgc2002** [comment]
Nop, I'm disconnecting 30 secs after making the sendSync. And the 30 secs cycle is making a 2 secs delay and then a poolMessage, 2 secs and pooling again, and so on until 30 secs.

And the issue does not happen all the time, just randomly, so having done fine once does not means it will work again later.

About the iq response, the thing is that I don't get any response at all, not a wrong response. Even detecting that case and sending the sendSync again, the result is still none.

**Comment by WHAnonymous** [comment]
@hgc2002 you always get a response from the server, if you don't get that response, you connection isn't right or you are doing something wrong. Try this script as many times you want, it should work (supposing you are running it in a local machine):

```php
<?php
require_once('/Chat-API/src/whatsprot.class.php');

$username = '***';
$nickname = 'Test'; 

$w = new WhatsProt($username, $nickname, true);
$w->connect();

$w->loginWithPassword($password);

$number = '';
$w->sendSync(array($number));

while (1) {
    $w->pollMessage();
}
```
