### ISSUE TITLE
How to detect the moment when users change whatsapp phone number?

### ISSUE THREAD

**Issue by alexmercury** [WHAnonymous/Chat-API#823]
Hi,

I wanted to ask if there is a possibility to detect when a user changes their whatsapp number. Whatsapp client catches it in the following way: 
![number change](https://cloud.githubusercontent.com/assets/4478912/8450489/0b1cc226-1fe4-11e5-9365-c68c4665abdd.jpg)

Is this implemented in the library? I need to catch this moment in order to avoid duplicating of the same user but with different phone numbers. 

Thanks in advance for your help.

**Comment by WHAnonymous** [comment]
@alexmercury yes, you receive a notification, if you send me the node i'll add as event

**Comment by alexmercury** [comment]
Hi @WHAnonymous

here is the node which I received when changing the number:

```xml
<notification from="0000000000000-1434967022@g.us" id="3543980452" participant="111111111111@s.whatsapp.net" type="w:gp2" t="1435832228" notify="WhatsApp">
  <modify>
    <participant jid="222222222222@s.whatsapp.net"></participant>
  </modify>
</notification>
```
11111111111 - the old number, before change
22222222222 - the new/target number

**Comment by assegaf** [comment]
that event on the group that your account also a member too ?
or that event is your contact directly, both of you added each other number ?

**Comment by CODeRUS** [comment]
@assegaf it's obvious this event is from group

**Comment by alexmercury** [comment]
@assegaf, yes @CODeRUS is right, that is an event from the group I belong to.

**Comment by mgp25** [comment]
@alexmercury it should work now

Regards
