### ISSUE TITLE
Composer not able to install on windows

### ISSUE THREAD

**Issue by rahulserver** [WHAnonymous/Chat-API#824]
I installed composer and downloaded zip of this repo. Then when I run composer require whatsapp/chat-api, I get below exception:

```
D:\WhatsappAutomation\PHP-Chat-API-master>composer require whatsapp/chat-api
Using version ^2.5 for whatsapp/chat-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package whatsapp/chat-api No version set (parsed as 1.0.0) c
ould not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further commo
n problems.

Installation failed, reverting ./composer.json to its original content.

D:\WhatsappAutomation\PHP-Chat-API-master>
```

**Comment by 61l50n** [comment]
How can i install? cause always composer lock..

{
    "_readme": [
        "This file locks the dependencies of your project to a known state",
        "Read more about it at https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file",
        "This file is @generated automatically"
    ],
    "hash": "adae22cfca68e95a08ff162a71b01597",
    "packages": [],
    "packages-dev": [],
    "aliases": [],
    "minimum-stability": "stable",
    "stability-flags": [],
    "prefer-stable": false,
    "prefer-lowest": false,
    "platform": {
        "php": ">=5.3",
        "ext-curl": "*",
        "ext-gd": "*",
        "ext-sockets": "*",
        "ext-openssl": "*",
        "ext-pdo": "*",
        "ext-sqlite3": "*"
    },
    "platform-dev": []
}
