### ISSUE TITLE
Return sendGetProfilePicture, sendGetRequestLastSeen instead of echo

### ISSUE THREAD

**Issue by yagerstano** [WHAnonymous/Chat-API#825]
Hi, and thank you so much for your efforts.
Could you help with the two events above, we need to get the info in return to calls instead of echoes so it would be possible to store in an array :

 fputcsv( $newFile, explode("," , $csvData[$c] . "," . $wProt->sendGetProfilePicture($csvData[$c], true) . "," . $wProt->sendGetRequestLastSeen($csvData[$c]) ));

**Comment by mgp25** [comment]
Bind events to those calls, and return the data from the event's function. There is an explanation here about how to use events:

- [How to use events](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#using-events)
- [Examples](https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#requesting-last-seen-and-profile-picture)

If you have any other doubt, let me know

Regards
