### ISSUE TITLE
My number is blocked

### ISSUE THREAD

**Issue by allaga** [WHAnonymous/Chat-API#826]
Hello :)

I foolishly sent several groups too much text and I was blocked for the third day on the block

what will advise?

thank :)

**Comment by hansrouge** [comment]
1. Dont use the api for spamming.
2. Register a new number.

**Comment by allaga** [comment]
but I do not spam sent out, and the announcement of the upcoming event

**Comment by mgp25** [comment]
@allaga WhatsApp don't know wether is spam or not, all kind of bulk messaging is considered spam in WhatsApp, consider using broadcast instead.

Regards

**Comment by m1m6** [comment]
@mgp25  can u please check my problem ??

**Comment by allaga** [comment]
number ever to recover from the banned?

**Comment by hansrouge** [comment]
@allaga after ~ 2 month you can register it again.
