### ISSUE TITLE
How to send message only if contact is online?

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#830]
I'm trying to figure out a way to send message only if contact is online.
I've tried sendPresenceSubscription but it returns the presence status in command line and I was not able to store it to a variable, so is there any way I could automate & send message only if contact is online?
Thanks!

**Comment by mgp25** [comment]
Use event manager: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#using-events

List of all events: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#list-of-all-events

Regards

**Comment by kumaramit1996** [comment]
How do I store the result(displayed in CLI) by sendGetRequestLastSeen into a variable and then extract the if the contact were online or not through it?
I'm trying to build something which will send message to an array of contacts(namely admins) - and it will send only if they are online, else it will send to most recent(in terms of last seen). How do I code it?

**Comment by mgp25** [comment]
@kumaramit1996 i told you in the previous comment, you need to use event system, bind a function to the event and from there you can do whatever you want

Regards
