### ISSUE TITLE
WhatsApp system didn't work again

### ISSUE THREAD

**Issue by spywalkers** [WHAnonymous/Chat-API#831]
Hello WHAnonymous, I wanna ask about the sudden blocked numbers. It was worked for 3 months for our hourly scheduled information until today. Then it services stopped (at 8 July 2015, about 09:00-10:00 AM GMT+8) because I checked using BlockChecker which said that the number is blocked. Can I switch the number to a new one? or there is a change for request code?
```
(
    [in] => 8xxxxxxxxx
    [cc] => xx
    [id] => li‗ùg©°¥¾l»‗ÛçØå▲■→<
    [lg] => id
    [lc] => ID
    [sim_mcc] => 510
    [sim_mnc] => 000
    [method] => sms
    [token] => 0382c1b83cac285e2be22f95e8663612
)
stdClass Object
(
    [status] => fail
    [reason] => blocked
)
There was a problem trying to request the code.
```

**Comment by mgp25** [comment]
@spywalkers Your number is blocked, you can register it again neither reset the password, you need to use another number, if you think this is a mistake, try contacting WhatsApp Support and telling that your number was being used in your mobile device and suddenly stopped working.

Regards

**Comment by spywalkers** [comment]
I see. 
I can change the broadcast sender for some groups which I've set as an admin there. Some others still cannot work. 
The new sender is a number which blocked at 2-3 months ago because of broadcasting messages to many numbers that is not registered. So maybe the server renewed it as a new ID. Hope it can be a useful information that **your blocked number will can be used again at 2-3 months later**.

Regards
