### ISSUE TITLE
I want to be my number this added to the receiver's mobile phone?

### ISSUE THREAD

**Issue by jacoboliveira** [WHAnonymous/Chat-API#834]
Hello friends,
as whether the number where I'm sending the message that added the contacts of the receiver?
I want to be my number this added to the receiver's mobile phone?
Its know?
Thanks in advance

**Comment by mgp25** [comment]
@jacoboliveira i think, you want to say this: "Is it possible to know if a contact have my number added as a contact?"

No, is not possible.

Regards
