### ISSUE TITLE
Sending image via whatsapp api using c#

### ISSUE THREAD

**Issue by m1m6** [WHAnonymous/Chat-API#835]
hello i'm trying to send an image using c#

but the image not delivered and there is no exception message !!!

here's my code 

        byte[] img = File.ReadAllBytes("e:\\img.gif");
            wa.OnConnectSuccess += () =>
            {
                MessageBox.Show("Connected to whatsapp...");

                wa.OnLoginSuccess += (phoneNumber, data) =>
                {
                    wa.SendMessage(to, msg);
                    
                    wa.SendMessageImage(to,img,ApiBase.ImageType.GIF);
                    MessageBox.Show("Message Sent...");
                };
         }

**Comment by viniciusjarina** [comment]
@m1m6 Maybe you should open this issue at https://github.com/mgp25/Chat-API-.NET 

This is the php API not the C#
