### ISSUE TITLE
How to be always online?

### ISSUE THREAD

**Issue by EyWalls** [WHAnonymous/Chat-API#836]
I would be still always online but after about 5 minutes automatically disconnects and gives me the following error:
[Symfony \ Component \ Debug \ Exception \ ClassNotFoundException]
Attempted to load class "ConnectionException" from namespace "Koibox \ EmpresaBundle \ Services \ WhatsAPI".
Did you forget to "use" statement for e.g. "Doctrine \ DBAL \ ConnectionException" or "Doctrine \ DBAL \ Exception \ ConnectionException"?

Currently I try to do so:

    while(true){
        $now = new \DateTime();
        while($w->pollMessage());
    
        if($now >= $now10seconds){
            $now10seconds = clone $now;
            $now10seconds->modify('+10 seconds');
            $w->sendPing();
        }
        .........
    }

What would be the proper way to do this?

Thanks!!!

**Comment by mgp25** [comment]
@EyWalls use `sendPing()` if you are inactive for 300 seconds and you will keep active

Regards

**Comment by EyWalls** [comment]
I do that but is disconnected. Do you detect a error in the code?
Thanks you very much!!

**Comment by mgp25** [comment]
change your while to this:

```php
while(true){
 $w->pollMessage();
}

**Comment by EyWalls** [comment]
I will try. Thank you very much!

**Comment by EyWalls** [comment]
It don't work :(

Always an exception occurs:

[ConnectionException]
Connection Closed!

This is my complete code:
        
        $w = new WhatsProt(----, ----, ---);
        $w->connect();
        $w->loginWithPassword($passwordWhatsApp);
        $w->eventManager()->bind("onGetMessage", array($this, "onMessage"));
        $w->eventManager()->bind("onPing", array($this, "onPing"));
        $w->sendPresence();

        $now = new \DateTime();
        $now10seconds = clone $now;
        $now10seconds->modify('+20 seconds');
        while(true){
            $w->pollMessage();
            $now = new \DateTime();
            if($now >= $now10seconds){
                $now10seconds = clone $now;
                $now10seconds->modify('+20 seconds');
                $w->sendPing();
            }
        }


Thank you @mgp25  for all

**Comment by mgp25** [comment]
@EyWalls post your debug log

**Comment by EyWalls** [comment]
php app/console cliente:whatsapp_online2:send
```
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="346YYYYYY">f#�346YYYYYY4����D�<9��PV}Z��H�"1436445926WhatsApp/2.12.61 S40Version/14.26 Device/Nokia302 MccMnc/214007</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>%�
                 T?��7�]�݋o8V�</challenge>

tx  <response>�CG�Q����1R�/?O�U9Ϡ�Ż�2��У,</response>

rx  <success t="1436445927" props="4" kind="free" status="active" creation="1436285480" expiration="1467821480">�~�S�J���^�~�i!�</success>

tx  <presence name="MyName"></presence>

tx  <presence type="active"></presence>

rx  <receipt from="346WWWWWWWW@s.whatsapp.net" id="message-1436444357-1" retry="2" offline="2" t="1436444358"></receipt>

tx  <ack to="346WWWWWWWW@s.whatsapp.net" id="message-1436444357-1" type="read" t="1436445927"></ack>

rx  <receipt from="346XXXXXXX@s.whatsapp.net" id="message-1436444358-2" offline="0" t="1436444359"></receipt>

tx  <ack to="346XXXXXXX@s.whatsapp.net" id="message-1436444358-2" type="read" t="1436445927"></ack>

rx  <receipt from="346WWWWWWWW@s.whatsapp.net" id="message-1436444357-1" offline="0" type="read" t="1436444952"></receipt>

tx  <ack to="346WWWWWWWW@s.whatsapp.net" id="message-1436444357-1" type="read" t="1436445927"></ack>

rx  <receipt from="346ZZZZZZZZ@s.whatsapp.net" id="message-1436441409-1" offline="0" type="read" t="1436445921"></receipt>

tx  <ack to="346ZZZZZZZZ@s.whatsapp.net" id="message-1436441409-1" type="read" t="1436445927"></ack>

rx  <ib from="s.whatsapp.net">
rx    <offline count="4"></offline>
rx  </ib>

rx  <presence from="346YYYYYY@s.whatsapp.net"></presence>

rx  <presence from="346ZZZZZZZZ@s.whatsapp.net"></presence>

rx  <presence from="346XXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <presence from="346XXXXXXX@s.whatsapp.net"></presence>

rx  <presence from="346ZZZZZZZZ@s.whatsapp.net" type="unavailable" last="1436445959"></presence>

rx  <presence from="346XXXXXXX@s.whatsapp.net" type="unavailable" last="deny"></presence>

rx  <stream:error>
rx    <ack></ack>
rx  </stream:error>
```
