### ISSUE TITLE
Receiving messages without opening page  in web browser

### ISSUE THREAD

**Issue by FarVision** [WHAnonymous/Chat-API#837]
Hi
First of all I am thankful to @mgp25 , @CODeRUS , @0xTryCatch and all the others contributors to keep this updated and helping the others. :+1: . 

I want to receive the whatsapp messages 24 hours without opening page in web browser.

Is this possible? 

Thanks in advance

**Comment by mgp25** [comment]
@FarVision the best way is to run it in command line and keep it running, you can put the files in the server and execute the script remotely or via cronjob.

If you wanna keep the things simple, set a cronjob or run it locally

Regards

**Comment by FarVision** [comment]
Thanks for the reply @mgp25 . Just one question

e.g
If i will run https://github.com/WHAnonymous/Chat-API/blob/master/examples/ajaxDemo/index.php

in cron just once as we open this in browser will it execute continuously and pollmessages.
Hope that i am not irritating you.
