### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by yashindmitry** [WHAnonymous/Chat-API#838]
Hello. Unable to register on the Russian Room (7), in what could be the problem?

php tools/whatsapp/test.php 
####################
#                  #
# WA Register Tool #
#                  #
####################

Username (country code + number without + or 00): 79063411977

Type sms or voice: sms
Array
(
    [in] => 063411977
    [cc] => 79
    [id] => ~�'��
                  cf���p|j�y
    [lg] => ru
    [lc] => RU
    [sim_mcc] => 250
    [sim_mnc] => 000
    [method] => sms
    [token] => f994df91d03a09d773d2b8af37412a9e
)
stdClass Object
(
    [status] => fail
    [reason] => bad_token
)
There was a problem trying to request the code.

**Comment by mgp25** [comment]
@yashindmitry fix will come in a few minutes. There was an error in my latest commit

Regards

**Comment by yashindmitry** [comment]
Thanks!

**Comment by Twister21** [comment]
I got the same error.
