### ISSUE TITLE
How to extract result of sendGetRequestLastSeen($number)?

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#839]
I need to extract result of sendGetRequestLastSeen($number) and store the lastseen in a variable. I was able to extract the request by adding return value to the fn but couldn't make it happen for result. Any idea how this could be implemented?

**Comment by 0xTryCatch** [comment]
Don't keep asking the same questions. It was answered two days ago.

**Comment by kumaramit1996** [comment]
<code>
function requestLastSeen($mynumber, $from, $id, $type, $time, $name, $result)
	{
	    echo $type;
	}
	$events = new MyEvents($w);
	$w->eventManager()->bind("onGetRequestLastSeen", "requestLastSeen");

	$res = $w->sendGetRequestLastSeen('9199xxxxxxxx');
</code>
Figured it out but still unable to get it under $res, any help?

**Comment by mgp25** [comment]
@kumaramit1996 look at the function, use it!

**Comment by kumaramit1996** [comment]
@mgp25 still couldn't figure out to return/var_dump $type so that it could be extracted in an array. Basically I'm trying to make an array of online people. The problem is pretty simple. Can you guide in a few words?
