### ISSUE TITLE
Login Status

### ISSUE THREAD

**Issue by amansinna** [WHAnonymous/Chat-API#840]
Is there any way to check the login status??
When I printed the object i found there is something like "loginStatus", but i dont know how to use it to check login status.
plz help me.

**Comment by mgp25** [comment]
@amansinna what do you mean by 'login status'?

**Comment by amansinna** [comment]
@mgp25 I am trying to create a whatsapp listener which echos back messages according to the messages received but I am having problem in it. After few interval of time the connection is closed and the listener is turned off. So can you plz help me in this.

**Comment by mgp25** [comment]
@amansinna if you follow the examples and documentation you can stay online all the time you want, but if there is an internet connection problem, there is actually no solution yet, check this issue for more info: #642 

I have to rewrite all the socket stuff
