### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by jaypratapsingh** [WHAnonymous/Chat-API#841]
I have use this api on server then i got following error

Fatal error: Call to undefined function socket_create()

**Comment by kharchenkodenis** [comment]
you will need connect php module php_socket.dll in php.ini

**Comment by jaypratapsingh** [comment]
i have using this api on 1&1 server and on that server there is no php.ini file

**Comment by kharchenkodenis** [comment]
change hoster

**Comment by jaypratapsingh** [comment]
no i have purchased domain, okay i have uploaded the php.ini file so this function $wa->connect(); is not called. I don't know why it is not called but i am using same file or folder everything is working correct but when i use same thing on server with configured php.ini file then connect() function not execute.

**Comment by mgp25** [comment]
@jaypratapsingh search in google how to set up your own php.ini, there a lots of guides in the internet, as @kharchenkodenis you need to activate / install the dependencies, for more info: https://github.com/WHAnonymous/Chat-API/wiki

**Comment by jaypratapsingh** [comment]
@mgp25 yes i have setup my own php.ini but the problem is coming when i execute the connect() function. I had removed the connect() from my test.php use this function in loginWithPassword() in whatsprot.class.php but nothing is working. So i have every solution which ever i know but nothing is working on server. So please test your code on running server not wamp.
