### ISSUE TITLE
?> or 502 Bad Gateway

### ISSUE THREAD

**Issue by kharchenkodenis** [WHAnonymous/Chat-API#842]
it is normal to each of the files PHP, there is not enough ? > At the end of the file ?

**Comment by kharchenkodenis** [comment]
i am usung /examples/whatsapp.php

and get an error
502 Bad Gateway
The server returned an invalid or incomplete response. Bad Gateway

but using CLI its wors perfectly

whats wrong?

**Comment by kharchenkodenis** [comment]
the problem on line 
$w->loginWithPassword('C8qzlE...');

**Comment by mgp25** [comment]
@kharchenkodenis yes, it is normal there is nothing to worry about the final `?>` and by the way, `Error 502` has nothing to do with the API: http://www.checkupdown.com/status/E502_es.html

Search in google

Regards
