### ISSUE TITLE
'Receiving' bulk messages?

### ISSUE THREAD

**Issue by 3zzy** [WHAnonymous/Chat-API#843]
I'm looking to use this API in a very specific manner. I don't intend send messages at all using the API, but I was wondering if I can use it to receive messages from hundreds or even thousands of users daily, process the information internally and reach out to them via other channels? 

Would I still be banned?

**Comment by 0xTryCatch** [comment]
Yes. It is not allowed and it will be detected by WhatsApp followed by a block.

**Comment by 3zzy** [comment]
Thanks for the super quick response!

Ah heck, is there *any* way I can receive, just receive messages from users?

**Comment by 0xTryCatch** [comment]
Well sure, just not in the volumes you mentioned. Keep it low and you'll be fine.

**Comment by ctaity** [comment]
hi, i am a productor of tvshow in argentina, we like to recive message from people. How many message i can recive??? we dont send response, only recive info, text, videos , etc.
Exists some procedure we can do to authorize this type of application?
Thanks 

sorry for my english.

**Comment by jesussales** [comment]
@ctaity send me a mail to jesussales@gmail.com  and try to help to you. .. i'm spanish

**Comment by 0xTryCatch** [comment]
I have locked this issue because sending/receiving bulk messages is not endorsed. You will be blocked by WhatsApp if you do.
