### ISSUE TITLE
How to check for contact's online status [not last seen]?

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#844]
How do I check if a contact/number is currently online or not?

**Comment by mgp25** [comment]
Please take time to read other issues and wiki

Regards

**Comment by kumaramit1996** [comment]
Searched a lot, issues & codebase both. onPresenceSubscription doesn't return the online status.

**Comment by WHAnonymous** [comment]
@kumaramit1996 there are more events
