### ISSUE TITLE
fsockopen(): SSL operation failed with code 1

### ISSUE THREAD

**Issue by illusionuk** [WHAnonymous/Chat-API#845]
Hi,

On some occasions when sending an image via sendMessageImage(). I received the following.

fsockopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by mgp25** [comment]
@illusionuk you are using an outdated code, please update it

Regards

**Comment by illusionuk** [comment]
@mgp25 
Thanks, I updated but still had the issue.
https://github.com/WHAnonymous/Chat-API/issues/781#issuecomment-109886033 has helped in the meantime.
