### ISSUE TITLE
OnGetMessage event doesn't work

### ISSUE THREAD

**Issue by alexmercury** [WHAnonymous/Chat-API#846]
Hi @mgp25,

I noticed that OnGetMessage event stopped working. Now node (this node comes in when someone sends a message to the user directly and not to a group) looks like this:

```xml
<message from="0000000000000@s.whatsapp.net" id="1436761552-12" type="text" t="1436779863" notify="Alex">
 <enc v="1" type="pkmsg">3���!E��č�q"z����u�j�>���>���a!�i�@|�p�6N�%Ÿ$��H�K*�I:/="B3!����x��a��l}q��dԫ~��;n�����} "0��������)�1���F���dsH(?�0 </enc>
</message>
```
Can you please double-check?
Thanks.

**Comment by WHAnonymous** [comment]
@alexmercury no, it's working perfectly, use an account register with this API, not android account as you are showing. Use registerTool

**Comment by utking** [comment]
I have the same problem. I have already reregistered with API, but it did not help - I can receive messages with image but can't receive text messages, which statuses show they were received. 
rx  <message from="7924xxxxxxx@s.whatsapp.net" id="1437088740.--353" type="text" t="1437088740" notify="utkingg">
rx    <enc v="1" type="pkmsg">�Ψ!�+X��#-wb?�o��Q�0����V#���Z0�=!�å�b�劉=Y�uP���Z<��tR�V�&q"B3!�v�τ=$B�$j�}����;F7��Y*"27���t��>�g��d�H㬎b?(����0</enc>
rx  </message>

**Comment by ksankark** [comment]
I am also getting the same scenario(Account registration has done with this API). 

```html
<message from="911234567890@s.whatsapp.net" id="12345678-13" retry="1" offline="1" type="text" t="1437094722" notify="XXXX">
  <enc v="1" type="pkmsg">3ÊÈ¸!sðÎÈˆ_g8Î¿eÐ=E!g,–`&e½ÊW+ÓÊS!ý±6kÊŽcÜ½.±7Õ
{c‰d"¢\rˆá}°ƒ÷
"B3
!õZX44ÐrÅ?¦Ñêu_zªøîÓ÷®F¢…Íö9Y#"=¦§#çÓÉPâÔ¬¢u¼!
.n*3(¸¯‡[0</enc>
</message>
```

**Comment by mgp25** [comment]
Please read this: https://github.com/WHAnonymous/Chat-API/issues/858#issuecomment-122224842
