### ISSUE TITLE
Donate

### ISSUE THREAD

**Issue by p031985s** [WHAnonymous/Chat-API#847]
Hi there...

Your code has been too useful and i want to donate you...
Do you have other way to do it, i do not have BitCoin Wallet.

Thank You.

**Comment by WHAnonymous** [comment]
@p031985s there are many bad boys out there, you know :wink: and it's better to avoid them

There are many services that you don't need a BitCoin Wallet, you can buy the BTC with your paypal and then using this BTC address: 1HcEX9foem5atreEg1gbQ6xVeosN5WEcjs
