### ISSUE TITLE
What's the plan?

### ISSUE THREAD

**Issue by nikfariz** [WHAnonymous/Chat-API#848]
Reading about the legal letter that you received, I'm wondering what is your plan? Will this repo still exist 1 week or 1 month down the line?

Venomous0x just deleted its repo. 

I started using WhatsAPI a few years back when it just started. I've seen the glory days of using this API to communicate with my contacts. I've experienced the ups and downs of using this API  with my app. I truly believe this is a great API.

The problem started when Whatsapp started to block my numbers, even when I only send messages to 10 of my contacts. Within a week, all the numbers that I have was blocked. I have no idea what to do.

I stopped using WhatsAPI with my app and returned back to using SMS as one of the methods of communication. It was not fun and it was costly.

I think we have to abide by the law. But, I also think we must find a workaround.

Why dont we think of something to keep this concept going. We may not have WhatsAPI (or Chat-API) in the future, but we will still have WhatsApp.

Let's build an API to connect to the Web-based Whatsapp. In the end, we would still be using the official Whatsapp client. No threats to their business. No laws are broken.

What say you?

**Comment by 0xTryCatch** [comment]
The web stuff is handled by the phone so you would still need the complete API...

**Comment by nikfariz** [comment]
well, develop something that doesnt break the law but still give the best WhatsAPI can do.

I'm sure there are thousands of developers here who would want to contribute towards a common goal.

**Comment by 0xTryCatch** [comment]
WhatsApp only allows you to use their app and their web. Anything else is breaking the EULA.

**Comment by WHAnonymous** [comment]
@nikfariz Yes, this repo will be active always and up to date.

According to your web-stuff question, we have already started working on that and it will be only for us, honestly i don't like spam, and the web-stuff is not required to use this API, if you don't want to be blocked avoid high traffic, don't send messages to users who does not have you added...

[Closed]
