### ISSUE TITLE
Chat-API rejecting custom photos

### ISSUE THREAD

**Issue by NLCJ** [WHAnonymous/Chat-API#849]
I am trying to send a random photo from our database upon request to a group chat. The problem is that I cannot seem to send photos.

This photo (http://www.animaatjes.nl/plaatjes/c/cute/animaatjes-cute-66685.jpg) have I downloaded and uploaded to my server named test.jpg, when I send this photo I receive it correctly in my chat with the bot. 
However, if I get a random other jpg photo of our album, resize it to a size smaller than the above picture and rename it to test.jpg placing it at exactly the same location through FTP (essentially changing nothing in the code); it does not work. 

Debug info:
```xml
tx  <iq id="1" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="jQuFmW5JvLBvF6mwJM44zMS7Q5rXYHkRmu5zAo+Tvds=" type="image" size="5696"></media>
tx  </iq>

rx  <iq from="s.whatsapp.net" id="1" type="result">
rx    <media url="https://mmi608.whatsapp.net/u/PINLFrz4CbSN1-QRlwjjqUmUcUMABRrJ6-Sw7A/Aq-Phe7J51zg23JTCM9K6WnD_gYVDNauN5xP94aOSFCO" ip="184.173.204.35"></media>
rx  </iq>
```

Am I missing something here?

**Comment by 0xTryCatch** [comment]
You get a positive response. What is the problem you experience?

**Comment by mgp25** [comment]
@NLCJ post the script please

**Comment by NLCJ** [comment]
I do get a positive response for only one image. Whenever I try to upload one of my own at the server I get a response as above. The code is;
```
$w = new WhatsProt( $mobileNumber, $nickname, $debug );
// Connect and login
$w->connect();
$w->loginWithPassword( $password );

// Get the messages
$w->pollMessage();

while( true ) {
    while ($w->pollMessage()) ;
    // Check for received messages:
    $messages = $w->getMessages();
    if (count($messages) > 0) {
        foreach ($messages as $message) {
            $body = @$message->getChild("body")->getData();
            $name = @$message->getAttribute("notify");
            // Send random foto
            if (stristr($body, "timo") && stristr($body, "foto")) {
                // Get random picture
                $d_getrandompicture = mysql_query("SELECT * FROM files WHERE `name` LIKE '%.jpg' ORDER BY RAND() LIMIT 1");
                $d_randompicture = mysql_fetch_array($d_getrandompicture);

                // Get file path
                $filePath = "removedCorrectFilePath/006825.jpg";
                $w->sendMessageImage("*********", $filePath); // Not working
                $w->sendMessageImage("*********", "test.jpg"); // Working only with photo linked above
            }
        }
    }
}
```

I also noted that I do not get a message like below when selecting a local image, this is what WhatsApp also responds when uploading the image above;
```
tx  <message to="31623192538-1356619113@g.us" type="media" id="1436865795-1" t="1436866216">
tx    <media type="image" url="https://mmi117.whatsapp.net/d/Al16aF00BqFHaxHuYbyqK5MZ33aRGTvRUn-iswh1UsDX.jpg" encoding="raw" file="Al16aF00BqFHaxHuYbyqK5MZ33aRGTvRUn-iswh1UsDX.jpg" size="16794"> 3378 byte data</media>
tx  </message>
```

**Comment by mgp25** [comment]
@NLCJ are you using full path to the image?

**Comment by NLCJ** [comment]
Yes. I also tried placing the images in the same folder as the script and accessing them via the web - neither of them worked.

**Comment by mgp25** [comment]
@NLCJ weird, if you want send me an email, and ill try to help you

**Comment by mgp25** [comment]
**UPDATE** It was server issue as far i could seen. @NLCJ will post his resolution once he make it works. Not API issue

Regards

**Comment by NLCJ** [comment]
Howdy. It took me a while, but I figured it out. In the file mediauploader.php at line 74 you have this:
`$hBAOS .= "Content-Type: " . $mediafile['filemimetype'] . "\r\n\r\n";`

Somehow my server determined that my files consist of the type 'image/jpeg         ' - which WhatsApp rejects. Placing this at line 68 in mediauploader.php solved it;
