### ISSUE TITLE
Login problem

### ISSUE THREAD

**Issue by zostrum** [WHAnonymous/Chat-API#850]
Hi!
I have login problem - i'm recieving "LoginFailureException".
I'm already read FAQ and changed password and phone number 4 or 5 times.
But the trouble is same. What can be wrong?
P.S. to generate password i used this tool - https://github.com/mgp25/WART

**Comment by 0xTryCatch** [comment]
Use blockChecker.php to see if your number is blocked

**Comment by zostrum** [comment]
Yes, you was right - one of numbers was blocked, but for others i recieve "Wrong identity".
What does it means?

**Comment by mgp25** [comment]
@zostrum you are trying to check credentials with a different identity. The identity is generated when registering your number, if you used WART to register your number, paste that identity inside the `wadata` folder. I recommend you using `registerTool.php` again and that will fix everything if you dont know how to do it

Regards

**Comment by zostrum** [comment]
Thanks a lot!
