### ISSUE TITLE
How to forward recieved messages on pollMessage to a $target? 

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#852]
$w->pollMessage();
$msgs = $w->getMessages();
//print_r($msgs);
foreach ($msgs as $m) {
        	$w->sendMessage($target, $m);
}

I tried this code but it forwards the NodeString & not the message.

**Comment by mgp25** [comment]
You will find the solution in the example scripts

Regards

**Comment by kumaramit1996** [comment]
Which one precisely?
