### ISSUE TITLE
Problem with forwarding messages

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#853]
$msgs = $w->getMessages();
foreach ($msgs->getChild('body')->getData() as $m) {
     $w->sendMessage('9199xxxxxxxx', $m);
}

"PHP Fatal error:  Call to a member function getChild() on array" Getting this error when I try to extract the message part from the array. What other way can I extract the message body and from?

**Comment by 0xTryCatch** [comment]
You need to learn to program in PHP first before asking all these questions. We are not here to help you with PHP, only with the API itself
