### ISSUE TITLE
blocking number after 20 messagse 

### ISSUE THREAD

**Issue by kharchenkodenis** [WHAnonymous/Chat-API#856]
Hi 
I tried to send 20 messages in a row and my number is blocked . How to do it correctly ?
{"status":"fail","reason":"blocked"}

```
foreach ($messages as $message)	
			{
			$w->sendMessage($target , $message);
			}
```

**Comment by p031985s** [comment]
Hi there...

You can use:
foreach ($messages as $message) 
{
	$w->sendMessageComposing($target); //Writing state
    usleep(500000); //500 Miliseconds delay
	$w->sendMessage($target , $message);
    $w->sendMessagePaused($target); //Stop writing
}

Whats App block you because you are not writing the message, you have to send writing state and wait for a little miliseconds.
Sorry for my English.
