### ISSUE TITLE
Encrypted messages

### ISSUE THREAD

**Issue by SirMosh** [WHAnonymous/Chat-API#857]
Hey, i started some days ago to use Chat-API. Had no problems in making the register and the login part but when i got to make the chat between two persons i had some problems. I took the Ajax example and tried to work with it but it had some errors, like some useless uppercases on some function names or a letter that needed to be deleted from them in order to make them work.(I guess versions changed, so did the functions, took the real function names from the documentation). 
Anyway, i managed to fix the errors, even sent messages to a friend from the web chat but when i receive messages from somebody(that uses an android phone as i tested till now) i don't get anything. I checked the debug, tried to extract some variables and i saw that the messages are encrypted. If i am in a group with multiple users i can see every message but talking on private with one person gives me encrypted messages. I can provide more info, pictures tomorow if needed. 
Please tell me if i forgot about something, maybe i am doing something wrong, like forgot about some functions or something that i don't know. Thanks a lot for support and have a nice day.

**Comment by 0xTryCatch** [comment]
Best thing to do is to register the number again.

**Comment by mgp25** [comment]
https://github.com/WHAnonymous/Chat-API/issues/858#issuecomment-122224842
