### ISSUE TITLE
onGetMessage does not fire?

### ISSUE THREAD

**Issue by utking** [WHAnonymous/Chat-API#858]
I'd like to reopen #846 closed several days ago.

I cannot receive any text message because of onGetMessage does not fire. $node->getChild('body') return null every time. I have already reregistered with API, but it did not help - I can receive messages with image but can't receive text messages, which statuses show they were received. Though I'm  receiving images with onGetImage.
And, as I can see, I'm not the only one who experienced this problem.
```
rx  <message from="7924xxxxxxx@s.whatsapp.net" id="1437088740.--353" type="text" t="1437088740" notify="utkingg">
rx    <enc v="1" type="pkmsg">�Ψ!�+X��#-wb?�o��Q�0����V#���Z0�=!�å�b�劉=Y�uP���Z<��tR�V�&q"B3!�v�τ=$B�$j�}����;F7��Y*"27���t��>�g��d�H㬎b?(����0</enc>
rx  </message>
```

**Comment by SirMosh** [comment]
Yep, i made a new issue with this problem too like 10 hours ago, they told me to register the number again whitch i tried some days ago. I will try again but i doubt that it will work.

**Comment by utking** [comment]
I tried to reregister with CI tool for two days now. No changes.

**Comment by mgp25** [comment]
@utking You are receiving encrypted messages what it means you have registered your number with an android device (you have used password extractor or registered with API using android data) which is wrong because we use Nokia data.

If you want to solve this register your number again with `registerTool.php` or delete account and register using `registerTool.php` In case you have registered already with this script, delete your account first and then register it.

Q: Why are you receiving encrypted messages?
A: Because you have registered that account with an android device and automatically keys (libaxololt has been set in WA server).

@SirMosh Read what i posted here

If you do what i posted here above it will work 100%

Regards

**Comment by SirMosh** [comment]
It worked, thank you very much!

**Comment by utking** [comment]
Deletion and registering again helped. Thanks!

**Comment by jenchote** [comment]
Hi @mgp25, I wanna thanks, I have tried your instruction and it work perfectly! :)

**Comment by transonly** [comment]
Hm, i'm pretty sure i deleted my account from my android phone to be able to re-register with the tool.
The Dutch countrycode is +31. This is what i get back from the tool after entering sms:
Username (country code + number without + or 00): ingrid 31 627333603


Type sms or voice: sms
The provided phone number is not valid.root@transonly Chat-API-2.5.1/examples#

**Comment by mgp25** [comment]
@transonly you should write this instead:

`Username (country code + number without + or 00): 31627333603`

**Comment by transonly** [comment]
I was just looking at the exampelregister.php and came to that conclusion the same time you where typing i guess. :-) Thanks for the quick reply though!

**Comment by mgp25** [comment]
@transonly btw, i recommend you using `registerTool.php` instead (CLI script)

**Comment by transonly** [comment]
Yes, i'm using registerTool.php. And i've now succeeded registering the number. :)

**Comment by transonly** [comment]
And now when i try to re-register another number i get after typing sms:

C~
 ▒┌─
≤ _ ▒
   ┼├. R
        ├─≤ ▒°├
               ─ 22 └
                     ┼┤├
                        _.─~~├@├─▒┼_~┼┌≤ C
▒├-API-2.5.1/
             │▒└─┌
                  _#

**Comment by shvburade** [comment]
i am getting ecrypted message 
rx  <message from="91mynumber@s.whatsapp.net" type="text" id="+OPz1dOfsU1H1" offline="0" t="1442928190" notify="Shiva Burade">
rx    <enc v="1" type="msg">3 !���E�@=̘��rJc$���sS�	*��^>�z5	"vB��	M��BfR���I�áw��7�4</enc>
rx  </message>

i delete everything in wadata
used resetaccount
used registerTool for code and used WART for password

i read issues regarding encrypted messages and found resetaccount is a solution but it is not working for me
telll me whats wrong in here?

**Comment by Opencontent** [comment]
Same issue me too :(
Reset account and re-register does not work...

enc v="1" type="pkmsg">���!e��AN����z[�ʼk$5uk��E�߹z};k!�o�kбL��"��3��n�#޴R��;;GhH"B3
!��\��ћB�X�5�
�h�{��v�-T"Iȍa)�$�V�ÌL��<�$A�v�(�g0</enc>

**Comment by renemtz6** [comment]
Hi, i  delete the account and follow the steps 3 times and the messages are still encrypted, there is someting else i can do?
thank you

**Comment by mgp25** [comment]
Install extension, read wiki dependencies section

**Comment by flapsup** [comment]
This works fine and see NOT ecrypted code anymore..... until somebody registrates the phonenummer as contact in the iPhone and sends something back then encryption is back..

How is this possible? Any solution to prevent this? Thank you
