### ISSUE TITLE
Login error - Seems that Whatsapp server is blocking ChatAPI

### ISSUE THREAD

**Issue by eduardobento** [WHAnonymous/Chat-API#860]
I made some tests and all of them, I get not authorized. Somebody with this same problem ? This problem appers today (2015-07-17)

   rx  failure
   rx    not-authorized></not-authorized
   rx  /failure

**Comment by p031985s** [comment]
Hi there...

It seem your phone number has been blocked, the chatapi is working fine, my script is running without problem... try registering a new phone number.

**Comment by eduardobento** [comment]
Thanks, I will try!

**Comment by phpjoker** [comment]
@eduardobento
Update your api version.

**Comment by eduardobento** [comment]
I´m using the last version.
Strange that trying to registrer the same number in normal Android Client, don´t ask for sms code.

**Comment by eduardobento** [comment]
Sorry guys, in the 3o time that I try to register, it works.
Seems that the password has changed in Whatsapp server.

Strange... thanks...

**Comment by PHPian** [comment]
so, @eduardobento how did this get resolved. did you keep on trying to register, it failed few times and then it worked on its own.

**Comment by eduardobento** [comment]
Hi,

I´m still having problems with numbers that was registered in Android. Even
deleting the account in android, re-making with registerTool.php.
So I´m studing the yousup api to resolve this problems.. =/

And you ?




------------------------------

*Eduardo Bento <eduardo@youngarts.com.br>Equipe de desenvolvimento*
<http://www.youngarts.com.br/> <http://www.youngarts.com.br/>
<http://www.facebook.com/youngartstec>
<http://www.twitter.com/youngartstec>  <eduardo@youngarts.com.br>

2015-07-28 2:58 GMT-03:00 PHPian <notifications@github.com>:

**Comment by mgp25** [comment]
@eduardobento sigh...

before doing anything else. Follow this steps:

1. Delete account in android
2. Delete all the files inside `wadata` folder
3. Use `registerTool.php`

**Comment by mgp25** [comment]
@eduardobento use this script: https://github.com/WHAnonymous/Chat-API/blob/master/examples/resetAccount.php

**Comment by eduardobento** [comment]
Hi mpg25 !

This works for me, perfectly. Just needed to make a change in resetAccount.php, adding "$w->Connect();" before "$w->loginWithPassword($pw);". So, if anybody have problems, its very simple to resolve:

1. Apply resetAccount.php (Link above)
2. Delete all the files inside wadata folder
3. Use registerTool.php

No encripted data incoming! 
Thanks mgp25!

**Comment by mgp25** [comment]
@eduardobento updated the script

Regards

**Comment by bgani** [comment]
Hi mpg25 ! I hava a same issue. How can i do solution steps with Chat-API-NET

**Comment by mgp25** [comment]
This is not Chat API net repo
