### ISSUE TITLE
WhatsApp API, is now Old Version

### ISSUE THREAD

**Issue by wasimjee** [WHAnonymous/Chat-API#861]
The current API is giving message as old version

**Comment by 0xTryCatch** [comment]
You are running an outdated version of this repo. It is working.

**Comment by p031985s** [comment]
check Constants.php
    const WHATSAPP_VER = '2.12.88';                                                          // The WhatsApp version.

**Comment by wasimjee** [comment]
ok its working, but the WART is not working, giving bad token

**Comment by mgp25** [comment]
@wasimjee WART is working, check latest updates

**Comment by Subhajit321** [comment]
WART is not working. I am using latest version.
![image](https://user-images.githubusercontent.com/39081525/42363873-d50e6922-8116-11e8-89f1-d2b5b087460a.png)
Please help me
