### ISSUE TITLE
Is it okay to deploy multiple scripts over a cloud server?

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#864]
Is it okay to deploy multiple scripts over a cloud server? Are there any chances of it leading to ban or something? Planning to use AWS or Digital Ocean. 

Thanks

**Comment by 0xTryCatch** [comment]
Both are most probably blacklisted by WhatsApp so do use them.

**Comment by kumaramit1996** [comment]
Blacklisted?!

**Comment by kumaramit1996** [comment]
@0xTryCatch By blacklisted do you mean I'll be blocked? I guess you mean whitelisted!?

**Comment by 0xTryCatch** [comment]
No blacklisted, so yes you will be blocked

**Comment by kumaramit1996** [comment]
@0xTryCatch any other possible method to deploy scripts over cloud?

**Comment by 0xTryCatch** [comment]
What is the use case?

**Comment by kumaramit1996** [comment]
Need to forward messages back and forth. Script will act as a mediator and will send message only to online contacts. No spamming involved.

**Comment by mgp25** [comment]
Any kind of bulk sending / receiving will be blocked, no matter if you act as a mediator, WhatsApp will consider that as spam and it will block you

Use this API for personal usage only, that way it will work like a charm

**Comment by Sputuks3** [comment]
If I deployed this on other commercial LAMP web hosting companies, will WhatsApp detect? Have they blacked listed them?
