### ISSUE TITLE
unable to connect to c.whatsapp.net:443 (Connection timed out)

### ISSUE THREAD

**Issue by yanelev** [WHAnonymous/Chat-API#866]
Is anyone experiencing the same problem?
Is there an issue on WhatsApp side?

**Comment by jordynegen11** [comment]
Here the same! s.whatsapp.net and c.whatsapp.net down since 40 minutes ago.....

**Comment by pablokerestezachi** [comment]
Please helpppp

Saludos,
Pablo

**Comment by 0xTryCatch** [comment]
You can are using an outdated version of the API. Upgrade to the latest version.
