### ISSUE TITLE
BroadCast dont work

### ISSUE THREAD

**Issue by javierpalopez** [WHAnonymous/Chat-API#867]
Hello,

The BroadCast function response are fine but I dont receive the messages:

The function return:
```xml
tx  <message to="1437398290@broadcast" type="text" id="1437398290-1">
tx    <body>test broadcast</body>
tx    <broadcast>
tx      <to jid="34665796XXX@s.whatsapp.net"></to>
tx      <to jid="34644454XXX@s.whatsapp.net"></to>
tx    </broadcast>
tx  </message>

rx  <ack from="1437398290@broadcast" id="1437398290-1" class="message" count="0" t="1437398290"></ack>
```

But I never receive the messages.

It happens to someone else????? My code works fine one days ago and the normal "send function" works OK.

**Comment by mgp25** [comment]
@javierpalopez is not neccesary to write so many `?`.

Broadcast is working perfectly, it seems you haven't read any previous issues related to broadcast. **Only people who have your number added, will receive broadcast**, if the contacts doesn't have your number they won't receive anything.

**Comment by javierpalopez** [comment]
Hi mgp25,

This is not true for me. The target phones have the number correctly.

The same code works a few days ago.

Please, Could you try if works normally with your account??

This is the code.
.....
$w = new WhatsProt($username, $nickname, $debug);
$conexion = $w->connect();
$w->loginWithPassword($password);
$w->sendGetServerProperties();
$w->sendClientConfig();
$w->sendSync($contacts);
$id_mensaje = $w->sendBroadcastMessage($targets , $message);
.....

Thanks

**Comment by mgp25** [comment]
@javierpalopez quote your code properly. 

Of course it works! Maybe you are not polling enough right after sending broadcast, do a while loop poolling right after

**Comment by javierpalopez** [comment]
thanks for the reply!  Now is works fine.

I delete the contact in the target phone and save again, and this solve the problem.

Sorry for my english and thanks again

**Comment by adelsjunior** [comment]
Hello @mgp25 ,
Where can I see um Example paragraph sending messages for group and TRANSMISSION List? Already HAS A New Version WhatsApi do ?

Excuse my English , I am Brazilian...heheh
