### ISSUE TITLE
Message receiving stopped in the middle of listening

### ISSUE THREAD

**Issue by rogobob** [WHAnonymous/Chat-API#869]
Hello,

I have a very strange issue since yesterday. One account stopped receiving messages - in fact it started receiving strange nodes:

1 Encrypted messages
```
rx  <message from=""xxx@s.whatsapp.net"" id=""xxx-11"" type=""text"" t=""1437364172"" notify=""Name"">
rx    <enc v=""1"" type=""pkmsg"">3 ! ÔâuhÉ~pOå6]CD6rÏÊ³¨Ö 4¤Òf8C ! •(]Ì fB% Ë1ï ýZ­£ú 5× ‡ª
¡7ÈG""B3
! µ€ Ž3û ²ü·•–¸kTV{=‡—3‰”¶5ƒ3‘.°] "" ¾a ÷v rü ô‹}LRßð&ÅJ8 æ„(÷»˜Z0 </enc>
rx  </message>
```

2 'X byte data' messages with 'phash' in the node
```
rx  <message from=""xxx-1422628397@g.us"" id=""1437324295-2"" participant=""xxx@s.whatsapp.net"" phash=""1:nA4coo4b"" type=""text"" t=""1437324377"" notify=""Name"">
rx    <body> 1203 byte data</body>
rx  </message>
```

Also, presence nodes with last='deny' are received very often. I suppose many contacts have custom privacy settings, maybe it's related.

```
rx  <presence from=""xxx@s.whatsapp.net"" type=""unavailable"" last=""deny""></presence>
```

I followed the solution at https://github.com/WHAnonymous/Chat-API/issues/858#issuecomment-122224842 but it didn't work for me. The account was completely deleted from WhatsApp from within the Android app. Then the app was deleted and the account re-registered via the API. The account still cannot receive and encryption is enabled. The account was originally registered via Android and later re-registered via this API (latest WA version 2.12.88). For some time messages were received successfully. So it appears to be a change in the protocol but I'm not sure.

I really appreciate your great work on this project. I hope it's a local issue.

I can provide privately a complete lifetime log of the account.

**Comment by mgp25** [comment]
@rogobob remove your account via API and then use `registerTool.php` do NOT use android for registering or even using the same account, it will cause issues.

**Comment by rogobob** [comment]
@mgp25 
I removed the account using sendRemoveAccount() and re-registered but received messages are still encrypted.

**Comment by mgp25** [comment]
@rogobob don't use any Android device or any android data, if you use that you will enable encryption, if you follow the same as here https://github.com/WHAnonymous/Chat-API/issues/858#issuecomment-122224842 it will work to you

Regards

**Comment by rogobob** [comment]
@mgp25 I am not using any android device / data. I am registering with the Nokia data from the API. I followed the comment twice already - removed the account and re-registered it using registerTool.

Some messages are not encrypted, but messages from some contacts are always encrypted.

**Comment by mgp25** [comment]
@rogobob delete your account again, make sure you have removed your identity first from `wadata` folder, once then you can try using `registerTool.php` and it should work :smile: 

Regards
