### ISSUE TITLE
ConnectionException 'Connectivity error'

### ISSUE THREAD

**Issue by CuBiC3D** [WHAnonymous/Chat-API#870]
My older git clone stopped connecting to WhatsApp servers, so I pulled today to the recent Version from git. I experience some strange behaviour: After **exactly** 5 minutes I get the following error:

```
PHP Fatal error:  Uncaught exception 'ConnectionException' with message 'Connectivity error' in /xxx/Chat-API/src/whatsprot.class.php:590
Stack trace:
#0 /xxx/agent.php(108): WhatsProt->pollMessage()
#1 {main}
  thrown in /xxx/Chat-API/src/whatsprot.class.php on line 590
```

agent.php is always connected and event driven script using simply
```php
while(true) {
   if(!$w->pollMessage())
      sleep(1);
}
```
after connection, subscribing and binding events old style by using `$w->eventManager()->bind`. Maybe somehow related to #868, #866?

**Comment by CuBiC3D** [comment]
Ok here we have the problem:
```php
if ($s) {
            // Something to read
            if ($stanza = $this->readStanza()) {
                $this->processInboundData($stanza, $autoReceipt, $type);
=>              return true;
            }
        }
        if ($s == 0)
        {
            if (!isset($this->timeout))
              $this->timeout = time();
            if ((time() - $this->timeout) > 300)
            {
              $this->timeout = null;
              $this->disconnect();
              throw new ConnectionException('Connectivity error');
            }
        }
=>      else {
          $this->timeout = null;
        }
        return false;
```
Marked else will never be reached, because there's a if with return before matching same values. What is this timeout even for? I mean if I call `pollMessage` after fixing the issue resetting `$this->timeout` before return, it would always result in a timeout after 300 sec getting no messages.

**Comment by mgp25** [comment]
@CuBiC3D i'll fix that later. What's the point of having WhatsApp running if there wasn't any data after 5 minutes? Anyway, you can catch the exception and use `reconnect()` function, this will be a better flow than keeping online forever.

**Comment by CuBiC3D** [comment]
@mgp25 At the moment, if you run it for 5 minutes and there is data, it would throw that exception anyway, because `$this->timeout` is never resetting.

The point is, I'm pulling every second to get the events triggered. You can pull much faster from an open socket, than connect, auth and disconnect every second.

Using `reconnect()` in a catch block, would exactly result in keeping it running forever ;) And to know if there's data or not I still need to pull right?

**Comment by VMosoti** [comment]
getting this response;any one else experiencing this?
```xml
rx  <stream:error>
rx    <conflict></conflict>
rx    <text>Replaced by new connection</text>
rx  </stream:error>
```
which results into  **Fatal error:** Uncaught exception 'ConnectionException' with message 'Connection Closed!' in /var/www/html/projo/vendor/whatsapp/chat-api/src/whatsprot.class.php:565

I have the latest code from the repo.

**Comment by mgp25** [comment]
@VMosoti Man, read your error: `Replaced by new connection` you can't use the same number in your device and in the API at the same time

**Comment by VMosoti** [comment]
@mgp25, thought so too but I have used the number anywhere else.Let me do the reg process again.

**Comment by mgp25** [comment]
@CuBiC3D check if everything is fine, i'll wait for your feedback

**Comment by CuBiC3D** [comment]
Okay, thanks @mgp25.
I've tested it - `$this->timeout` is now resetting on successful data fetch and behaving like expected.

But it's not really clear to me, why there is a timeout anyway. Not getting data from `pullMessage()` is not necessarily a "Connectivity error" since this is the only way to check for data.
