### ISSUE TITLE
erro rx <stream: error>

### ISSUE THREAD

**Issue by msxandroid** [WHAnonymous/Chat-API#871]
I'm having problem sending an average photo and then to capture the event returns error message
```xml
rx <stream:error>
rx <xml-not-well-formed> </xml-not-well-formed>
rx </stream:error>
```

I'm using the latest version of the api

**Comment by mgp25** [comment]
@msxandroid post full debug log

**Comment by mgp25** [comment]
@msxandroid i tested sending any kind of image and works perfectly, if you still face this issue, let me know, and remember to post full debug log

Regards
