### ISSUE TITLE
Check number blocked

### ISSUE THREAD

**Issue by kwiiby** [WHAnonymous/Chat-API#872]
Hi, I'm using blockChecker.php to check this but it is always returning an error, here is my debug:

```
Wrong identity.
Array
(
    [cc] => 55
    [in] => ??????????
    [id] => ????????????
    [lg] => pt
    [lc] => BR
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)

Fatal error: Uncaught exception 'Exception' with message 'There was a problem trying to request the code.' in C:\wamp\www\src\whatsprot.class.php on line 182

Exception: There was a problem trying to request the code. in C:\wamp\www\src\whatsprot.class.php on line 182

Call Stack:
    0.0002     239208   1. {main}() C:\wamp\www\examples\blockChecker.php:0
    2.3139    1977744   2. WhatsProt->checkCredentials() C:\wamp\www\examples\blockChecker.php:34
```

**Comment by guns2410** [comment]
Refer to #651 

You have wrong identity. Register number using registerTool.php or copy identity to a file in wadata folder

**Comment by rogobob** [comment]
First remove the identity file(s) in /wadata folder corresponding to the number. One reason for a wrong identity could be that the user logged in from a mobile phone, creating new credentials and invalidating yours.

**Comment by kwiiby** [comment]
So, If the number isn't mine, what should I do? because I won't have the identity in this case.

**Comment by guns2410** [comment]
@kwiiby, if you try and register number again, you will get status as blocked in case the number is blocked.
