### ISSUE TITLE
Unable to re-direct/forward media messages

### ISSUE THREAD

**Issue by kumaramit1996** [WHAnonymous/Chat-API#876]
```php
foreach ($msgs as $m) {
$message = $m->getChild("body")->getData();
$w->sendMessage($target, $message);
} 
```

This snippet of code works absolutely fine for text messages, but it breaks on media messages. How do I forward/re-direct media messages? :)

**Comment by kumaramit1996** [comment]
Couldn't find anything related to it in Wiki either.

**Comment by mgp25** [comment]
@kumaramit1996 remember to quote the code. Only add an if condition to that code, anyway, the wiki only provides information about how this API works, the rest is part of the user, coding and logistic part

**Comment by kumaramit1996** [comment]
@mgp25 How do I store an incoming message(media) to a file, and then forward it accordingly? Even after adding if condition, my code fails at $message = $m->getChild("body")->getData(); 

Any workaround?

**Comment by mgp25** [comment]
sigh... In the wiki is well explained how to forward an already uploaded/sent image, you have to understand the code instead of trying people to give you solutions, everything is in the wiki and in the examples

**Comment by kumaramit1996** [comment]
Where are the incoming images/media files stored? Couldn't find them in wadata folder. :/
