### ISSUE TITLE
Blocking right after trying to loginWithPassword

### ISSUE THREAD

**Issue by nikax** [WHAnonymous/Chat-API#879]
In file exampleFunctional.php I placed folowing code after login credentials: 

    echo "[] Logging in as '$nickname' ($username)\n";
    //Create the whatsapp object and setup a connection.
    $w = new WhatsProt($username, $nickname, $debug);
    $w->connect();

    // Now loginWithPassword function sends Nickname and (Available) Presence
    $w->loginWithPassword($password);

    echo "[*] Connected to WhatsApp\n\n";

    exit;

I registered a new account using registerTool.php, received password, then tried to log in using the code above. The first time it went well, but the second time the number was blocked and I got LoginFailedException all the time, blockChecker also says it's blocked. Tried a several different numbers with the same result.
BTW, I tried to use exampleFunctional.php from the repo without any modifications and still got blocked.

**Comment by 0xTryCatch** [comment]
Are you using the latest code? And how many messages did you send?

**Comment by nikax** [comment]
Updated the code yesterday. I was able to sent no messages, because was blocked right after the first login attempt.

**Comment by 0xTryCatch** [comment]
Probably IP related then. Are you using Amazon or similar?

**Comment by nikax** [comment]
No, I'm testing from my home network and can use original android app with the same IP. Also tried from Hetzner.de VDS - same result

**Comment by nikax** [comment]
I've finally successfully logged in. Looks like for some numbers it works and for some numbers it does not. I think, it has nothing to do with the code anyway. Closing. @0xTryCatch, thanks for your support.
