### ISSUE TITLE
Send html "a" href link

### ISSUE THREAD

**Issue by pedrocarvajal** [WHAnonymous/Chat-API#880]
I have the code:

$menssage = "http://google.com";

I receive the message plain.

I have to use some other code to send link?

**Comment by 0xTryCatch** [comment]
Add the sender number to your phone's address book and it will work

**Comment by pedrocarvajal** [comment]
and if I have not registered?

I want to send different messages to unknown numbers with link


---

Google translate sorry

**Comment by pedrocarvajal** [comment]
I am using a loop with more than 100 numbers, and they have recorded me

----

Google translate sorry

**Comment by 0xTryCatch** [comment]
Then it is impossible. And you will be blocked soon as well.

We don't support spammers, go away.

**Comment by CODeRUS** [comment]
I have an almost legal way to send a clickable link, but this info costs $50

**Comment by pedrocarvajal** [comment]
It is not spam, it is scrapping a web sales

we want to advise whether to publish an ad or not.

**Comment by pedrocarvajal** [comment]
I'll talk to my client and contact you

**Comment by WHAnonymous** [comment]
@pedrocarvajal we don't support you, use this API for personal usage only, we don't support any kind of bulk sending or even sending unsolicited messages to semi-random users
