### ISSUE TITLE
onMessageReceivedClient after send message

### ISSUE THREAD

**Issue by Catanp** [WHAnonymous/Chat-API#881]
Hi i can call this event "onMessageReceivedClient"  1 hour after delivery of the message?

Thanks

**Comment by mgp25** [comment]
@Catanp you dont call that event, if you use that event it will trigger the binded function when the user reads the message, everything will be shown in the debug log, if you disconnect before getting that receipt in the next login you will receive it.

Regards

**Comment by Catanp** [comment]
Sorry but don't work i send a message ana my phone is switch off, when i switct on my phone i use this script but  pollMessages() don't show me a recipt

thanks in advance


require_once('../src/whatsprot.class.php');

$debug = true;
$username = "******";
$nickname = "***"; 
$password="***";

$w = new WhatsProt($username, $nickname, $debug);
$w->eventManager()->bind("onMessageReceivedServer", "event_onMessageReceivedServer");
$w->eventManager()->bind("onMessageReceivedClient", "event_onMessageReceivedClient");

function event_onMessageReceivedClient($mynumber, $from, $id, $type, $time) 
{
    if($type == "read")
        echo "The message with id ($id) has been read from $mynumber to $from received by client.<br />";
    else
        echo "The message with id ($id) has been received from $mynumber to $from received by client.<br />";
}
function event_onMessageReceivedServer($mynumber, $from, $id, $type, $time) {
        echo "$type message $id from $mynumber to $from received by Server. <br />";
}

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password);


while(true)
{
    $w->pollMessages();
	
}
