### ISSUE TITLE
[error] Tracker exception! LoginFailure

### ISSUE THREAD

**Issue by flores10** [WHAnonymous/Chat-API#883]
Hi, sorry for my bad english, but i have a problem with login tracker. When i start the tracker, he say me [error] Tracker Exception! Login failure!. I read and try all Troubleshooting Login failure, but i can't fix it. I checked phonenumber blocked, he say not block, and config.php have number, secret code (=), db pass and time hour correct. At the end, i enabled debug option in config.php and copy this outpout message, thx a lot. (pd: edit phone number and secret code, for security)

Image 1 http://images.meteociel.fr/im/2747/image1_gqo3.jpg

**Comment by guns2410** [comment]
@flores10, i see a message which says not-authorized. This could occur if

1. Password is incorrect
2. You are blocked (temporary/permanent)

Double check the password. Recommend register again using the command line CLI registration tool and be sure that you are using the latest version of the API.

**Comment by mgp25** [comment]
@flores10 this is the API not the package you are using, do what @guns2410 has said and remove the `nextChallenge` data from `wadata` folder

Regards
