### ISSUE TITLE
Can I join the project?

### ISSUE THREAD

**Issue by artemzakholodilo** [WHAnonymous/Chat-API#884]
How stable the latest version and how can I join the project?

**Comment by mgp25** [comment]
Stable version v2.5.2: https://github.com/WHAnonymous/Chat-API/archive/v2.5.2.zip

Everything is up to date and working perfectly. Here is all the documentation: https://github.com/WHAnonymous/Chat-API/wiki

If you want to contribute, feel free to send pull requests

Regards

**Comment by artemzakholodilo** [comment]
Thank you
