### ISSUE TITLE
Cant send Image in onGetMessage 

### ISSUE THREAD

**Issue by CreaDEV** [WHAnonymous/Chat-API#885]
My Code worked a very long time but today i noticed, that the images i want to send in `onGetMessage+ doesnt get send.

But in my normal sending script images get sent.

Here is my code from `onGetMessage`:
```php
    function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
    {
        $w->sendPresenceSubscription($from);
        $w->pollMessage();
        $w->sendMessageComposing($from);
        sleep(rand(5, 10));
        $w->pollMessage();
        $w->sendMessagePaused($from);

        if($mgBack != '')
        {
	        $w->sendMessage($from, $mgBack);
        }

        if($mgBackImage != '')
        {
	        $w->sendMessageImage($from, $mgBackImage);
        }

    }

    $w = new WhatsProt($whatsappDATA->fromNumber, $whatsappDATA->whatID,   $whatsappDATA->whatNick, false);
    $w->eventManager()->bind("onGetMessage", "onMessage");
    $w->Connect();
    $w->LoginWithPassword($whatsappDATA->whatPassword);
    while($w->pollMessage())
    {
    }
```

**Comment by mgp25** [comment]
@CreaDEV this is your `onGetMessage` function? where is it binded? Post all code references

**Comment by CreaDEV** [comment]
And which part of the code is the outdated? sendMessage is still working! And how must i change my code that sendMessageImage will work again?

**Comment by mgp25** [comment]
@CreaDEV in the constructor, update your code, check your code with the latest in this repository and check all the issues, i think this is already answered

Regards

**Comment by CreaDEV** [comment]
i have update my code. but sendMessageImage still doenst work. the rest of the code works fine.

    function onMessage($mynumber, $from, $id, $type, $time, $name, $body)
    {
        if($mgBack != '')
        {
            $w->sendMessage($from, $mgBack);//this part works great
            $w->pollMessage();
        }

        if($mgBackImage != '')
        {
            $w->sendMessageImage($from, $mgBackImage);//this part doesnt work
            $w->pollMessage();
        }

    }

    $w = new WhatsProt($whatsappDATA->fromNumber, $whatsappDATA->whatnick,false);
    $w->eventManager()->bind("onGetMessage", "onMessage");
    $w->connect();
    $w->loginWithPassword($whatsappDATA->whatPassword);

    while($w->pollMessage())
    {
    }
