### ISSUE TITLE
Get Only ID Picture

### ISSUE THREAD

**Issue by paulocotta** [WHAnonymous/Chat-API#886]
Hello. What is the only way to get the id of the image of the profile?
Thank you

**Comment by mgp25** [comment]
What do you mean by id? You can use ` onGetProfilePicture($mynumber, $from, $type, $data)` event

**Comment by paulocotta** [comment]
I mean the ID (xxxxx) returned no rx, for example
<picture id="xxxxx" type="image"> 29562 byte data</picture>

**Comment by paulocotta** [comment]
"<picture id="xxxxx" type="image"> 29562 byte data</picture>"

**Comment by mgp25** [comment]
@paulocotta that id is not relevant, it doesnt give any personal or related info to the media. It's only a counter in hexadecimal

As you can see here: https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L989

Better save the profile image by its number/jid

Regards

**Comment by paulocotta** [comment]
It becomes relevant, because I can use it to mount the following URL:
"https://dyn.web.whatsapp.com/pp?t=l&u=NUMBER%40c.us&i=ID_PICTURE"

**Comment by mgp25** [comment]
@paulocotta no, you are getting confused the `iq` id is different from image id, and web whatsapp has little things the API hasn't. If you want further help, post a real URL example and maybe i can help you with an aditional function

**Comment by paulocotta** [comment]
Of course, how can I send a message in private. For I will give a real example

**Comment by mgp25** [comment]
@paulocotta you will find my email in my gitgub's profile page

**Comment by paulocotta** [comment]
OK, OK, sent email
