### ISSUE TITLE
Sending image to whatsapp number is not working

### ISSUE THREAD

**Issue by sangeetakumari566** [WHAnonymous/Chat-API#887]
```php
$username = "";
$nickname = "";
$password = ""; // The one we got registering the number
$debug = true;

// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);

$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!
$target = '34666554433'; // The number of the person you are sending the message
$caption = "Look at this awesome image!";
//filepath is the absolute path of the image file and $fsize is the file size in bytes
$w->sendMessageImage
($target, $filepath, false, $fsize, '', $caption);
$w->pollMessage();
```
![2015-07-27 17-42-49](https://cloud.githubusercontent.com/assets/13522159/8907442/f3e19dfe-3486-11e5-9a4b-6a0107578906.png)

But this code is not working i am m not getting any image in my whatsapp mobile number
Sending Video and Audio is working as expected but Image sending is not working.

I attached the debug image.
![2015-07-27 17-42-49](https://cloud.githubusercontent.com/assets/13522159/8907470/377fac04-3487-11e5-8064-3e7dbee5d6f4.png)

Please reply me as soon as possible.

**Comment by mgp25** [comment]
@sangeetakumari566 why don't you read previous issues and wiki before open a duplicate issue?

You are not polling enough, do it in a loop
