### ISSUE TITLE
Get Read/Recieve Receipts for Broadcasts

### ISSUE THREAD

**Issue by TobiM93** [WHAnonymous/Chat-API#889]
Hi Guys, I'm currently looking for a solution to save the receipts ( read / recieved ) of my broadcast messages to a DB. I'm familiar with the Event System inside MyEvents but at the moment I'm kind of confused how to set up everything.

 I think I have to use: 
`onGetBroadcastLists($mynumber, $broadcastLists){}`   in combination with: 
`
onMessageReceivedClient($mynumber, $from, $id, $type, $time, $participant) {} , onMessageReceivedServer($mynumber, $from, $id, $type, $time) {} .
`

It would be awesome hearing from you ! Thank you very much !

**Comment by mgp25** [comment]
@TobiM93 Yes, you are right. using `onMessageReceivedClient` you will get in `type` attrib. `receipt` when the user receives the message and `read` when the user has read it.

`onMessageReceivedServer` will tell you if the message was sent successfully (receipt from server)

With `onGetBroadcastLists` you will get all your broadcast lists

How to use events: https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#using-events

Regards

**Comment by TobiM93** [comment]
@mgp25 Sorry for bothering you again, what I'm doing wrong? I don't get any result. 

$w->connect();
$w->loginWithPassword($password);
$w->sendSync($contacts);
$w->sendGetStatuses($contacts); 
$w->sendPresenceSubscription($str);
$w->sendSetProfilePicture($path);
$w->onGetBroadcastLists();
$w->disconnect();  

MyEvents.php

public function onGetBroadcastLists( $mynumber, $broadcastLists ) {
   
   echo "This is" $broadcastLists ;
   
   }

**Comment by mgp25** [comment]
@TobiM93 remember to quote your code for easy reading.

The problem is, thta you are disconnecting too fast, before `$w->disconnect();`

do this:
```php
$w->connect();
$w->loginWithPassword($password);
$w->sendSync($contacts);
$w->sendGetStatuses($contacts); 
$w->sendPresenceSubscription($str);
$w->sendSetProfilePicture($path);
$w->onGetBroadcastLists();
while(true)
  $pollMessage();
```

Regards

**Comment by TobiM93** [comment]
@mgp25 Thank you ! I just thought it could be something like this but wasn't quit sure.

**Comment by TobiM93** [comment]
@mgp25  I'm so sorry, just don't get any result. I stripped my code to this and also tried with for loop instead of your while. My MyEvents.php Code is same as above. But I only get: 

WooHoo!, Phone number 491525652XXXX connected successfully!

It doesn't even disconnect.
```      
$w = new WhatsProt($username,$nickname, FALSE);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents); 
$w->eventManager()->bind("onGetMessage", "GetMessage");

    
$w->connect();
$w->loginWithPassword($password);
$w->onGetBroadcastLists();
for($i = 0; $i < 40; $i++)
{
    $w->PollMessages();
}
$w->disconnect();  
```

**Comment by KirovAir** [comment]
@TobiM93 it should not disconnect. If I am correct $w->PollMessages(); is a blocking call and waiting for data. With your current code at least ~40 or so event must happen before you reach the disconnect. If you want to disconnect when no data is received you can use something like:
while ($w->PollMessages()); but I would not recommend this.

**Comment by James2376** [comment]
@TobiM93 @mgp25 Hi I just tried to save receipts in a Mysql Database, the onGetBroadcastLists Function works fine but I don't know how to extract the ID of the broadcast to save it inside my Mysql Database and afterwards compare it to the receipts I get from users. I want to do the following task: Get ID of broadcast and save it to Database afterwards track amount of read receipts by broadcast ID.

Could one of you please help me ?

**Comment by mgp25** [comment]
@TobiM93 @KirovAir btw, there is no `PollMessages()` is `pollMessage()`

@James2376 use events, `onGetBroadcastLists`
