### ISSUE TITLE
Good protocol conventions for receiving messages

### ISSUE THREAD

**Issue by KirovAir** [WHAnonymous/Chat-API#890]
Hi all,

First of all, sorry to open an issue. (it's not really an issue but more a question).

I am currently in the process of creating a WA client which only job is to receive media files from 
various users. (It will be a number to receive pictures on a party)
The client will not respond, it will just receive the media and that's it. 

Now, I want to implement the WA protocol as nicely as possible to avoid any ban.
I have read the wiki and the CLI examples and I have came to the following:

**On first start:**
```php
connect();
loginWithPassword(WHATSAPP_PASSWORD);
sendGetPrivacyBlockedList(); 
sendGetClientConfig();
sendGetServerProperties();
sendGetHasVoipEnabled($numbers); 
sendGetGroups();
sendGetBroadcastLists();
sendSync($numbers); 
foreach ($numbers as $number) {
    sendPresenceSubscription($number);
}
sendGetStatuses($numbers);
foreach ($numbers as $number) {
    sendGetProfilePicture($number); 
}
sendPing();
```

**On every reboot:**
```php
connect();
loginWithPassword(WHATSAPP_PASSWORD);
sendGetPrivacyBlockedList(); 
```

**onGetMessage(), onGetImage(), onGetVideo()** etc.
When a new user:
```php
sendGetProfilePicture($from, true); // Used to save profile pic.
sendPresenceSubscription($from);
sendSync($from);
```
Otherwise:
```
None.
```

**onNumberWasRemoved()**
```
sendPresenceUnsubscription($number);
```

**onNumberWasUpdated()**
```
sendPresenceUnsubscription($number);
sendPresenceSubscription($number);
sendGetProfilePicture($number); 
sendGetStatuses($number);
```

Is this a good approach regarding the presence subscriptions of should I subscribe/unsubscribe on every reboot?
Am I missing any other event or response which I should include in my code to do things the 'right' way?
Is there an address where I can donate?

Next I'd like to say thanks to the dedicated developers. This is one of the most active gits I have followed so far. Thanks for your hard work!

**Comment by mgp25** [comment]
@KirovAir Everything seems fine, if it's only receiving it shoudn't be any problem, note that maybe if lot of people ( we are talking about thousands ), sends you images, WhatsApp can suspect and temporary ban that account, but yeah it seems a good flow.

Nope, only subscribe once (when syncing [also once]), and only unsubscribe when blocked or removed number.

There is a way to donate via Bitcoin, but is not required, most of the people who collaborate in this project takes this as a hobby :smile: 

Anyway: https://github.com/WHAnonymous/Chat-API#chat-api---

Regards

**Comment by KirovAir** [comment]
Thanks for the fast response mgp25!

**Comment by tonic1975** [comment]
interested in this post.
@mgp25 , think you Wahtsapp can block a number that receive only message of text (not send)?
thank you
