### ISSUE TITLE
I am getting encrypted messages.

### ISSUE THREAD

**Issue by tejasj101** [WHAnonymous/Chat-API#891]
Hello there,

I am getting the encrypted messages. I gone through the wiki, but I didn't find how to decrypt it. I read many place that try with latest code (I tried it but didn't work for me.).

Please note this happens to my one number only, the another number is working fine.

Please guide.
Thanks & Regards

**Comment by mgp25** [comment]
@tejasj101 it's explained here: https://github.com/WHAnonymous/Chat-API/issues/858#issuecomment-122224842

Remove your account, delete files stored in `wadata` folder and register using `registerTool.php`

Regards

**Comment by tejasj101** [comment]
Thanks for the prompt reply. How can I remove my account. I didn't register that number via any device. I just used it through the API.

**Comment by CODeRUS** [comment]
If you used this number in android earlier then your contacts should remove you from phonebook and add you again

**Comment by mgp25** [comment]
Use this: https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L1185

Disconnect

Remove all data from `wadata` folder, and use `registerTool.php` again.

Also what @CODeRUS said will work
