### ISSUE TITLE
not completed execution

### ISSUE THREAD

**Issue by ahmedmus** [WHAnonymous/Chat-API#892]
when I am trying to send a message it stops here
```xml
<stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="96170307065"></auth>
```

**Comment by mgp25** [comment]
@ahmedmus post your script code. Make sure your account is not blocked, use `blockChecker.php`

Regards

**Comment by ahmedmus** [comment]
no it is not blocked 



$password=" xxxxxxxxxxxxxxxxxxxxxx";

$userPhone="961XXXXXX";
$userIdentity="hello";
$debug=true;


$w = new WhatsProt($userPhone, $userIdentity, $debug);

$w->Connect();

$w->loginWithPassword($password);


$w->sendMessage($phone ,"hi");

**Comment by mgp25** [comment]
@ahmedmus you are not polling. Use this instead:

```php
$password=" xxxxxxxxxxxxxxxxxxxxxx";

$username = "961XXXXXX";
$nickname = "Test";
$debug = true;


$w = new WhatsProt($username, $nickname, $debug);
$w->Connect();

$w->loginWithPassword($password);
$w->sendMessage($phone ,"hi");

while(true)
$w->pollMessage();
```
