### ISSUE TITLE
how to show error message 

### ISSUE THREAD

**Issue by saomair** [WHAnonymous/Chat-API#896]
require '../src/whatsprot.class.php';
require '../src/events/MyEvents.php';
$username = "xxxxxxxxxxxxx";
$nickname = "xxxx";
$password = "txxxxxxxxx="; // The one we got registering the number
$debug = false;
// Create a instance of WhastPort.
$w = new WhatsProt($username, $nickname, $debug);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents);
$w->connect(); // Connect to WhatsApp network
$w->loginWithPassword($password); // logging in with the password we got!	
$target = xxxxxxxxxxxxx; 

$w->sendGetRequestLastSeen($target);

Above is the script which i am using, my question is if the person has privacy on how to show error message example below.

Show last seen or if not then show error code="403" text="forbidden" error

Thank you

**Comment by mgp25** [comment]
@saomair quote your code, next time remember it.

You get that error because the user you are trying to check the `last seen` time has enabled privacy, that's it.

**Comment by saomair** [comment]
Thank you MGP25 , but my question is if Privacy Enable how to show error message ?

**Comment by saomair** [comment]
i want to echo error message if Privacy is enable if not the show the last seen

**Comment by mgp25** [comment]
@saomair use event manager, it's explained in the wiki

**Comment by saomair** [comment]
can you show me any small example please ?

**Comment by saomair** [comment]
i am still waiting please can you show me any example ?

**Comment by mgp25** [comment]
@saomair it's explained in the wiki, use event manager, `onError` event. there are also examples in the folder `examples` like `exampleFunctional.php` so you can see how events work
