### ISSUE TITLE
Dont get the messages while sending a message/image/video

### ISSUE THREAD

**Issue by sant527** [WHAnonymous/Chat-API#898]
My number is `XXXXXXXX`

I am in a group whose id is `GGGGGGG-1438338377`

phone number `YYYYYYYY` is also a member in that group . He is sitting beside me. 

So `YYYYYYYY`  sent a message ("hai, i am at home") to group(GGGGGGG-1438338377) . And my Mobile (on which whatsapp is insatalled for number XXXXXXXX) is switchedoff. (so i cant recieve any messages till i switch it on). I generally do this whenever i use chat-api.

I am sending an image to the group `GGGGGGG-1438338377` from my laptop using chat-api. The following is the code.
```php
<?php
require_once('/home/gaura/WhatsAPI-Official/src/whatsprot.class.php');
$username = "XXXXXX";
$nickname = "jai";
$w = new WhatsProt($username,null, $nickname, true);
$w->Connect();
$w->LoginWithPassword('kkkkkkkkkkkk');
$gid = "GGGGGGGG-1438338377";
$w->sendMessageImage($gid, "/home/gaura/sample.jpg");
$w->disconnect();
?>
```

The image is sent to group `GGGGGGG-1438338377` successfully. ALso my friend sitting beside me gets the image immediately on the group (`GGGGGGG-1438338377`) in his whatsapp.

Now i switch on the mobile. Thing I observed is i dont get the message "hai, i am at home" on my whatsapp in my mobile on the group `GGGGGGG-1438338377` from my friend. 

Also i dont see the image on my group. 

So i am missing both message and the image on my mobile whatsapp.

So what is observed is,  when i ran chat-api it got all the messages. the following output shows that "hai, i am at home" is downloaded by chat-api
```xml
rx  <message from="XXXXXXXXX-1438338377@g.us" id="1438361855-3" participant="YYYYYYYYY@s.whatsapp.net" offline="0" type="text" t="1438361855" notify="">
rx    <body>hai, i am at home</body>
rx  </message>

tx  <receipt type="read" participant="YYYYYYYYY@s.whatsapp.net" to="XXXXXXXXX-1438338377@g.us" id="1438361855-3" t="1438361877"></receipt>

......

rx  <ack from="XXXXXXXXX-1438338377@g.us" id="1438361855-3" participant="YYYYYYYYY@s.whatsapp.net" class="receipt" type="read"></ack>
```

It shows the  `rx    <body>hai, i am at home</body>` and says `class="receipt" type="read"></ack>`

So how to stop chat-api to download messages while sending image/message/video. Because i will miss some messages if this happens in my phone.

**Comment by mgp25** [comment]
@sant527 first of all, update your code, you are using an outdated version.

Use event manager to get all messages, and if you want you can save it in a sqlite database which is already coded in the API. you can see more info about this in the wiki on `How to use events` and `save messages`

And remember to poll messages and dont disconnect so fast.

Regards
