### ISSUE TITLE
Encryption in action again, something changed.

### ISSUE THREAD

**Issue by Udirley** [WHAnonymous/Chat-API#899]
See how I'm getting messages to numbers recently activated.

```xml
rx  <message from="55xxxxxxxx@s.whatsapp.net" id="1438346026-34" type="text" t="1438352024" notify="Name">
rx    <enc v="1" type="pkmsg">▒ĩ!za▒\lY2▒ ▒▒1s▒▒KAAK▒▒e!▒▒▒N<|▒ە        ▒yH▒6𴔠0u▒▒▒▒▒A▒'▒b"B3
!▒3Ʒ▒S▒#▒Q▒▒F1@▒
                N▒z▒e▒▒/▒▒▒s"▒+b▒▒▒▒!▒$a▒▒▒fӳ▒▒▒e(▒▒٦0</enc>
rx  </message>

tx  <receipt type="read" to="55xxxxxxxx@s.whatsapp.net" id="1438346026-34"></receipt>
```

**Comment by Udirley** [comment]
rx  <message from="55xxxxxxxx@s.whatsapp.net" id="1438346026-34" type="text" t="1438352024" notify="Name">
rx    <enc v="1" type="pkmsg">▒ĩ!za▒\lY2▒ ▒▒1s▒▒KAAK▒▒e!▒▒▒N<|▒ە        ▒yH▒6𴔠0u▒▒▒▒▒A▒'▒b"B3
!▒3Ʒ▒S▒#▒Q▒▒F1@▒
                N▒z▒e▒▒/▒▒▒s"▒+b▒▒▒▒!▒$a▒▒▒fӳ▒▒▒e(▒▒٦0</enc>
rx  </message>

tx  <receipt type="read" to="55xxxxxxxx@s.whatsapp.net" id="1438346026-34"></receipt>

**Comment by Udirley** [comment]
rx  \<message from="55xxxxxxxx@s.whatsapp.net" id="1438346026-34" type="text" t="1438352024" notify="Name"\>
rx    \<enc v="1" type="pkmsg">▒ĩ!za▒\lY2▒ ▒▒1s▒▒KAAK▒▒e!▒▒▒N<|▒ە        ▒yH▒6𴔠0u▒▒▒▒▒A▒'▒b"B3
!▒3Ʒ▒S▒#▒Q▒▒F1@▒
                N▒z▒e▒▒/▒▒▒s"▒+b▒▒▒▒!▒$a▒▒▒fӳ▒▒▒e(▒▒٦0</enc>
rx  \</message\>

tx  \<receipt type="read" to="55xxxxxxxx@s.whatsapp.net" id="1438346026-34">\</receipt>

**Comment by mgp25** [comment]
@Udirley instead of opening new issues, why you don't search already answered issues?

Use this script: https://github.com/WHAnonymous/Chat-API/blob/master/examples/resetAccount.php

And then use `registerTool.php`
