### ISSUE TITLE
Error: sendMessageAudio - Limit Size?

### ISSUE THREAD

**Issue by alissonlinneker** [WHAnonymous/Chat-API#901]
I have MP3 file (Size: 11022497 bytes)
Sometimes sends, but I received it cut only 24k.
Why?

I can not send audio greater than 10MB. Even changing the `upload_max_filesize` and `post_max_size` in `php.ini`

**Comment by mgp25** [comment]
@alissonlinneker it's explained in the code and wiki. WhatsApp limits media files to 5MB

https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L2441
