### ISSUE TITLE
Emojis how to ? Already looked up FAQ etc..

### ISSUE THREAD

**Issue by TobiM93** [WHAnonymous/Chat-API#902]
Hi I already read the FAQ Part about the Emojis but can't change them from this : ##1F454## to \xF0\x9F\x91\x94 I also tried with some PHP Library but I don't get it =( 
Could you help me with some code please ?

**Comment by mgp25** [comment]
@TobiM93 you can use this helper class instead: https://github.com/WHAnonymous/Chat-API/blob/master/src/smileys.class.php

**Comment by TobiM93** [comment]
@mgp25 Hi sorry for bothering you again. I found a solution with the help of your script but if I POST a Message like: "Hi this is a Test \xF0\x9F\x91\x94" via AJAX to my PHP Script and use it as $caption for a BroadcastMessage I just get the  \xF0\x9F\x91\x94 displayed inside the message. If I do it manually like tiping $caption = "Hi this is a Test \xF0\x9F\x91\x94" it converts to the Emoji. What am I doing wrong ? I get UTF-8 by mb_internal_encoding("UTF-8");  inside my PHP Script.
