### ISSUE TITLE
Maximum execution time exceeded error on Google cloud storage app engine

### ISSUE THREAD

**Issue by bhargavgollamudi** [WHAnonymous/Chat-API#903]
Hi,  I have been using this API from two months. I am using ajaxDemo folder files for sending text messages to a number. In test server i am not getting any error. But i am getting PHP fatal error on Google cloud storage app engine. The socket.php file ajax request has running for more than 1 minute. In google app engine max execution time is 1 minute.  How should is solve this issue ? I have tested also using latest files.

Following is the code i am using in socket.php file

session_start();
session_write_close();
include_once('includes/config.inc.php');
$time = $_SESSION["running"];

function onGetProfilePicture($from, $target, $type, $data)
{
	global $is_production;
	$fileUrl = '';
	
    if ($type == "preview")
	{
        $filename = 'gs://simtredbdump/preview_' . $target . '.jpg';
		$fileUrl = 'download_file.php?file_name=preview_' . $target . '.jpg';
    }
	else
	{
       $filename = 'gs://simtredbdump/' . $target . '.jpg';
	   $fileUrl = 'download_file.php?file_name=' . $target . '.jpg';
    }

    $fp = @fopen($filename, "w");
    
	if ($fp)
	{
        fwrite($fp, $data);
        fclose($fp);
    }
	
    session_start();
    $_SESSION["profilepic"] = $fileUrl;
    session_write_close();
}

function running($time)
{
    session_start();
    $running = $_SESSION["running"];
    
	if ($running != $time)
	{
       die();
    }
	
    session_write_close();
    return true; //continue running
}

$target = @$_POST["target"];
require_once("whatsapp_api/whatsprot.class.php");
$username = $whatsAppNumber; // Mobile number with code
$debug = false;
$name = "Real Estate";
$identityFile = false;

if($is_production == 1)
{
	$identityFile = 'gs://simtredbdump/id.'. $whatsAppNumber .'.dat';
}

$w = new WhatsProt($username, $name, $debug, $identityFile);

if($is_production == 1)
{
	$filename = 'gs://simtredbdump/nextChallenge.'. $mobile .'.dat';
	$w->setChallengeName($filename);
}

$w->connect();
$w->loginWithPassword($whatsAppPassword);
$w->eventManager()->bind("onGetProfilePicture", "onGetProfilePicture");
$w->sendPing();

$initial = @$_POST["initial"];

if ($initial == "true" && $target != null)
{
    //request contact picture only on first call
    $w->sendGetProfilePicture($target);
}

//subscribe contact status
$w->SendPresenceSubscription($target);

while (running($time))
{
    while($w->pollMessage());

    running($time); 
	session_start();
    $outbound = $_SESSION["outbound"];
    $_SESSION["outbound"] = array();
    session_write_close();
	
    if (count($outbound) > 0)
	{
        foreach ($outbound as $message)
		{
            $w->sendMessage($message["target"], $message["body"]);
            $w->pollMessage();
        }
    }
    
    $w->sendPing();

    //check for received messages:
    $messages = $w->getMessages();
	
    if (count($messages) > 0)
	{
        session_start();
        $inbound = $_SESSION["inbound"];
       
        foreach ($messages as $message)
		{
			$from_str = @$message->getAttribute('from');
			$temp_str_pos = strpos($from_str, "@");
			$from = substr($from_str, 0, $temp_str_pos);
			
			if($from == $target)
			{
				$data = @$message->getChild("body")->getData();
				
				if ($data != null && $data != '')
				{
					$inbound[] = $data;
				}
            }
        }
		
        $_SESSION["inbound"] = $inbound;
        session_write_close();
    }
	
	$w->sendPing();
}

**Comment by 0xTryCatch** [comment]
This issue is not related to the API. Increase your max execution time.

**Comment by bhargavgollamudi** [comment]
But i am getting this error in whatsprot.class.php file. 

Fatal error: The request was aborted because it exceeded the maximum execution time. in /base/data/home/apps/s~eng-diagram-703/1.386189211877119777/whatsapp_api/whatsprot.class.php on line 570


At LIne Number 570
$s = socket_select($r, $w, $e, Constants::TIMEOUT_SEC, Constants::TIMEOUT_USEC);

Will it change if i change TIMEOUT_USEC to 59 instead of  0 ?

**Comment by 0xTryCatch** [comment]
It is a PHP setting, not API related
