### ISSUE TITLE
message unreadable (encrypted?)

### ISSUE THREAD

**Issue by kw005** [WHAnonymous/Chat-API#905]
Hi,
 when running "# php whatsapp.php -l" I get all however I am unable to read the messages received?
How can I read those messages?

...
rx    enc v="1" type="msg">3
!▒▒▒0▒:▒▒HqU"鮾l▒▒K▒▒i▒(▒▒t
"vm]T▒▒▒]d▒f▒p▒▒▒}▒
                   h6 /enc>
..

**Comment by CODeRUS** [comment]
https://github.com/WHAnonymous/Chat-API/issues/891
https://github.com/WHAnonymous/Chat-API/issues/893
https://github.com/WHAnonymous/Chat-API/issues/899

**Comment by kw005** [comment]
I removed the account, deleted src/wadata/* and re-registered. 
The same problem, I still cannot read any messages. Do I miss something?

 <message from...
rx    enc v="1" type="msg">3
!▒▒▒0▒:▒▒HqU"鮾l▒▒K▒▒i▒(▒▒t"▒쨥▒▒LuٻǽL▒67
▒▒d▒▒/enc>
rx  /message>

tx  receipt type="read" to="4

**Comment by kw005** [comment]
#906 - more people think there might be a bug.

**Comment by WHAnonymous** [comment]
@kw005 look mate, there is no bug. Just use the `resetAccount.php` script, it's also explained in many other issues
