### ISSUE TITLE
message unreadable (encrypted?) - still open!!

### ISSUE THREAD

**Issue by kw005** [WHAnonymous/Chat-API#906]
#905

I reset the account, deleted src/wadata/* and re-registered. 
The same problem, I still cannot read any messages. Do I miss something?

 <message from...
rx    enc v="1" type="msg">3
!▒▒▒0▒:▒▒HqU"鮾l▒▒K▒▒i▒(▒▒t"▒쨥▒▒LuٻǽL▒67
▒▒d▒▒/enc>
rx  /message>

tx  receipt type="read" to="4

**Comment by 0xTryCatch** [comment]
Stop opening new issues. Use the resetAccount script in examples. It works.

**Comment by kw005** [comment]
Sorry, I did it the 3 times - it does NOT work.

############
Step 1
############


# php resetAccount.php
####################
#                  #
#     WA RESET     #
#                  #
####################


Username (country code + number without + or 00): 49157***


Your accounts password: ***


 OK! Now use registerTool.php

############
Step 2
############

srv/wadata# rm -r *

############
Step 3
############

s# php registerTool.php
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number without + or 00): 4915736688499


Type sms or voice: voice
Array
(
    [in] => 1573****
    [cc] => 49
s`▒^u;▒▒kŁ▒-▒s▒h
    [lg] => de
    [lc] => DE
    [sim_mcc] => 262
    [sim_mnc] => 000
    [method] => voice
    [token] => f4a8871943b52c3ace07c7ecbe8da205
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => voice
    [retry_after] => 82805
)


Enter the received code: 297-005

Your password is: *****


############
Step 4
############
# php whatsapp.php -l
PHP Notice:  Undefined offset: 2 in /home/pi/Chat-API/tests/whatsapp.php on line 34
[] Logging in as ....
...
  enc v="1" type="msg">3
!¦¦¦0¦:¦¦HqU"?l¦¦K¦¦i¦(¦¦t"cv¦¦k¦[¦¦¦=j¦<¦dq¦y¦¦/enc>
rx  /message>

.....

[tag:ProtocolNode:private] => enc
                            [attributeHash:ProtocolNode:private] => Array
                                (
                                    [v] => 1
                                    [type] => msg
                                )

                            [children:ProtocolNode:private] =>
                            [data:ProtocolNode:private] => 3
!¦¦¦0¦:¦¦HqU"?l¦¦K¦¦i¦(¦¦t"cv¦¦k¦[¦¦¦=j¦<¦dq¦y¦¦
                        )

                )
....

------------>
This does work?

**Comment by Udirley** [comment]
Good afternoon,

I've also realized this procedure more than once and with different numbers, and keep getting encrypted messages.

If I send a message from an IOS message is received normally.
If I send an encrypted message arrives to Android.

Please help us find a solution.

**Comment by kw005** [comment]
Yes, I am using android. So it seems to be a BUG and it is NOT working!!!!

**Comment by WHAnonymous** [comment]
@kw005 man, quit using android, i mean, don't use your number in android device, that's it. Delete your account in your device if required, remember to delete your identity, and then register your number, this way you will reset your account, if you keep using android, you will receive encrypted messages, and it's not a bug.

So be patience, and do it right.

**Comment by kw005** [comment]
@WHAnonymous, sorry for being impatient here. The SIM card has been placed for weeks in a "Samsung E1200i", so there is no way to even install the app whatsapp on that phone. I did "resetAccount.php" and reset + re-register the number several times with the same result receicing encrypted messages. So, I have to place the sim card back in an android device, delete my account there and then do those steps mentioned again?

**Comment by WHAnonymous** [comment]
@kw005 yes, that will do the trick. Once you have deleted your account using your device, delete all files inside the `wadata` folder, then simply run `registerTool.php`

**Comment by Udirley** [comment]
@kw005 This you will do've ever done.
Completely deleted the account using the device itself where the chip is installed and then deleted the files (.dat) related to this number in wadata directory, then again ran the registerTool.php.
The bill returns to work but receiving encrypted messages when the person who is sending me the message using Android.
The only difference in the procedures performed is that I can not erase all wadata directory files for I have many numbers there, so I deleted only relaciondos files with the number.

**Comment by guicouto** [comment]
Hello Guys. I know thas the subject was solved many times here, but reset account and after using registerTool.php didn't solve my problem. I tried twice, and doesn't work. Anyone can help me please? Hugs

**Comment by mgp25** [comment]
@guicouto Install all dependencies/extensiones mentioned in the wiki
