### ISSUE TITLE
send text message via group

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#908]
@mgp25 @WHAnonymous  .. i make an c# interface to this api .. all things works fine but when i send message using query string using my Arabic language, i get notification created group and add friends but the text is question marks !!!!! however when i copy the request link and  used it in my browser i get right message !!! .. so why i get incorrect message (question marks) through my interface but get the correct message if i use my browser ???

**Comment by WHAnonymous** [comment]
@beljk remember to UTF-8 encode it
