### ISSUE TITLE
problem with create new group

### ISSUE THREAD

**Issue by amin0256** [WHAnonymous/Chat-API#909]
Hi,
I want to create a new group with 2 participant but i have problem.
this is my php code: 
```php
$Gid = $w->sendGroupsChatCreate('Joke', ['999999999xxx', '99999999yyy');
```
and this is debug tools: 
```xml
tx  <iq xmlns="w:g2" id="2" type="set" to="g.us">
tx    <create subject="Joke">
tx      <participant jid="99999999yyy@s.whatsapp.net"></participant>
tx      <participant jid="989383234886@s.whatsapp.net"></participant>
tx    </create>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

rx  <presence from="99999mainnumber@s.whatsapp.net"></presence>

rx  <presence from="9999999zzz@s.whatsapp.net" type="unavailable" last="deny"></presence>
```
9999999zzz number is not exist in the participant list !

what is the problem?
thanks for helping.

**Comment by WHAnonymous** [comment]
@amin0256 you have not added `9999999zzz` to `$Gid = $w->sendGroupsChatCreate('Joke', '999999999xxx', '99999999yyy');`

And this:

```xml
rx  <presence from="9999999zzz@s.whatsapp.net" type="unavailable" last="deny"></presence>
```

means your are subscribed to that user, and it went offline

Also in your `iq` there are two participants:

```xml
tx      <participant jid="99999999yyy@s.whatsapp.net"></participant>
tx      <participant jid="989383234886@s.whatsapp.net"></participant>
```

so i do not see any problem. If your problem persist, give more details
