### ISSUE TITLE
PHP Version

### ISSUE THREAD

**Issue by edufranzen** [WHAnonymous/Chat-API#910]
Using PHP version 5.5 I can obtain the code of whatsapp, but when I use with PHP version 5.3.10 I receive this error:

`missing_param [param] => token`

I can´t upgrade the PHP version in my project, but do you know any way that I can integrate the ChatAPI with this PHP version?

**Comment by WHAnonymous** [comment]
@edufranzen download the API code again, you have an outdated one

**Comment by edufranzen** [comment]
I've done this, but didn't work...

Date: Thu, 6 Aug 2015 06:46:09 -0700

**Comment by WHAnonymous** [comment]
@edufranzen contact @mgp25 his mail is in his github's profile page
