### ISSUE TITLE
Is correct this code?

### ISSUE THREAD

**Issue by stefy97100** [WHAnonymous/Chat-API#911]
Hi, i used Chat-API but I get my number banned.. I have change the code, can you please tell if now it can work without get banned? Thanks

```php
<?php
	require_once 'src/whatsprot.class.php';

	$username = "number";
	$password = "password";
	$debug = true;  

	$target = 'target'; //Target Phone,reciever phone
	$message = 'TEST';

	$w = new WhatsProt($username, "ITT BARSANTI", $debug);
	$w->connect();

	$w->loginWithPassword($password);

	$w->sendGetPrivacyBlockedList();

	$w->sendGetClientConfig();

	$w->sendGetServerProperties();

	$w->sendSync($target);

	$w->sendPresenceSubscription($target);

	$w->sendMessageComposing($target);
	sleep(1);

	$w->sendMessagePaused($target);

	$w->sendMessage($target, $message);

	$w->pollMessages();
	sleep(2);

	$w->disconnect();
?>

**Comment by guns2410** [comment]
There are number of possibilities of a number getting blocked.

1. Sending too many messages to non-contacts
2. Syncing contacts too often (Sync Contacts only on the first login and not too often)
3. Did not send typing node and paused typing node before sending a message
4. SPAMMING
5. Many Block requests from people

**and the list goes on...**

I see you disconnect too often within the script. If you are running a cron job, be sure that the time interval is high. Else run an endless loop to keep the connection alive.

Just make sure that you follow exactly the same things that the official client does and you should not be blocked.

And yes, you should poll message before sending one. This could be one of the things that might save you from a block.

I guess all the information that you need is there in the WIKI. Be sure to use the latest version of the API and read the WIKI thoroughly before moving ahead.

**Comment by stefy97100** [comment]
My problem is that i send the messages only to non contacts.. The user give me their number and I send him some messages... What I have to do? They have first to add my number on their phone?

**Comment by guns2410** [comment]
@stefy97100, if you are sending messages to non-contacts you are **SPAMMING**. Your number **WILL** be blocked.
