### ISSUE TITLE
Please read

### ISSUE THREAD

**Issue by stefy97100** [WHAnonymous/Chat-API#912]
Hi, i’m the user of this discussion (https://github.com/WHAnonymous/Chat-API/issues/911)
I will NOT spam!! I’m developing a website for my school where the student can subscribe to some private courses for get help from other student. I’m using WhatsApp for send to the student if they can or not partecipate to the course. I get the number from the student but i’m not on their contact list, what i have to do?
Thanks

**Comment by CODeRUS** [comment]
Obviously: You need to ask then to add you to phonebook to receive messages with no problems.

**Comment by stefy97100** [comment]
Is possible to check who have add me on the phonebook? (list of numbers)

**Comment by CODeRUS** [comment]
Well, no.
