### ISSUE TITLE
Successful registration, but unable to log in (number not blocked)

### ISSUE THREAD

**Issue by jhappone** [WHAnonymous/Chat-API#913]
Hi!

I'm really happy to find this kind if Whatsapp-api, but I'm having troubles when trying to use it. In short, registration went ok but I cannot log in. Number is not blocked. I've tried with four different phone numbers with vanilla API installation, two different server, but it always fails on `$w->loginWithPassword` with `Fatal error: Uncaught exception 'LoginFailureException'`

I'm running PHP 5.6.2

Here are the registration and connection steps with debug output, code is the example code (`registerTool.php`, `Simple CLI client.php` and `blockChecker.php`)

I registered my number successfully and obtained password:

```
####################
#                  #
# WA Register Tool #
#                  #
####################


Username (country code + number without + or 00): 3584499*****


Type sms or voice: sms
Array
(
    [in] => 4499*****
    [cc] => 358
    [id] => ▒v▒]▒z{
▒▒(▒'▒(▒p`$w
    [lg] => fi
    [lc] => FI
    [sim_mcc] => 244
    [sim_mnc] => 000
    [method] => sms
    [token] => 5e95951a2f3a1750648a67605e7d22ae
)
stdClass Object
(
    [status] => sent
    [length] => 6
    [method] => sms
    [retry_after] => 1805
)


Enter the received code: 956-274

Your password is: ucQrANGHJWCVH****
stdClass Object
(
    [status] => ok
    [login] => 3584499*****
    [pw] => ucQrANGHJWCVHOH****
    [type] => new
    [expiration] => 1470515577
    [kind] => free
    [price] => 0,89 €
    [cost] => 0.89
    [currency] => EUR
    [price_expiration] => 1441677252
)
```

`Simple CLI client.php` configuration:
```php
////////////////CONFIGURATION///////////////////////
////////////////////////////////////////////////////
$username = "Foobar 223345******";
$password = "ucQrANGHJWCVH****";
$nickname = "Foo bar";
$debug = true;
/////////////////////////////////////////////////////
```

When I try to connect using `Simple CLI client.php`,  I get the following:

```xml
> php Simple\ CLI\ client.php 3584499*****

####################################
#                                  #
#           WA CLI CLIENT          #
#                                  #
####################################

====================================
[] logging in as 'Foo bar' (Foobar 22334543908)
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="Foobar 22334543908"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>▒+s!
                   ▒f▒▒▒▒pbİ&c</challenge>

tx  <response>▒▒▒H[J▒8)-O▒▒▒▒&▒▒Fn▒1l¡▒9▒▒▒▒5▒%l▒</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

Fatal error: Uncaught exception 'LoginFailureException' in /...../php/Chat-API/src/whatsprot.class.php:2273
Stack trace:
#0 /...../php/Chat-API/src/whatsprot.class.php(551): WhatsProt->doLogin()
#1 /...../php/Chat-API/examples/Simple CLI client.php(62): WhatsProt->loginWithPassword('ucQrANGHJWCVHOH...')
#2 {main}
  thrown in /...../php/Chat-API/src/whatsprot.class.php on line 2273
```

In FAQ `<not-authorized></not-authorized>` states that my number is blocked, but when I try blockChecker.php:

<pre>
####################
#                  #
# WA Block Checker #
#                  #
####################

Username (country code + number without + or 00): 3584499*****

Your number 3584499***** with the following password tS+WIw34McS6rjIIO5VnkfWDvRU= is not blocked
</pre>

I'm also wondering, why the password in returned in blockChecker.php is always changing?

I hope you could give me some hints how to continue? Is there any other log where to see what is going on?

br,
Jukka

**Comment by WHAnonymous** [comment]
@jhappone Some numbers are facing a new weird issue (the one you are talking about) and we're researching it, as soon as we know something, we'll let you know, meanwhile you can use other numbers.

> I'm also wondering, why the password in returned in blockChecker.php is always changing?

That's what bockChecker do, if you aren't blocked, then WhatsApp will let you to reset the password, in that case you aren't blocked :smile:

Here is log from other user experiencing the same issue:

```xml
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="***********"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>"??U?.??W?/*?</challenge>

tx  <response>9?????kҎ̨ゔ??Z?????uqn??>~</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by WHAnonymous** [comment]
@jhappone i just notice one thing in your settings:

```php
$username = "Foobar 223345******";
```

should be only the number:

```php
$username = "223345******";
```

Without the `Foobar`

**Comment by jhappone** [comment]
Hi and thank you!

Now it works like a charm!

Keep up the good work!

br,
Jukka
