### ISSUE TITLE
blocked after adding members to group

### ISSUE THREAD

**Issue by MoudiZd** [WHAnonymous/Chat-API#915]
Hellow ! in brief description i have created a group and added 5 members that have my number in their contact list but oops i have been blocked !
Same thing before sometimes it was made without any problem .
So what it has been changed in whatsapp conditions and terms of use ?

**Comment by WHAnonymous** [comment]
@MoudiZd nothing has changed, maybe you have done something wrong or someone blocked you

**Comment by luciano-work** [comment]
Also happens to me
A few minutes later :(

**Comment by WHAnonymous** [comment]
@luciano-work want further support? post debug log and code

**Comment by luciano-work** [comment]
I tried again and blocked another number :(

Im use this function 
/*
$usuario = "55xxxxxxxxxxx";
$nickname = "xxxx";
$password  = "xxxxx";

$w = new WhatsProt($usuario, $nickname, true);
$events = new MyEvents($w);
$events->setEventsToListenFor($events->activeEvents);

$w->connect();
$w->loginWithPassword($password);

//this code block my number
$groupId = "55xxxxxxxxxxx-1439495879";
$participants = "55xxxxxxxxxxx";
$w->sendGroupsParticipantsAdd($groupId, $participants);
*/

the code 'add' the contact in the group but Then blocked my number again :(
How do I send the debug paragraph ? My Two numbers Were blocked.

**Comment by 0xTryCatch** [comment]
Did you create the group first with ```sendGroupsCreate```?

**Comment by luciano-work** [comment]
@0xTryCatch I did this :

My phone number (X)
My API number (Y)

I created the group through my phone number (X) using the WA app and add my API number (Y) to the group , Then promoted him (Y) as a group administrator ,
removed the number (X) from group using the API and Then tried to add back the number (X) in the group again, Which was blocked my number (Y) API.

Does this happen because the group was created through the WA app and not the API?

**Comment by luciano-work** [comment]
@WHAnonymous 
Now I created the group using API and added a new contact but also blocked my new number :(

//CREATE GROUP
$participants = array("34123456789", "34987654321");
$w->sendGroupsChatCreate("Group Name", $participants);

//ADD 
groupId = "55xxxxxxxxxxx-1439554612";
$participants = array("55xxxxxxxxxxx");
$w->sendGroupsParticipantsAdd($groupId, $participants);

NOBODY IS WITH THIS PROBLEM ?

**Comment by WHAnonymous** [comment]
@luciano-work post debug log

**Comment by luciano-work** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="55xxxxxxxxx">]�F'55xxxxxxxxx8�/�Z �;z\P���<�f41439559013</auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>��L��F�|*FC"��nҴz</challenge>

tx  <response>U���B#D�H�7�)��X���V�L��(+�E%�i�</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

**Comment by WHAnonymous** [comment]
@luciano-work i mean when you are creating the group and adding the number, i need that debug log

**Comment by luciano-work** [comment]
@WHAnonymous 

I found the problem :)
if you try add the participant in the group Where it already exists, your number will be blocked .
my code had a loop!

Thank you :)
