### ISSUE TITLE
LoginFailureException

### ISSUE THREAD

**Issue by cpussetto** [WHAnonymous/Chat-API#917]
Hello, I tried all options and not get a correct login.

The error I get is:
`
Fatal error: Uncaught exception 'LoginFailureException' in /home/clubdefo/public_html/whatsapp_api/Chat-API-master/src/whatsprot.class.php:2273 Stack trace: # 0 / home / clubdefo / public_html / whatsapp_api / Chat-API -master / src / whatsprot.class.php (551) WhatsProt-> doLogin () # 1 /home/clubdefo/public_html/whatsapp_api/Chat-API-master/examples/exampleFunctional.php(64): WhatsProt-> loginWithPassword ('Mj9FM + pJVfsL6mb ...') # 2 {main} thrown in /home/clubdefo/public_html/whatsapp_api/Chat-API-master/src/whatsprot.class.php on line 2273
`

I generated the ID and password using `registerTools.php`
Then I reset the password with `blockChecker.php` smoothly (is not blocked)

Username (country code + number without + or 00): Your number `[MY NUMBER]` With the following password `***7DfQHhO*****DNb*0g****Pc=` is not blocked

Also delete the entire directory `/wadata` and realized the process several times without success.

Previously also make the process WART unsuccessfully, I read all considerations l wiki without success.

They can assist me? Thank you.

**Update:** Other info, I tested with numbers Personal and Claro Argentina, I understand that is not dependent on the number or the country, but I would like to confirm this point.

**Comment by cpussetto** [comment]
Other info, I tested with numbers Personal and Claro Argentina, I understand that is not dependent on the number or the country, but I would like to confirm this point.

**Comment by cpussetto** [comment]
The last password is: TJ/l4ebeSN+XAtzjTr2CwcBNq7w=

**Comment by 0xTryCatch** [comment]
Can you show the response from the registration please? Hide the password

**Comment by WHAnonymous** [comment]
@cpussetto post full debug please and if you want, send the number and password and we'll try in our side

**Comment by phoenix-blue** [comment]
I have here also the same problem.
When i use an simple send script (with an password get from WART) i receive the message into whatsapp.
Only when i run the client.php i get the same error.

I think that i somewhere have forget write the user info, is there an other place (except in the Simple CLI client.php) where i insert the $username,$nickname and $password?

**Comment by cpussetto** [comment]
Ok , I will send the information to your email promptly

**Comment by cpussetto** [comment]
Dear,
I have already sent the information requested by email

**Comment by WHAnonymous** [comment]
@cpussetto reset your password using `registerTool.php` but use this number when logging in instead:

`5493515304845`

Notice the `9` after the country code

**Comment by cpussetto** [comment]
Hello, Thanks runs OK!
