### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by arth1992** [WHAnonymous/Chat-API#918]
Hello

I got this error whenever i try to send or receive messages.
"Booo!, Phone number 91************* is disconnected!" 
Any  solution for this ?

**Comment by WHAnonymous** [comment]
@arth1992 read the wiki: https://github.com/WHAnonymous/Chat-API/wiki

Check if the number is blocked with `blockChecker.php` if it's blocked, there is nothing to do, if it is not, then use any script in the `examples` folder and try if it works.

**Comment by arth1992** [comment]
Thanks for your solution.

sorry . but i am asking another question.  whenever i try to receive message its shows only one message and after when i reload it there are no msg to show. its empty.  Is there any way to receive msgs continuously every 1 min ?  Please help me with this i am stucked.

Can you provide me with any solution ?

Thanks in advance 
Arth
