### ISSUE TITLE
Erro send image

### ISSUE THREAD

**Issue by usinadeideia** [WHAnonymous/Chat-API#919]
Hello guys,

I have a problem, sending some pictures and they come in contact WhatsApp, others do not arrive, since checked extension (PNG, JPG) and size, all with 1 to 10k.

What could be happening?

Thank you

**Comment by 0xTryCatch** [comment]
Post your debug log

**Comment by WHAnonymous** [comment]
@usinadeideia you are not polling enough, if you want further support, remember to post full debug log and code if possible
