### ISSUE TITLE
Report Spam feature

### ISSUE THREAD

**Issue by Sputuks3** [WHAnonymous/Chat-API#920]
How to implement this feature? For numbers not in contact list

**Comment by 0xTryCatch** [comment]
Not something that will be implemented in this API

**Comment by Sputuks3** [comment]
Why not? Show some commitment in line with our anti-spam policy

**Comment by WHAnonymous** [comment]
@Sputuks3 it's ans easy implementation, but for now, we aren't implementing this in the API, if you want, you can modify the code to send that request, it's only a one line modification of an already coded function
