### ISSUE TITLE
Blocked if i have a lot of contacts than don't have me back

### ISSUE THREAD

**Issue by sabado** [WHAnonymous/Chat-API#922]
My chatapi was banned from whatsapp, and now was unbanned. They can´t say me the reason but recommended me to ask people to add me in their contacts list.  is it possible to do through a method or something?

i always synchronize the contact list in every batch of incoming messages!

Thanks!

**Comment by WHAnonymous** [comment]
@sabado 

- Do NOT send bulk messaging. This API is for personal usage only.
- It doesn't matter if you have synced the number or not, the important thing is that the contact have your number added i his contact list, if the contact doesn't have your number and you don't use it for personal usage, you will be blocked.
- The only way, is that your contacts add your number in their contact list

**Comment by sabado** [comment]
we do not send messages, we only receive a lot of messages from our tv viewers!  But, they do not add the number, i gess...

**Comment by pablokerestezachi** [comment]
And how your tv viewers could you send a message without adding the contact?

Saludos,
Pablo

**Comment by WHAnonymous** [comment]
@pablokerestezachi they can't, they must add the number first
