### ISSUE TITLE
 onProfilePictureChanged()

### ISSUE THREAD

**Issue by CristianOspina** [WHAnonymous/Chat-API#923]
Hello, I cant find enought information about this event.
What I need to do to get this event work? I have a subscription to a contact and when he update the picture just nothing happens. I need to sync he too?

Im just making a echo on the method to know if the picture has changed or not, but its not working, can someone show me a example of this method?

Thanks!

**Comment by WHAnonymous** [comment]
@CristianOspina you need first to activate the event as explained in the wiki: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#using-events

If you have already done that. You need to have that user synced and then subscribed, once then, you will start receiving notifications from that contact, and when the contact changed the profile image, you will receive a notification that will trigger the event.
