### ISSUE TITLE
Get media messages

### ISSUE THREAD

**Issue by arth1992** [WHAnonymous/Chat-API#925]
How to get media messages url  when receiving messages ?  

I used 
```php
 $media = $message->getAttribute("media")->getData();
```

but its not working 
Is the specific function for that ?

**Comment by luciano-work** [comment]
Use this Event: 
onGetImage( $mynumber, $from, $id, $type, $time, $name, $size, $url, $file, $mimeType, $fileHash, $width, $height, $preview, $caption );

and this Function: 
pollMessage();

https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#receiving-messages
