### ISSUE TITLE
Presence

### ISSUE THREAD

**Issue by robocop249** [WHAnonymous/Chat-API#927]
Hi there, in Wiki I found the following code:

```php
if user is offline
    $w->sendGetRequestLastSeen($contact);

$w->sendMessageComposing(contact); // Send composing

$w->sendMessagePaused(contact); // Send paused

$w->sendMessage(contact, message); // Send message
```

I then tried to find out how to lookup if a user is online. 
It seems to be the following function :

```php
public function sendPresenceSubscription($to)
    {
        $node = new ProtocolNode("presence", array("type" => "subscribe", "to" => $this->getJID($to)), null, "");
        $this->sendNode($node);
    }
```

But this function does not return a boolean, so how can I get the information without using the event system?

**Comment by WHAnonymous** [comment]
@robocop249 you can't, if you want to check when the user is online or not, you need to use event system, subscribing the user before

**Comment by robocop249** [comment]
So what do you mean with this entry in wiki then?

```php
if user is offline
    $w->sendGetRequestLastSeen($contact);

$w->sendMessageComposing(contact); // Send composing

$w->sendMessagePaused(contact); // Send paused

$w->sendMessage(contact, message); // Send message
```

**Comment by WHAnonymous** [comment]
@robocop249 checking if the user is online or not, you request last seen time, that's it, i think it's very clear. Use event system as i said before
