### ISSUE TITLE
Received message is garbled 

### ISSUE THREAD

**Issue by 3zzy** [WHAnonymous/Chat-API#929]
I'm using **exampleFunctional.php** to test the API.

I can send messages from here <--- this message was successfully **sent** from the terminal and received on the phone.

However, messages **to** the api are gardbled. I sent a `Hiiiii`, and got this: 

```xml
    <message from="91998767xxxx@s.whatsapp.net" type="text" id="1439823934-679" t="1439874143" notify="Ibrahim">
      <enc v="1" type="msg">3
    !?2h????Ґ??????B=??S???BJ?$
                                "??6??
    ?F=ޕ?%???=%?y>?r</enc>
    </message>
```

**Comment by WHAnonymous** [comment]
@3zzy that's because you have preciously registered that number in an android device, to solve this use [resetAccount.php](https://github.com/WHAnonymous/Chat-API/blob/master/examples/resetAccount.php)

This has been answered in other issues, be sure to check them before opening a new issue.

**Comment by 3zzy** [comment]
Just ran resetTool, entered the password I already had from using registerTool, and then ran registerTool again, but still the same. Received messages are encrypted.

**Comment by WHAnonymous** [comment]
@3zzy send me an email and i'll help you, you are doing something wrong

**Comment by 3zzy** [comment]
I did `composer require whatsapp/chat-api` and it installed version `2.5.2`. 

However, it doesn't come with resetAccount.php as I see on github, what am I doing wrong?

**Comment by Udirley** [comment]
I'm looking nosy, but I have said several times # 899 and # 906 that resetAcount.php is not solving the problem of encrypted messages.
I tried several times but to no avail. For now I'm using new numbers that have never been recorded before so works, but if I try a number that has been registered in Android does not.
If you can solve let me know because I am also in need of help.

**Comment by WHAnonymous** [comment]
@Udirley if you follow that steps correctly, it will work, remember that maybe your contacts still have the keys of your previous registration, so you have to ask them to remove your number and add it again.

**Comment by 3zzy** [comment]
Ask them to remove? Ohk, i didnt try that yet.
