### ISSUE TITLE
Advice to avoid block

### ISSUE THREAD

**Issue by yaserzizo** [WHAnonymous/Chat-API#930]
I have group (11 contact) and i want to send them just one Message per hour (max 20 message per day) and here is my code 

```
header('Content-Type: text/html; charset=utf-8');
require_once '../src/whatsprot.class.php';

$username = "###########";// $_GET["phone"];
$password = "#######################";//$_GET["pass"];

//$startTime = time();


$gId = "###########-##########";
$message= $_POST["msg"];
    $wa = new WhatsProt($username, "WhatsApp", false);

    $wa->connect();
    $wa->loginWithPassword($password);
    $wa->sendActiveStatus();
    $wa->sendMessage($gId, $message);
    $wa->pollMessage();
    $wa->sendActiveStatus();
```

do i need to add any thing to it to avoid block

**Comment by 0xTryCatch** [comment]
It looks ok but there is no guarantee WA will not block you

**Comment by yaserzizo** [comment]
thank you  a lot 
but if I edit my script to be as below :


$wa = new WhatsProt($username, "WhatsApp", false);
    $wa->setMessageStore(new SqliteMessageStore($username));
    $wa->connect();
    $wa->loginWithPassword($password);
    $wa->sendActiveStatus();
    $wa->pollMessage();
     $wa->sendMessageComposing($gId);
    sleep(1);
    $wa->sendMessagePaused($gId);
     $wa->sendMessage($gId, $message);
    $wa->pollMessage();
    $wa->sendActiveStatus();

will it be more save or the first one is better ??
