### ISSUE TITLE
examples/resetAccount.php

### ISSUE THREAD

**Issue by Zkriya** [WHAnonymous/Chat-API#932]
If you try to reset your account your phone number will be blocked.

**Comment by gojigeje** [comment]
anybody can confirm this issue?

**Comment by 0xTryCatch** [comment]
Please explain. What did you do?

**Comment by breakerh** [comment]
Your mobile phone will be unverified. That's normal. (And i saw that i got kicked out of all groups?)
But blocked? No, just tried it. still working..

**Comment by WHAnonymous** [comment]
@breakerh that's because it removes the account you you can register from zero.

@Zkriya is still working, and running perfectly. If you have any doubt, let me know
