### ISSUE TITLE
Provided number does not match any known patterns for

### ISSUE THREAD

**Issue by Drorby** [WHAnonymous/Chat-API#933]
Hi
I try to using WART to get a code but when I click on Requestcode and i get error 
"Provided number does not match any known patterns for"

Why ? What to do ?

**Comment by WHAnonymous** [comment]
Download latest WART here: https://github.com/mgp25/wart

**Comment by Drorby** [comment]
Sorry about the stupid question but if i click on the WART-1.8.2.1.exe I move to page that don't have DOWNLOAD place....
on what I need to click for downloading the file ?

**Comment by Drorby** [comment]
Sorry about the stupid question but if i click on the WART-1.8.2.1.exe I
move to page that don't have DOWNLOAD place....
on what I need to click for downloading the file ?

2015-08-20 12:27 GMT+03:00 WHAnonymous <notifications@github.com>:

> Closed #933 <https://github.com/WHAnonymous/Chat-API/issues/933>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WHAnonymous/Chat-API/issues/933#event-387485725>.
>



-- 
*רק טוב,*
דרור בן יהודה
052-4338616
