### ISSUE TITLE
Emoji just works manually

### ISSUE THREAD

**Issue by James2376** [WHAnonymous/Chat-API#934]
Hi I just tried to add Emojis to my Broadcast-Messages. 

I send the following text as `$caption=$_POST["mes"];`  via AJAX to my PHP File: `Hello World \xF0\x9F\x91\xB3`  the Message does not change the `\xF0\x9F\x91\xB3` to the Emoji. 

If I declare `$caption = "Hello World \xF0\x9F\x91\xB3"` inside the PHP File directly so without AJAX it works and the Emoji is there. I go crazy about this for weeks please help me.

**Comment by WHAnonymous** [comment]
@James2376 use this helper class https://github.com/WHAnonymous/Chat-API/blob/master/src/smileys.class.php

**Comment by James2376** [comment]
@WHAnonymous Hi thank you for your fast help I already found this helper class but I can't use it in my code. So I need to figure out why the code is working fine if I'm typing the Emoji manually \xF0\x9F\x91\xB3 and why it doesn't work if I'm using a textarea and Ajax to Post to $Caption.

**Comment by WHAnonymous** [comment]
@James2376 you are not using UTF-8 in your POST request.

```html
<form method="post" accept-charset="UTF-8"  ...>
```

**Comment by James2376** [comment]
@WHAnonymous

 Hi I just tried your code and it doesn't work out =(   This are the relevant code snippets:     

         $('#11').on("click", "#versenden2", function(){  
        var message = $.trim($('#faketextbox2').html().replace(/<br\s?\/?>/g, "\n"));    
        $('#message2').val($('#faketextbox2').html(message).text());
        
 
        var txt = document.getElementById("message2").value;
        var tit = document.getElementById("KampagnenTitel2").value;
        var zeit = document.getElementById("KampagnenZeit2").value; 
        alert(txt);
            
     $.ajax({    //create an ajax request to load_page.php
        type: "POST",
        url: "KampagneMessage.php",
        data: { mes: txt, tit: tit, zeit: zeit},
        dataType: "text",
        contentType: "application/x-www-form-urlencoded; charset=UTF-8",
        success: function(responses){ 
            alert(responses)         
        }   
         })
    });


The  var txt value is the following string: "Hello World  \xF0\x9F\x98\xB1"   and my PHP:

<?php
header("Content-Type: text/html; charset=utf-8");


$input =$_POST["mes"];
$titel = $_POST["tit"];
$zeit = $_POST["zeit"];
 
...
?>
 $input is send by the WhatsApp Broadcast but only shows the raw code "Hello World  \xF0\x9F\x98\xB1"

**Comment by qligier** [comment]
When you declare the string double quoted, \xF0 is [interpreted by PHP](http://php.net/manual/en/language.types.string.php#language.types.string.syntax.double) as an UTF-8 character (given by its hecadecimal representation). When you write it in a form, your browser interprets it as four characters (assuming that you just typed it as regular characters) and PHP doesn't do anything with the string (as if it was declared with single quotes):
```php
$caption = "Hello World \xF0"; // \xF0 is evaluated as one character
$input = $_POST["mes"]; // \xF0 is evaluated as four characters
// equivalent to:
$input = 'Hello World \xF0'; // \xF0 also evaluated as four characters
```

You should [type the "real" UTF-8 character](https://www.google.com/search?q=How+to+type+special+characters) in your form.

**Comment by James2376** [comment]
@qligier Thank you for your response. How can I get my Input Value evaluated as one character ?

**Comment by qligier** [comment]
You should [type the "real" UTF-8 character](https://www.google.com/search?q=How+to+type+special+characters) in your form.

Another possibility:
```php
$message = preg_replace_callback('/\\x([0-9A-F]{2})/iU', function ($matches) { return hex2bin($matches[1]); }, 'Hello World \xF0\x9F\x98\xB1');
```

**Comment by James2376** [comment]
@qligier If I use the other possibility where do I put my $_Post["mes"] or am I wrong by implementing this function into my PHP File after getting the Data from Ajax Post in my HTML.

**Comment by qligier** [comment]
With your variables, it becomes:
```php
$input = preg_replace_callback(
    '/\\x([0-9a-fA-F]{2})/', 
    function ($matches) { 
        return hex2bin($matches[1]); 
    }, 
    $_POST["mes"]
);
```

**Comment by James2376** [comment]
@qligier Hi just tried it but it sadly doesn't work. The output on my phone is: Hello World \xF0\x9F\x98\xB1 but not the emoji =(

**Comment by qligier** [comment]
It needs maybe more backslashes:
```php
$input = preg_replace_callback(
    '/\\\\x([0-9a-fA-F]{2})/', 
    function ($matches) { 
        return hex2bin($matches[1]); 
    }, 
    $_POST["mes"]
);
```

**Comment by James2376** [comment]
=/ no I'm sorry I tried it with several more backslashes. 
(Es wird  leider immer als Text versandt und nicht als Emoji, was macht denn die Funktion ? )

**Comment by qligier** [comment]
[It does work](https://3v4l.org/P3VaM) since PHP 5.4.0. You must have another problem in your code.

The function uses a regex to find all occurences of **\xYY** and replace **YY** by its binary representation (**YY** being the hexadecimal representation).
