### ISSUE TITLE
Disconnected when using phone whatsapp and chat-api same time

### ISSUE THREAD

**Issue by johngamarra** [WHAnonymous/Chat-API#937]
Hi,

I'm having some trouble with this, it's possible to connect using chat-api and using the phone normally at same time? because I'm trying to do it and I get 'Connection Closed!" messages when I open WhatsApp in my phone

**Comment by ludufre** [comment]
You can not enter both at the same time.

**Comment by johngamarra** [comment]
At least it's possible to connect and get the lastest messages? even if the phone already have them?

**Comment by 0xTryCatch** [comment]
No. Delivered messages are removed from the server.
