### ISSUE TITLE
LastSeen returning random "seconds" values.

### ISSUE THREAD

**Issue by viniciusjarina** [WHAnonymous/Chat-API#938]
Hello 

Since today WA servers start to return random values for the request "lastseen" although the last seen feature seems to be working on old versions of WA client.

```xml
tx  <iq to="55119XXXXXXXX@s.whatsapp.net" type="get" id="2" xmlns="jabber:iq:last">
tx    <query></query>
tx  </iq>

rx  <iq from="55119XXXXXXXX@s.whatsapp.net" type="result" id="2">
rx    <query seconds="1902320"></query>
rx  </iq>
```
Any idea what could be wrong?

**Comment by CODeRUS** [comment]
show 5 lastseen requests in a row

**Comment by viniciusjarina** [comment]
Hi @CODeRUS 

here is a dump of 5 lastseen requests in a row.

https://gist.github.com/viniciusjarina/c527228299c12fe2e867

**Comment by WHAnonymous** [comment]
@viniciusjarina It's happening to all of us, we are researching it, as soon as we know the change, we will update the code and let you know in this issue

**Comment by viniciusjarina** [comment]
Great @WHAnonymous 

If you need anything else to help, please let me know.

Thank you.

**Comment by CODeRUS** [comment]
@viniciusjarina yes, please sniff latest android client traffic and decrypt it to see whatsapp protocol nodes :)

**Comment by viniciusjarina** [comment]
@CODeRUS I think we don't need to sniff the latest version, since older versions of WA are still showing the right last seen value :wink:

**Comment by gi097** [comment]
The problem should be in the "id", because no matter if you add the current time or not: those seconds change with a lot of numbers. Maybe WA uses a new id layout?

**Comment by gi097** [comment]
@CODeRUS I some SSL packet data for you, if you can decrypt it, I will give you.

**Comment by WHAnonymous** [comment]
All information send it to my email. We are close to get the new request btw.

**Comment by gi097** [comment]
@WHAnonymous I did sent two HEX packets from my Android client. I have no idea if you can decrypt it. And that's good news to hear.

**Comment by matteocontrini** [comment]
[Here](https://github.com/hidespb/node-whatsapi/issues/97#issuecomment-134256876) is an update, looking at the source code. I'm not sure about that because the code is complicated, but that's how it works in the official app, there's no request for last seen anymore.

**Comment by WHAnonymous** [comment]
@matteocontrini Yes, you are right. Presence will return you the `lastseen` when the user is online, that way you need to always sync the contact first in order to get the `last seen` of the contact.

Flow:

```
Sync
Presence Subscription

If offline
   Show last seen
```

When this is tested and implemented i'll close the issue

Thanks for all the collaboration to everyone

**Comment by viniciusjarina** [comment]
Hi @matteocontrini Will the server send the last seen on presence subscription even if the user was never online?

For instance if you just add someone to your list, you are able to see his/her last seen even if his/her was never online.

**Comment by matteocontrini** [comment]
@viniciusjarina what do you mean? An user cannot be in your list of contacts if he has never been online, because that would mean he's not inside WhatsApp.

Btw I've just verified that a request for presence subscription immediately sends a response, with the `type` (online/offline) at the moment of the request and the last seen UNIX UTC timestamp.

**Comment by WHAnonymous** [comment]
Solved. Presence subscription return the `last seen`

```xml
tx <presence to="***@s.whatsapp.net" type="subscribe"/>

rx <presence from="***@s.whatsapp.net" type="unavailable" last="1440421593"/>
```

Notice the `last` attribute, i close this issue as it's already solved, and i'll update the code tonight and remove the deprecated function to get last seen time. I'll post commit here once updated

**Comment by WHAnonymous** [comment]
Use `sendPresenceSubscription($to)` function.

If the user is offline you'll get the `last seen`.

```xml
rx <presence from="***@s.whatsapp.net" type="unavailable" last="1440421593"/>
```

Use the event `onPresenceUnavailable` to handle this

Hope everything is clear now

**Comment by viniciusjarina** [comment]
Great @WHAnonymous, snd thank you @matteocontrini

**Comment by Stepkaa** [comment]
Can you please provide the code that should be in MyEvents.php? Maybe it will also be useful for people in wiki.

**Comment by WHAnonymous** [comment]
@Stepkaa everything is already implemented, but you can follow this example: https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#using-events

**Comment by gi097** [comment]
@Steptkaa use the onPresenceUnavaible event. Where the value 'last' is the last seen time from a user in UNIX UTC time.
