### ISSUE TITLE
forward message

### ISSUE THREAD

**Issue by jeilun** [WHAnonymous/Chat-API#939]
How can I forward a message by using this API ?

**Comment by WHAnonymous** [comment]
@jeilun save the message using the event system and sending it to another contact

**Comment by jeilun** [comment]
forwarding messages in whatsapp is fast and doesn't use my bandwidth how can do this with you API ?
thanks

**Comment by WHAnonymous** [comment]
@jeilun save the message using the event system and sending it to another contact

Everything is explained in the wiki
