### ISSUE TITLE
onMessage

### ISSUE THREAD

**Issue by hurbanores** [WHAnonymous/Chat-API#940]
I added a new number, but i made the validation process and all work's almost fine because i can't recive any messages, i try with method onMessage and don't see anything.

I have another number and it work's fine, i registered this number before the update almost a month ago

Wating for your answer

Regards.

**Comment by WHAnonymous** [comment]
@hurbanores post your debug log

**Comment by utking** [comment]
I had the same issue a week ago. It started to work again after that contact deleted and re-created his account from his phone.
