### ISSUE TITLE
i want to use proxy in this api

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#942]
@WHAnonymous  how to add proxy ,, i hope to answer me not reject my request .. really i want to see the url of send message and any thing .. please help me

**Comment by WHAnonymous** [comment]
@beljk You can add a proxy, but that wont help you, code the right flow and that will work perfectly, you don't need any proxy. This uses sockets, there isnt any http request (no url), the only http requests are  for the registration process, the rest is done using sockets

**Comment by beljk** [comment]
@WHAnonymous  Aha thanks for advice
