### ISSUE TITLE
can not receive messages

### ISSUE THREAD

**Issue by nnuridin** [WHAnonymous/Chat-API#943]
Hi!
I can't receave message, where I made a mistake

$username = "7707******6";
$password = "z********************=";

$w = new WhatsProt($username, "Nicname", true);
$w->connect();
$w->loginWithPassword($password);

while (true) {
	$w->PollMessage();
	$msgs = $w->GetMessages();

	foreach ($msgs as $m) {
		print_r($m);
	}
}

Fatal error:  Maximum execution time of 30 seconds exceeded in F:\www\Chat-API-master\src\whatsprot.class.php on line 573

Please help

**Comment by 0xTryCatch** [comment]
Increase your max execution time: http://php.net/manual/en/function.set-time-limit.php

**Comment by nnuridin** [comment]
I solved the problem
while ($w->PollMessage()) {

$msgs = $w->GetMessages();

foreach ($msgs as $m) {
    print_r($m);
}

}

But can not read text : 
3
!ǈx�WD
\"�Zl��J4���K�%�kN���E"L��ܑL�2jn�3���Ru���

**Comment by 0xTryCatch** [comment]
#891
#893
#899
