### ISSUE TITLE
LoginFailureException with password received from Chat-API / WART

### ISSUE THREAD

**Issue by auhadams** [WHAnonymous/Chat-API#949]
First I tried to register with chat-api. I have received a password and tried to log in. And then LoginFailureException was thrown.
Then I tried to register via WART. WART didn't send me sms, but i received voice call with a code. Then I successfully received a password. I saved my identity to id.7967xxxxxxx.dat .
Next I did this:
```php
$w = new WhatsProt('7967xxxxxxx', $nickname, true);
$res = $w->connect();
$w->loginWithPassword($password);
```

Result:
```php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="7967xxxxxxx"></auth>

[LoginFailureException] 
 (0)
{...}\whatsprot.class.php:2270
#0: WhatsProt->doLogin()
	{...}\whatsprot.class.php:551
#1: WhatsProt->loginWithPassword(string)
	{...}\dev\test.php:28
```

What do i do wrong?

**Comment by WHAnonymous** [comment]
@auhadams your number could be blocked, use `blockChecker.php` script to check if its blocked

If its blocked you need another number, if its not, let me know and ill help you

**Comment by auhadams** [comment]
1. 
```php
Array ( [cc] => 7 [in] => 67xxxxxxx [id] => o����~]ݔ{>g#�_5� [lg] => ru [lc] => RU ) 
stdClass Object ( [status] => fail [reason] => length_short )
[Exception] 
There was a problem trying to request the code. (0)
{...}\whatsprot.class.php:182
#0: WhatsProt->checkCredentials()
```
2. I see that digit 9 disappeared somewhere. I tried to change cc for Russia in countries.csv from 79 to 7. Result:
```php
Your number 7967xxxxxxxx with the following password tj9{..}M= is not blocked
```

**Comment by auhadams** [comment]
Today  I tried to send message with yowsup (https://github.com/tgalal/yowsup/wiki). I used the password which received with last checkCredentials() . And it work there. But doesn't log in with chat-api.
Then I tried german phone number. Got identity and password with WART. loginWithPassword returns the same result (LoginFailureException). But yowsup sended successfully.
So, my number is not blocked.

------------------

I noticed that I have some problems in buildIdentity(). 
```php
if (is_readable($identity_file)) {
            $data = urldecode(file_get_contents($identity_file));
            $length = strlen($data);
            if ($length == 20 || $length == 16) {
                return $data;
            }
}
```
The length of identity (getted with wart) is not 20 or 16. And it generates new identity, which length is not equal 20 or 16 too. I commented out length check line, because every time it generates new identity for me. Maybe there is problem?

**Comment by WHAnonymous** [comment]
@auhadams send me your number and working password and ill test it, and tell you whats happening

**Comment by auhadams** [comment]
@WHAnonymous 
I send the data to your email

**Comment by mgp25** [comment]
@auhadams i sent you an sms code, send me back that code via mail

**Comment by WHAnonymous** [comment]
@auhadams i sent you an sms code, send me back that code via mail

**Comment by WHAnonymous** [comment]
@auhadams register it again using `registerTool.php` and make sure you are using the latest version of this API, use the login value and that will work, if you still face this error, post your debug log while successful register

**Comment by auhadams** [comment]
@WHAnonymous 

I use the latest version of the API.
First try: https://yadi.sk/i/mNq_yRy_ih7rF
Then try with german number: https://yadi.sk/i/pyCnemD4ih7ty

Then I set right mnc in code: 
https://yadi.sk/i/i2RCLTN0ih83w
https://yadi.sk/i/Zx_ub7N-ih86Q

Voice method: https://yadi.sk/i/Zx_ub7N-ih86Q

**Comment by auhadams** [comment]
@WHAnonymous 
I just receive new password with WART (for german phone number). Because registerTool.php is not work for me.

Log in results:
```php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="4915758921110"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

[ConnectionException] 
Tree length did not match received length (buff = 18 & treeLength = 25) (0)
{...}/ChatAPI/src/whatsprot.class.php:3704
#0: WhatsProt->readStanza()
	{...}/ChatAPI/src/whatsprot.class.php:577
#1: WhatsProt->pollMessage()
	{...}/ChatAPI/src/whatsprot.class.php:2261
#2: WhatsProt->doLogin()
	{...}/ChatAPI/src/whatsprot.class.php:553
#3: WhatsProt->loginWithPassword(string)
	{...}/test.php:17
```

I refreshed the page many times, and got this:

```php
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="49XXXXXXXXXX"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>,����3+E��6�avm��</challenge>

tx  <response>���m��)�@p�.úĽl}{���1�%�Rv��5���</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>

[LoginFailureException] 
 (0)
{...}/ChatAPI/src/whatsprot.class.php:2272
#0: WhatsProt->doLogin()
	{...}/ChatAPI/src/whatsprot.class.php:553
#1: WhatsProt->loginWithPassword(string)
	{...}/test.php:17
```

More rows ) But can't authorize.

As I said earlier, api generate my identity every hit, because its length is not 20 or 16. May be this is my problem?

**Comment by WHAnonymous** [comment]
@auhadams  contact with @mgp25 via mail, he will help you

**Comment by eyemiru** [comment]
I have the exact same issue as mgp55 … any solution yet?
