### ISSUE TITLE
Is there any way to get 640x640 Profile pictures, like in WhatsApi?

### ISSUE THREAD

**Issue by Stepkaa** [WHAnonymous/Chat-API#951]
I know that there is only way to get 250x250 photos using `sendGetProfilePicture`. But can i get large photo instead of preview one? Thanks.

**Comment by WHAnonymous** [comment]
https://github.com/WHAnonymous/Chat-API/blob/master/src/whatsprot.class.php#L987

Check that line and set `$large` to `true`
