### ISSUE TITLE
exampleFunctional.php and pollMessage()

### ISSUE THREAD

**Issue by shvburade** [WHAnonymous/Chat-API#952]
i am new to using apis 
when i am trying to run `exampleFunctional.php` it shows and error

```
Fatal error: Maximum execution time of 10 seconds exceeded in C:\Users\Shiva\Documents\EasyPHP-DevServer-14.1VC11\data\localweb\projects\Chat-API-master\src\rc4.php on line 29
```

the other error is `pollMessage()` is not working it is showing error as
`Call to undefined method WhatsProt::PollMessages()`

i want to see the recieved the messages, i am able to send messages but now i want to recieve message

**Comment by WHAnonymous** [comment]
@shvburade i recommend you to read the wiki where everything is explained and also use the [PHP Manual](https://php.net/docs.php)

You can use this to set to infinite the maximum executing time by using: `set_time_limit(0)`

Also you call `pollMessages()` but it is really `pollMessage()`. You can check the [wiki](https://github.com/WHAnonymous/Chat-API/wiki) for more examples and explanations

Regards

**Comment by shvburade** [comment]
thank you 
what if i want to see the conversation with a particular contact

**Comment by WHAnonymous** [comment]
https://github.com/WHAnonymous/Chat-API/blob/master/examples/Simple%20CLI%20client.php
