### ISSUE TITLE
Cannot sync new contacts more than once per hour

### ISSUE THREAD

**Issue by plopinou** [WHAnonymous/Chat-API#953]
Hello,
I've developped a bot with your wonderfull API which sends a video to people sending it a key message.
When I receive this message, I know that the person has added me in its contacts, and I then send a sendSync :
```php
$w->sendSync(array($phoneNumber), null, 3);
```
followed by a :
```php
$w->sendPresenceSubscription($phoneNumber);
```
... in the `onSyncResult` event function, if the number exists.
Everything's fine the first time, but if another person is sending a message less than 1 hour after, whatsapp server is always responding :
```xml
rx  <iq from="xxxxxxxxxxx@s.whatsapp.net" type="error" id="89">
rx    <error code="501" text="feature-not-implemented" backoff="3600"></error>
rx  </iq>
```

Question : Is this a normal behavior ? Or is my phone number already "flagged" in any way by the whatsapp servers ? I can change my script to sync all the new contacts only once per hour if this is the case.

**Comment by WHAnonymous** [comment]
@plopinou you only need to sync only once the contact, then you don't need to sync that contact again. If you are starting a conversation and you don't have synced that number previously, then before sending any message you must sync the contact, because is not right to send a message without syncing (supposing you are starting the chat).

Also don't abuse to much the sync function, you can also save all new contacts in an array and once an hour sync them (if you are getting `backoff`).

The flow the app does is explained in the wiki.

**Comment by plopinou** [comment]
I must have badly explained myself, sorry :).

I currently wait for a person to send me a message for me to sync them before everything else.
My complete flow is :
- receiving a key message
- checking that the person is not in the DB
- if not, adding the person in the DB with the flag "sync = none", then sending a delta sync with the phone number
- waiting for the onSyncResult event, and when received, checking that the person exists. If yes, changing the sync flag in the DB to "ok" and never try to sync again with this phone number
- then later, send a videos to all contacts in the DB with sync = "ok", and only them.

The problem is that if I sync 2 new person in less than an hour, I will never have the "onSyncResult" called the second time. Instead I have an onGetError with the debug I pasted in my OP.
Currently, I don't send any message nor video to a person without the sync flag to "ok" to avoid any possible ban.

Thus my question : is it a normal behavior ?

**Comment by WHAnonymous** [comment]
@plopinou yes, it's a normal behavior, in that case, you should save all contacts you want to sync in an array (during the backoff time), and once this time has passed, sync all them

And you ready to go :smile:

**Comment by plopinou** [comment]
Thanks a lot for the confirmation, I'm modifying the script as I indented to do :)
