### ISSUE TITLE
sync

### ISSUE THREAD

**Issue by shvburade** [WHAnonymous/Chat-API#954]
what is `$_GET["u"];` in contactSync
does it mean username or nickname?

**Comment by WHAnonymous** [comment]
Explanation: https://secure.php.net/manual/en/reserved.variables.get.php

GET variable to get data from url, it's explained in the link above

**Comment by shvburade** [comment]
i know what GET means but what is the value of ["u"] in url 

$username = $_GET["phone"];
$password = $_GET["pass"];
$u        = $_GET["u"];

i know what is username and password but what is $u

**Comment by WHAnonymous** [comment]
https://github.com/WHAnonymous/Chat-API/blob/master/examples/contactsync.php#L15

**Comment by shvburade** [comment]
can you tell me which api you have used for getting contacts from google 
in whatsapp.php to get the contacts from google the called this function 
when i use this i get a error 'Could not get Authentication code from google' 
i even visited the $clientlogin_url but couldnt find anything there 

i searched for the google contact api but the api provided by google seem to different then this?
is there any alternative to $clientlogin_url?

 private function getAuthString($user)
    {
        // Construct an HTTP POST request
        $clientlogin_url = "https://www.google.com/accounts/ClientLogin";
        $clientlogin_post = array(
            "accountType" => "HOSTED_OR_GOOGLE",
            "Email" => $this->config[$user]['email'],
            "Passwd" => $this->config[$user]['emailPassword'],
            "service" => "cp",
            "source" => "whatsapp"
        );

        // Set some options (some for SHTTP)
        curl_setopt($this->curl, CURLOPT_URL, $clientlogin_url);
        curl_setopt($this->curl, CURLOPT_POST, true);
        curl_setopt($this->curl, CURLOPT_POSTFIELDS, $clientlogin_post);
        curl_setopt($this->curl, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
        curl_setopt($this->curl, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($this->curl, CURLOPT_RETURNTRANSFER, 1);

        // Execute
        $authresponse = curl_exec($this->curl);

        // Get the Auth string and save it
        $matches = null;
        $res = preg_match("/Auth=([a-z0-9_-]+)/i", $authresponse, $matches);
        if ($res == 1) {
            $this->auth = $matches[1];

            return $matches[1];
        }
        throw new Exception('Could not get Authentication code from google');
    }

**Comment by shvburade** [comment]
how should i get the authentication code from google??
