### ISSUE TITLE
My number not get block but not Authorize 

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#955]
@mgp25 @WHAnonymous  when i register my number with same salt using WART it change password and login fine using CHAT API .NET but when use this api its give me this debug message

```xml
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by WHAnonymous** [comment]
@beljk register it using `registerTool.php` and then it will work perfectly with Chat API.
