### ISSUE TITLE
Set Thumbnail  for video or img

### ISSUE THREAD

**Issue by moosavialeki** [WHAnonymous/Chat-API#962]
hi

i want set custom Thumbnail  for video and img like this link:

http://www.droidtipstricks.com/whatsapp-picture-trick-thumbnail-chnage/

**Comment by WHAnonymous** [comment]
@moosavialeki this API by default set the correct thumbnail to the image, you can set other thumbnail by changing the functions. Check `func.php` and `whatsprot.class.php`

**Comment by moosavialeki** [comment]
@WHAnonymous this API set incorrect thumbnail  for video !
video thumbnail is a problem for this api
(sorry i can't write english very good)

**Comment by WHAnonymous** [comment]
@moosavialeki its explained in the wiki you need `ffmpeg` installed

More info in the wiki: https://github.com/WHAnonymous/Chat-API/wiki

All the documentation, setup guide, everything is in there
