### ISSUE TITLE
Image Message not send

### ISSUE THREAD

**Issue by ppiyushjv** [WHAnonymous/Chat-API#963]
Hi,
I am facing a problem when sending an image. 
I try to convert image to byte

byte[] img = File.ReadAllBytes("d:\1.jpg");
byte[] imageBytes = null; using (MemoryStream ms = new MemoryStream()) { using (Bitmap b = new Bitmap("d:\1.jpg")) { b.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg); } imageBytes = ms.ToArray(); }
so please tell me how to send image by message

**Comment by luciano-work** [comment]
You just need to indicate the image path

$caption = "Look at this awesome image!";
$target = "34123456789";
$pathToVideo = ""; // This could be url or path to image.  ex: http://mysite/image/test.jpg
$w->sendMessageImage($to, $filepath, false, $fsize, $fhash, $caption);
$w->pollMessage();

see the wiki: https://github.com/WHAnonymous/Chat-API/wiki

**Comment by WHAnonymous** [comment]
This is not Chat API Net, go to the proper repository
