### ISSUE TITLE
sendGroupsParticipantsRemove not working

### ISSUE THREAD

**Issue by kwiiby** [WHAnonymous/Chat-API#964]
Hey, I'm trying to use the function `sendGroupsParticipantsRemove`, but, it does not remove the participants from the group, (this was working until three days ago).

In my logs it sends `tx` and receives `rx` normal, I don't know why this is coming on.

**Comment by WHAnonymous** [comment]
@kwiiby if you dont post the debug log this issue is invalid

**Comment by kwiiby** [comment]
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="xxxxxxxx"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>xxxxxxxxxxxxxx</challenge>

tx  <response>xxxxxxxxxxxxx</response>

rx  <success t="1441034195" props="4" kind="free" status="active" creation="1440866193" expiration="1472402193">xxxxxxxxxx</success>

tx  <presence name=""></presence>

tx  <iq id="1" type="get" xmlns="w" to="s.whatsapp.net">
tx    <props></props>
tx  </iq>

tx  <iq id="2" type="set" xmlns="urn:xmpp:whatsapp:push" to="s.whatsapp.net">
tx    <config platform="S40" version="2.12.96"></config>
tx  </iq>

rx  <ib from="s.whatsapp.net">
rx    <offline count="0"></offline>
rx  </ib>

tx  <iq id="3" xmlns="w:p" type="get" to="s.whatsapp.net">
tx    <ping></ping>
tx  </iq>

tx  <presence type="subscribe" to="xxxxxxxx@s.whatsapp.net"></presence>

tx  <iq id="4" type="get" xmlns="w:g2" to="g.us">
tx    <participating></participating>
tx  </iq>

rx  <presence from="xxxxxxxx@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="1">
rx    <props version="4">
rx      <prop name="timeout" value="300"></prop>
rx      <prop name="wbarchive" value="1"></prop>
rx      <prop name="e2e_images" value="0"></prop>
rx      <prop name="e2e_groups" value="0"></prop>
rx      <prop name="mspes" value="1"></prop>
rx      <prop name="plaintext_reenable_threshold" value="5"></prop>
rx      <prop name="plaintext_disabled" value="1"></prop>
rx      <prop name="source" value="3"></prop>
rx      <prop name="location" value="0"></prop>
rx      <prop name="readreceipts" value="1415214000"></prop>
rx      <prop name="qr" value="0"></prop>
rx      <prop name="groups_v2" value="1"></prop>
rx      <prop name="lists" value="1"></prop>
rx      <prop name="library" value="0"></prop>
rx      <prop name="audio" value="1"></prop>
rx      <prop name="checkmarks" value="0"></prop>
rx      <prop name="newmedia" value="0"></prop>
rx      <prop name="video_max_edge" value="960"></prop>
rx      <prop name="image_max_kbytes" value="5120"></prop>
rx      <prop name="image_quality" value="80"></prop>
rx      <prop name="image_max_edge" value="1600"></prop>
rx      <prop name="media" value="16"></prop>
rx      <prop name="broadcast" value="50"></prop>
rx      <prop name="max_subject" value="25"></prop>
rx      <prop name="max_participants" value="101"></prop>
rx      <prop name="max_groups" value="9999"></prop>
rx    </props>
rx  </iq>

rx  <iq from="s.whatsapp.net" type="result" id="2"></iq>

rx  <presence from="xxxxxxxx@s.whatsapp.net"></presence>

rx  <presence from="xxxxxxx@s.whatsapp.net"></presence>

rx  <iq from="s.whatsapp.net" type="result" id="3" t="1441034196"></iq>

rx  <iq from="g.us" type="result" id="4">
rx    <groups></groups>
rx  </iq>

tx  <iq id="Zs76gEty2fjm1" type="set" xmlns="w:g2" to="number-1441034191@g.us">
tx    <remove>
tx      <participant jid="number1@s.whatsapp.net"></participant>
tx      <participant jid="number2@s.whatsapp.net"></participant>
tx    </remove>
tx  </iq>

rx  <iq from="number-1441034191@g.us" type="result" id="Zs76gEty2fjm1">
rx    <remove>
rx      <participant jid="number1@s.whatsapp.net"></participant>
rx      <participant jid="number2@s.whatsapp.net"></participant>
rx    </remove>
rx  </iq>


Then when I login, I get not-authorized.

**Comment by kwiiby** [comment]
Now tried to remove just one person and it worked, it seems that the problem is when I try to remove them all.

**Comment by WHAnonymous** [comment]
@kwiiby can you post the script code?

**Comment by kwiiby** [comment]
```
<?php
require_once('src/whatsprot.class.php');
require 'src/events/MyEvents.php';

$debug = true;

// Conecta ao WhatsApp
$w = new WhatsProt('xx', '', true);
$w->connect();
$w->loginWithPassword('xxpassword');
$w->sendGetServerProperties();
$w->sendClientConfig();
$w->pollMessage();
$w->sendPing();
$w->sendPresenceSubscription($usuario);
$w->sendGetGroups();
$groupId = 'xxxxx-xxxx@g.us';
$w->sendGroupsParticipantsRemove($groupId, array('number1xxxx', 'number2xxxx'));
$w->sendPing();
$w->pollMessage();
```

**Comment by WHAnonymous** [comment]
@kwiiby add this:

```php
while(1)
{
    $w->pollMessage();
}
```
try it and check if it works, if not post debug log again

**Comment by kwiiby** [comment]
Doesn't works, please, check it out the edited code and test.

Create a group with 2 or more people, then try to remove all of them at the same time. It works for you?

**Comment by WHAnonymous** [comment]
@kwiiby you need to poll messages enough between that calls. And also, its very weird to create a group and remove the participants

**Comment by kwiiby** [comment]
"pollMesage" do not solve the problem, the number becomes blocked (not-authorized) the same way, I believe that WhatsApp has blocked the functionality to remove more than one person in the same "request". the goal here is not to create a group and remove people, but remove two people from a group at the same time when I want, you know? You can check if whatsapp packets remain the same? thanks.

**Comment by phpjoker** [comment]
Unfortunately, a few days that whatsapp has changed his ways in making groups. And strongly dealt with by block.

**Comment by WHAnonymous** [comment]
@kwiiby @phpjoker i'll check and update in a while
