### ISSUE TITLE
How to sniff packets

### ISSUE THREAD

**Issue by kwiiby** [WHAnonymous/Chat-API#965]
Hello, can anyone teach me how to track WhatsApp packets for me to try to help the repository giving maintenance in case of upgrade? I know that the API has a debug log, however, I would like to see the packets that are sent from my mobile with the official client to see if it matches the API.

Thank you. :)

**Comment by CODeRUS** [comment]
https://github.com/davidgfnet/wireshark-whatsapp

**Comment by kwiiby** [comment]
Cool, thanks.
