### ISSUE TITLE
boradcast images groups

### ISSUE THREAD

**Issue by yairnet** [WHAnonymous/Chat-API#967]
hi,
i try send imgs to many groups and i have big delay 5 sec per group,
It seems to me exaggerated!

How can I speed up sending one picture to 30 groups?
i try use broadcast but i think only to members no groups,
if i send img all system stop to work and unlock after img send... 
i find how i can send one img to 30 gorups fast...

thx :)

**Comment by WHAnonymous** [comment]
It's explained in the wiki: https://github.com/WHAnonymous/Chat-API/wiki
