### ISSUE TITLE
Function sendGetCipherKeysFromUser

### ISSUE THREAD

**Issue by sckebby** [WHAnonymous/Chat-API#968]
Hi,
I have try the function `sendGetCipherKeysFromUser` and it's return me:

```xml
<iq from="s.whatsapp.net" type="result" id="4">
    <list>
      <user jid="3XXXXXXXXX@s.whatsapp.net">
        <registration>�</registration>
        <type></type>
        <identity>'5,�3S���n�>���t���-�:=��F���cd</identity>
        <skey>
          <id></id>
          <value>������/���ǽ�Bmp�y�L�`^c���</value>
          <signature>���.�^>@u>!�;�<�L�{�Lf[�I��4]�{�h9!&*�J�F_�}X�?�E5��</signature>
        </skey>
        <key>
          <id>�</id>
          <value>�|��#ʣ4���"���3�}��a���%t{</value>
        </key>
      </user>
    </list>
  </iq>
```

Is the Identity Value the same as the identity genereted to create account ? What utility can I have to retreive this values for an WA User ?

Thanks for help.

**Comment by 0xTryCatch** [comment]
No. The identity for creating an account is private otherwise you can take over any mobile number.

**Comment by sckebby** [comment]
Thank you, but what kind of utility this function have ? To decode Messages ?

**Comment by WHAnonymous** [comment]
@sckebby avoid that function, we are not using that
