### ISSUE TITLE
my number was banned 

### ISSUE THREAD

**Issue by ahmedmus** [WHAnonymous/Chat-API#969]
my number was banned after only using `pollmessage( )` once 
what is the problem and can I retrive my phone number?

**Comment by WHAnonymous** [comment]
@ahmedmus that's impossible, if WhatsApp blocked your number then you were doing something bad. 

Want to check if it's really banned? Use `blockChecker.php` script

The rest is explained in the wiki: https://github.com/WHAnonymous/Chat-API/wiki
