### ISSUE TITLE
Problem parsing emoji unicode with json decode

### ISSUE THREAD

**Issue by C0dekid** [WHAnonymous/Chat-API#972]
Hello all,

I have a problem with parsing the unicode with json and php json decode.
If I put this in the json file: "\\xF0\\x9F\\x98\\x84" the output in Whatsapp will be:

\xF0\x9F\x98\x84

I like to add some emoji's as respond to someone's command. PHP-code:

$keyword_file = file_get_contents("C:\Whatsapp\src\data_files\keywords.json");
$keyword_json = json_decode($keyword_file, true);

JSON:
[{"keyword":"Hello little guy! \\xF0\\x9F\\x98\\x84"}]

EDIT:
Unicode: "&#x1f60a" also doesn't work.
I used the parser from: https://github.com/WHAnonymous/Chat-API/issues/

FIXED ISSUE:
Special thanks to Quentin (qligier). He/she gave me a solution.
I found out that you have to use the "Surrogates codes":

Smiley Table: http://apps.timwhitlock.info/unicode/inspect/hex/1F601
Smiley: 😁
Json: [{"keyword":"Hey little guy! \uD83D\uDE01"}]
PHP: htmlentities($var, ENT_QUOTES, "utf-8"); // For so far this is working for me.

Thanks,

Jer

**Comment by qligier** [comment]
You problem isn't related to the library.

Your JSON string isn't well encoded, it should be `[{"keyword":"Hello little guy! \u00F0\u009F\u0098\u0084"}]`. You need to replace every **\x** by **\u00** ([test it](https://3v4l.org/WanQb)).

Quentin

**Comment by C0dekid** [comment]
Thanks Quentin!

I will try that now, let you know how it went :-)

Jer

**Comment by 0xTryCatch** [comment]
If your issue is solved please close the ticket, otherwise let us know it still persist
