### ISSUE TITLE
Number blocked or anything else ?

### ISSUE THREAD

**Issue by TobiM93** [WHAnonymous/Chat-API#973]
Hi Guys I just registered a new number to WhatsApp via Android Emulator and WA Password App.
I entered the generated PW from WA Password. My other account ( registered 01/2015 ) get's the same message. What is going on ? Am I doing anything wrong ? But all I receive is this:

```xml
WooHoo!, Phone number 491525XXX1961 connected successfully!
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>
tx  <auth mechanism="WAUTH-2" user="491525XXX1961"></auth>
rx  <start from="s.whatsapp.net"></start>
rx  <stream:features></stream:features>
rx  <challenge>���[���!��W�)f���</challenge>
tx  <response>2�I9��N�Τp����c7#\ʦ� >�Nb(��O</response>
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
```

**Comment by modsfabio** [comment]
My number also gets banned after a few minutes... 

rx  <failure>
rx    <not-authorized retry="40743" expire="81486" code="103"></not-authorized>
rx  </failure>

**Comment by TobiM93** [comment]
@modsfabio was it your first try or was the number already working ?

**Comment by modsfabio** [comment]
Number was working for months before. Got banned first time 3 days ago. Today again after a few minutes


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: TobiM93 <notifications@github.com> 
Datum: 03.09.2015  19:41  (GMT+01:00) 
An: WHAnonymous/Chat-API <Chat-API@noreply.github.com> 
Cc: modsfabio <fabio@modszombies.com> 
Betreff: Re: [Chat-API] Number blocked or anything else ? (#973) 

@modsfabio was it your first try or was the number already working ?

**Comment by TobiM93** [comment]
@modsfabio Okay so same here.... what do you think ? Do you have havy traffic ? Propably Update ? I got the API Version from Oct / 2014

**Comment by TobiM93** [comment]
@modsfabio I just downloaded the newest Chat Api version and it's running now.

**Comment by modsfabio** [comment]
Today only 5 messages and then banned after a few minutes..After the first ban i downloaded the latest api and still banned.. i have no idea


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: TobiM93 <notifications@github.com> 
Datum: 03.09.2015  20:09  (GMT+01:00) 
An: WHAnonymous/Chat-API <Chat-API@noreply.github.com> 
Cc: modsfabio <fabio@modszombies.com> 
Betreff: Re: [Chat-API] Number blocked or anything else ? (#973) 

@modsfabio Okay so same here.... what do you think ? Do you have havy traffic ? Propably Update ? I got the API Version from Oct / 2014

**Comment by WHAnonymous** [comment]
@TobiM93 Please read the wiki, everything is explained there. Try `blockChecker.php` if that tell you it's not blocked, use `registerTool.php` and it will work again.

@modsfabio yours is a temportal block

`not-authorized retry="40743" expire="81486" code="103"`

Retry login in `40743` seconds
