### ISSUE TITLE
Features response

### ISSUE THREAD

**Issue by sckebby** [WHAnonymous/Chat-API#975]
Hi,
I receive this XML from WA server, what does it mean ? is it somethings about the update of the App ?

rx  notification from="44XXXXXXX83@s.whatsapp.net" type="features" offline="0" id="2333509348" t="1441350483">
rx    feature>
rx      encrypt_v2 value="none"></encrypt_v2>
rx    </feature>
rx  </notification>

I have try to resetAccount to avoid the incoming encrypted messages, on the device too, I have register the Sim directly with the Chat-API script (RegisterTool.php) but I continue to receive message like this.

rx  &lt;message from="44XXXXXXX28@s.whatsapp.net" type="text" offline="0" id="1441254147-97" t="1441361430" notify="Pio">
rx    &lt;enc v="1" type="pkmsg">3���!U� ��Q���� �:���cE߲U9f����!tE^5!��kp���H��L"%���Pa��N_T"?0"B3 !�a��X�����{����J|�N��5d�t���"]7�o��$7��ɉE�S�N����Y(�n0</enc>
rx  </message>

Before my friend update the WA-App on his phone, Message was delivered not encrypted, so they is no way to decrypt message from the last release of WA ?

Thanks for help.

**Comment by 0xTryCatch** [comment]
#891
#893
#899

**Comment by sckebby** [comment]
ops sorry, thanks you.
