### ISSUE TITLE
Blocking without reason

### ISSUE THREAD

**Issue by samamed** [WHAnonymous/Chat-API#976]
in my android phone i add one Participants and remove it and again add it and again remove it ... every 5 sec ....
very nice and no blocking problem

but in API i add one Participants after 2 min delete it and after 2 min remove it and add again and remove again ..

!!!BLOCK!!!
why ?!

I just wanted to test my code related to add or remove Participants !!  !but blocked!

A month ago, we were easily remove all Member in group by send array to sendGroupsParticipantsRemove  but now when use it and send multiple user whatsapp block you

why ?!

The problem is in my code or in the API?
Why is there a difference between a mobile phone and this API?

--------------------------------------
related problem:
#964
#974

**Comment by WHAnonymous** [comment]
https://github.com/WHAnonymous/Chat-API/commit/054f2d7841b65080029c293b7a61ba8b59abd686
