### ISSUE TITLE
Add/Remove a participant to a broadcast list

### ISSUE THREAD

**Issue by sigelstefan** [WHAnonymous/Chat-API#979]
Is it or will it be possible to add and remove a participant to a broadcast list and reuse it to send a broadcast message? Do I have to create every time a new list with `sendBroadcastMessege($contacts, $message)` and delete them with `sendDeleteBroadcastLists($list)`? 

On my phone I can add and remove participant to a broadcast list like for a group. So it's possible but I don't know how to create a node for those functions.

**Comment by CODeRUS** [comment]
On your phone do following:
Rename broadcast, change participants.
Uninstall WhatsApp, wipe all whatsapp data from /data/data/com.whatsapp
Install WhatsApp again, activate account, wait until it sync data from server
And check what broadcast have and what participants inside.

Please do not ask any additional questions BEFORE doing this.

**Comment by WHAnonymous** [comment]
@sigelstefan All it's done server side, so don't worry, if you use the API code it will be okay.

A proof of this is what @CODeRUS have said. Test it so you can know how it works
