### ISSUE TITLE
how use sendBroadcastMessage

### ISSUE THREAD

**Issue by rdy23x** [WHAnonymous/Chat-API#980]
i am using example who is on this documentation but not work please can you help me

```php
$targets = array("34123456789", "34987654321");
$message = "This is broadcast message";
$w->sendBroadcastMessage($targets, $message);
```

**Comment by WHAnonymous** [comment]
@rdy23x always post your debug log, without it we can't do anything

**Comment by WHAnonymous** [comment]
@rdy23x i just tried it and works perfectly, maybe it's because you are not polling enough

Add this at the end of your script:

```php
while(true)
{
    $w->pollMessage();
}
```
