### ISSUE TITLE
help

### ISSUE THREAD

**Issue by macr243** [WHAnonymous/Chat-API#981]
when i am trying to use $w->loginWithPassword($password);  the api send an error, it is Call to undefined function mcrypt_create_iv(), what's the problem?

**Comment by qligier** [comment]
As the message says, the _mcrypt_create_iv_ isn't available. You have to [install](http://php.net/manual/en/mcrypt.installation.php) and/or activate the __mcrypt__ extension.

A [simple Google search](https://www.google.ch/search?q=mcrypt+activate) gives a lot of useful ressources.

Quentin
