### ISSUE TITLE
Вывести данные getMessages из массива

### ISSUE THREAD

**Issue by akylkb** [WHAnonymous/Chat-API#983]
Как вывести сообщение на экран и другие данные?, из этого массива
Array
(
    [0] => ProtocolNode Object
        (
            [tag:ProtocolNode:private] => message
            [attributeHash:ProtocolNode:private] => Array
                (
                    [from] => 6666666666@s.whatsapp.net
                    [type] => text
                    [id] => 1441336655-00
                    [t] => 1441444466
                    [notify] => akyl
                )

            [children:ProtocolNode:private] => Array
                (
                    [0] => ProtocolNode Object
                        (
                            [tag:ProtocolNode:private] => body
                            [attributeHash:ProtocolNode:private] => Array
                                (
                                )

                            [children:ProtocolNode:private] => 
                            [data:ProtocolNode:private] => Привет мир
                        )

                )

            [data:ProtocolNode:private] => 
        )

)

**Comment by WHAnonymous** [comment]
@akylkb i don't know russian, you should write in a language everybody can understand. And quote your code and do not `var_dump`
