### ISSUE TITLE
block checker is not effective anymore

### ISSUE THREAD

**Issue by MoudiZd** [WHAnonymous/Chat-API#992]
As i can see that when i try to check a blocked number and an active number in both cases the block checker php file return incorrect so we cannot know anymore if the number is blocked or the identity is wrong

Can you help in such statement !

**Comment by WHAnonymous** [comment]
@MoudiZd debug log? do you know that if you don't post debug log, i consider this like irrelevant?

**Comment by MoudiZd** [comment]
````
####################
#                  #
# WA Block Checker #
#                  #
####################


Username (country code + number without + or 00): 96176323126


Wrong identity.
Array
(
    [cc] => 961
    [in] => 76323126
دٌ↔ُل]{kّⁿ↓▒=╛ن■↕
    [lg] => ar
    [lc] => LB
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
)

Fatal error: Uncaught exception 'Exception' with message 'There was a problem tr
ying to request the code.' in C:\xampp\htdocs\whatsapp-apis\Chat-API-master----\
src\whatsprot.class.php:183
Stack trace:
#0 C:\xampp\htdocs\whatsapp-apis\Chat-API-master----\examples\blockChecker.php(3
4): WhatsProt->checkCredentials()
#1 {main}
  thrown in C:\xampp\htdocs\whatsapp-apis\Chat-API-master----\src\whatsprot.clas
s.php on line 183
````

this number 96176323126 is a blocked number and in past when i try to check for a blocked  number the response from wa it was 

stdClass Object
(
    [status] => fail
    [reason] => blocked
)

But now as i can see that in both cases (when a number is blocked , or the identity is wrong) the wa server response by reason incorrect

so we cannot know anymore if the number is blocked or just the identity is wrong !

**Comment by 0xTryCatch** [comment]
It still returns ```blocked```, just tested it. So your number is not blocked anymore, congratulations! :)

**Comment by MoudiZd** [comment]
But i have about 10 numbers all when i check are not blocked but incorrect reason 

but when i go to connect with any number this is the log :
````
tx  <stream:features>
tx    <readreceipts></readreceipts>
tx    <groups_v2></groups_v2>
tx    <privacy></privacy>
tx    <presence></presence>
tx  </stream:features>

tx  <auth mechanism="WAUTH-2" user="**********"></auth>

rx  <start from="s.whatsapp.net"></start>

rx  <stream:features></stream:features>

rx  <challenge>0�_^1�ᑅ`�D˨.s^.</challenge>

tx  <response>�I�9������u��(H�K�N{�$Z�i�t</response>

rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
````
I am aware that the number is blocked temporary

so what it may be the problem and what about ip and mac address

really is a strange issue

Yesterday it was working without any problem !

**Comment by WHAnonymous** [comment]
@MoudiZd it's because wrong identity. Try registering again, if you can't blocked, easy

**Comment by MoudiZd** [comment]
if i am blocked the log must say authentication failure ! So their is any other possible to get the not-authorized and be blocked ?

In more clear question : did always when i am blocked i will got the authentication-error ? or their is sometimes that i will get the not-authorized

i think that if you provide a table that contains the error status table and the cause of each error this might be best for debugging

**Comment by WHAnonymous** [comment]
@MoudiZd look... this is getting very annoying. There is a fucking wiki, there is explained everything: https://github.com/WHAnonymous/Chat-API/wiki/Frequently-asked-questions#problems-logging-in-errors-or-not_authorized

**Comment by MoudiZd** [comment]
too bad ....... you are saying in your wiki that this message

````
rx  <failure>
rx    <not-authorized></not-authorized>
rx  </failure>
````

meaning that i am blocked when this message occured also when identity is wrong so i am very confused in your wiki

each time i search your wiki i get confused more !
anyway sorry for annoying you ......

**Comment by WHAnonymous** [comment]
@MoudiZd not authorized means blocked. ALWAYS

**Comment by casion** [comment]
Hi guys,

I have the same issue here.

How is the best way to check if my number was blocked? Is it an Exception, a custom response? When does it occurs? PollMessage, login, sendmessage?

best regards

**Comment by ariel12345** [comment]
Does anyone know a solution , even for me it is blocked from the start , and did not work at all , please help me

**Comment by kerwitz** [comment]
Just for the sake of completeness: not authorized may also appear when you lost the required identity.
That's the case whenever you receive `reason => incorrect` from the blockChecker.php.
Thus, not authorized *does not* always mean blocked and you may be able to register the account again to receive a fresh identity. Just try using the registerTool.php to see wether your account got ultimately blocked or not.

**Comment by kadnan** [comment]
@kerwitz , for me **Registertool* returns as following, totally clueless. First time it worked fine. Is there anyway to Unregister Number?

```
Array
(
    [cc] => 92
    [in] => 1233
    [lg] => en
    [lc] => PK
    [id] => >zv?+?????w!l?v?5b?
    [mistyped] => 6
    [network_radio_type] => 1
    [simnum] => 1
    [s] => 
    [copiedrc] => 1
    [hasinrc] => 1
    [rcmatch] => 1
    [pid] => 9618
    [extexist] => 1
    [extstate] => 1
)
stdClass Object
(
    [status] => fail
    [reason] => incorrect
    [sms_length] => 6
    [voice_length] => 6
    [sms_wait] => 0
    [voice_wait] => 0
)
There was a problem trying to request the code.

```
