### ISSUE TITLE
Failed to loginWithPassword !! the nextChallenge.dat file

### ISSUE THREAD

**Issue by fa-deve** [WHAnonymous/Chat-API#993]
Hi ,i cann't login due to don't have nextChallenge.dat file only have id.***.dat file in wadata folder .
what is the nextChallenge.dat file ??  
what can i do ?

**Comment by viniciusjarina** [comment]
@fa-deve  did you register using the registerTool?

**Comment by fa-deve** [comment]
yes . i registered using registerTool.php and got :
[status] => ok
[login] => 20xxxxxxx
[pw] => ypkcqXfSmunHbN9pM87U9SDwvFI=
[type] => existing
[expiration] => 1472666032
[kind] => free
[price] => 0.99 
[cost] => 0.99
[currency] => USD
[price_expiration] => 1444806560

**Comment by WHAnonymous** [comment]
@fa-deve next challenge has nothing to do with it. Make sure you have all dependencies installed, like #989 which required to install mcrypt and configure it php.ini. It's something at your side not API issue

**Comment by fa-deve** [comment]
@WHAnonymous  
i cannot understand the real reason of my problem , code is working fine for sometime 
and got
![sync](https://cloud.githubusercontent.com/assets/14147885/9788717/e31b937c-57cb-11e5-89c2-f34be9cff502.PNG)
and in other time i cannot login and got 
![sync3](https://cloud.githubusercontent.com/assets/14147885/9788736/15f6ed1e-57cc-11e5-9eb0-65a4597cb49a.png)

note : number exists not blocked
any help ? is this due to mcrypt and php.ini ?? or another thing ??.
