### ISSUE TITLE
used contactsync.php

### ISSUE THREAD

**Issue by xpixljo** [WHAnonymous/Chat-API#994]
hi 

anyone can tell me how i can used contactsync and mysql 
to filter multi number 

i want used php and mysql and contactsync to make colum in db 
and when i, used corn job will test 1000 by 1000 to get this number reg or no 
plz i want help

**Comment by catch2patch** [comment]
read the wiki (the damned wiki) and also spammers don't have any support here...

**Comment by phpjoker** [comment]
@catch2patch :+1:
