### ISSUE TITLE
Send image have some issue 

### ISSUE THREAD

**Issue by beljk** [WHAnonymous/Chat-API#995]
Dear @WHAnonymous  , send image working fine when using this function

ws->

but when i used another function that need image path ,hash and size to send image without uploading it again didn't works fine..
 ws->

scenario 
i get hash and size from the last message i had sent using first function then in second send when i got hash and size i using the second function to send message without uploading it again

here is error
```xml
tx  <iq id="2" to="s.whatsapp.net" type="set" xmlns="w:m">
tx    <media hash="9QJPI7hoO0VzGOX8vi aLSUQ5 yU0bcamECK zKG9z0=" type="image" size="20800"></media>
tx  </iq>

rx  <iq from="s.whatsapp.net" type="error" id="2">
rx    <error code="500" text="internal-server-error"></error>
rx  </iq>
```

**Comment by mgp25** [comment]
@beljk look at your hash it has spaces, check it

Regards

**Comment by beljk** [comment]
@mgp25 how can i get hash and size of image
