### ISSUE TITLE
Attempted to call function "mcrypt_create_iv" from the global namespace

### ISSUE THREAD

**Issue by Madhuri7112** [WHAnonymous/Chat-API#997]
This is the error i get when i try to run the following snippet.

```php
    $username = "91999999999";   //THis is fake number,I have given my original number in my app
    $nickname = "maddy";
    $debug = true;
    $password = "my_password";
    $w = new WhatsProt($username, $nickname, $debug);
    $w->connect(); 
    $w->loginWithPassword($password);
    $events = new MyEvents($w);
    $w->eventManager()->bind("onGetMessage", "onMessage");
    $w->pollMessage();
```

I have integrated this API in my symfony project.
I have registered successfully and got my password.
Can you please tell me the fix for this?

The error shows at 
```php
    $this->phoneNumber
                ));
     $this->sendAvailableForChat();
     $this->messageId = substr(base64_encode(mcrypt_create_iv(64, MCRYPT_DEV_URANDOM)), 0,      12);
        return true;
    }
```

`line 2278 of whatsprot.class.php`

**Comment by rayidi** [comment]
Hello Madhuri,

You probably missing mcrypt package see reference here `http://blog.quadspot.de/wordpress/symfony2/symfony2-tutorial-part-1-project-setup`

**Comment by Madhuri7112** [comment]
@rayidi Is there a way to comment that line and give the message id in any other way?

**Comment by rayidi** [comment]
I guess, we're not..
It's in the part of hash generation, @mgp25 might help you in this.

**Comment by mgp25** [comment]
@Madhuri7112 yes, but not secure at all. You can create identity but urlencoding a sha1 hash
