### ISSUE TITLE
Random Seconds value for sendGetRequestLastSeen Response

### ISSUE THREAD

**Issue by sckebby** [WHAnonymous/Chat-API#998]
Hi, 
I have got a strange response with the sendGetRequestLastSeen method, My onGetRequestLastSeen Event function always respond me a random $seconds value. Does it append to you ?

`<iq from="336XXXXXXX@s.whatsapp.net" type="result" id="3">
  <query seconds="1053317"></query>
</iq>`

`<iq from="336XXXXXXX@s.whatsapp.net" type="result" id="3">
  <query seconds="853317"></query>
</iq>`

Thanks for help.

**Comment by viniciusjarina** [comment]
@sckebby dup of https://github.com/WHAnonymous/Chat-API/issues/938

This was already reported, use the event onPresenceUnavailable to handle this.

**Comment by sckebby** [comment]
Thanks for help. ;)
